### ISSUE TITLE
p:timeline - TimelineUpdater.getCurrentInstance returns null

### ISSUE THREAD

**Issue by guzial** [primefaces-extensions/primefaces-extensions.github.com#127]
Hi,

I wondering why i get for TimelineUpdater.getCurrentInstance("nameOfID")  null.
I pass as a parameter id of timeline object.
When i execute command:

FacesContext fc = FacesContext.getCurrentInstance();
fc.getViewRoot().findComponent("nameOfID") 

i get TimeLine object.

But code:

(Map<String, TimelineUpdater>) fc.getAttributes().get(TimelineUpdater.class.getName()) 

returns null. So this is the reason why   TimelineUpdater.getCurrentInstance terminates and returns null.

Question is why and what i do wrong or what should i check.

**Comment by ova2** [comment]
Please create an issue in the PrimeFaces core. This component was migrated to PrimeFaces.
