### ISSUE TITLE
pe:layout - Implement updatable nested layouts

### ISSUE THREAD

**Issue by ova2** [primefaces-extensions/primefaces-extensions.github.com#14]
What steps will reproduce the problem?
1. Create a PE Layout
2. Create several layoutPanes
3. Try to update one layoutPane

What is the expected output? What do you see instead?

LayoutPane should have an ID or a styleClass that can be used in update attributes to update the content.

What version of the product are you using? On what operating system?

PF 3.4.1 and PE 0.6.0

Please provide any additional information below.

As workaround a outputPanel can be used within a layoutPane. However this does not work to update a layoutPane containing other layoutPanes as nested layoutPanes cannot have outputPanels between them.

**Comment by ova2** [comment]
Outdated requirement. I cannot see how to implement this feature with the jQuery Layout plugin. Won't Fix.

**Comment by temaleva** [comment]
We also gave it up and are using now flex boxes instead.
