### ISSUE TITLE
Request for a new timePicker attribute

### ISSUE THREAD

**Issue by onyii5119** [primefaces-extensions/primefaces-extensions.github.com#180]
Please add a new attribute to timePicker to force the user to select time from the popup? This is to prevent manual entry and avoid validation errors. This attribute should have a similar behavior to the "readonlyInput" of p:calendar.

Thanks.

**Comment by tandraschko** [comment]
Duplicate: https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/302
