### ISSUE TITLE
pe:inputNumber dont set null to an empty value

### ISSUE THREAD

**Issue by ova2** [primefaces-extensions/primefaces-extensions.github.com#19]
What steps will reproduce the problem?
1.access the pe:inputNumber example: http://fractalsoft.net/primeext-showcase-mojarra/sections/inputNumber/advanceUsage.jsf ;
2. Put a value >0 in the last field called "Empty value (empty) not required";
3. Submit the form;
4. See the output of the field "Empty value (empty) not required". It's ok.
5. Remove value of field "Empty value (empty) not required";
6. See the output value again. 

It's expected "empty" (setting null in bean) but always set zero.

In my app I have the same problem, and I didn't see an solution using PE.
With p:inputText works fine.

Regards,

Evandro
# 

The field displayed after submit is "Value of seventh input", not "Empty value (empty) not required".

Sorry
# 

Of course!

If you follow the steps above you will find that, after submitting to a value and then deletes it, the field no longer receives the null value. Always assuming the value zero and not "null" as expected.

Hence the validation of "required" no longer works, because zero is a valid number.
# 

Note: The first steps in the e-mail were executed in showcase.
# 

so the displayed value is "empty" but the bean value is "0" but should be null?
# 

n the third step the expected result is null and void should be displayed. What happens is that the number zero is displayed.

See the attached images.

![step_1](https://f.cloud.github.com/assets/767334/40450/a963beea-55a1-11e2-909e-adafedeae953.png)

![step_2](https://f.cloud.github.com/assets/767334/40451/b10d32b6-55a1-11e2-95ac-d917df7aa6f6.png)

![step_3](https://f.cloud.github.com/assets/767334/40452/b5771e5c-55a1-11e2-8d86-fff2e5a99543.png)
# 

This behavior is expected by the jquery plugin.
I won't change this logic for now.
Mauricio, would you like to take of it if you are able to work again?
# 

Hi!

Ok, maybe a jquery behavior, but isn't a jsf behavior. 

Today I'm using JSF inputText and this problem does not occur.

From what I saw in the source code, the error occurs by using the Double class directly. If he worked with string and return only when a number number was entered, the zero does not appear.

Similar to what is done in inputText.
# 

Well, if you understand what behavior is expected. It only remains to close the ticket.
# 

Exactly but i'm not the creator of this component and i never used it.
So IMO it's better that the developer of component should have a look at it or should decide.
# 

I have the same problem as Evandro. In this case I saw before many tickets, but there is no solutions. Please fix it.
# 

In diciempre 17 I will be again able to use my left hand.
As soon as I can I will seek solutions to this issue and other releated.

Thanks for understanding.

**Comment by samtriani** [comment]
Using primefaces 5.2 & prime extensions 3.2.0 adding  any value to inputnumber the client validation is always true, any idea for this bug???...

<p:column headerText="Header Text">
           <p:cellEditor>
               <f:facet name="output"><h:outputText value="#{obj.val}" /></f:facet>
               <f:facet name="input"><pe:inputNumber  id="numId" value="{obj.val}" required="true"/></f:facet>
           </p:cellEditor>
       </p:column>

**Comment by tandraschko** [comment]
we already removed pe:inputNumber and moved it to PF. So try 6.0 first.

**Comment by tandraschko** [comment]
JFYI: https://github.com/primefaces/primefaces/issues/1498
This is only available in elite released and in the upcoming 6.1.
