### ISSUE TITLE
ajaxExceptionHandler - add attributes for setupping popup window and content

### ISSUE THREAD

**Issue by slany** [primefaces-extensions/primefaces-extensions.github.com#192]
add option for enable/disable follow features:
resizable, autoresize, width, height, ...

This idea of this enhancement started on http://forum.primefaces.org/viewtopic.php?f=14&t=34958.

**Comment by ova2** [comment]
AjaxErrorHandler has been removed due to bugs and because PrimeFaces has a better functionality with PrimeFaces ExceptionHandler.
