### ISSUE TITLE
add parserfile and stylesheet to pe:codeMirror tag

### ISSUE THREAD

**Issue by shikida** [primefaces-extensions/primefaces-extensions.github.com#201]
CodeMirror supports custom parsers and syntax highlight css. 

For example

[script type="text/javascript"]
  var editor = CodeMirror.fromTextArea('code', {
    height: "450px",
    parserfile: "../contrib/plsql/js/parseplsql.js",
    stylesheet: "css/plsqlcolors.css",
    path: "../../js/",
    textWrapping: false
  });
[/script]
Please add these to pe:codeMirror tag. Thanks.

**Comment by tandraschko** [comment]
As you are currently the only one who need it, please create a pull request. PrimeFaces Extensions is a community based project.
