### ISSUE TITLE
PF Ext - QR Code Decoder - Enhancement Request

### ISSUE THREAD

**Issue by rasekar2000** [primefaces-extensions/primefaces-extensions.github.com#211]
Now that QR Code Generation is available, can we have QR Code Decoder as well. < Reverse of it >. Another open source is available for this one. 
Working Example is in http://zxing.org/w/decode.jspx and the source code is in https://github.com/zxing/zxing/blob/master/zxingorg/src/main/java/com/google/zxing/web/DecodeServlet.java

This will be of great help to PF Community.

**Comment by tandraschko** [comment]
PrimeFaces Extensions is a community based project. If you would like to contribute this feature, please reopen the ticket and provide a pull request.
