### ISSUE TITLE
PF Ext - QR Code Generator for vCard, MECard and others- Enhancement Request

### ISSUE THREAD

**Issue by rasekar2000** [primefaces-extensions/primefaces-extensions.github.com#212]
QR Code Generator can be automated for VCard , MECard and others.
http://zxing.appspot.com/generator/

We can have other enhancements as well tracked in separate GitHub issues.
Can you please consider implementing?

**Comment by tandraschko** [comment]
PrimeFaces Extensions is a community based project. If you would like to contribute this feature, please reopen the ticket and provide a pull request.
