### ISSUE TITLE
PF Ext - QR Code Generator with downloadable Image - Enhancement Request

### ISSUE THREAD

**Issue by rasekar2000** [primefaces-extensions/primefaces-extensions.github.com#213]
Is it possible to enhance

 http://www.primefaces.org/showcase-ext/sections/qrCode/basicUsage.jsf with downloadable image of the same generated QR Code.

 You may review the "Download" image after  generating any form of QR Code Content
 http://zxing.appspot.com/generator/

Thanks in advance.

**Comment by tandraschko** [comment]
PrimeFaces Extensions is a community based project. If you would like to contribute this feature, please reopen the ticket and provide a pull request.
