### ISSUE TITLE
PF Ext - QR Code Generator with 3 Content Type option - Enhancement Request

### ISSUE THREAD

**Issue by rasekar2000** [primefaces-extensions/primefaces-extensions.github.com#214]
http://zxing.appspot.com/generator/
 is offering 3 types of Character Encode option - ISO-8859-1 and Shift_JIS .

Can we have all or important ones please in PF Ext QR Code Component.

Thanks in advance.

**Comment by tandraschko** [comment]
PrimeFaces Extensions is a community based project. If you would like to contribute this feature, please reopen the ticket and provide a pull request.
