### ISSUE TITLE
AjaxErrorHandler should only handle PF Ajax requests

### ISSUE THREAD

**Issue by tandraschko** [primefaces-extensions/primefaces-extensions.github.com#217]
Currently it globally listens on each jquery AJAX request:
(document).ajaxComplete(handlerFunction);

You can use the 'pfAjaxComplete' event, just look e.g. in blockUI.

**Comment by ova2** [comment]
AjaxErrorHandler has been removed due to bugs and because PrimeFaces has a better functionality with PrimeFaces ExceptionHandler.
