### ISSUE TITLE
Link CodeMirror Homepage on the component root pages

### ISSUE THREAD

**Issue by ova2** [primefaces-extensions/primefaces-extensions.github.com#22]
Thomas, would be it possible to list all available themes for CodeMirror in the documentation or direct in the showcase? According to this link http://codemirror.net/theme/ the following themes are available:

ambiance
blackboard
cobalt
eclipse
elegant
erlang-dark
lesser-dark
monokai
neat
night
rubyblue
vibrant-ink
xq-dark

Maybe a task for your apprentice? :-)
# 

Sorry Oleg but i can't see any benefit. I must add a link for the modes etc. then, too. Same for CKEditor.
This components can't be used without the docu of our wrapped JS.
# 

Sure, a link is fine.

**Comment by melloware** [comment]
The basic usage Showcase example was updated to show all Themes, Languages, and Keymaps and allows them to be tweaked via Ajax.
