### ISSUE TITLE
ajaxErrorHandler should not leak so much info in Production stage

### ISSUE THREAD

**Issue by rmillet42** [primefaces-extensions/primefaces-extensions.github.com#234]
When javax.faces.PROJECT_STAGE is Production,
ajaxErrorHandler response should not contains the Exception type, Exception message, Exception stack trace or host name.

It should be replaced by default messages and possibly enabled by an option in web.xml.

For example, in the showcase, the code contains
```
PrimeFacesExt.getAjaxErrorHandlerInstance().setHostname('Ubuntu-1104-natty-32-minimal');
```
 even when no exception is raised which shows that the server uses an old distibution which do not receive security updates since october 2012.

**Comment by ova2** [comment]
AjaxErrorHandler has been removed due to bugs and because PrimeFaces has a better functionality with PrimeFaces ExceptionHandler.
