### ISSUE TITLE
Change landing page to a menu-oriented layour

### ISSUE THREAD

**Issue by kito99** [primefaces-extensions/primefaces-extensions.github.com#244]
Just a suggestion: the PrimeFaces Extensions home page (http://primefaces-extensions.github.io/) is difficult to navigate (i.e. find the link you're looking for). I suggest going to a menu-oriented layout or even just a sidebar with the most often used links. 

I also think it'd be good to have a packaged zip/tar download (or individual JAR download links) as opposed to requiring that people go to Maven central. Believe it or not, there are still quite a few projects that don't use a Maven repository.

**Comment by tandraschko** [comment]
Will close it as won't fix - extensions is in maintenance mode.
