### ISSUE TITLE
Tooltip - implement styleClass attribute

### ISSUE THREAD

**Issue by gexge** [primefaces-extensions/primefaces-extensions.github.com#255]
Couldn't find any way to change a tooltip style except globally by ".ui-tooltip".
Please allow custom style for a specific tooltip (maybe pe:tooltip styleClass?).

**Comment by ova2** [comment]
Please provide a Pull Request. This enchancement has a very low prio for us.

**Comment by tandraschko** [comment]
Would be great if you could provide a PR.

**Comment by tandraschko** [comment]
no PR and activity for 2 years, will close it for now.
