### ISSUE TITLE
2.1.0/2.0.0 waypoint offset

### ISSUE THREAD

**Issue by fyamada** [primefaces-extensions/primefaces-extensions.github.com#273]
I can't reproduce the Infinite scrolling 1 example as it is defined in the showcase. It only works as expected when I set the offset='100%'. I tested also with version 2.0.0 and the behavior is the same (the reached event is not triggered).
Working with PF5.0, Mojarra 2.1.8, Glassfish 4

**Comment by ova2** [comment]
works for me.
