### ISSUE TITLE
pe:timeline - change AJAX event not called when change event group if timeChangeable = false

### ISSUE THREAD

**Issue by mkrzempek** [primefaces-extensions/primefaces-extensions.github.com#278]
I need timeline that agrees to change event group (groupChangeable = true) and not agree to change event time (timeChangeable = false).

If both flags are set to true "change" AJAX event is called properly. But if I change timeChangeable flag to false, "change" event is not called at all.

**Comment by ova2** [comment]
Please create an issue in the PrimeFaces core. This component was migrated to PrimeFaces.
