### ISSUE TITLE
With primefaces-extensions-2.1.0 Always throws an error validation with all  required inputNumbers into an DynaForm

### ISSUE THREAD

**Issue by juanmiguelRuaDev** [primefaces-extensions/primefaces-extensions.github.com#280]
With primefaces-extension-2.1.0. When you try to process an *DynaForm* with a required `<pe:inputNumber />` inside, this **inputNumber** component is always validated like null.

**Comment by ova2** [comment]
It seems to be a problem with pe:inputNumber then. Have you tried PF Extensions 3.0.0?

**Comment by tandraschko** [comment]
I would close it oleg. Idle since over 1 year.
