### ISSUE TITLE
timeline collapsing groups with no data - group text doesn´t fit anymore

### ISSUE THREAD

**Issue by DDOUP** [primefaces-extensions/primefaces-extensions.github.com#282]
if a group has no data, this group row is collapsing. 
The text of the group doesn´t fit anymore.
![timeline_collapsed](https://cloud.githubusercontent.com/assets/8915639/4405456/4836be50-44bb-11e4-8db1-642681d9f35a.PNG)

example:
go to http://www.primefaces.org/showcase-ext/sections/timeline/grouping.jsf
and delete all data events of the last group (truck 15)

**Comment by ova2** [comment]
I was fixed in the current 3.1.0 release.
