### ISSUE TITLE
p:timeline - Bug on mobile / Double click to add an event has wrong start time and group

### ISSUE THREAD

**Issue by Pushkutza** [primefaces-extensions/primefaces-extensions.github.com#294]
http://www.primefaces.org/showcase-ext/sections/timeline/editServer.jsf
On mobile (HTC m8 for eg) 
- when you double tap to add a new event the start date is not calculated correctly. Its a few units in behind (in the past). 
- also if you have more groups the first group is always selected regardless of the position you double tap.

**Comment by ova2** [comment]
I have no plans to use vs.js as long nobody pays for this work.

**Comment by ova2** [comment]
Please create an issue in the PrimeFaces core. This component was migrated to PrimeFaces.
