### ISSUE TITLE
ImageAreaSelect error whent cursor touch left border of screen

### ISSUE THREAD

**Issue by omarbr** [primefaces-extensions/primefaces-extensions.github.com#295]
when browser is maximized, select on image from right to left to touch with the cursor on the left border of the screen.
at release mouse button, java.lang.NumberFormatException For input string: "NaN" .

test this on showcase with window7 browser chrome, firefox, iexplorer.
same result.

**Comment by omarbr** [comment]
sorry but i have no idea for resolve this problem

**Comment by tandraschko** [comment]
looked at it but IMO this should be fixed by the imgAreaSelect plugin.
Please create a issue there, this is NOT related to our JSF bridge of the JS imgAreaSelect plugin.
