### ISSUE TITLE
encodeTheme(Context,String,String) missing for <pe:head>

### ISSUE THREAD

**Issue by alfonx** [primefaces-extensions/primefaces-extensions.github.com#300]
I used <pe:head> and after upgrading to PF5.1.7 and PE3.0.0 i can't use it anymore, because a method signature  
 encodeTheme(FacesContext,String,String)
is missing in org.primefaces.extensions.component.head.HeadRenderer. The existing signature is
 encodeTheme(FacesContext)

Also I cannot find pe:head in your showcase anymore. Maybe you want to document whether it is deprecated, dropped and/or how it should be replaced.

**Comment by tandraschko** [comment]
As we currently don't plan to release a bugfix release for 5.1, i will close this as won't fix.
I migrated pe:head already for the upcoming 5.2 release, so it isn't depcreated.
