### ISSUE TITLE
pe:timePicker - Time Range mode, when running disables Start Time Widget

### ISSUE THREAD

**Issue by 4thevin** [primefaces-extensions/primefaces-extensions.github.com#301]
![tp1](https://cloud.githubusercontent.com/assets/10580258/5791621/f146ab72-9ef2-11e4-819e-f6012be4c74b.png)
![tp2](https://cloud.githubusercontent.com/assets/10580258/5791622/f166a51c-9ef2-11e4-85fe-5eab09e707a9.png)

When the app is run, I am unable to select values in the start time widget. Only when I select values in the To Time widget does the validation in the js works and the start time widget gets updated. 
Also, at times, when I select time in the endTime widget it updates in the startTime widget.
Please help.

**Comment by ova2** [comment]
How can I help if you didn't show the code and didn't tell your PF Extensions version?

Ensure that widgets have unique widgetVar pro row in data iteration components, like p:dataTable. Use rowIndexVar for that or similar.

**Comment by 4thevin** [comment]
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui" xmlns:o="http://omnifaces.org/ui"
	xmlns:pe="http://primefaces.org/ui/extensions">

<h:head>
	<meta name="viewport" content="width=device-width, initial-scale=1" />
</h:head>

<h:body>
	<h:form name="form" id="form">

		<ui:include src="/common/header.xhtml"></ui:include>
		<ui:include src="/common/menu.xhtml"></ui:include>

		<h:panelGroup layout="block" styleClass="main_div1">
			<h:panelGroup layout="block" styleClass="main_div2">



				<f:event listener="#{loginBean.loadImage}" type="preRenderView"></f:event>


				<p:growl id="growl" showDetail="true" sticky="true" globalOnly="true" escape="true" />
				<p:focus context="timeSheet" />
				
				
				<h2>
					<h:outputText value="Employee Information" />
				</h2>
				


				

				<h:panelGroup layout="block" styleClass="left_col_sm">
					<h:panelGroup layout="block" styleClass="inner_left_col_sm">

						<p:panelGrid style="border:1px;width:700px">
							<p:row>
								<p:column styleClass="brown">
									<h:outputLabel value="EMPLOYEE NO." />
								</p:column>
								<p:column styleClass="gray">
									<h:outputLabel value="#{loginBean.empNo}" />
								</p:column>
								<p:column styleClass="brown">
									<h:outputLabel value="EMPLOYEE&nbsp;NAME" />
								</p:column>
								<p:column styleClass="gray">
									<h:outputLabel value="#{loginBean.empName}" />
								</p:column>
							</p:row>
							<p:row>
								<p:column styleClass="brown">
									<h:outputLabel value="DEPARTMENT&nbsp;NAME" />
								</p:column>
								<p:column styleClass="gray">
									<h:outputLabel value="#{loginBean.deptName}" />
								</p:column>
								<p:column styleClass="brown">
									<h:outputLabel value="DIVISION" />
								</p:column>
								<p:column styleClass="gray">
									<h:outputLabel value="#{loginBean.division}" />
								</p:column>

							</p:row>
						</p:panelGrid>
					</h:panelGroup>
				</h:panelGroup>
				<h:panelGroup layout="block" styleClass="inner_left_col_sm">
					<p:graphicImage cache="true"
						style="height:100px;width:100px;background:url('../images/profile.jpg') left no-repeat  !important; padding:0px  0px 0px 0px !important "
						value="#{loginBean.myImage}">
						<f:param name="id" value="#{loginBean.empNo}" />
					</p:graphicImage>

				</h:panelGroup>


				<h2>
					<h:outputText value="Enter Timesheet" />
				</h2>
				

				<p:dataTable id="timeSheet" var="dailybeanDt"
					styleClass="panelGridCenter" value="#{dailyBean.dailyReportList}"
					editable="true" editMode="cell" paginator="true" rows="10"
					rowKey="#{dailybeanDt.rowNumber}" rowIndexVar="rowIndex"
					selectionMode="single">

					
					

					<f:facet name="header">Daily Timesheet Entry</f:facet>
					
					
					
					<p:column headerText="Report Date" style="text-align:center">
						<p:cellEditor>
							<f:facet name="output">
								<h:outputText value="#{dailybeanDt.docDate}">
									<f:convertDateTime pattern="dd/MM/yyyy"></f:convertDateTime>

								</h:outputText>
							</f:facet>

							<f:facet name="input">
								<p:calendar id="popup" disabled="false" maxdate="#{currentDate}"
									pattern="dd/MM/yyyy" value="#{dailybeanDt.docDate}"
									required="true"
									requiredMessage="Enter Date for Timesheet Entry"
									beforeShowDay="FridaysDisabled">

				
								</p:calendar>
								<p:message for="popup" display="text" />
							</f:facet>
						</p:cellEditor>
					</p:column>

					<p:column headerText="Category" style="text-align:center">
						<p:cellEditor>
							<f:facet name="output">
								<h:outputText value="#{dailybeanDt.jobCategory}" />
							</f:facet>
							<f:facet name="input">
								<p:selectOneMenu id="category"
									value="#{dailybeanDt.jobCategory}" required="true"
									requiredMessage="Please select Category">
									<f:selectItem itemLabel="Select Category" itemValue="#{null}"
										noSelectionOption="true" />

									<f:selectItems value="#{dailyBean.categoryList.entrySet()}"
										var="qa" itemLabel="#{qa.value}" itemValue="#{qa.value}" />
								</p:selectOneMenu>
								<p:message for="category" showDetail="true" display="text" />
							</f:facet>
						</p:cellEditor>
					</p:column>
					
					
					
					
					
					
					
					
					
					

					<p:column headerText="Workplace" style="text-align:center"
						id="work">
						<p:cellEditor>
							<f:facet name="output">
								<h:outputText value="#{dailybeanDt.workPlace}" />
							</f:facet>
							<f:facet name="input">
								<p:selectOneMenu id="workplace" value="#{dailybeanDt.workPlace}"
									required="true" requiredMessage="Plesae select Workplace">
									<f:selectItem itemLabel="Select Workplace" itemValue="#{null}"
										noSelectionOption="true" />
									<f:selectItems value="#{dailyBean.workplaceList.entrySet()}"
										var="qa" itemLabel="#{qa.value}" itemValue="#{qa.value}" />
								</p:selectOneMenu>
								<p:message for="workplace" showDetail="true" display="text" />
							</f:facet>
						</p:cellEditor>
					</p:column>

					<p:column headerText="Charge Type" style="text-align:center"
						id="charge">
						<p:cellEditor>
							<f:facet name="output">
								<h:outputText value="#{dailybeanDt.chargeType}" />
							</f:facet>
							<f:facet name="input">

								<p:selectOneMenu id="chargetype"
									value="#{dailybeanDt.chargeType}" required="true"
									requiredMessage="Plesae select ChargeType">
									<f:selectItem itemLabel="Select ChargeType" itemValue="#{null}"
										noSelectionOption="true" />
									<f:selectItems value="#{dailyBean.chargetypeList.entrySet()}"
										var="qa" itemLabel="#{qa.value}" itemValue="#{qa.value}" />
								</p:selectOneMenu>
								<p:message for="chargetype" showDetail="true" display="text" />
							</f:facet>
						</p:cellEditor>
					</p:column>
					
					<p:column headerText="From Time (24H Format-Eg. 13:00)" style="text-align:center;width:80px">
						<p:cellEditor>
							<f:facet name="output">
								<pe:timePicker value="#{dailybeanDt.fromTime}" mode="popup">
								</pe:timePicker>
							</f:facet>
							<f:facet name="input">
								<pe:timePicker value="#{dailybeanDt.fromTime}"   mode="popup" />
							</f:facet>
						</p:cellEditor>
					</p:column>

					<p:column headerText="To Time (24H Format-Eg. 13:00)" style="text-align:center;width:80px">
						<p:cellEditor>
							<f:facet name="output">
								<pe:timePicker value="#{dailybeanDt.toTime}" mode="popup"> </pe:timePicker>
							</f:facet>
							<f:facet name="input">
								<pe:timePicker value="#{dailybeanDt.toTime}" mode="popup" />






						

							</f:facet>
						</p:cellEditor>
					</p:column>
					<p:column headerText="Job Description"
						style="width:200px;text-align:center">
						<p:cellEditor>
							<f:facet name="output">
								<h:outputText value="#{dailybeanDt.jobDescription}" 	id="jobdesco" />
							</f:facet>
							<f:facet name="input">
								<p:inputText id="jobdesc" value="#{dailybeanDt.jobDescription}"
									style="width:300px;height:30px" required="true"
									requiredMessage="Please enter Job Description" />
								<p:message for="jobdesc" showDetail="true" />
							</f:facet>
						</p:cellEditor>
					</p:column>


					<p:column style="width:200px" id="action">
						<p:commandButton icon="#{dailybeanDt.icon}"
							value="#{dailybeanDt.actionType}"
							update=":form:growl,:form:timeSheet" process="@this"
							action="#{dailyBean.addRow(dailybeanDt.actionType,dailybeanDt)}">
						</p:commandButton>
						
					</p:column>

				</p:dataTable>
				<p:dialog id="timeSheetDialog" widgetVar="timeSheetDialog"
					width="260" height="70" showHeader="true" resizable="false"
					header="#{dailyBean.primeDialogHeader}"
					style=" border:3px solid #ba1021 !important; font-weight:bold"
					showEffect="clip" hideEffect="clip" closeOnEscape="true"
					closable="true" modal="true">
					<p:outputLabel value="#{dailyBean.primeDialogMsg}" />
					<br />
				</p:dialog>
				<p:dialog id="timeSheetDialogTime" widgetVar="timeSheetDialogTime"
					width="260" height="70" showHeader="true" resizable="false"
					header="#{dailyBean.primeDialogHeader2}"
					style=" border:3px solid #ba1021 !important; font-weight:bold"
					showEffect="clip" hideEffect="clip" closeOnEscape="true"
					closable="true" modal="true">
					<p:outputLabel value="#{dailyBean.primeDialogMsg2}" />
					<br />
				</p:dialog>
				<br />
				<br />

				<h:panelGroup layout="block" styleClass="tealri">
					<p:commandButton icon="ui-icon-check"
						action="#{dailyBean.saveReport}" value="Save Timesheet"
						update=":form:growl,:form:timeSheet">

					</p:commandButton>
				</h:panelGroup>
			</h:panelGroup>
		</h:panelGroup>

		<ui:include src="/common/footer.xhtml"></ui:include>
	</h:form>

	<script>
		function FridaysDisabled(date) {
			var day = date.getDay();
			return [ (day != 5), '' ]
		}
	</script>
</h:body>
</html>

**Comment by 4thevin** [comment]
Using primefaces-extensions-3.0.0.jar

**Comment by ova2** [comment]
Difficult to say, too much code. Can you create a very simple example with a simple p:dataTable and pe:timePicker within it?

**Comment by 4thevin** [comment]
<p:dataTable id="timeSheet" var="dailybeanDt"
					styleClass="panelGridCenter" value="#{dailyBean.dailyReportList}"
					editable="true" editMode="cell" paginator="true" rows="10"
					rowKey="#{dailybeanDt.rowNumber}" rowIndexVar="rowIndex" > 

					<p:column headerText="From Time (24H Format-Eg. 13:00)" style="width:80px">
						<p:cellEditor>
							<f:facet name="output">
								<pe:timePicker value="#{dailybeanDt.fromTime}" mode="popup" widgetVar="fromTimeo">
								</pe:timePicker>
							</f:facet>
							<f:facet name="input">
								<pe:timePicker value="#{dailybeanDt.fromTime}"   mode="popup"  id="fromTime" widgetVar="fromTime"/>
							</f:facet>
						</p:cellEditor>
					</p:column>
					
					<p:column headerText="To Time (24H Format-Eg. 13:00)" style="width:80px">
						<p:cellEditor>
							<f:facet name="output">
								<pe:timePicker value="#{dailybeanDt.toTime}" mode="popup" widgetVar="toTimeo"> </pe:timePicker>
							</f:facet>
							<f:facet name="input">
								<pe:timePicker value="#{dailybeanDt.toTime}" mode="popup" id="toTime" widgetVar="toTime" />

							</f:facet>
						</p:cellEditor>
					</p:column>
					
					<p:column style="width:200px" id="action">
						<p:commandButton icon="#{dailybeanDt.icon}"
							value="#{dailybeanDt.actionType}"
							update=":form:timeSheet" process="@this"
							action="#{dailyBean.addRow(dailybeanDt.actionType,dailybeanDt)}">
						</p:commandButton>
					</p:column>
				</p:dataTable>

**Comment by 4thevin** [comment]
This is the same example, trimmed down to just 2 timepicker components (time Range)

**Comment by ova2** [comment]
Can you try to change all widgetVar in p:timePicker like this one?

widgetVar="toTime#{rowIndex}"

You also have two identical p:cellEditor with identical p:timePicker. Why? Can you ensure that all names in widgetVar are unique?

**Comment by 4thevin** [comment]
Would it make a difference, considering they are all in the same row ?

**Comment by 4thevin** [comment]
Is there any way I can disable keyboard entry in pe:timePicker? or I want to enable only keyboard entry  and disable the component from opening up.
Reason is when i use an ajax event of type timeSelect and blur together, the timeSelect event does not work in a p:datatable. I have been facing issues with this for quite some time so please provide a solution or workaround.

**Comment by smithh032772** [comment]
I would not/never try to use pe:timePicker with 'editable' p:dataTable. Honestly, I would never use 'editable' p:dataTable for anything.

 editable="true" editMode="cell"

**Comment by 4thevin** [comment]
WHAAT? Why ? : O
That is one of the core functionalities of my application. If it fails, then I have to switch back to p:calendar, where I didn't like the appearance of the timeOnly component. if timePicker (with time Range JS validation) works perfectly, then there is no issue.
You mean to say I cannot use a fundamental Primefaces component with a key Primefaces Extensions component ? :(

**Comment by smithh032772** [comment]
Search PrimeFaces forum and see how many people have issues using cell
editor and or editable datatable and calendar.

**Comment by ova2** [comment]
Agree, editable data table is evil. Especially perfomance. Better to
provide a detail view to edit row data.
Am 30.01.2015 15:49 schrieb "smithh032772" <notifications@github.com>:

> Search PrimeFaces forum and see how many people have issues using cell
> editor and or editable datatable and calendar.

**Comment by 4thevin** [comment]
My purpose is to have an empty datatable and the user has to enter details cell wise and row-wise. So there has to be validation between cells in the same rows and in different rows. So it has to be celledit. Any suggestions ?

**Comment by smithh032772** [comment]
Suggestions have been given. I don't think you will get any other/more
suggestions. Go with your approach/requirement or the suggestions provided.
:)

**Comment by tandraschko** [comment]
Will close it for now.
if you think this is an bug, please provide a PR or a simple maven-jetty-application and reopen.
