### ISSUE TITLE
pe:timePicker - implement readonlyInput attribute

### ISSUE THREAD

**Issue by 4thevin** [primefaces-extensions/primefaces-extensions.github.com#302]
Is there any way to disable keyboard entry in pe:timePicker ?
There is no default property as of now like in p:calendar (readonlyInput=true)

**Comment by ova2** [comment]
readonlyInput is not yet supported because nobody required it. You can try to set readonly with JavaScript in document.ready for now.

**Comment by melloware** [comment]
+1. This would be a very handy feature of Timepicker.

**Comment by tandraschko** [comment]
Would be great if you could provide a PR.
