### ISSUE TITLE
pe:timePicker - 2 components inside datatable causing issue

### ISSUE THREAD

**Issue by 4thevin** [primefaces-extensions/primefaces-extensions.github.com#303]
I have 2 pe:timePicker components next to each other in an editable datatable. When I select the value of the one on the left by choosing minutes, it updates the component next to it.
![pe timepicker issue](https://cloud.githubusercontent.com/assets/10580258/5999877/bfe02940-aae7-11e4-8791-232be60d7d7d.png)

Please look into this.

**Comment by feverdog** [comment]
Are you using the same 'widgetVar' for the timepicker widgets? It could cause this kind of behavior, I think.

**Comment by ova2** [comment]
Yes, check your widgetVar. You can append some unique ID to the widgetVar for every cell / row.
