### ISSUE TITLE
resources-optimizer-maven-plugin don't include the license file 

### ISSUE THREAD

**Issue by puntogil** [primefaces-extensions/primefaces-extensions.github.com#304]
Not available LICENSE file in source directory structure
Please. Added license and copyright notice.
the fedora pakaging guideline is very strictly precise about this problem
https://fedoraproject.org/wiki/Packaging:LicensingGuidelines?rd=Packaging/LicensingGuidelines#License_Text
thanks
regards

**Comment by ova2** [comment]
What license do you mean? For the Google Closure compiler or for the PrimeFaces Extensions? Both are released under Apache License http://www.apache.org/licenses/LICENSE-2.0

**Comment by puntogil** [comment]
Hi,
for the PrimeFaces Extensions org.primefaces.extensions:resources-optimizer-maven-plugin
regards

**Comment by ova2** [comment]
I meant what license file do we need? One from Apache?

**Comment by puntogil** [comment]
yes, http://www.apache.org/licenses/LICENSE-2.0.txt
thanks

**Comment by ova2** [comment]
Ok. I will also try to update the version of the Google Closure Compiler I use in this plugin.

**Comment by ova2** [comment]
Please review my changes https://github.com/primefaces-extensions/resources-optimizer-maven-plugin/commit/99ce831f4df082cc9d791d5ae073e04dfa60c4a2

I added the LICENSE.txt direct unter sources. If you open the JAR, you will find the structure:
* META-INF
* org
* LICENSE.txt

Is it ok? If it is ok, I will release the plugin. Thanks.

**Comment by puntogil** [comment]
yes, for me is ok.
Thanks

**Comment by ova2** [comment]
have released the version 1.2.0.
should be available in the Maven central repo tomorrow.

**Comment by puntogil** [comment]
Again thanks
we don't use pre-built libraries
http://fedoraproject.org/wiki/Packaging:Guidelines#No_inclusion_of_pre-built_binaries_or_libraries

**Comment by puntogil** [comment]
https://kojipkgs.fedoraproject.org//work/tasks/8553/9268553/build.log

**Comment by ova2** [comment]
Is it good or bad? :-) I see warnings in the log - will fix them in the
next release.
Am 19.03.2015 00:06 schrieb "puntogil" <notifications@github.com>:

**Comment by puntogil** [comment]
good, very good. thanks :)
