### ISSUE TITLE
Timeline - IE11 - 'createStyleSheet' unsuported

### ISSUE THREAD

**Issue by sasynkam** [primefaces-extensions/primefaces-extensions.github.com#305]
IE 11 throws:
SCRIPT438: Object doesn't support property or method 'createStyleSheet'
File: primefaces-extensions.js.xhtml, Line: 217, Column: 10

when I want to show timeline. In "emulation mode" or older versions of IE it works.

IE 11.0.9600.17498, PrimeFaces: 5.1.6, PrimeFaces Extensions: 3.0.0, JSF: mojarra 2.1.27, Server: TomEE 1.5.2

**Comment by tandraschko** [comment]
createStyleSheet is also used when we lazy download the component resources if not available yet.
Please also assign it to me if you fixed the problem in the timeline.

**Comment by ova2** [comment]
Reported here https://github.com/almende/chap-links-library/issues/336

**Comment by ova2** [comment]
The autor of the native plugin gave us a tip. This is not the problem of Timeline. Please look into this https://github.com/almende/chap-links-library/issues/336 Thomas, you can do the same.

@sasynkam Can you conform please, you use excanvas.js?

**Comment by sasynkam** [comment]
Hi, we don't use excanvas.js

**Comment by ova2** [comment]
Timeline doesn't use createStyleSheet too. Are you sure the error is raised by Timeline and not by core.js or from somewhere else?

**Comment by sasynkam** [comment]
Not, but it looks like that: http://postimg.org/image/3zxfeekq1
Moreover timeline in PrimeFaces Extensions Showcase works.

**Comment by ova2** [comment]
It is not Timeline related. It is somewhere in core.js. Assigned to Thomas. Probably a fix in PF is also nessesary. Thomas, can you add something like?

```javascript
if  (typeof document.createStyleSheet === 'undefined') {
  document.createStyleSheet = function () {
    return document.createElement('script');
  }
}
```
