### ISSUE TITLE
InputNumber - set decimal value to minValue

### ISSUE THREAD

**Issue by kikutaro** [primefaces-extensions/primefaces-extensions.github.com#306]
I set 1.5 to minValue for InputNumber component.
 
```XML
<pe:inputNumber minValue="1.5" value="#{inputNumberBean.val}" />
```
It couldn't accept like 1.6, 1.7, 1.8 ...etc , it only accept over 2.0. Is this right spec or need some settings?

I use PrimeFaces Extension 2.1.0 in javaee-web-api 7.0.

**Comment by tandraschko** [comment]
works fine for me in the showcase (http://localhost:8080/primeext-showcase/sections/inputNumber/basicUsage.jsf) if add minValue e.g. to ="1.5", the js from the inputnumber plugin throws an error
