### ISSUE TITLE
Create pe:signature component

### ISSUE THREAD

**Issue by pbellede** [primefaces-extensions/primefaces-extensions.github.com#309]
Hello,

Can you create a signature component based on 

https://github.com/willowsystems/jSignature/

Thanks a lot

**Comment by tandraschko** [comment]
we could but primefaces extensions is community based, so please develop it and create an pull request.
if you would like to sponser it, you can contact oleg or me or use PrimeFaces PRO.

**Comment by ova2** [comment]
I agree with Thomas. Nobody will implement this component in PF Extensions unless you go Extensions PRO http://www.primefaces.org/support.html or will implement it yourself and submit per a Pull Request.
