### ISSUE TITLE
ckEditor loses html tags if toolbar doesn't have button of that tag

### ISSUE THREAD

**Issue by mncs** [primefaces-extensions/primefaces-extensions.github.com#311]
Hi. I'm trying render html text into a readonly ckEditor. For do this, use an empty toolbar to show only the text, but when I do that I lose all html tags in my text and only  "\<p>" tags appear.

If I add the corresponding button to the toolbar, html tag of that button appear in editor. 
For example if I add the "Bold" button to the toolbar, I have the "\<strong>" tag in my text, but if I don't add that button the \<strong>, the tag dissapears from my text.

Here is a sample
My Html text: 
\<p>This is \<strong>a strong text\</strong>\</p>

Using this, ckeditor works:
pe:ckEditor id="editor" value="#{bean.getText()}" 																toolbar="[['Bold']]" readOnly="true" 

But if I quit the "Bold button" from the toolbar I lose the \<strong> tag
pe:ckEditor id="editor" value="#{bean.getText()}" 																toolbar="['']" readOnly="true" 

This is the html of this case: \<p>This is a strong text\</p>

**Comment by tandraschko** [comment]
Sounds releated to CKEditor, not to our small bridge.
Please ask the CKEditor guys and if we can fix something, come back to us.

**Comment by mncs** [comment]
Ok, thanks I'll write here their response.

**Comment by tandraschko** [comment]
will close it for now.
