### ISSUE TITLE
Gridster - Dashboard Tool

### ISSUE THREAD

**Issue by rider87** [primefaces-extensions/primefaces-extensions.github.com#312]
Dear all, 

Could you implement in Primefaces this drag tool?
The javascript is already available. You will find it here: http://gridster.net/

Please add  also resize:
http://gridster.net/demos/using-resize-callbacks.html

This would be very useful for create your own dashboard.
Best Regards

**Comment by tandraschko** [comment]
Hi,

as primefaces extensions is a community based project, please develop it and create a pull request.
It's unlikely that anyone of us will implement it for you.

**Comment by ova2** [comment]
I agree with Thomas. Nobody will implement this component in PF Extensions unless you go Extensions PRO http://www.primefaces.org/support.html or will implement it yourself and submit per a Pull Request.
