### ISSUE TITLE
pe:documentViewer - locale not loading

### ISSUE THREAD

**Issue by feverdog** [primefaces-extensions/primefaces-extensions.github.com#314]
Greetings,

The DocumentViewer component is not loading "pt_BR" locale, every other locale seems fine but this one is not working.

I have tried every possible combination with no success "pt_br", "pt-br", "pt-BR", "pt", "br"

Thumbs up for your work guys, I really do enjoy PE!
Thank you very much :D

**Comment by tandraschko** [comment]
All locales are listed here:
https://github.com/primefaces-extensions/core/tree/master/src/main/resources/META-INF/resources/primefaces-extensions/documentviewer/locale

More locales may be available if we would upgrade PDF.js

**Comment by melloware** [comment]
Fixed in 6.1 by upgrading to PDF.js 1.5.188 I also added to the Showcase an example of switching to pt_BR and it works fine.
