### ISSUE TITLE
pe:exporter - complex cellEditor facet output

### ISSUE THREAD

**Issue by Julienng** [primefaces-extensions/primefaces-extensions.github.com#315]
I have a complex editable dataTable with some customization for the user. I want to export to pdf/excel but i have a issue.

For instance:  
```html
<p:dataTable id="tableId" var="car" value="#{sandboxBean.cars}"
		paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink}"
		paginator="true" rows="10" style="margin-bottom:20px" editable="true" editMode="cell">

		<p:columns var="col" value="#{sandboxBean.columnCars}">
			<f:facet name="header">
				<h:outputText value="#{col}" />
			</f:facet>
			<p:cellEditor>
				<f:facet name="output">
					<h:outputText value="#{car[col]}" style="background: lightyellow;" rendered="#{col == 'year'}" />
					
					<h:outputText value="#{car[col]}" style="background: lightblue;" rendered="#{col == 'id'}" />
					
					<h:outputText value="#{car[col]}" style="background: lightgreen;" rendered="#{col != 'year' and col != 'id'}" />
				</f:facet>
				<f:facet name="input">
					<p:inputMask value="#{car[col]}" rendered="#{col == 'year'}" mask="9 999" />
					
					<p:inputText value="#{car[col]}" rendered="#{col == 'id'}" />
					
					<p:inputText rendered="#{col != 'year' and col != 'id'}" />
				</f:facet>
			</p:cellEditor>
		</p:columns>
	</p:dataTable>
```
The result is javax.faces.component.UIPanel@xxxxx instead of the value of the cell.
The same example works well if I only have one component in the facet output.

**Comment by sudheerj** [comment]
Normally exporter will fetch the datatable data from single h:outputText. Sometimes it is required/mandatory to have multiple components inside the column component.In that case you can use custom exporter to customize the export code according to your requirements.

 But in your case you can use single h:outputText itself with multiple conditions for style property.So just remove multiple output elements with single output element which has multiple conditions.

**Comment by Julienng** [comment]
This example is a just an example of my issue. In my real case, I can't handle my facet output with only one outputText.

*Why the component support a partial use case of celleditor ?*  
I understand that I can use the custom exporter but that can be a good feature to support this case natively.

**Comment by sudheerj** [comment]
Most of the datatable columns will have single outputText to display the data.So it is advised to have single instance(applying conditions) instead of multiple outputtext values.

It is not correct.Normally every datatable(including celleditor) represented with single outputtext value only.Anyway we will review the need and possibility of this issue,based on that either we will implement this or close this issue.

**Comment by sudheerj** [comment]
We can better manage this scenario with single outputtext by evaluating conditions from controller instead of supporting multiple outputtext values.
