### ISSUE TITLE
pe:tristateCheckbox - check default event

### ISSUE THREAD

**Issue by anatoly314** [primefaces-extensions/primefaces-extensions.github.com#317]
in a pe:triStateCheckbox component you can't use p:ajax without specifying an event like you're showing in your showcase here: http://www.primefaces.org/showcase-ext/views/triStateCheckbox.jsf
Instead you should write <p:ajax event="change" ... /> like is written on your showcase repository in github. You can see for more details SO question here: http://stackoverflow.com/questions/29393082/petristatecheckbox-doesnt-work-with-pajax/29393388?noredirect=1#comment46963535_29393388

**Comment by ova2** [comment]
Please provide a pull request.

**Comment by tandraschko** [comment]
will also check it for tristateManyCheckbox

**Comment by ova2** [comment]
Hi guys,

This pull request introduced a new bug. I have created an issue https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/386
