### ISSUE TITLE
Timeline start and end parameters are not taken into account

### ISSUE THREAD

**Issue by amoralico** [primefaces-extensions/primefaces-extensions.github.com#323]
Due to resolution issue #313, now start and end parameters are not taken into account.

You should take it into account in links.Timeline constructor.before call     

this.setVisibleChartRange(undefined, undefined, false);

**Comment by ova2** [comment]
I haven't understood. What is links.Timeline constructor.before and where is problem exactly? Is it reproducable in the showcase?

**Comment by amoralico** [comment]
I mean the attributes 'start' and 'end' used in tag  <pe:timeline>.

links refers to the javascript class 'links.Timeline'. and I think the problem is here
https://github.com/primefaces-extensions/core/commit/1b8cd985a7cc29cb1946290b6d55a9112832a3b2

when lines 305 to 309  were removed/replaced.

It is not reproducible in the show case because these attributes are not used.

**Comment by ova2** [comment]
Ok, thanks, I see. I have created an issue for the native Timeline script: https://github.com/almende/chap-links-library/issues/346

We will see, maybe I will create a pull request for the native script or fix this issue in the PF Extensions for the next release.

**Comment by ova2** [comment]
Fixed
