### ISSUE TITLE
pe:javascript: ReferenceError: ext is not defined

### ISSUE THREAD

**Issue by ova2** [primefaces-extensions/primefaces-extensions.github.com#326]
`pe:javascript` with DOM events causes an JS error: "ReferenceError: ext is not defined". Try e.g.

```javascript
<p:selectManyCheckbox ....>
    <pe:javascript event="change" execute="alert('Wow')"/>
</p:selectManyCheckbox
```

The `onchange` callback in the rendered HTML looks as

```
onchange="PrimeFacesExt.behavior.Javascript({source:'...',event:'change',execute:function(source,event,params,ext){alert('Wow');}},ext);"
```

The `ext` at end is the problem. This is because we don't consider PF's `ClientBehaviorRenderingMode` in the `JavascriptBehaviorRenderer` like the `AjaxRequestBuilder` does it:

```java
    public String buildBehavior(ClientBehaviorRenderingMode mode) {
        addFragmentConfig();
        
        if(mode.equals(ClientBehaviorRenderingMode.UNOBSTRUSIVE))
            buffer.append("},ext);");
        else if(mode.equals(ClientBehaviorRenderingMode.OBSTRUSIVE))
            buffer.append("});");
        
        if(preventDefault) {
            buffer.append("return false;");
        }
        
        String request = buffer.toString();
        
        reset();
        
        return request;
    }
```

We should check the `ClientBehaviorRenderingMode` in the `JavascriptBehaviorRenderer` too (before doing or not `script.append("},ext);");`).

Not DOM events are ok because behaviors are rendered with `ClientBehaviorRenderingMode.UNOBSTRUSIVE`.

**Comment by ova2** [comment]
Thomas, I have fixed this issue. Can you please review my changes in JavascriptBehaviorRenderer.java? Thanks.

**Comment by tandraschko** [comment]
Looks fine. If it works in your tests, everything is perfect. Thanks Oleg.

**Comment by ova2** [comment]
Yes, it works in all tests with all events.
