### ISSUE TITLE
AjaxErrorHandler in Extensions 3.1.0 doesn't work with PF 5.2

### ISSUE THREAD

**Issue by ova2** [primefaces-extensions/primefaces-extensions.github.com#327]
Thomas, can you look into this? It is reproducable in every example. The dialog doesn't appear. Furthermore, I think `buttonOnclick="ajaxErrorHandler.hide();"` in examples should be rewritten as `buttonOnclick="PF('ajaxErrorHandler').hide();"`.

By the way, should we maybe remove this component in favor of the PrimeFaces' ExceptionHandler?

I would remove some old components from Extensions in the next major release.

**Comment by tandraschko** [comment]
If pavol doesn't like to maintain it anymore, we should just remove it.
I really don't have much time and i will not invest it in components i've never used.

**Comment by ova2** [comment]
Ok, I will remove it then if Pavol will not fix this issue in the next weeks.

**Comment by ova2** [comment]
Done. The AjaxErrorHandler removed.

Added PrimeExceptionHandlerFactory and PrimeExceptionHandlerELResolver to the showcase in order to use the PrimeFaces' ExceptionHandler.

**Comment by Species8372** [comment]
I am currently migrating from an older primefaces-extensions Version.
I didnt find the removal of this feature anywhere, are there release-notes?
Also i am quite concerned that tandraschko is using all other features of this library, else he would remove them when they are having a bug?!

**Comment by ova2** [comment]
See the homepage http://primefaces-extensions.github.io/ and the release notes https://github.com/primefaces-extensions/primefaces-extensions.github.com/wiki/Release-Notes.

**Comment by tandraschko** [comment]
@Species8372
It's not my fault if there is no active community to fix bugs.
Pavol isn't active since many many months and there is a ExpceptionHandler available in PF core. 
There is no reason for me or oleg to spend time to fix.
