### ISSUE TITLE
Add a regex to validate the complete input with KeyFilter

### ISSUE THREAD

**Issue by Julienng** [primefaces-extensions/primefaces-extensions.github.com#328]
Hi,
I want to limit the length of my input before and after dot with something like `/[0-9]{3}\.[0-9]{2}/`.
This regEx don't work, I can't add number in.

Is it an issue ? Someone know a workaround for this ?

**Comment by Julienng** [comment]
After read the code, I fork and implement it.  
I can handle regEx like that `/^[0-9]{0,3}((\\.|,)[0-9]{0,6}|)$/`. This is a fast implementation and the name of my parameter is not really explicit. But it work well.

**Comment by tandraschko** [comment]
feel free to provide a pull request + description what you changed.

**Comment by Julienng** [comment]
I will. Just need to clean my code.
This is not a bug, the keyFilter was based on keyPress. I add a a function based on the event 'input' to look on the complete field.
