### ISSUE TITLE
InputNumber hidden value field is not being updated for Ajax keypress Event

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions.github.com#330]
If you have a p:ajax event="keypress" you will see the hidden is not updated and thus not sent to the server side on keypress.

If you use p:ajax event="change" everything works but that is only after the field is exited.

**Comment by tandraschko** [comment]
should work now. please give it a try.

**Comment by melloware** [comment]
Looks good.  thanks for fixing!
