### ISSUE TITLE
pe:timeline - Add customStackOrder option for timeline item

### ISSUE THREAD

**Issue by spauny** [primefaces-extensions/primefaces-extensions.github.com#331]
The native widget for timeline supports customStackOrder for forcing some items to be always stacked on top or bottom: 
customStackOrder: "Provide a custom sort function to order the items. The order of the items is determining the way they are stacked. The function customStackOrder is called with two parameters, both of type 'timeline.Item'"

Is there any way we could have this in the primefaces extensions timeline implementation? 

Thank you!

**Comment by ova2** [comment]
I'm not sure if I have time to add this feature. Feel free to provide a Pull Request :-) We are an open source project. Pull Requests are welcome!

**Comment by ova2** [comment]
Please create an issue in the PrimeFaces core. This component was migrated to PrimeFaces.
