### ISSUE TITLE
pe:exporter - Multitarget within ui:repeat

### ISSUE THREAD

**Issue by AzoJason** [primefaces-extensions/primefaces-extensions.github.com#334]
The pe:Exporter is allowing the export of multiple tables in one file.

This doesnt work, if the tables are generated within an ui:repeat tag.

The following maven project demonstrates the behaviour:
http://s000.tinyupload.com/?file_id=76733303821918612665

The contents of the tables in the exported file are empty.

Requesting feedback regarding fixability of this issue.

**Comment by sudheerj** [comment]
How it works inside c:forEach tag? Is it the issue posted in forum as well?

**Comment by tandraschko** [comment]
Please reopen if you provide feedback. Will close it for now.
