### ISSUE TITLE
"readOnly" attribute should be "readonly" in pe:ckEditor 3.1.0?

### ISSUE THREAD

**Issue by persapiens** [primefaces-extensions/primefaces-extensions.github.com#335]
When I use pe:ckEditor component in netbeans, it warns readOnly attribute does not exist, but it works!
If I use readonly, netbeans stops warning, but it does not work!

**Comment by tandraschko** [comment]
you are right.
The taglib is correct but the component class and renderer must be changed -> https://github.com/primefaces-extensions/core/tree/master/src/main/java/org/primefaces/extensions/component/ckeditor

please provide a pull request.
