### ISSUE TITLE
KeyFilter Turkish Keyboard Problem

### ISSUE THREAD

**Issue by tolgaonbay** [primefaces-extensions/primefaces-extensions.github.com#341]
Hi,

We found a bug in keyFilter component that is AFAIK only valid in Turkish keyboards. Some of the special characters (e.g. #, $, @, ...) can be used even if they are filtered out in the component with a valid regex. Those characters that I mentioned are generated with an AltGr key. Some of the mappings include:
```
AltGr + 3 => #
AltGr + 4 => $
AltGr + Q => @
AltGr + ] => ~
```

For example with below definition, users can enter #, $, @ characters in a Turkish keyboard.
```xml
<pe:keyFilter for="vkn" regEx="/[0-9]/i" preventPaste="false" />
```

You can look at the Turkish keyboard layout from http://ascii-table.com/keyboard.php/179

At the below line, e.ctrlKey and e.altKey are both true for the specified key strokes. I don't think it is a right solution, but if I remove the if condition from the script, it works like a charm. If you could tell me what this if condition is written for, I can create a fix and send it back to you guys. 

https://github.com/primefaces-extensions/core/blob/master/src/main/resources/META-INF/resources/primefaces-extensions/keyfilter/0-jquery.keyfilter.js#L104

Thanks

**Comment by ova2** [comment]
Thomas, what do you think, would be the patch ok?

**Comment by tolgaonbay** [comment]
@tandraschko @ova2 any idea?

**Comment by tandraschko** [comment]
Hi,

the jquery plugin is a external plugin.
There is also a newer version available AFAICS: https://github.com/akzhan/jquery-keyfilter/

Could you try 1.8? If it sill doesn't work, please consider to create a issue in their github repo.

**Comment by tandraschko** [comment]
Any news on this?
