### ISSUE TITLE
pe:documentViewer 3.2.0 not working in PF5 5.2.6 Chrome

### ISSUE THREAD

**Issue by koekiebox** [primefaces-extensions/primefaces-extensions.github.com#346]
PDF Document Viewer is not working in PrimeFaces when using Chrome. I get a JavaScript error when using Chrome.

Firefox 32.0.3 works, but not Chrome 43.0.2357.130.

Link to issue: http://forum.primefaces.org/viewtopic.php?f=14&t=42573

**Comment by francesco-strazzullo** [comment]
@koekiebox did you try the showcase version?

**Comment by francesco-strazzullo** [comment]
On the showcase with Chrome everything it's working fine. Closing it!
