### ISSUE TITLE
Master Detail with Data Table Filter

### ISSUE THREAD

**Issue by Ryaryu** [primefaces-extensions/primefaces-extensions.github.com#347]
I have a Master Detail, and in the 2nd level, a DataTable with Filtering. The Filter is a drop-down (using facets).

The problem is: I click in a row in the 1st level table to go to the 2nd level, change the filter in the drop-down, then change it back to default value (null), then go back to 1st level, then reopen the 2nd level by clicking in another row there. For some reason, the DataTable stops updating when I return to the 2nd level (it still has the first clicked row's data), as if there was an error in the request.

If you can't reproduce the problem, please post and I'll give a code (trying to make this issue small).

Primefaces-Extensions version is 3.2.0, Primefaces version is 5.2, JSF is 2.2.10 and using WildFly 8.2.0 Final.

**Comment by ova2** [comment]
I don't think this is a problem with MasterDetail. Have you tried this without MasterDetail? I think you have to reset the filtered data set on the client- oder server-side. PrimeFaces have both - client- and server-side APIs for table reset. Please try to reset the table.

**Comment by Ryaryu** [comment]
It seems to be the case. I've researched and found that Primefaces exposes a method clearFilters() for DataTables. By using it I was able to update the table. Thank you.
