### ISSUE TITLE
InputNumber not processed as input:visible

### ISSUE THREAD

**Issue by feverdog** [primefaces-extensions/primefaces-extensions.github.com#348]
Greetings,

I have a form that contains several inputs, that will be hidden/shown using javascript, accordingly to the business rules.Then I set the command button to process only the visible inputs, like this:

 <p:commandButton id="buttonConsultar" value="Consultar"
                                         icon="ui-icon-search alt-icon"
                                         styleClass="btn btn-green" 
                                         process="@this, @(input:visible)"
                                         action="#{vc.consultar}" />

And it works perfectly with all of the visible inputs, except for "pe:inputNumber" which is not processed, so the value is never sent to the backing backing bean.

A workaround for this is setting for the commandButton to manually process the inputNumber component:

 <p:commandButton id="buttonConsultar" value="Consultar"
                                         icon="ui-icon-search alt-icon"
                                         styleClass="btn btn-green" 
                                         process="@this, @(input:visible), valorCheque"
                                         action="#{vc.consultar}" />

Well, I don't know if this helps, but I thought that maybe you guys would like to improve it, in order to have the same behavior as primefaces itself.

Best Regards.

**Comment by tandraschko** [comment]
Thats not possible as the inputNumber is designed with a visible an invisible input.
the visible input display the formatted value, the hidden input contains the real and cleaned value.
