### ISSUE TITLE
pe:documentViewer - Print Option not printing correctly

### ISSUE THREAD

**Issue by ehurt** [primefaces-extensions/primefaces-extensions.github.com#350]
When we use the print button on the document viewer, the output cut off certain pages and images get cut off. The printed version looks really bad. I have saw on the pdf.js site, they are resolving some of these issues. The version of primefaces extensions we are using is 3.0.0.

**Comment by francesco-strazzullo** [comment]
Did you tested the print on the showcase example?

**Comment by ehurt** [comment]
I just tested it out in the showcase. It cut off text in your example in the table of contents. The page breaks look wrong. The table of contents is shirt down in the page.

**Comment by francesco-strazzullo** [comment]
Ok I will try it! Thanks!

**Comment by tandraschko** [comment]
Will close it for now, updating PDF.js might fix it.
