### ISSUE TITLE
codeMirror doesn't have attributes "requiredMessage" and "validator" in taglib but it supports them implicity

### ISSUE THREAD

**Issue by xtron** [primefaces-extensions/primefaces-extensions.github.com#351]
![codemirror](https://cloud.githubusercontent.com/assets/345073/8775680/2e3904d6-2ef3-11e5-8ebd-afd4f5aed534.png)

**Comment by xtron** [comment]
Аnd also "valueChangeListener" attribute.

**Comment by tandraschko** [comment]
please provide an pull request.

**Comment by xtron** [comment]
Ok.
https://github.com/xtron/core/commit/99c131a5a2a294d325e10d5744b4e60143dfcffc

**Comment by tandraschko** [comment]
Thanks!
