### ISSUE TITLE
pe:documentViewer - doesn't work in IE9

### ISSUE THREAD

**Issue by spadovan** [primefaces-extensions/primefaces-extensions.github.com#353]
DocumentViewer does not display the pdf file if i use Internet Explorer 9.
It works ok on Mozilla Firefox.

...using Primefaces Extensions 3.2.0

**Comment by francesco-strazzullo** [comment]
Hi spadovan, I will look into it!

**Comment by tandraschko** [comment]
Will close it for now, maybe a PDF.js would fix it.

**Comment by melloware** [comment]
Modified in 6.1 by upgrading to PDF.js 1.5.188.  They claim limited support for IE9.

https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

"IE9	limited	none	IE9 lacks a number of features and most notably typed arrays which causes subpar performance."
