### ISSUE TITLE
PF 5.2.10 Issue with PE InputNumber

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions.github.com#354]
I am using p:outputlabel with a pe:inputnumber and it works fine in PF 5.2.9 but in 5.2.10 I am seeing this error upon rendering.

PF 5.2.10
PFE 3.2.0
Mojarra 2.2

java.lang.AbstractMethodError: org.primefaces.extensions.component.inputnumber.InputNumber.setLabelledBy(Ljava/lang/String;)V
	at org.primefaces.component.outputlabel.OutputLabelRenderer.encodeEnd(OutputLabelRenderer.java:64)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:919)
	at org.primefaces.renderkit.CoreRenderer.renderChild(CoreRenderer.java:88)
	at org.primefaces.renderkit.CoreRenderer.renderChildren(CoreRenderer.java:71)
	at org.primefaces.component.panelgrid.PanelGridRenderer.encodeRow(PanelGridRenderer.java:196)
	at org.primefaces.component.panelgrid.PanelGridRenderer.encodeStaticBody(PanelGridRenderer.java:151)

**Comment by tandraschko** [comment]
Exntensions is not compatible with a elite release. We will fix it when we do a release for 5.3.

**Comment by kito99** [comment]
Hello @tandraschko, to clarify, what you're saying is that you don't guarantee compatibility with Elite releases in between the major releases, correct? You're not saying that Extensions should never be used with Elite releases, are you?

**Comment by tandraschko** [comment]
Hey kito,
exactly - it's to much effort to check compatibility and do releases after each elite release. You know, it's community based.

**Comment by ova2** [comment]
Agree with Thomas.

**Comment by kito99** [comment]
Thanks, @tandraschko. Do you guys fix issues like this for PrimeFaces PRO users who have the PrimeFaces Extensions support option?

**Comment by ova2** [comment]
I think if you have the PrimeFaces Extensions support option, it could be interesting for Thomas. Regarding me - I'm moving right now from JSF to AngularJS :-). My JSF activities are going down. I can still do small maintenance tasks and releases, but pull requests would be much better for us.

**Comment by tandraschko** [comment]
@kito99 never talked with anyone about such elite bugfix releases because it may really only work for a special elite version like 5.2.10.
But i think doing this via the PrimeFaces Extensions support option might be no problem actually. Just need to about if we really need a offical realease or it's enough to provide it via PrimeFaces portal.

**Comment by xKopax** [comment]
"Regarding me - I'm moving right now from JSF to AngularJS :-)."
@ova2  I know it's offtopic, but too sad to read this ='(

**Comment by fkjaekel** [comment]
IMHO, since PrimeFaces Extensions is recognized by PrimeFaces (link inside PF showcase, Extensions forum inside official forum, etc), also because it's highly used, they should ensure that new Elite versions will keep compatible with Extensions.

**Comment by tandraschko** [comment]
We just don't have time to do that. The current community isn't very active and i can't maintain this project for every elite release cause i'm active in many projects.
PrimeFaces PRO might be an option if you would like to sponsor it.
Otherwise feel free to fix it and provide a pull request. You can build from the git master than.

**Comment by fkjaekel** [comment]
Maybe a Elite program for Extensions too? I would surely pay for it.

We need some guarantee that Elite + Extensions will play nice together.

**Comment by tandraschko** [comment]
I will talk with Oleg and Cagatay and will come back to you via this ticket.

**Comment by melloware** [comment]
Thanks for looking into this @tandraschko .  We have been a huge PF supporter and PRO customer for 3 years and we extensively use PE Timepicker and Inputnumber in our suite of applications.  This marrying of Extensions + PRO would be extremely valuable.

**Comment by alfonx** [comment]
A a quick&diry fix that can help:
1. Copy InputNumber.java from the extensions source code into your project
2. Add the new required methods:


 	@Override
	public void setLabelledBy(String labelledBy) {
		getStateHelper().put("labelledby", labelledBy);
	}

	@Override
	public String getLabelledBy() {
		return (String) getStateHelper().get("labelledby");
	}

	@Override
	public String getValidatableInputClientId() {
		return this.getClientId(getFacesContext()) + "_input";
	}
3. Now there is a good chance that your server (e.g. tomcat7) will pickup the modified class and everything works live a charm.

Note: I know this is an ugly hack, but this approach worked for me many times...

**Comment by tandraschko** [comment]
Fixed in trunk. Please test test test everything!

**Comment by melloware** [comment]
5.3 has been officially released.  When is PFE getting released to match it?

**Comment by ova2** [comment]
http://forum.primefaces.org/viewtopic.php?f=14&t=43543&sid=a058273d2070b6c5ef6b2fb2096ee781
