### ISSUE TITLE
Bug in the "Timeline:Editable events and server-side API" example

### ISSUE THREAD

**Issue by backtozero** [primefaces-extensions/primefaces-extensions.github.com#355]
When you create a new book with the same room number as existed on the timeline, you will change already existed booking with that number.
Also if you delete the new booking, the booking with the same room number will be lost.

**Comment by ova2** [comment]
Maybe. But this is an application logic and not the logic of the component. The component itself is fine.

**Comment by backtozero** [comment]
As i understand this is the source.
```java
 @Override  
  public int hashCode() {  
        return roomNumber != null ? roomNumber.hashCode() : 0;  
  } 
```
