### ISSUE TITLE
ImageAreaSelect maxWidth maxHeight seems Not working

### ISSUE THREAD

**Issue by maggo2801** [primefaces-extensions/primefaces-extensions.github.com#356]
In Version 3.2.0 seems maxWidt and maxHeight Not working. 
The selection area ignore these settings and go bigger.

**Comment by tandraschko** [comment]
Please provide an pull request to fix the problem.

**Comment by tandraschko** [comment]
It's a community based project. If you don't provide a pull request, it's not guaranteed that i will fixed it.
Please investigate and provide a pull request, i will a do a review.
We really need the community to keep the project alive.

**Comment by tandraschko** [comment]
Should be fixed.
