### ISSUE TITLE
New Component: pe:updateOn and component/component id independent updates

### ISSUE THREAD

**Issue by tandraschko** [primefaces-extensions/primefaces-extensions.github.com#358]
pe:updateOn has 3 modes:

1) "key" based mode

<pe:updateOn key="userdata-changed" />

pe:updateOn can be a child of a component
e.g.
 <h:ouputpanel>
    <pe:updateOn key="userdata-changed" />
</h:outputPanel>

the user can use the "key" mechanism via
RequestContext.update("@key(userdata-changed)");
or even
p:ajax update="@key(userdata-changed)"

2) AutoUpdate for every component (simliar to PrimeFaces autoUpdate flag)

<pe:updateOn auto="true"  />

3) "trigger" based mode 
The target component decides when it will be updated, not the button:
<pe:updateOn trigger="@form:myButton" />

**Comment by tandraschko** [comment]
I won't implement this is extensions but i leave it for future to not forget about it.

**Comment by melloware** [comment]
Closing now that https://github.com/primefaces/primefaces/issues/2838 has been created in PrimeFaces.  If anybody needs the extra features listed here we can always re-open this ticket.

**Comment by tandraschko** [comment]
+1

**Comment by Rapster** [comment]
As an example for updateOn: https://github.com/encoway/edu (no longer maintened)

**Comment by Rapster** [comment]
I'm quite interested for having a "key for subscription" on `p:autoUpdate`. I'd like to write something like:

```xml
<pa:menuButton id="cart"
               icon="fa-shopping-cart"
               model="#{cartManager.cartModel}"
               badge="#{cartManager.total}">
    <p:autoUpdate on="update-cart" listener="#{cartManager.createMenuModel}" />
</pa:menuButton>

<p:button value="#{i18n['IMEXP_START_NEW_CONF']}"
          onclick="PF('dlgCreateConf').show()"
          rendered="#{confVersionController.confVersionAvailableForCreation}"
          update="@on('update-cart)"/>
```

Does it make sense to you?

**Comment by tandraschko** [comment]
sure, thats the same thing as the "key mode" in my first post; maybe we can also call it event/observer like CDI

**Comment by Rapster** [comment]
Should I create a ticket on PF then? The idea being to extend `p:autoUpdate` and not create a new component

**Comment by tandraschko** [comment]
yep
