### ISSUE TITLE
Server-side updates of timeline does not work when no widgetVar attribute is defined.

### ISSUE THREAD

**Issue by TheodorRichard** [primefaces-extensions/primefaces-extensions.github.com#359]
See http://stackoverflow.com/questions/32562998/jsf-primefaces-extensions-timeline-how-to-update-a-timeline-via-ajax for details.

**Comment by ova2** [comment]
Ok, thanks. I will look into this,

**Comment by TheodorRichard** [comment]
Hi ova2,

another issue that I noticed is that the JS file primefaces-extensions.source.js is loaded from github directly. See this screenshot:


![web_inspector_ _localhost_ _view_jsf](https://cloud.githubusercontent.com/assets/13250030/10069990/f7cb39a0-62af-11e5-862f-889d25e47d55.png)

Why is that? Same is also true for the showcase. Should I file a bug?

**Comment by ova2** [comment]
This is a feature (primefaces-extensions.source.js is loaded from github) to enable debugging of compressed files. It is only loaded from github if you open the browser dev. tools. See my blog post http://ovaraksin.blogspot.ch/2015/06/create-source-maps-at-project-build.html

**Comment by TheodorRichard** [comment]
Ah, ok, wasn't aware that this is possible at all. Thanks for the info!

**Comment by ova2** [comment]
I can not reproduce this behavior. The same scenario is working fine in the showcase http://www.primefaces.org/showcase-ext/sections/timeline/basic.jsf Timeline gets updated on Ajax requests without any widgetVar.

**Comment by aaronkelly111** [comment]
I was able to reproduce this in 6.0.

**Comment by ova2** [comment]
Timeline component was moved to PrimeFaces. Please ask in the PrimeFaces forum.
