### ISSUE TITLE
Is ajaxErrorHandler removed in v 4.0

### ISSUE THREAD

**Issue by rdebusscher** [primefaces-extensions/primefaces-extensions.github.com#360]
Changing the maven dependency from 3.1 to 4.0 gives error on the tag pe:ajaxErrorHandler

**Comment by tandraschko** [comment]
Jep, was removed because the developer is inactive since about 1-2 years and we had several bugs/missing features. Sorry.
The ExceptionHandler in PrimeFaces is more flexible.

**Comment by ova2** [comment]
Hi Rudi. It was removed in 3.2 in favor of PrimeFaces AjaxHandler. See https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/327

**Comment by rdebusscher** [comment]
Thanks for the info. I'll have a look at the PrimeFaces one.
