### ISSUE TITLE
pe:switch/case - switch evaluates cases only when rendering

### ISSUE THREAD

**Issue by VsevolodGolovanov** [primefaces-extensions/primefaces-extensions.github.com#362]
Extensions 4.0.0.

	<h:form>
		<ui:repeat value="#{[1,2]}" var="v">
			<pe:switch value="#{v}">
				<pe:case value="#{1}">
					<p:inputText value="#{bean.value}" />
				</pe:case>
				<pe:defaultCase>
					no inputs here
				</pe:defaultCase>
			</pe:switch>
		</ui:repeat>
		<p:commandButton value="submit" process="@form" />
	</h:form>

Switch sets cases `rendered` value only during Render Response. A single component instance can be reused, e.g. when iterating with ui:repeat. This leads to the problem: in the example above the input value won't reach the bean property.

* Request 1, GET, rendering.
  * First ui:repeat iteration: pe:case for v=1 setRendered(true).
  * Second ui:repeat iteration:  pe:case for v=1 setRendered(false).
* Request 2, POST (submitted form), decoding (JSF phase Apply Request Values).
  * First ui:repeat iteration: pe:case for v=1 isRendered() == false since previous request. Decode processing doesn't reach p:inputText.

Switch should evaluate cases and call setRendered during other JSF phases, in processDecodes, processValidators, processUpdates and broadcast. Also in visitTree (except during Restore View), otherwise e.g. p:autoComplete completeMethod won't get called. Not sure about invokeOnComponent.

Other suggestions:
* better move the render time case evaluation to the component too, it doesn't belong in a renderer;
* don't render a div, Switch shouldn't render any markup itself. (It's unexpected a bit harmful: e.g., when choosing an input, I don't want an extra block element wrapper.)

**Comment by tandraschko** [comment]
Feel free to provide a pull request.
I never used the component, it was one of my first component and it will likely not move to PrimeFaces.

**Comment by VsevolodGolovanov** [comment]
> it will likely not move to PrimeFaces

That's sad, it's useful.
For example:
```
<p:dataTable ...>
	<p:columns ... var="column">
		<pe:switch value="#{column.type}">
			<pe:defaultCase>
				<!-- default representation -->
			</pe:defaultCase>
			
			<!-- inheriting template can customize certain columns with pe:case  -->
			<ui:insert name="custom_column_cases" />
		</pe:switch>
	</p:columns>
</p:dataTable>
```

**Comment by tandraschko** [comment]
Maybe we will do something like a poll, don't know.
I just know that there are not many users of the component and it can be replaced by rendered="...".

**Comment by tandraschko** [comment]
if you don't provie a PR, i will close it as won't fix bevor the upcoming release.

**Comment by VsevolodGolovanov** [comment]
Will providing a PR improve the chances of surviving the move to PrimeFaces? What's the deadline for the upcoming release? I thought of pitching this component to OmniFaces.

**Comment by tandraschko** [comment]
We still discussing which components will move or not but i think extensions won't die completely.
Whats sure is that we will release a 6.0 version after the PF 6.0, with the component that were not migrated. 
e.g. importConstants moved to PF, so we will remove it from PFE.

Also 6.0, PFE will move to "maintanence mode".
That means for me:
- If a API changes in PF, i will make PFE compatible
- No new components
- Issues without pull requests from the community will be closed
- Not sure if we will do releases but there are services available like jitpack

I think your changes improves the chance as it will be tweaked for "real world".
I think PF will be releases April-Mai.

**Comment by VsevolodGolovanov** [comment]
PR sent: https://github.com/primefaces-extensions/core/pull/24

**Comment by tandraschko** [comment]
Thanks!
