### ISSUE TITLE
pe:inputNumber minValue > 10 broken

### ISSUE THREAD

**Issue by dalbert2** [primefaces-extensions/primefaces-extensions.github.com#364]
Validation appears to be performed with each keystroke so f you set the minValue = 5, you can't enter any numbers smaller than 5 in the field (so for example, you couldn't enter 15).  If you enter 65 and then try to back up, you can't delete the 6 (because 0 is below the minValue).  minValue is badly broken

<pe:inputNumber value="#{maxTemp}" minValue="25" maxValue="85" decimalPlaces="0"  />

**Comment by tandraschko** [comment]
please check the jquery autonumeric plugin - we just wrapped it.

**Comment by tandraschko** [comment]
Notes from the plugin page: 

IMPORTANT - please understand that vMin & vMax settings are limits. Meaning the user cannot enter a value greater than the vMax value and cannot enter or delete a value below the vMin setting. When setting the vMin & vMax values to both positive or negative you could create a paradoxical situation which limits the user ability to enter values. Consider the following:

    vMin:'5' & vMax:'10' - you can never enter the number 10.
    vMin:'10' & vMax:'100' and no default value - you can never enter any value.
    vMin:'0.01' & vMax:'9.99' and no default value - you can not start to enter number less than 1.
    vMin:'0.00' & vMax:'-9.99' and no default value - you can not enter any value.
    To avoid many of these scenarios I recommend that you set vMin or vMax to "0" and validate later.

**Comment by dalbert2** [comment]
Thank you for the quick reply.  I will review the autonumeric plugin, but I think any reasonable user would consider the current minValue behavior severely broken.  I suggest removing it or at least boldface documenting this very odd behavior.  As currently implemented, minValue is a fantastic way to introduce obvious and subtle bugs into user forms.
