### ISSUE TITLE
pe:inputNumber value resetting to initial value inside p:tab

### ISSUE THREAD

**Issue by ashishreddy123** [primefaces-extensions/primefaces-extensions.github.com#366]
I have a `<p:tabView>` on my screen where one of the tabs(`<p:tab>`) has several `<pe:inputNumber> ` with minValue attribute set to -9999999999.99. When I enter any value be it positive or negative and switch between the tabs, the input value resets to its initial value whereas for the inputs with no minValue set, it retains the entered value after switching between the tabs.

**Comment by tandraschko** [comment]
The component has already bean moved to PrimeFaces.
So please create a issue there with a very very small and simple example.
