### ISSUE TITLE
pe:dynaForm - StackOverflowError when using composite component as dynaFormControl template

### ISSUE THREAD

**Issue by petrjung** [primefaces-extensions/primefaces-extensions.github.com#367]
When using a p:selectOneMenu output is rendered as expected, but when using my:selectOneMenu .. which is slightly modified p:selectOneMenu composite component .. i got an java.lang.StackOverflowError: null. 

I have tried any composite component is in the dynaFormControl aims to the same result.

In debug it seem there are wrong implementation of the invokeOnChildren in case of the composite component.

[petrjung-dynaform-primefaces-extension-bug.txt](https://github.com/primefaces-extensions/primefaces-extensions.github.com/files/85638/petrjung-dynaform-primefaces-extension-bug.txt)

**Comment by petrjung** [comment]
<org.primefaces.version>5.3</org.primefaces.version>
    <org.primefaces.extensions.version>4.0.0</org.primefaces.extensions.version>

**Comment by ova2** [comment]
Feel free to fix this bug and provide a Pull Request. We haven't maintain the components because they will be merged to PrimeFaces.

**Comment by Rapster** [comment]
We use a lot of composite as `dynaFormControl`, it does not occur this problem.

**Comment by tandraschko** [comment]
Please provide a simple maven-jetty-sample application to replicate.

**Comment by Rapster** [comment]
I had this error because one of the composite's attribute was null. I don't think it's a problem about `DynaForm` itself. I suggest to close this ticket.

**Comment by ova2** [comment]
I can not replicate this issue too. Closed.
