### ISSUE TITLE
InputNumber implizit support for locale specific separators

### ISSUE THREAD

**Issue by cchet** [primefaces-extensions/primefaces-extensions.github.com#368]
It would be nice if inputNumber would provide the feature to provide the separators depending on a set locale.
Since its possible to get the locale specific separator  via ``` DecimalFormatSymbols.getInstance(Locale.US).getDecimalSeparator() ``` it would be pleasant to have the possibility to just provide the locale instead of providing each separator instead.

**Comment by ova2** [comment]
AFAIK, it already works in this manner. There is a Locale attrbute and all separators are created by Locale automatically. By the way, this component has been moved to PrimeFaces core. We don't develop this component anymore!

**Comment by cchet** [comment]
Sorry bad. Missed that
