### ISSUE TITLE
Add https support to gravatar component

### ISSUE THREAD

**Issue by arthurgregorio** [primefaces-extensions/primefaces-extensions.github.com#372]
Add support to HTTPS protocol on gravatar component, something like this: 
```
<pe:gravatar id="userImage" 
             secured="true"
             value="#{userSessionBean.authenticatedUserEmail}"/>
```
And when "secured" tag is specified the request should be over https protocol on the component renderer.

Or turn `generateURL` method protected on the renderer, so we can override it.

This request is justified by these warnings appearing on my console everytime. its because my site is using HTTPS and the gravatar request is not over HTTPS.

![warnings](http://i.imgur.com/jSZwq4n.png)

**Comment by tandraschko** [comment]
please provider a pull request.

**Comment by tandraschko** [comment]
Will will probably release a RC in ~2-3 weeks, if you would like to get a fix for the upcoming release, please provide a PR.

**Comment by tandraschko** [comment]
and i would always use https instead of http.

**Comment by arthurgregorio** [comment]
ok! I will try to prepare the PR until the date.

"and i would always use https instead of http." it means: change the default url to HTTPS instead of provide a attribute to the user to select it?

**Comment by tandraschko** [comment]
yup or is there any possible reason to NOT use HTTPS?

**Comment by arthurgregorio** [comment]
actually i can't see one, but maybe a proxy or something filtering the traffic for a internal application inside a intranet.. 

anyway... i think the options is more suitable to all cases..

**Comment by tandraschko** [comment]
It's ok but secured should be true per default.
Would be great if you could provide it soon.

**Comment by arthurgregorio** [comment]
I will do this task on monday 09/05, tks and sorry for the delay...

**Comment by arthurgregorio** [comment]
Created PR number 30 on core branch

**Comment by tandraschko** [comment]
I thought you would like to make it configurable?

**Comment by arthurgregorio** [comment]
hi, i made a new commit with the configurable way, a2954cd.

but i can't test it, the maven says i don't have primefaces-6.0-SNAPSHOT on my repo and i can't find him to put on them project and test the changes...

**Comment by tandraschko** [comment]
You need to build PrimeFaces from source, too.

**Comment by tandraschko** [comment]
Thanks!
