### ISSUE TITLE
TimePicker - Javascript error when using different's locale

### ISSUE THREAD

**Issue by rluckez** [primefaces-extensions/primefaces-extensions.github.com#373]
On timerpicker.source.js there are some functions that use attribute "amPmText" to know what time is. 
When application locale is changed, for example pt_BR the time do not use am-pm concept anymore, it's work on 24 hours format concept and javascript does not know how to handle it, causing not expected behavior when tried to change the time using arrows in inline mode.
![capture2](https://cloud.githubusercontent.com/assets/11165664/14128307/16f774cc-f5f6-11e5-8543-bda576dc2c47.png)
![capture](https://cloud.githubusercontent.com/assets/11165664/14128308/1720955a-f5f6-11e5-836d-ef79f5f5d660.PNG)

**Comment by ova2** [comment]
Feel free to provide a patch (pull request).

**Comment by melloware** [comment]
@rluckez can you please provide your pr_BR local you included as explained on this page so I can test it?

https://github.com/primefaces-extensions/primefaces-extensions.github.com/wiki/PrimeFaces-Extensions-Locales

**Comment by melloware** [comment]
I just updated the showcase Advanced Usage to change locale and i use pt_BR and everything is working fine dynamically.  Can't reproduce.

**Comment by melloware** [comment]
No response in a week and I have a working showcase demo so closing this issue
