### ISSUE TITLE
Tooltip - shared=true script does not end

### ISSUE THREAD

**Issue by matthieu38** [primefaces-extensions/primefaces-extensions.github.com#375]
Hi, I have a problem with pe:tooltip shared=true.
My versions are :
primefaces-5.3.8
primefaces-extensions-4.0.0

The simple example given here does not work for me (I have the exact same code) :
http://www.primefaces.org/showcase-ext/sections/tooltip/sharedTooltips.jsf;jsessionid=18yq310mxnoq1868ueox1t91b

The goal is to have informations on every lines like this :
http://stackoverflow.com/questions/20141104/tooltip-for-each-row-in-data-table
I tried this solution too but the forSelector does not work either :
```
<p:dataTable var="entry" value="#{dataTableController.messages}" styleClass="myTable" rowIndexVar="rowIndex">
    <p:column headerText="Header 1">
        <h:outputText value="#{entry.value1}" />
    </p:column>  
    <p:column headerText="Header 2">
        <h:outputText value="#{entry.value2}" />
        <pe:tooltip value="This is row number #{rowIndex}" forSelector=".myTable tr[role=row][data-ri=#{rowIndex}]" shared="true" atPosition="top center" myPosition="bottom center" showDelay="500" />
    </p:column>
</p:dataTable>
```

**Comment by ova2** [comment]
Please provide a patch if you think it is a bug.

**Comment by matthieu38** [comment]
Hello Oleg,
Thanks for your answer but my first idea was to know if I was the only one with this problem ?

**Comment by tandraschko** [comment]
Showcase is working fine. If you have the same problem still with the newest version, please create new issue with a exact code example.
