### ISSUE TITLE
InputNumber type="number" with javascript error

### ISSUE THREAD

**Issue by fischer1983** [primefaces-extensions/primefaces-extensions.github.com#376]
Hi,

I am using the PF Extensions 4.0.0 and 5.3 PF. To set the inputNumber with type = "number" the following error occurs in the browser console:

`jquery.js.xhtml?ln=primefaces&v=5.3:14 Uncaught Error: The <INPUT> is not supported by autoNumeric()`

I believe to be associated with #252 

Thanks for attention.

**Comment by tandraschko** [comment]
Not possible -> https://github.com/BobKnothe/autoNumeric/issues/97
