### ISSUE TITLE
JavascriptBehaviorHandler should extend Primefaces AbstractBehaviorHandler

### ISSUE THREAD

**Issue by CSchulz** [primefaces-extensions/primefaces-extensions.github.com#377]
The current implementation uses an old attribute name to attach the javascript behavior inside of a composite component (**javax.faces.RetargetableHandlers**).

To support newer implementations (of Mojarra) it would be good to implement something like 
```
  /** The key of the attached object handlers for Mojarra runtime. */
  private static final String MOJARRA_ATTACHED_OBJECT_HANDLERS_KEY;
  static {
    String handlersKey = "javax.faces.RetargetableHandlers"; // Assume Mojarra < 2.2 
    try {
      // For Mojarra > 2.2, there will be key field declared
      Class<?> clazz = Class.forName("com.sun.faces.facelets.tag.jsf.CompositeComponentTagHandler");
      Field handlersKeyField = clazz.getDeclaredField("ATTACHED_OBJECT_HANDLERS_KEY");
      handlersKeyField.setAccessible(true);
      handlersKey = (String) handlersKeyField.get(null);
    } catch (Exception e) { // CS:IGNORE on any exception, consider that we don't have Mojarra 2.2 runtime
    }
    MOJARRA_ATTACHED_OBJECT_HANDLERS_KEY = handlersKey;
  }
```
http://forum.primefaces.org/viewtopic.php?f=3&t=34600

To support different implementations like Mojarra and MyFaces, the easiest way would be to copy or inherit the [AbstractBehaviorHandler](https://github.com/primefaces/primefaces/blob/986440f5705d1f4462ec1a084eaa4b1062d20211/src/main/java/org/primefaces/behavior/base/AbstractBehaviorHandler.java) of PrimeFaces.

**Comment by tandraschko** [comment]
If you would like to see it in the next release, please provide a PR to extend from AbstractBehaviorHandler.

**Comment by tandraschko** [comment]
Will you provide a PR?

**Comment by CSchulz** [comment]
Yes I will do that.

**Comment by tandraschko** [comment]
Merged and fixed a compilation error. Thanks!

**Comment by CSchulz** [comment]
Thanks, I have no access to the primefaces 6 snapshots or I don't know where to retrieve them.

Are they available to everyone?

**Comment by tandraschko** [comment]
Nope, you need to build from source

**Comment by CSchulz** [comment]
Doh, thank! :laughing:
