### ISSUE TITLE
DynaForm should support columnClasses

### ISSUE THREAD

**Issue by Rapster** [primefaces-extensions/primefaces-extensions.github.com#380]
DynaForm is like a table (e.g `h:panelGrid`), what do you think of having `columnClasses `attribute alowing to define style for label and control. Let me explain my case, my labels should use `label-container` class and control should use `field-container` class.

You'd tell me, you can override css by doing this:

```
#dynaForm .pe-dynaform-label {
    // awesome style
}
```

And you're right, this is what I did so far, but what about control?

What I want to do, is to avoid to define for each `dynaFormControl` the same `styleClass`, I have 20 cases to support!

So to make it the simplest as possible, I was thinking by doing this like a `h:panelGrid`, with `columnClasses`, what do you think? The format must contain maximum two classes, one for the label and the other the control. Exemple:
```
<pe:dynaForm columnClasses="label-container, field-container" >
</pe:dynaForm>
```

**Comment by ova2** [comment]
Feel free to provide a patch. The idea is good.

**Comment by Rapster** [comment]
Okay I'm working on it ;)

**Comment by ova2** [comment]
Fixed with https://github.com/primefaces-extensions/core/pull/28 and https://github.com/primefaces-extensions/showcase/pull/2
