### ISSUE TITLE
Use of dynaFormControl.for with composite

### ISSUE THREAD

**Issue by Rapster** [primefaces-extensions/primefaces-extensions.github.com#381]
The problem is simple, I want to use the "for" attribute with a composite, but I have this exception:

> java.lang.ClassCastException: javax.faces.component.UINamingContainer cannot be cast to javax.faces.component.EditableValueHolder

According to the `DynaFormRenderer` code, it makes sense, my composite is not an `InputHolder`:
```
String targetClientId =
    (target instanceof InputHolder) ? ((InputHolder) target).getInputClientId() : target.getClientId(fc);

    dynaFormLabel.setTargetClientId(targetClientId);
    dynaFormLabel.setTargetValid(((EditableValueHolder) target).isValid());
    dynaFormLabel.setTargetRequired(((EditableValueHolder) target).isRequired());
```

How to make `for` pointing to `aur_id` of my composite? I was thinking of using `editableValueHolder` with `name` "writableSelection", but didn't work... I think something is missing here :/

```
<pe:dynaFormControl type="AUR_ID" for="aur_id" >
                <sc:selectOneMenu id="aur_id"
                                  bean="#{bean}"
                                  formField="#{formField}"
                                  items="#{cc.attrs.listProvider.geItems(formField)}"/>
</pe:dynaFormControl>
```

Basically, here is my composite:
```
<cc:interface>
    <cc:attribute name="bean" required="true" />
    <cc:attribute name="formField" required="true" />
    <cc:editableValueHolder name="writableSelection" />
</cc:interface>

<cc:implementation >
        <p:selectOneMenu id="writableSelection"
                         value="#{cc.attrs.bean[cc.attrs.formField.property.name]}"
       </p:selectOneMenu>
</cc:implementation>
```

Not sure if I missed something, or should I improve `DynaFormRenderer` so it gets the `editableValueHolder` property? _(I'm not sure how to do that...)_

**Comment by ova2** [comment]
Hmm... I haven't any idea currently because I didn't used this compoment with composite components. Composite components are NamingContainer component and have always special handling...

**Comment by tandraschko** [comment]
Never tried it but could you try:
for="aur_id:writableSelection"
?

**Comment by tandraschko** [comment]
If it doesn't work, we would need to find a way how we can handle this case.
I currently can't find a way to check this case:

UIComponent.isCompositeComponent(composite) = true
composite instanceof EditableValueHolderAttachedObjectHandler = false
composite instanceof EditableValueHolder = false
composite instanceof EditableValueHolderAttachedObjectTarget = false

I think someone would need to check the JSF impls. Not sure if it's possible without hacks.

**Comment by Rapster** [comment]
@tandraschko your suggestion `for="aur_id:writableSelection"` did work although I don't think it is not a clean to do it. it would be nice to do as I wrote before. It works so far so I won't say we didn't find a way to solve this problem :)

In same context, I have a very strange problem which I think is still related to this issue. If the input contained in the composite is required, the associated label is not followed by the star `*`, `aria-required="true"` is well encoded in HTML in the input though _(which indicates it's a required field)_. 

It works well with "common" components such as Calendar, Input, etc...

**Comment by Rapster** [comment]
I fixed the initial problem here https://github.com/primefaces-extensions/core/commit/876601cb902751062e44b5c4c841f6a6d5fc647b, but the second problem still remains

**Comment by tandraschko** [comment]
great! does it work fine in both mojarra and myfaces?
So i would add to PrimeFaces core instead extensions.

**Comment by Rapster** [comment]
Yes, it's working with both ;)

**Comment by tandraschko** [comment]
added the main logik here: https://github.com/primefaces/primefaces/commit/e94ca9f9b2be322d965c423664e0fa8584357656

Would be great if you could change your PR to use this method.

Thanks!

**Comment by Rapster** [comment]
I'll do once PF will make an official release. We're already using a PE SNAPSHOT version and we'd like  to avoid this as much as possible.

**Comment by Rapster** [comment]
Although, I do not agree with the new implementation. Why did you remove the recursive method? For example, I have a composite containing an other one which is basically an Autocomplete. It must be recursive as it might return another composite... and not an input holder

**Comment by tandraschko** [comment]
Your method was fine but i would just like an util method to get the EditableValueHolder out of the CC.
Another method should do the recursion.

The reason for me is that CC doesn't have a good abstraction over it's "API", therefore its good to provide a collection of utils over CC's (e.g. our AbstractBehaviorHandler).
Probably we will have a CompositeComponentUtils soon.

**Comment by Rapster** [comment]
Yes I think another method doing the recursion would be nice. I'm closing this ticket, as the main problem is fixed. But another one remains...
