### ISSUE TITLE
pe:DocumentViewer - ~500 warnings print to console on page load

### ISSUE THREAD

**Issue by ericd7** [primefaces-extensions/primefaces-extensions.github.com#382]
Not exactly sure what the cause of this is, it occurs in the showcase example and my own projects.

**Comment by tandraschko** [comment]
Please provide a simple maven/jetty sample application.
It works fine in the current development version.

**Comment by Rapster** [comment]
Indeed, something strange happens [here ](http://www.primefaces.org/showcase-ext/sections/documentviewer/basic.jsf)

Do "Inspect element" of your web browser and you'll see the warnings in the console

**Comment by ericd7** [comment]
Any update on this?

**Comment by tandraschko** [comment]
no as the example works fine.
PrimeFaces Extensions is a community based project. If you would like to fix something for this component, you need to create a PR.

**Comment by ericd7** [comment]
I mean if you click Rapster's link the component works fine but the console is flooded with warnings, I'd hope that's not intended functionality.

**Comment by tandraschko** [comment]
i'm sure thats the same with plain pdf.js

**Comment by tandraschko** [comment]
Nothing we can influence. We can just update pdf.js but currently noone maintains it.

**Comment by melloware** [comment]
Fixed in 6.1 by upgrading to PDF.js 1.5.188
