### ISSUE TITLE
TriStateCheckbox not working with PF6

### ISSUE THREAD

**Issue by Sniffie** [primefaces-extensions/primefaces-extensions.github.com#383]
Dear all,
I just installed PF6 today with PF Extensions 4.0.
If i run a xhtml site with TriStateCheckbox then in browser console the message "Widget not available: TriStateCheckbox" appears. Everything else is working...

**Comment by ova2** [comment]
4.0 is not compatible with PF 6.0. We have released PF Extensions 6.0.0 today.
