### ISSUE TITLE
DynaForm not working inside ui:repeat

### ISSUE THREAD

**Issue by Rapster** [primefaces-extensions/primefaces-extensions.github.com#384]
I detailed the problem here: http://forum.primefaces.org/viewtopic.php?f=14&t=45836&p=143285#p143285. Basically, submitted values are reseted once form is submitted

**Comment by Rapster** [comment]
PR is here https://github.com/primefaces-extensions/core/pull/31

**Comment by ova2** [comment]
Cool. Thanks. PR is merged.

**Comment by ova2** [comment]
I have released this change today with PF Extensions 6.0.0 :-)

By the way, I've added you as committer. I will receive an invitation.

**Comment by Rapster** [comment]
Thanks Oleg ;)
