### ISSUE TITLE
Remove DocumentViewer

### ISSUE THREAD

**Issue by ova2** [primefaces-extensions/primefaces-extensions.github.com#385]
The next maintance release 6.1.0 will not have old or already existing in PF components. Decided by project members.

**Comment by Rapster** [comment]
Does this mean CodeMirror and DocumentViewer are moving to Primefaces Core?

**Comment by tandraschko** [comment]
Nope, we just don't have commiters which maintains this component and the components have many bugs or are really old versions.

**Comment by Rapster** [comment]
We use `DocumentViewer` to display PDFs, what would be the alternative?

**Comment by tandraschko** [comment]
there is none - fix the bugs and maintain it in the next months/years ;)

**Comment by ova2** [comment]
Or move this component to a separate GitHub project.
Am 10.06.2016 15:37 schrieb "Thomas Andraschko" <notifications@github.com>:

**Comment by ova2** [comment]
Duplicate https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/387

I think DocumentViewer and CodeMirror will stay, but not maintained.

**Comment by tandraschko** [comment]
If so, we should close all related issues and state in the showcase

**Comment by melloware** [comment]
First I appreciate all the work you guys do but we use CodeMirror on multiple apps and find it extremely valuable.  Is the list of bugs on this component all listed here in the GitHub issues?  We may be able to spend some time on it to fix the bugs or keep it going.

**Comment by tandraschko** [comment]
First of all, you would need to upgrade it. The version used by PFE is very old

**Comment by tandraschko** [comment]
If you would like to take care of the whole component, please ping me until end of the month. otherwise we will remove it.

**Comment by melloware** [comment]
I wouldn't mind taking a shot at it.  My first step should be to attempt to upgrade the JS and CSS for codemirror correct?  Is there anything else I might need to know before attempting it?

**Comment by tandraschko** [comment]
nope, should be enough. But i'm not sure if we modified some code like resource includes or something. Just play a little bit with it.

**Comment by melloware** [comment]
OK I created a pull request upgrading to CodeMirror 5.18.2.  I left you some notes of what I did that was different than before.

https://github.com/primefaces-extensions/resources-codemirror/pull/2

**Comment by tandraschko** [comment]
Is the showcase and every feature working fine?

**Comment by melloware** [comment]
OK I didn't know if you wanted me to do phases I am going to work on that next and report back.

**Comment by melloware** [comment]
OK I added more to the pull request and updated to 5.18.3.  I was able to get the showcase working except i had to make one change on the JS Usage page.
Was:
`extraKeys="{ 'Ctrl-Space': function(cm) {CodeMirror.simpleHint(cm, CodeMirror.javascriptHint);}}"`

changed to...

`extraKeys="{ 'Ctrl-Space': 'autocomplete'}"`

It looks like they changed how they display hints and they removed CodeMirror.simpleHint and I am searching for an equivalent.

Also they now use RequireJS and some of their libraries break when trying to merge them into 1 JS. So I used their minifier...

https://codemirror.net/doc/compress.html

And had to remove offending JS files until I was finally able to get a working codemirror.js file.  You can read about one of the issues I ran into here:

https://github.com/codemirror/CodeMirror/issues/3883

But everything appears to be working.

**Comment by tandraschko** [comment]
does every sample work correctly? i remember we had a own code completion integration

**Comment by melloware** [comment]
I think what you are asking is did I test the showcase examples.  There are only 3 CodeMirror sample pages.  

Basic Usage = working

Code Completion = working?  It behaves exactly as the showcase does now. You press CTRL+SPACE and the Ajax Spinner spins.  http://www.primefaces.org/showcase-ext/sections/codeMirror/codeCompletion.jsf

JS Completion = see above had to make that 1 line change for CTRL+SPACE to show completion because CodeMirror no longer has CodeMirror.simpleHint() method.  At least I can't find any documentation or examples that show doing something similar to what you had.  I am still researching though.

**Comment by tandraschko** [comment]
Code Completion: it doesn't work on the deployed showcase but should work fine in the current trunk (without your changes). Would be great if you could check that.
It's a feature to integrate a custom completion logic via a JSF method

**Comment by melloware** [comment]
OK will look into it.  I also just fixed the JavaScript integration they changed simpleHint to Show Hint.

`extraKeys="{ 'Ctrl-Space': function(cm) {CodeMirror.showHint(cm, CodeMirror.hint.javascript);}}"`

**Comment by melloware** [comment]
@tandraschko I created 3 pull requests 1 in core, 1 in showcase, and 1 in codemirror.  I have all of the code and examples working and I modified the BasicUsage example to allow the user to dynamically change the Theme, Mode, or Keymap.

**Comment by tandraschko** [comment]
Great work! Would you like to get commiter? So you can maintain it by yourself in the future

**Comment by melloware** [comment]
Thank  you and yes committer privs would be great!

**Comment by tandraschko** [comment]
Done!
If you would like to, yes.
AFAICS there are some changes required in the pdf.js files.
in CKEditor project we have resourceModifier java class, maybe something similar would be great.

**Comment by melloware** [comment]
Should we also consider removing the following components that already have PF equivalents...

- BlockUI
- RemoteCommand
- Tooltip
- QRCode

**Comment by tandraschko** [comment]
RemoteCommand has more features, AFAIR Tooltip too.
Not sure about BlockUI and QRCode

**Comment by melloware** [comment]
Sorry one more what about Layout?  

- Layout

**Comment by Rapster** [comment]
It has more features as well

**Comment by melloware** [comment]
Closing this issue as I have fixed #374
