### ISSUE TITLE
Bug (regression) in TriStateCheckbox

### ISSUE THREAD

**Issue by ova2** [primefaces-extensions/primefaces-extensions.github.com#386]
We have a bug due to this bad pull request https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/317

Set values are always shown as 0 (not set checkbox). This is due to this change:

**public class TriStateCheckbox extends HtmlSelectBooleanCheckbox**

It should be reverted to

**public class TriStateCheckbox extends HtmlInputText**

because this component has three states as Strings "0", "1" and "2" and not boolean.

Default event should be set explicitly in the TriStateCheckbox. I think there is a special method getDefaultEvent or similar. But please don't extend it from HtmlSelectBooleanCheckbox because the value can not be proper rendered then. There is an exception in

```
int valCheck = 0;
try {
    valCheck = Integer.valueOf(ComponentUtils.getValueToRender(context, checkbox));
} catch (Exception ex) {
    valCheck = 0;
}
```

**Comment by Rapster** [comment]
If I may, since we're using apache `commons-lang3` I'd use `org.apache.commons.lang3.math.NumberUtils.toInt()` for better reading

**Comment by ova2** [comment]
But sure, you may, you are a committer :-)

**Comment by Rapster** [comment]
:-)
