### ISSUE TITLE
DynaForm validation of the first control doesn't work when V6.0 is used

### ISSUE THREAD

**Issue by sweetcard** [primefaces-extensions/primefaces-extensions.github.com#388]
In the following demo, the validation of the first control doesn't work.
The back bean can't get value of the first control either.

The demo link is here: 
http://www.primefaces.org/showcase-ext/sections/dynaform/basicUsage.jsf

**Comment by Rapster** [comment]
The demo uses PE 5.2 and validation works just fine. By the way @ova2, is it possible to deploy the new showcase?

Anyway, I just tried with PE 6.0.0 and it works fine as well. Did you see that error on showcase or personal use?

**Comment by sweetcard** [comment]
Thank you for your reply.
I found the error in my project not on showcase.
The same code in my project works with PE 5.3 but doesn't work with PE 6.0.0.
I haven't found any error log or output. 
Just change the version from 6.0.0 to 4.0.0. It works.

`  <dependency>
            <groupId>org.primefaces.extensions</groupId>
            <artifactId>primefaces-extensions</artifactId>
            <version>4.0.0</version>
        </dependency>`

**Comment by ova2** [comment]
I can not deploy the new showcase. This does Cagatay Civice, the PrimeFaces lead. I sent him the new WAR a long time ago, but they want to port the Timeline examples from the "old" showcase first.

**Comment by ryan-bennett** [comment]
I can confirm this issue as well in my project. The first input in the dynaform does not have it's value set nor is validated. The same input, when moved to another position is validated correctly.

PrimeFaces 6.0.1
PrimeFaces Extensions 6.0.0

**Comment by sweetcard** [comment]
@ryan-bennett 
The showcase checked out from git can't work either.
I spent hours to solve it but failed.
:(

**Comment by ryan-bennett** [comment]
HI Sweetcard

To work around this, add a dynaform section with a dummy type at the start of your model e.g.

Java
```
DynaFormModel dynaFormModel = new DynaFormModel();
DynaFormRow dummyRow = dynaFormModel.createRegularRow();
dummyRow.addControl(new Field().label(""), "dynaform_dummy", 2, 1);
```
JSF
```
<pe:dynaFormControl type="dynaform_dummy">
	<h:inputHidden />
</pe:dynaFormControl>
```

**Comment by sweetcard** [comment]
@ryan-bennett 
That's COOOOL!
It works for me. 
You save me some days.
Thank you very much.
I hope the issue could be fixed soon.
Thank you again.

**Comment by ryan-bennett** [comment]
Glad it helped.

**Comment by Rapster** [comment]
Am I wrong to say `DynaForm` works fine in the current showcase? It's hard to believe the contrary... The only difference I'd see would be PF version you guys are using. Although, I raised an issue which might be related of what you're talking: http://forum.primefaces.org/viewtopic.php?f=14&t=46195&p=144038#p144038

Is your first input a composite or a basic input?

**Comment by sweetcard** [comment]
@Rapster 
The showcase checked out from github does't work.
Check the attachment please.

<img width="1122" alt="pf-ext" src="https://cloud.githubusercontent.com/assets/17595667/16610749/d369f5c6-438f-11e6-901c-c36fd156aa96.png">

**Comment by Rapster** [comment]
I did reproduce the problem with the current branch. I'll check that as soon as I have some time to do so

**Comment by sweetcard** [comment]
@Rapster 
Excellent 💯 👍

**Comment by ova2** [comment]
@Rapster When you fixed this issue (regression), I will release the current state. One of clients uses this component and will find this issue too. That's for sure :-).

**Comment by Rapster** [comment]
I might need your help Oleg on this one...

**Comment by ova2** [comment]
Saidly, but I don't have any time currently and I don't do much JSF development. More JavaScript. Please try to follow your last changes. The component worked fine bevor 6.0 release. Thanks.

**Comment by Rapster** [comment]
Yes I know, since I did modification #384 there is few bugs regarding validation... and probably few other. I'll do my best but I'm still curious how many components are present in the JSF component tree. For example, if I take this example http://www.primefaces.org/showcase-ext/sections/dynaform/basicUsage.jsf, the number of component added is equal to the number of `dynaFormControl`?

**Comment by Rapster** [comment]
@sweetcard could you check again ? I just push a fix

**Comment by sweetcard** [comment]
@Rapster It works now. 
That's very cool.
Thanks for your excellent work. 👍

**Comment by Rapster** [comment]
Cool. @ova2 you can make a new release now ;)

**Comment by ova2** [comment]
@Rapster you are hero :-) Should we release 6.0.1? @tandraschko what do you mean?

**Comment by tandraschko** [comment]
+1 for the release
but i would just do the bugfixes and lets remove the duplicate components for 6.1
if we do a 6.0.1, a user don't expect that we remove components

**Comment by ova2** [comment]
User can still use 6.0.0 with not removed components. I would remove these two components and do a release. I can do a release this week. Only Extensions core and CKEditor.
