### ISSUE TITLE
DynaForm - Mandatory icon not displayed for composite

### ISSUE THREAD

**Issue by Rapster** [primefaces-extensions/primefaces-extensions.github.com#389]
If the targeted input's composite is required, the label is not followed by a star \* _(mandatory icon)_. After debugging, this instruction in DynaFormRenderer `dynaFormLabel.setTargetRequired(((EditableValueHolder) target).isRequired());` returns false instead of true. But same instruction in AutocompleteRenderer returns true: weird huh? _(In my case, the target is an Autocomplete)_

I reproduced the problem _(with rating as targeted input holder)_ in the showcase with MyFaces 2.2.8 and Mojarra 2.2.13

**Comment by ova2** [comment]
Does it work now with your last fix?

**Comment by Rapster** [comment]
No it does not :(

**Comment by Rapster** [comment]
By using a composite like this:

```
<cc:interface>
    <cc:attribute name="bean" required="true" />
    <cc:attribute name="formField" required="true" />
    <cc:editableValueHolder name="writableSelection" />
</cc:interface>

<cc:implementation >
        <p:selectOneMenu id="writableSelection"
                         value="#{cc.attrs.bean[cc.attrs.formField.property.name]}"
                         required="#{!dynaFormContext.skipValidation and cc.attrs.formField.mandatory}"
                         requiredMessage="#{i18n[cc.attrs.formField.label]} : #{i18n['KASPER_CONSTRAINT_NOTNULL_ENFORCED']}">
            <f:selectItems value="#{cc.attrs.items}"
                           var="object"
                           itemLabel="#{i18n[object[cc.attrs.itemLabel]]}"
                           itemValue="#{object[cc.attrs.itemValue]}"/>
            <f:converter converterId="formFieldConverter"/>
            <f:attribute name="formField"
                         value="#{cc.attrs.formField}"/>
        </p:selectOneMenu>

        <p:message for="writableSelection"
                   display="icon"
                   rendered="#{!cc.attrs.readonly}"/>
</cc:implementation>

```

After I debugged el expression in `AstValue` of jasper-el, I found something really strange when it comes to evaluate `required` attribute in `DynaFormRenderer`. `cc` should be evaluate as the composite itself _(selectOneMenuComposite.xhtml)_ but instead, it is the parent of `DynaForm` which is set _(dynaForm.xhtml)_. Here is the file architecture I have:

```
dynaForm.xhtml
 `-- dynaFormControl type = "A"
 |   `--selectOneMenuComposite.xhtml
 `--dynaFormControl type = "B"
     `--inputText
```

**Comment by Rapster** [comment]
I don't think it is related to `DynaForm` https://github.com/primefaces/primefaces/issues/1633

**Comment by melloware** [comment]
Not sure if this is related but these guys have DynaForm questions:  http://forum.primefaces.org/viewtopic.php?f=14&t=43697&p=152567

**Comment by melloware** [comment]
@Rapster now that primefaces/primefaces#1633 is fixed does that mean this issue is fixed as well or does code need to be added to PFE?

**Comment by Rapster** [comment]
It's not 100% fixed, it does not work with Mojarra impl. I hope I'll have time to take a look at it before 6.1-FINAL
