### ISSUE TITLE
Remove TriStateCheckbox

### ISSUE THREAD

**Issue by tandraschko** [primefaces-extensions/primefaces-extensions.github.com#390]
it was migrated to PF

**Comment by ova2** [comment]
Cool Thomas. Thanks!

**Comment by melloware** [comment]
I just removed it from the Showcase as well.

**Comment by tandraschko** [comment]
I actually changed it to p:triStateCheckbox and didn't removed it because the PF showcase doesn't contain all examples -> https://github.com/primefaces-extensions/showcase/commit/4fbcd20bb9982b8647608b747f0d1ed935a531ae

Same goes for timeline

**Comment by melloware** [comment]
Sorry reverted!  i was wondering why I just assumed you had updated the PF showcase that I can examine yet.
