### ISSUE TITLE
Exporter - Export datatable with rowExpansions

### ISSUE THREAD

**Issue by ronanrigal** [primefaces-extensions/primefaces-extensions.github.com#393]
Hello guys, i am trying to export a datatable that have a rowExpansion an inside this it have another 3 datatables only (the second have a rowExpansion with the third datatable), but in the export it just take the parent datatable and the first child (datatable) the other 2 are not taken.

There is a way to export all the content inside the rowExpansion?
@sudheerj  or some other member who can help me.

The following are links to an images where you can see what i want to export.
Screen:
[http://imageshack.com/a/img922/903/tF6NbM.png](url)

Code:
http://imageshack.com/a/img923/1159/owMD7g.png
http://imageshack.com/a/img922/5412/85vYZI.png
http://imageshack.com/a/img923/9528/MlrNrJ.png
http://imageshack.com/a/img924/2057/q6NyHg.png

Thanks you for your attention, i hope you can help me with this.

Att. Ronan Rigal.

**Comment by melloware** [comment]
@tandraschko All these links and screenshots no longer work so I have no idea what this user is trying to do.  Also I don't think anyone besides @sudheerj really understands this code enough to make a major change.  I propose closing this ticket as "wontfix".  Thoughts?

**Comment by Rapster** [comment]
Is it possible to highlight the differences between `<pe:exporter />` and `<p:dataExporter />`? It's not clear to me what are they :/

**Comment by melloware** [comment]
@Rapster from what I can tell there is a ton of overlap but the additions in pe:exporter are the ability to customize the headers and footers etc.  PrimeFaces exporter you have no control you just get what you get.  I am not sure if PF Exporter handles Subtables and Grouping etc but I believe Extensions does.    I know for me personally if I needed something other than PF defaults exporter I usually just write my own download in the format I want passing it the table values.  But that is just my opinion.

**Comment by jxmai** [comment]
@Rapster If I am not mistaken, the `<p:dataExporter>` can only export datatable, but the pe:exporter has the ability to export more types of component such as `<p:dataList>`.

**Comment by melloware** [comment]
I have fixed this example in the showcase and it is working fine for me in 6.1.

http://www.primefaces.org/showcase-ext/sections/exporter/expandableTable.jsf

So I am closing this ticket as invalid.
