### ISSUE TITLE
DynaForm first control is always null

### ISSUE THREAD

**Issue by integrityhu** [primefaces-extensions/primefaces-extensions.github.com#394]
Problem is, when the form is later submitted, field.value is always set to null regardless of which radio button is selected.
Please visit forum topic : http://forum.primefaces.org/viewtopic.php?f=14&t=46154

**Comment by Rapster** [comment]
Did you get the last version? I pushed something yesterday. You problem is related to this one #388 certainly

**Comment by Rapster** [comment]
Related to #388
