### ISSUE TITLE
DynaForm - first clientId is badly generated if contains in a repeater

### ISSUE THREAD

**Issue by Rapster** [primefaces-extensions/primefaces-extensions.github.com#397]
Whatever it's a composite or not, the first clientId does not contain the key generated by `DynaFormControl` (e.g r1c2reg). Since composite is not working with `DynaForm`, I used jQuery patch as a workaround, although, its does not work entirely because of this issue...

**Comment by Rapster** [comment]
See 0a713edcbdeedaf15b2a35bf974ac44ffafc552d

**Comment by melloware** [comment]
Nice work!
