### ISSUE TITLE
CodeMirror basic autocomplete example fails with javascript error

### ISSUE THREAD

**Issue by jasonwaggoner** [primefaces-extensions/primefaces-extensions.github.com#398]
TypeError: PrimeFacesExt.widget.CodeMirror is undefined

**Comment by tandraschko** [comment]
http://www.primefaces.org/showcase-ext/sections/codeMirror/jsCodeCompletion.jsf works fine for me.

**Comment by melloware** [comment]
This is fixed in 6.1
