### ISSUE TITLE
MasterDetail - Make empty selectDetailLevel optional

### ISSUE THREAD

**Issue by djmj** [primefaces-extensions/primefaces-extensions.github.com#400]
MasterDetail is a great component but it is very problematic when trying to reuse existing components with it. Each AJAX component such as _p:commandButton_ or _p:ajax_ needs an empty dummy _pe:selectDetailLevel_.

This would not be a problem if _selectDetailLevel_ would not throw an exception if its not within a _masterDetailLevel_. 

**Why is this important?**

JSF is a component oriented framework and big applications use many reusable custom components. The component itself do not know if they are within a _masterDetailLevel_. 

**Example**

I have a simple button that generates a property _generatedId_ from a different input _name_  within a _masterDetail_. 

```
<p:inputText id="name" value="#{cc.attrs.entity.name}"/>
<p:inputText id="generatedId" value="#{cc.attrs.entity.generatedId}"/>

<p:commandButton icon="ui-icon-gear" 
    action="#{entityUtilBean.createId(cc.attrs.entity)}"
    process="@this, name" update="generateId"/>
```

The Problem is, that i cannot add a _pe:selectDetailLevel_ to it. Since it is not always used within a _masterDetail_! And there is no rendered or disabled attribute on _selectDetailLevel_.

When i omitt the _selectDetailLevel_ i get following exception:

_javax.el.PropertyNotFoundException: Target Unreachable, 'null' returned null_ 
related to processing _#{cc.attrs.entity.name}_

This looks more like a scope problem where _#{cc.attrs.entity}_ is lost on next request.

**Workaround**

Add a attribute _inMasterDetail_ to each component and render ajax components twice, which makes problems with other referencing components such as _outputLabel_

```
<!-- version for masterDetail -->
<p:commandButton icon="ui-icon-gear" 
    action="#{entityUtilBean.createId(cc.attrs.entity)}"
    process="@this, name" update="generateId" rendered="#{cc.attrs.inMasterDetail}">
    <pe:selectDetailLevel/>
</p:commandButton >

<!-- version not for masterDetail -->
<p:commandButton icon="ui-icon-gear" 
    action="#{entityUtilBean.createId(cc.attrs.entity)}"
    process="@this, name" update="generateId" rendered="#{not cc.attrs.inMasterDetail}"/>
```

Related post: http://forum.primefaces.org/viewtopic.php?f=14&t=43724

**Changes**
- Why is an empty _pe:selectDetailLevel_ required anyway? make it optional. 
- Allow _selectDetailLevel_ as child without _masterDetail_. Just ignore it and do not throw _SelectDetailLevel can be only used inside of MasterDetailLevel_ , so we can just add empty _pe:selectDetailLevel_ to any possible ajax component.
- Add disabled or rendered attribute to _selectDetailLevel_ (would still need to pass attribute _inMasterDetail_ to components).

**Comment by ova2** [comment]
Nobody will take care of this component. Please fix it self and provide a pull request. Thanks.

**Comment by melloware** [comment]
It has been 1 year with no PR provided.  Closing this enhancement ticket.
