### ISSUE TITLE
MasterDetail - allow branch / only show level in breadcrumb within flow

### ISSUE THREAD

**Issue by djmj** [primefaces-extensions/primefaces-extensions.github.com#401]
Level's should optional not be shown if not in navigation flow. Example I have a two level navigation with a branch:
- Level 1
  - Level 2
  - Level 3

In _Level 1_ user can select either _Level 2_ or _Level 3_ using buttons.
The problem is when _Level 3_ is selected the breadcrumb will also show _Level 2_, which is not desired.

**Idea**

Show only level's in breadcrumb within flow. This option could be optional activated with an attribute on _masterDetailLevel_.

If source level is **1** and target level is **3** it means level **2** is not in flow and shall not be shown.

A simple approach is a new attribute _levelHide_ on _masterDetailLevel_ similar to _levelDisabled_. This still requires to save current level obsolete in bean, see workaround.

**Workaround**

Only workaround i came up is with is using _levelDisabled_ and saving current level in bean. Rendered is not working.

```
<pe:masterDetailLevel level="3" levelDisabled="#{bean.targetLevel ne 3}">
```

**Comment by ova2** [comment]
Nobody will take care of this component. Please fix it self and provide a pull request. Thanks.

**Comment by melloware** [comment]
It has been 1 year with no PR provided.  Closing this enhancement ticket.
