### ISSUE TITLE
Java Code Warnings Cleanup

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions.github.com#407]
Eclipse is reported the following dead code, variables, and other warnings that I would like to clean up if that is OK?  

- The import java.util.ArrayList is never used	AssignableParameter.java	line 21
- The import java.util.ArrayList is never used	HeadRenderer.java	line 22
- The import java.util.ArrayList is never used	LayoutPane.java	line 21
- The import java.util.ArrayList is never used	MethodParameter.java	line 21
- The import java.util.List is never used	AssignableParameter.java	line 22
- The import java.util.List is never used	HeadRenderer.java	line 23
- The import java.util.List is never used	LayoutPane.java	line 22
- The import java.util.List is never used	MethodParameter.java	line 22
- The import javax.el.ELContext is never used	HeadRenderer.java	line 25
- The import javax.el.ExpressionFactory is never used	HeadRenderer.java	line 26
- The import javax.el.ValueExpression is never used	HeadRenderer.java	line 27
- The import javax.el.ValueExpression is never used	LayoutPane.java	line 24
- The import javax.faces.component.FacesComponent is never used	GChart.java	line 10
- The import javax.faces.component.UINamingContainer is never used	AnalogClock.java	line 10
- The import javax.faces.component.UINamingContainer is never used	GChart.java	line 11
- The import javax.faces.component.UIViewRoot is never used	HeadRenderer.java	line 29
- The import javax.faces.context.FacesContext is never used	AnalogClock.java	line 11
- The import org.apache.poi.ss.usermodel.VerticalAlignment is never used	ExcelExporter.java	line 64
- The import org.primefaces.util.Constants is never used	HeadRenderer.java	line 33
- The static field Font.BOLD should be accessed in a static way	PDFExporter.java	line 898
- The static field Font.BOLD should be accessed in a static way	PDFExporter.java	line 908
- The static field Font.ITALIC should be accessed in a static way	PDFExporter.java	line 901
- The static field Font.ITALIC should be accessed in a static way	PDFExporter.java	line 911
- The static field Font.NORMAL should be accessed in a static way	PDFExporter.java	line 895
- The static field Font.NORMAL should be accessed in a static way	PDFExporter.java	line 905
- The value of the field GravatarRenderer.md is not used	GravatarRenderer.java	line 20
- The value of the local variable first is not used	ExcelExporter.java	line 290
- The value of the local variable rows is not used	ExcelExporter.java	line 215
- The value of the local variable rows is not used	ExcelExporter.java	line 292
- The value of the local variable rows is not used	PDFExporter.java	line 356

**Comment by melloware** [comment]
Commit https://github.com/primefaces-extensions/core/commit/4e0dc842f2f610312f02a838e2464deada2f770c

**Comment by Rapster** [comment]
Looks good to me but careful with the indentation, what did you change?

**Comment by melloware** [comment]
@Rapster.  Sorry I might have had my formatter on for 1 or 2 files.  I try to have all formatting off when making any changes.  The only things modified were the exact items listed above in the ticket.

Also i had a question?  Is there a standard formatter for the project?  Some of these Java files are a mess with formatting and indentation.

**Comment by Rapster** [comment]
AFAIK no, but I've met this same problem already. I guess we should follow PF guidelines. It might be a good idea to format everything, but still, you'll have to review every file to make sure it is easily readable.
