### ISSUE TITLE
Maven Site, PMD and Findbugs Reports

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions.github.com#411]
I thought it would be helpful so I have added Maven Site reporting to the pom.xml and generated the site documentation...

http://melloware.biz/pe/index.html

You will see PMD and Findbugs issues that I will be addressing with a commit.   These reports should always be clean.

http://melloware.biz/pe/pmd.html

http://melloware.biz/pe/findbugs.html

I am not going to address the Cut and Paste report, at least not yet...

http://melloware.biz/pe/cpd.html

**Comment by ova2** [comment]
Amazing! Thanks a lot!

**Comment by tandraschko** [comment]
+1

just not sure about your code changes
StandardCharsets e.g. is Java7 and PF is still compatible with Java6
I also don't see any reason to use Java7 features

**Comment by melloware** [comment]
OK I just reverted the use of StandardCharsets for "UTF-8".  The only difference is by not using that constant the getBytes() throws a UnsupportedEncodingException exception that must be checked where the constant does not.  However you are right its a JDK 7 class.

I also reverted the master pom.xml to Java 6.  I bumped it to 7.  The reason is @tandraschko I downloaded JDK6 and tried to build the project with 6 and it fails because PrimeFaces Optimizer plugin fails with "Class level 51.0" error.  So the project cannot be built with 6 right now unless there is something I am missing?

I will fix the //NOPMD and ignore that UselessParenthesis check.

**Comment by Rapster** [comment]
Once again, great job Emil ;) These reports could be hosted by github.com no?

**Comment by melloware** [comment]
@Rapster yes this could I guess I could check them into the website project?  @ova would that be the right place to put these?  They are all static HTML files and images that maven generates?

**Comment by ova2** [comment]
I think the project homepage would be the right place. That's for sure.

**Comment by Rapster** [comment]
@melloware simply create a new folder "reports " containing pmd, findbugs and cp folder  (at index.html level). These should be updated once a new version or commit is released or pushed. Makes me think of using a tool like Travis :)

**Comment by tandraschko** [comment]
Not sure about the optimizer plugin but we should definitly not move to java7 unless PF is doing it.

**Comment by ova2** [comment]
AFAIK Optimizer plugin was running with Java 6. Probably recently pull requests from one person changed something, not sure.

**Comment by melloware** [comment]
I will fix it and make sure everything builds with JDK6 before we cut the release for 6.1

**Comment by schlagges** [comment]
How is the release going? :-)
Really looking forward to the DynaForm fixes.

**Comment by tandraschko** [comment]
we won't release until 6.1 is final.

**Comment by tandraschko** [comment]
But you can ask @melloware about a RC ;)

**Comment by melloware** [comment]
Tomorrow I will cut another shapshot to go with PrimeFaces RC2 like we did for RC1.

**Comment by melloware** [comment]
Snapshots have been updated in Sonatype for PF RC2!

**Comment by melloware** [comment]
Project reports have been upload and I created a link from the main site but you can get to it directly here:

http://primefaces-extensions.github.io/reports/index.html
