### ISSUE TITLE
CKEditor - loses style tag on rendering

### ISSUE THREAD

**Issue by jxmai** [primefaces-extensions/primefaces-extensions.github.com#414]
test.xhtml

``` xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    xmlns:pe="http://primefaces.org/ui/extensions"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:fn="http://java.sun.com/jsp/jstl/functions"
    xmlns:i="http://java.sun.com/jsf/composite/components"
    xmlns:c="http://java.sun.com/jsp/jstl/core">

    <h:head>

    </h:head>

    <h:body>
        <h:form>
            <p:commandButton value="Load Data" 
                        process="@this" 
                        actionListener="#{test.viewData()}"
                        update="editor"></p:commandButton>


            <pe:ckEditor id="editor" value="#{test.data}">
            </pe:ckEditor>

            <!-- <p:editor id="editor" value="#{test.data}"></p:editor> -->
        </h:form>
    </h:body>

</ui:composition>
```

Test.java

``` java
import java.io.IOException;
import java.io.InputStream;
import java.io.Serializable;
import java.io.StringWriter;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;

import org.apache.commons.io.IOUtils;

@ManagedBean(name = "test")
@ViewScoped
public class Test implements Serializable {

    private static final long serialVersionUID = 8465294452198566201L;

    private String data;

    public void viewData() {
        InputStream inputStream = Test.class.getResourceAsStream("test.html");
        StringWriter writer = new StringWriter();
        try {
            IOUtils.copy(inputStream, writer);
            this.setData(writer.toString());
        } catch (IOException e) {
            e.printStackTrace();
        }

    }

    public String getData() {
        return data;
    }

    public void setData(String data) {
        this.data = data;
    }

}
```

test.html

``` html
<h1>Title </h1>

<style> table { width:100% } </style>
<table><tr>
<th>Col A</th>
<th>Col B</th>
<th>Col C</th>
<th>Col D</th>
<th>Col E</th>
</tr><tr><td>1</td><td>2</td><td>3</td><td>4</td><td>5</td></tr></table>
```

Steps to reproduce:

Inital Screenshot:

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/19401845/32aee802-9223-11e6-8cea-064bf1855a0e.png)

Step 1: Click Load Data on the top left of the screen

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/19401855/3f65199a-9223-11e6-8378-f2a9a22e90dc.png)

Step 2: Click source on the ckeditor, and there is no style tag at all. In the sample we have `table width:100%`

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/19401873/5614d586-9223-11e6-9a52-c2bea98d82be.png)

Notice that Primefaces ClEditor works fine. To test it, please uncomment the`p:editor` and comment the `pe:editor`.

Running on Primefaces 6.0.6 + Primefaces Extension 6.1 Snapshot

**Comment by melloware** [comment]
I wonder if it is related to this?  

http://ckeditor.com/forums/CKEditor/Styles-getting-lost-after-saving

which points to this feature:  http://docs.ckeditor.com/#!/guide/dev_advanced_content_filter-section-2

**Comment by melloware** [comment]
So it looks like you have 2 options.  You can use the XHTML prop customConfig="" to point to your custom CKEditor configuration and set CKEDITOR.config.allowedContent to true

> If want to disable Advanced Content Filter, set CKEDITOR.config.allowedContent to true. All available editor features will be activated and input data will not be filtered. Note that you cannot use CKEDITOR.config.disallowedContent when ACF is disabled.

Or I can check with @tandraschko about making this the default setting inside the component.

**Comment by jxmai** [comment]
@melloware Thanks for your instant response and the resources your provided :+1: 

I checked the forum post, the behaviour is matching what they called 'new feature', but it looks like a bug since the html content should not be modified by the filter function by default. 


I checked the custom config. It is working fine. 

Here is the updated version:

```xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pe="http://primefaces.org/ui/extensions"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:fn="http://java.sun.com/jsp/jstl/functions"
	xmlns:i="http://java.sun.com/jsf/composite/components"
	xmlns:c="http://java.sun.com/jsp/jstl/core">

	<h:head>

	</h:head>

	<h:body>
		<h:form>
			<p:commandButton value="Load Data" 
						process="@this" 
						actionListener="#{test.viewData()}"
						update="editor"></p:commandButton>
		
		
			<pe:ckEditor id="editor" 
						value="#{test.data}"
						customConfig="#{request.contextPath}/resources/js/ckeditor.js"
						>
			</pe:ckEditor>
			
			<!-- <p:editor id="editor" value="#{test.data}"></p:editor> -->
		</h:form>
	</h:body>

</ui:composition>
```

```js
CKEDITOR.editorConfig = function( config ) {
	CKEDITOR.config.allowedContent = true;
};
```

Result:

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/19402868/4e434116-9229-11e6-9458-7fea05bd8039.png)


> I can check with @tandraschko about making this the default setting inside the component.

+1

It is a useful setting, suggest to make it easier or put it in the documentation.

**Comment by melloware** [comment]
I have to say your bug descriptions are the best i have ever seen on Github!  And thanks for posting your working solution back.  You are right I am thinking of adding an "allowedContent" property the pe:editor to make this switch convenient for users who will probably have the same issue as you or as that guy in the forum post described.

**Comment by jxmai** [comment]
Thanks for your compliment and your help :)

**Comment by tandraschko** [comment]
We should should not set allowedContent per default to true. There is a reason why CKEditor did set it to false :D

But i have no problem to add a allowedContent attribute to the component.

**Comment by melloware** [comment]
Agreed.  It seems to cause a lot of anger on their forums but you are right let's leave it the default and I will will add a new property to the component to switch it.

**Comment by melloware** [comment]
Fixed with commit https://github.com/primefaces-extensions/core/commit/03a72c418cdff9bc9911f9b25627d98e2512f886

Added new property "advancedContentFilter=true/false".  It is true by default which is the default CKEditor behavior.  To disable it set it to False.

**Comment by jxmai** [comment]
@melloware Similar to Issue #415. 

The CKEDITOR is a global obj that will affect all instances.

https://github.com/primefaces-extensions/core/commit/03a72c418cdff9bc9911f9b25627d98e2512f886#diff-07381e5e91156ce1e33fd7f24b08580eR141

I raised a PR to patch this issue.

**Comment by melloware** [comment]
Thanks I was going to ask you about that.  Just merged.

**Comment by jxmai** [comment]
No problem :)

**Comment by jxmai** [comment]
@melloware I just found out another regression related to allowedContent. Would you like to take a look ? ```CKEditor.instances[this.id]``` could be undefined. If we don't put check on this, there will be an error.

Sample

```xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
     xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    xmlns:pe="http://primefaces.org/ui/extensions"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    >

    <h:head>
    </h:head>

    <h:body>
            <!--<p:commandButton oncomplete="PF('testDialog').show()" value="Test"></p:commandButton>-->

            <p:dialog id="dialog" widgetVar="testDialog">
	        		<h:form id="editorForm">
		        			<pe:ckEditor id="editor"></pe:ckEditor>
	        		</h:form>
	        	</p:dialog>
	        	
    </h:body>

 </ui:composition>
```

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/19822594/e74b06ae-9d29-11e6-88fe-c3c4c54e2abd.png)

we might need to use 

```js
if (typeof CKEDITOR.instances !== "undefined") {
    CKEDITOR.instances[this.id].config.allowedContent = !this.cfg.advancedContentFilter;
}
```

But the undefined itself is suspicious. How come non empty id can have no instance ?

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/19822712/907eb446-9d2a-11e6-94ea-586a125c402b.png)

**Comment by melloware** [comment]
Yes that is very strange. if it it has an ID i am struggling to see how the instance would be undefined?

**Comment by tandraschko** [comment]
Nope, this can happen in normal cases, when the editor is not visible yet (e.g. in a dialog).
The statement should be inside renderDeferred.

**Comment by melloware** [comment]
OK I just moved that code and committed the fix.

**Comment by tandraschko** [comment]
Probably it's even better inside the initialized callback, which will be called when the ckeditor was initialized successfully.

**Comment by melloware** [comment]
Good suggestion, I just moved both lines down into the initialized callback.

**Comment by jxmai** [comment]
No, putting the code to the initialized callback does not work in this case. Maybe because it is fired too late ?

Please try this example again: https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/414#issuecomment-255781906

the result will be undefined.

The code should be placed under rendered. The first change was correct. I tested both cases (https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/414#issuecomment-257031734 and https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/414#issuecomment-255781906), and they will passed if we revert the second change.

The changes should be like the following:

![image](https://cloud.githubusercontent.com/assets/10467831/19878270/8fcabb76-9fb4-11e6-9eac-62ffc4dc8595.png)

**Comment by melloware** [comment]
Thanks for testing. Reverted change back to the render method.

**Comment by tandraschko** [comment]
To be honest, i think that it's currently just randomly working.
I would check if ckeditor has a hookin callback or something to execute the new code.
In theory, the instance must not be there currently we try to access it.

**Comment by jxmai** [comment]
Alright, I examined the state by debugger at start.  I will  provide a couple debugging screenshots for analysis purposes (watch the top right hand corner). 

**Stage 1: Enter render callback, No instance at this time**

![snapshot3](https://cloud.githubusercontent.com/assets/10467831/19895609/6c1526ba-a01f-11e6-9da2-a0b348c6a466.png)

**Stage 2: init CKEditor, no instance before finishing** 
![snapshot3](https://cloud.githubusercontent.com/assets/10467831/19895626/803a6952-a01f-11e6-87db-f3f98d25170a.png)

**Stage 3: initialized CKEditor, an instance has been generated** 
![snapshot3](https://cloud.githubusercontent.com/assets/10467831/19895646/920ed5c8-a01f-11e6-8a89-23ffd9684690.png)

**Comment by jxmai** [comment]
> To be honest, i think that it's currently just randomly working.

Good vision :+1: Indeed. This issue is not done yet. **The config can still be undefined if applying an ajax update to the dialog / editor.** 

Clicking the Test button and the error will be thrown

```xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
     xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    xmlns:pe="http://primefaces.org/ui/extensions"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    >

    <h:head>
    </h:head>

    <h:body>
            <p:commandButton oncomplete="PF('testDialog').show()" value="Test" update="dialog"></p:commandButton>

            <p:dialog id="dialog" widgetVar="testDialog">
	        		<h:form id="editorForm">
		        			<pe:ckEditor id="editor"></pe:ckEditor>
	        		</h:form>
	        	</p:dialog>
	        	
    </h:body>

 </ui:composition>
```

**The render callback will call twice by clicking the test button. The first time will be fine, but the second time the config object will be undefined.**

![snapshot3](https://cloud.githubusercontent.com/assets/10467831/19906553/2d452eba-a049-11e6-8465-05d6353597cc.png)

This error will then freeze other PF javascript interaction on the same screen such as selectmenu and datatable celledit which is quite serious.

**Comment by melloware** [comment]
Reopeing this issue since it is not fully fixed yet.  Any update @jxmai?

**Comment by jxmai** [comment]
Hi @melloware , a new issue was mixed with this one if my analysis was correct.  the quick fix I mentioned can prevent the error but still failed to achieve the goal (update editor inside the dialog).  It was working fine on Primefaces 6.0, but not working on Primefaces 6.1 Snapshot.  **Regression was happened in between**.  

The problem  occurred during the process of upgrading to v4.5.9 (The previous update).  

In Primefaces 6.0, Click Test button and the dialog shows up immediately:

![snapshot3](https://cloud.githubusercontent.com/assets/10467831/20106892/43fda080-a59c-11e6-9324-1e5bef4f738a.png)

Currently, there is no dialog showing up on the first click even without the js error (The screenshot below was running on  Extensions 6.0 + CKEditor Project v 4.5.9 with commit: https://github.com/primefaces-extensions/resources-ckeditor/commit/3af38710a58723d93df64e21bbae3117f73dab00)

![snapshot3](https://cloud.githubusercontent.com/assets/10467831/20108558/0f3367ee-a5a2-11e6-830a-cd872bc604d5.png)

I think I need to raise a separate issue for it. What do you think :) ?

**Comment by melloware** [comment]
sure thing raise a new issue and I will close this one.
