### ISSUE TITLE
Primefaces Extension exporter regression - java.util.NoSuchElementException

### ISSUE THREAD

**Issue by jxmai** [primefaces-extensions/primefaces-extensions.github.com#416]
Sample Xhtml:

```html
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:pe="http://primefaces.org/ui/extensions">
<ui:composition>

	<h:head>

	</h:head>

	<h:body>

		<h:form>
			<p:dataList id="validationDetailsTabView" 
									itemType="disc"  
		            				paginator="true" 
		            				rows="5" 
		            				paginatorPosition="bottom" 
		            				>
		            				  
								    <f:facet name="header">  
								        <h:outputText value="Validation Details"/>  
								    </f:facet>  
								    
								    <f:facet name="footer">
								    	<p:commandButton value="Export as Excel"
								    					ajax="false"
								    	>
								    		<pe:exporter type="xlsx" target="validationDetailsTabView" fileName="validation_details" facetBackground="#008000" datasetPadding="4" /> 
								    	</p:commandButton>
								    </f:facet>
							</p:dataList>
		</h:form>
		
	</h:body>
    
</ui:composition>
</html>

```

Screenshot:

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/19570358/4269d766-96bf-11e6-881a-a6ba0916aab4.png)

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/19570384/616c8da2-96bf-11e6-96f4-77fc17372815.png)

Primefaces 6.0.6 + Primefaces Extension 6.1 Snapshot

Other info: Primefaces Extension 6.0 works fine

**Comment by tandraschko** [comment]
As PrimeFaces Extensions is a community based project, please analyze the problem and provide a PR.

**Comment by jxmai** [comment]
:+1: Sure, I logged the issue here first so that other people can see and in case I forget. Analysis will be later.

**Comment by melloware** [comment]
I will fix.  It was this commit  https://github.com/primefaces-extensions/core/commit/4dab14a8755568bac7c5d17920f823584700bbed#diff-8334016f90f71f0f377b532097ba4cc8  fixing  this PMD issue...

http://melloware.biz/pe/pmd.html

**Comment by melloware** [comment]
Just checked in the fix  https://github.com/primefaces-extensions/core/commit/5e2a54d9f69599b4ba348427f9de19eb651494f1#diff-8334016f90f71f0f377b532097ba4cc8

**Comment by jxmai** [comment]
Thanks! @melloware . It seems working now. If I understand your fix correctly, it was causing by ```loader.iterator()``` has no more element but without a checking. As a result, ```NoSuchElementException```. It should be OK 👍

**Comment by melloware** [comment]
Thanks @jxmai for reporting and testing!
