### ISSUE TITLE
New component: GnMenu

### ISSUE THREAD

**Issue by Rapster** [primefaces-extensions/primefaces-extensions.github.com#417]
I'd like to integrate this component in my project, I found two implementations:
- http://tympanus.net/Tutorials/GoogleNexusWebsiteMenu/ (plain JS and heavy css)
- https://codepen.io/illnino/pen/nsBif (looks simple but use scss)

I think it's a cool menu which complete the set of menus already present in PF, what do you think?

**Comment by melloware** [comment]
I like it.  Personally I like the 2nd one nsBif mostly because it looks like a cleaner implementation.

**Comment by Rapster** [comment]
Yes, I'm working on it, one thing I don't like about it, is submenu display. I'll see later if I can make submenus toggleable

**Comment by Rapster** [comment]
I won't have time for this one, sorry... Moreover it is not good as I thought if there is many menu items.
