### ISSUE TITLE
CKEditor - office 2013 skin is not compatible with Firefox

### ISSUE THREAD

**Issue by jxmai** [primefaces-extensions/primefaces-extensions.github.com#418]
Sample Code:

```xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
     xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    xmlns:pe="http://primefaces.org/ui/extensions"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    >

    <h:head>
    </h:head>

    <h:body>
        <h:form>
            <pe:ckEditor id="editor"  
                        skin="office2013"
            >
            </pe:ckEditor>

        </h:form>
    </h:body>

 </ui:composition>
```

**In chrome the editor is working fine**

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/19743312/67ac27ee-9b8e-11e6-8b24-f6721be96f85.png)

**But in Firefox, nothing shows up**

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/19743351/944389b4-9b8e-11e6-87c4-ebbeb42569db.png)

Running on Primefaces 6.0.6 + Primefaces Extension Snapshot + Tomcat / Jetty

**Comment by melloware** [comment]
I saw you upgraded CKEditor and then closed your pull request?  Is upgrading CKEditor fixing this issue?

**Comment by jxmai** [comment]
Yes, I thought it would be nice to try the latest version to see whether the bug still exist :) Unfortunately, the latest version cannot help to solve this issue. But anyway, the work has been done so I raised an PR.
I closed the PR because it was broken at that time, it is opened now.

**Comment by melloware** [comment]
Nice work!  You going to keep digging on this Firefox issue?

**Comment by jxmai** [comment]
Thanks. Yes, I will. One thing I notice is that the skin project has been out of support for a while. The last commit was about 3 years ago. but I might need to dig into it  before making a conclusion (whether is the skin problem or the extension problem).

4.5 has a question mark instead of a green check.

http://ckeditor.com/addon/office2013

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/19779056/111912ea-9c45-11e6-977d-a5e34087959d.png)


https://github.com/danyaPostfactum/ckeditor-office2013-skin

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/19779102/37599678-9c45-11e6-86e9-a8f748da06a2.png)

**Comment by tandraschko** [comment]
So the error should occur with plain ckeditor, too? (without JSF and PFE)

**Comment by jxmai** [comment]
That's a good point! I just tried it and I can confirm the office 2013 skin **works fine** without JSF and PFE. That means it is not the skin's issue and this issue is valid.

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/19813338/e2bc850c-9cfe-11e6-929d-10233b80e5d7.png)

**Comment by jxmai** [comment]
Fixed. I will raise a PR shortly.

![snapshot2](https://cloud.githubusercontent.com/assets/10467831/19814657/c12600a2-9d04-11e6-9927-48875e8b81d4.png)

**Comment by melloware** [comment]
Nice work!

**Comment by jxmai** [comment]
Tested. It should be fine. Closing.
