### ISSUE TITLE
Timeline component throws errors in the showcase

### ISSUE THREAD

**Issue by jxmai** [primefaces-extensions/primefaces-extensions.github.com#420]
URL is :  .../sections/timeline/editClient.jsf

![image](https://cloud.githubusercontent.com/assets/10467831/19916506/8026e53a-a088-11e6-8fb3-f10276b8aebd.png)

![image](https://cloud.githubusercontent.com/assets/10467831/19916458/1509759c-a088-11e6-9ec8-b8fd5778cf48.png)

The reason is there is no ```p:convertTimelineEvents```

![image](https://cloud.githubusercontent.com/assets/10467831/19916486/3dd0f2e8-a088-11e6-8504-bdbc604c60f9.png)

**Comment by Rapster** [comment]
First, how come TimeLine showcases is still there? Secondly, `convertTimelineEvents` has been removed from primefaces-extensions.taglib.xml since we upgrade into PF 6.0, but still physically present here `TimelineEventsConverter`. See commit ffc1198e38651b0749a9b2a4e99d1b8c27d349a8 `TimelineEventsConverter` has not been migrated as it should

**Comment by tandraschko** [comment]
I restored the showcase because PF didn't migrated all the examples.
IMO we should just remove the examples with p:convertTimelineEvents....
PF6 is already a half year old and noone needed the tag till now.
But feel free to provide a PR in PF if you need it.

**Comment by melloware** [comment]
And before we release 6.1 we should remove Timeline, TriStateCheckbox and any other code from the Showcase that has been moved to PF6.

**Comment by tandraschko** [comment]
If you will migrate the samples to primefaces, we can remove it.
Otherwise we leave it as users may need the examples (was requested some times in the forum).

**Comment by melloware** [comment]
I have removed the non working examples from the Timeline showcase.
