### ISSUE TITLE
Extensions core version 6.1.0-SNAPSHOT is missing in sonatype

### ISSUE THREAD

**Issue by sytolk** [primefaces-extensions/primefaces-extensions.github.com#421]
It`s have important bugfix for me in 6.1.0-SNAPSHOT version can you upload it in sonatype?
https://oss.sonatype.org/content/groups/public/org/primefaces/extensions/primefaces-extensions/

**Comment by tandraschko** [comment]
build from source ;)
however, the code must probably not work with 6.0 anymore.

**Comment by tandraschko** [comment]
@melloware If you would like to setup up snapshots builds, please assign the ticket to you. Otherwise i would close it as won't fix.
We had some builds some years ago but not sure if they are still there. Maybe you can contact Oleg.

**Comment by sytolk** [comment]
@tandraschko I have already build it from source.. how can I know for the bugs with DynaForm validation in 6.0 :) the problem is that I can`t upload it in git with my local maven repository..

**Comment by melloware** [comment]
I will build snapshot versions of the latest to the Sonatype repo.  I should have it done in the next couple of hours

**Comment by melloware** [comment]
Latest SNAPSHOTS are available now: https://oss.sonatype.org/content/repositories/snapshots/org/primefaces/extensions/

**Comment by sytolk** [comment]
Thanks!
