### ISSUE TITLE
CKEditor - Regression unable to perform AJAX update inside a dialog since upgrade to v 4.5.9

### ISSUE THREAD

**Issue by jxmai** [primefaces-extensions/primefaces-extensions.github.com#423]
This issue was discovered during the time I was investigating Issue #414 (See comment: https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/414#issuecomment-259199297)

In order to reproduce this issue and to make sure this regression was actually happened in the ckeditor project, we need to use ```v6.0.0 as the core``` and only to roll back the ckeditor project.

---
Steps to reproduce:

As a quick demo, I slightly modified the **pom.xml** in the showcase as follows

![snapshot3](https://cloud.githubusercontent.com/assets/10467831/20122061/9ac7bca0-a5da-11e6-9887-4a678fea996f.png)

**Sample xhtml**

```xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
     xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:p="http://primefaces.org/ui"
    xmlns:pe="http://primefaces.org/ui/extensions"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    >

    <h:head>
    </h:head>

    <h:body>
            <p:commandButton oncomplete="PF('testDialog').show()" value="Test" update="dialog"></p:commandButton>

            <p:dialog id="dialog" widgetVar="testDialog">
                    <h:form id="editorForm">
                            <pe:ckEditor id="editor"></pe:ckEditor>
                    </h:form>
                </p:dialog>

    </h:body>

 </ui:composition>
```

Step 2: checkout the commit: https://github.com/primefaces-extensions/resources-ckeditor/commit/3af38710a58723d93df64e21bbae3117f73dab00 and clean install the project

Step 3: run the sample xhtml I provided.

---

The problem  occurred during the process of upgrading to v4.5.9 

In Primefaces 6.0, Click Test button and the dialog shows up immediately:

![snapshot3](https://cloud.githubusercontent.com/assets/10467831/20106892/43fda080-a59c-11e6-9324-1e5bef4f738a.png)

Currently, there is no dialog showing up on the first click even without the js error (The screenshot below was running on  Extensions 6.0 + CKEditor Project v 4.5.9 with commit: https://github.com/primefaces-extensions/resources-ckeditor/commit/3af38710a58723d93df64e21bbae3117f73dab00)

![snapshot3](https://cloud.githubusercontent.com/assets/10467831/20108558/0f3367ee-a5a2-11e6-830a-cd872bc604d5.png)

**Comment by tandraschko** [comment]
testing with 6.0 is senseless as trunk is already based on 6.1 since a half year.
So does it work with 6.1 or whats the problem?

**Comment by jxmai** [comment]
No. This issue was discovered in the 6.1 trunk. I rolled back to trace the initial bad commit. **Let's break the mind-map down:** 

- ext core 6.1 Snapshot + resource-ckeditor 6.1 Snapshot (`failed`)
- ext core 6.0 + resource-ckeditor 6.0 (`passed`)

---

It must be a regression, but I cannot tell whether the bug was introduced in the ext core or in the ckeditor. Going further:

- ext core 6.0 + resource-ckeditor 6.1 Snapshot (`failed`)
- ext core 6.0 + resource-ckeditor 6.0 (`passed`)

---

Up to here, I can tell the bug was introduced in the resource ckeditor. 

- ext core 6.0 + resource-ckeditor 6.1 Snapshot with commit (https://github.com/primefaces-extensions/resources-ckeditor/commit/3af38710a58723d93df64e21bbae3117f73dab00) (`failed`)

- ext core 6.0 + resource-ckeditor 6.1 Snapshot with commit (https://github.com/primefaces-extensions/resources-ckeditor/commit/b98495edeab8e217fc20d30fa5335335666e25da) (`passed`)


Regression happened between:

![snapshot3](https://cloud.githubusercontent.com/assets/10467831/20147933/d70d6dd2-a66f-11e6-94d2-0aeba57c79c4.png)

**Comment by tandraschko** [comment]
@melloware if you have time to fix, please do. If you need help for something, just ping me.

**Comment by melloware** [comment]
I will see if I can track it down and reach out if I can't figure it out.

**Comment by melloware** [comment]
OK I was able to debug it and find a few issues.  I added this example to the Showcase so we can test it again in the future as well.  @jxmai feel free to test out to see if it is fixed.

Commit: https://github.com/primefaces-extensions/core/commit/cf2ba746de0247ba99e975ecf18ede217435b1be

**Comment by jxmai** [comment]
Works great :)  I tested the new code using both the bug sample and a real application. This issue can be marked as fixed IMO.

**Comment by melloware** [comment]
Thanks for testing!  Closing it out.
