### ISSUE TITLE
pe:ckeditor save button has no label

### ISSUE THREAD

**Issue by seschi98** [primefaces-extensions/primefaces-extensions.github.com#424]
We discovered a bug in the CKEditor extension of PrimeFaces: The toolbar button "Save" does not have a title attribute. If you go to the showcase page at [http://www.primefaces.org/showcase-ext/sections/ckEditor/basicUsage.jsf](http://www.primefaces.org/showcase-ext/sections/ckEditor/basicUsage.jsf) you can hover over every single button and you will get a tiny label/hint.

If you do the same with the "Save" button, you won't see anything showing up. If you are in Chrome or Firefox, you will also see in your status bar that there is just an empty string as a parameter in javascript:void() instead of the label text.

We would be very happy to see this fixed.

![bug primefaces ckeditor](https://cloud.githubusercontent.com/assets/8929221/20784789/cf9cac00-b79c-11e6-9134-6c51217e8f71.png)

**Comment by melloware** [comment]
We will investigate and fix

**Comment by melloware** [comment]
Fixed in 6.1 with this commit.  https://github.com/primefaces-extensions/core/commit/8b0bef72069d62148fb5112de0c5d3196ab8aa2a

**Comment by jxmai** [comment]
@melloware I tested. The changes worked fine even on different languages.  There is a small issue that you might want to take a look at:  

In `primefaces-extensions.source.js`: https://github.com/primefaces-extensions/core/blob/4e0dc842f2f610312f02a838e2464deada2f770c/src/sourcemap/6.0.0/primefaces-extensions.source.js#L739. There is a mirror code for some reason.

![snapshot3](https://cloud.githubusercontent.com/assets/10467831/21019166/22ba33b0-bd35-11e6-9ba7-d849f4ba14bd.png)

**Comment by melloware** [comment]
That is just in the source map which is used for debugging.  So when we release 6.1 there will be a new source map which has the update.  I just found out what that was recently from Oleg!  Check out his blog post..

http://ovaraksin.blogspot.ch/2015/06/create-source-maps-at-project-build.html

**Comment by jxmai** [comment]
Thanks for the link. Cool :+1:
