### ISSUE TITLE
Layout - togglerTip doesn't work

### ISSUE THREAD

**Issue by Xanas80** [primefaces-extensions/primefaces-extensions.github.com#428]
The attribute values from togglerTipClosed and togglerTipOpen are not used. The default values 'Close' and 'Open' still used instead of the custom values.

```xml
<pe:layout fullPage="true"
           resizerTip="#{baseBundle['base.layout.resize']}"
           togglerTipClosed="#{baseBundle['base.layout.open']}"
           togglerTipOpen="#{baseBundle['base.layout.close']}">
...
</pe:layout>
```

**Comment by melloware** [comment]
It looks like the Tips used to work that way and along the way the Layout changed how they use their tips but this widget was not updated to go along with it.  I will fix it.

**Comment by melloware** [comment]
Are you sure this is an issue?  Look at this showcase example:
http://www.primefaces.org/showcase-ext/sections/layout/fullPageLayoutAttr.jsf

If you click on "Show layout created by pane options" link it takes you to this page:
http://www.primefaces.org/showcase-ext/sections/layout/fullPageAttr.jsf

And I see the tooltips says "Close Me", "Open Me" etc.

**Comment by Xanas80** [comment]
Yes, i am sure it is an issue.
Have a look at your linked showcase example at the toggler between West-North and West-Center and West-Center and West-South.

**Comment by Xanas80** [comment]
And it would be nice the togglerTips of layout works with 
```xml
<pe:tooltip global="true"/>
```

**Comment by Rapster** [comment]
Looks like it happens with nested panes

**Comment by melloware** [comment]
I will do some more investigation.  I just updated this component so let me test on the latest version

**Comment by melloware** [comment]
OK so for the nested child panes it is not respecting the tooltips in the JQuery Layout component.  I have reported the defect here:   https://github.com/allpro/layout/issues/16

Also I have confirmed Global Tooltips don';t work becuase the Jquery Layout component is changing the DOM to add title="" when the Global ToolTip inspects the DOM and replaces all tooltip="" with oldtooltip="" so the browser doesn't show the tooltip.  So basically since Layout is dynamically adding tooltip it constantly overwrites what the Global ToolTip is doing.

**Comment by Rapster** [comment]
Not sure you'll get an answer, it's been a while the project has not been updated

**Comment by melloware** [comment]
I am using this guys fork as he has done some nice updates including making it forward compatible wiht Jquery 3.0.  https://github.com/GedMarc/layout  Maybe he will fix it. :)

**Comment by melloware** [comment]
OK working with the JQuery Layout team they pointed out that we are using an older version of the options and that the defaults are not global for every child.  The only way to fix it was I had to do the following:

1. Add a new tip called 'sliderTip' which is the tooltip when the slider is hovered.
2. Had to add the 4 options at the LayoutPane level.  So on the Layout those are the 'Default' tooltips.  Each LayoutPane can be individual assigned the same 4 tooltips so now you can have individual hints on every single pane! Example Below

```xml
<pe:layout resizerTip="Resize Default" 
                  togglerTipClosed="Close Default" 
                  togglerTipOpen="Open Default" 
                  sliderTip="Slide Default">  
...
        <pe:layoutPane position="north" size="50%" 
                                  resizerTip="Resize North" 
                                  togglerTipClosed="Close North" 
                                  togglerTipOpen="Open North"
                                  sliderTip="Slide North">  
</pe:layout>
```

**Comment by Xanas80** [comment]
Good job! :)
