### ISSUE TITLE
Exporter - postProcessor called multiple times on multiple targets

### ISSUE THREAD

**Issue by simoneobo** [primefaces-extensions/primefaces-extensions.github.com#433]
Hi guys,
i'm using exporter component on two targets with postProcessor method, and the method is called multiple times depending to numbers of targets.
I think this is an issue and post process must be called only once.

Example:
`<pe:exporter type="xlsx" target="tab1,tab2" postProcessor="#{dataExporterMB.postProcessXLSX}"/>`

Bean code:
`public void postProcessXLSX(Object document) {
  System.out.println("POST PROCESSOR TEST");
}`

In this case the string "POST PROCESSOR TEST" is showed twice.

What do you think?

Thanks

**Comment by Rapster** [comment]
First, it'be interesting to have a look to the stacktrace. I'm quite sure you'll find an explanation from that. Second, provide a sample so we can check what's wrong. Clone this repository https://github.com/primefaces/primefaces-test, add primefaces-extensions as a dependency and you're ready to go

**Comment by simoneobo** [comment]
Hi, thanks for your response. 

This one is an extract of export function from ExcelExporter.java of Primefaces.

`    	[...]
       **if(preProcessor != null) {
    		preProcessor.invoke(context.getELContext(), new Object[]{wb});
    	}**

        for(DataTable table : tables) {
            String sheetName = getSheetName(context, table);
            if(sheetName == null) {
                sheetName = table.getId();
            }
            
            Sheet sheet = wb.createSheet(sheetName);
            exportTable(context, table, sheet, pageOnly, selectionOnly);
        }
            	
    	**if(postProcessor != null) {
    		postProcessor.invoke(context.getELContext(), new Object[]{wb});
    	}**
        [...]`

You see that for multiple tables preProcessor and postProcessor are called only once.

This code instead is from function Export of ExcelExporter.java from Primefaces Extensions 6 (begin at line 93)

`while (st.hasMoreElements()) {
            String tableName = (String) st.nextElement();
            [...]
            DataList list;
            DataTable table;
            **if (preProcessor != null) {
                preProcessor.invoke(context.getELContext(), new Object[]{wb});
            }**
            [....]
            **if (postProcessor != null) {
                    postProcessor.invoke(context.getELContext(), new Object[]{wb});
             }**
        sheet.createRow(sheet.getLastRowNum() + Integer.parseInt(datasetPadding));
        }`

Pre and Post process are inside while loop, so they are called multiple times on the same excel sheet.

So, for example, if i export two tables using <pe:export target="tab1,tab2" postProcess="{bean.postProcess}/> and in postProcess function i write a simple code for make text font bold, it will be called twice, undoing the bold effect (first time it will make text bold, second time it will undo the prior bold effect).

Anyway, I will try to provide a sample code. Thanks

**Comment by melloware** [comment]
Agreed I see exactly what you are talking about.  I will fix it.

**Comment by melloware** [comment]
Please review this commit...

https://github.com/primefaces-extensions/core/commit/977a2d7f60ac7bcf8f34f9b3228d7c2f0931d36f

**Comment by simoneobo** [comment]
Looks good for me. Thank you! 👍

**Comment by melloware** [comment]
@simoneobo can you look at #469 from @SantoshCC?   he is saying the row number is now reporting incorrectly in the Excel PostProcessor?

**Comment by simoneobo** [comment]
@melloware ok read it. I'm waiting an example because i don't understand the problem related to this fix

**Comment by melloware** [comment]
@simoneobo Agreed.  I think your fix suggested to do what PrimeFaces was doing is the right thing to do.  I have no idea what he means by "the row number" is wrong.  I may end up closing that ticket as invalid.
