### ISSUE TITLE
New Component: FloatTHead

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions.github.com#434]
We use a lot of Scrolling datatables at my company and they always request to be sticky header.  Well I reported it as a PRO user and PF said NO they won't support Sticky + Scrolling.  See these Github issues as examples:
https://github.com/primefaces/primefaces/issues/1400
https://github.com/primefaces/primefaces/issues/834
https://github.com/primefaces/primefaces/issues/1966
https://github.com/primefaces/primefaces/issues/326

I was considering implementing JQuery FloatTHead: http://mkoryak.github.io/floatThead/datatables/

It solves every single floating datatable problem and works with Responsive tables, scrolling tables, resizing tables etc etc etc.

Thoughts?

**Comment by jxmai** [comment]
Cool feature ! :+1:  I had this issue before. Looks like it is still an issue ... (another non-related issue I have seen was the sticky header can float on top of the premium layout menu) 

The question is how to integrate this feature into PF extension since p:datatable is in PF core ?

**Comment by melloware** [comment]
Right now you do this...
`<p:datatable sticky="true"...`
I am thinking the new PFE component you would do this...
`<pe:floathead target="myDataTable"/>`
Where it would just find the datatable by taget and then find the <th> of the datatable and attach Jquery FloatHead to it.

**Comment by jxmai** [comment]
Alright, it looks reasonable :) . Going further I think the `<pe:floathead>` would be nice to  have multiple targets identified by space or comma.

For instance:

```html
<p:datatable id="table1"/>
<p:datatable id="table2"/>
<p:datatable id="table3"/>
...

<pe:floathead target="table1,table2,table3..."/>

or

<pe:floathead target="table1 table2 table3..."/>
```

**Comment by melloware** [comment]
It will allow both multiple targets and the cool primefaces [selectors](http://www.primefaces.org/showcase/ui/ajax/selector.xhtml) as well so you could say...

`<pe:floathead target="@(.ui-datatable)"/>`

Which says find all components on the page styled with ui-datatable which is all p:datatables.

**Comment by jxmai** [comment]
> It will allow both multiple targets and the cool primefaces selectors

That's the even better ! If the primefaces selectors work, `<pe:floathead>` will be really flexible to use.

**Comment by melloware** [comment]
So in my testing so far this isn't exactly perfect.  It still has some strange anomolies like the native PF Sticky header does when using Responsive layout of the Table.  Still testing.

**Comment by melloware** [comment]
Closing this ticket as the TFloatHead is not an improvement over the PF sticky behavior.
