### ISSUE TITLE
DocumentViewer - Download file is always named document.pdf when streamed

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions.github.com#436]
Multiple users asking for this functionality that when using StreamedContent the download of the file is always named "document.pdf" by default.   Users are asking for a way of overriding that default name to give it their own name.

See this forum thread:  http://forum.primefaces.org/viewtopic.php?f=14&t=43602

**Comment by melloware** [comment]
Fix #436 DocumentViewer - new property "download" to name download files when using StreamedContent .

`<pe:documentViewer height="500" value="#{basicDocumentViewerController.content}" download="extensions-rocks.pdf"/>`

**Comment by tandraschko** [comment]
JFYI: there is a console.log in your commit ;)

**Comment by melloware** [comment]
Ahh yeah I was debugging what the URL looked like.  Will remove thanks!

**Comment by mauromol** [comment]
@melloware why not using `org.primefaces.model.StreamedContent.getName()` to get the document name, just like `p:fileDownload` does?? It sounds redundant to me to have to specify the name again in `download` attribute...

**Comment by melloware** [comment]
I think I can do this. Create a new ticket please.
