### ISSUE TITLE
pe:triStateCheckbox not working in PrimeFaces 6.0

### ISSUE THREAD

**Issue by wolf97084** [primefaces-extensions/primefaces-extensions.github.com#437]
pe:triStateCheckbox with converter is not working correctly in PrimeFaces 6.0., PF Extension 6 It was working fine with PrimeFaces 5.3 and PF Extension 4.

The object passed into getAsString in Converter class always has a value (true/false.) Any null value is passed in as false.

**Comment by tandraschko** [comment]
tristate was moved to PF.
You can create a issue there but the respect the issue template.

**Comment by wolf97084** [comment]
Thank you. I am using the community version, so guess I am out of luck now.

**Comment by tandraschko** [comment]
6.1 will be released with the component in the next months. So if you build from trunk by yourself and create a issue if the issue still persists, you will get a bugfixed version soon ;)
