### ISSUE TITLE
imageAreaSelect keyboard support does not work in google chrome

### ISSUE THREAD

**Issue by lagar84** [primefaces-extensions/primefaces-extensions.github.com#438]
Greetings,

Component imageAreaSelect keyboard does not work in chrome because Chrome uses 'keydown' event, but script is using 'keypress'.

In line 1130 Chrome is excluded from 'safari', so for chrome 'keypress' is used, but Chrome offers no support for arrow keys in 'keypress'.

```javascript
/* Do the dreaded browser detection */
var msie = (/msie ([\w.]+)/i.exec(ua)||[])[1],
safari = /webkit/i.test(ua) && !/chrome/i.test(ua);
```

In line 1160 in file imageareaselect.source.js there is a test to define the key event:

```javascript
/*
* In MSIE and WebKit, we need to use the keydown event instead of keypress
*/
$.imgAreaSelect.keyPress = msie || safari ? 'keydown' : 'keypress';
```

Forcing Chrome to use 'keydown', everything works fine.

**Comment by tandraschko** [comment]
Please create the issue in the imgareaselect github, we can upgrade the plugin if its fixed

**Comment by lagar84** [comment]
Thanks for the feedback, I did not realized that is a third party plugin.
Looking at https://github.com/odyniec/imgareaselect I saw there already is an open issue about this:

https://github.com/odyniec/imgareaselect/issues/29

Unfortunately the project seems to be dead (last release end of 2013) - I will try to find a newer component or workaround the issue.

**Comment by melloware** [comment]
Or if you want to fix the JS yourself and test it submit a PR here.  It does look like that project was dead so there is no harm tweaking this JS in PFE in my opinion.

**Comment by lagar84** [comment]
I created a pull request ( https://github.com/primefaces-extensions/core/pull/41 ).

Sorry for creating the issue on wrong project, Only now I noted.

**Comment by melloware** [comment]
No your issue was in the right place, all issues go here.  Thanks for the PR!
