### ISSUE TITLE
New Component: Clipboard

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions.github.com#439]
Clipboard allows you to copy or cut to the OS clipboard.  Copying text to the clipboard shouldn't be hard. It shouldn't require dozens of steps to configure or hundreds of KBs to load. But most of all, it shouldn't depend on Flash or any bloated framework.

Based on clipboard.js: https://clipboardjs.com/

Example usage either cut/copy from an Input box or just have the text to copy.

```xml
<p:inputText id="txtCut" value="#{clipboardController.cutInput}"/>
<p:commandButton id="btnCut" value="Cut" icon="fa fa-cut" />
<pe:clipboard id="clipCut" trigger="btnCut" action="cut" target="txtCut">
    <p:ajax event="success" listener="#{clipboardController.successListener}" />
    <p:ajax event="error" listener="#{clipboardController.errorListener}" />
</pe:clipboard>
```

Or just put the text you want to go to the clipboard...

```xml
<p:button id="btnNonAjax" value="Non-Ajax Copy" icon="fa fa-copy" href="#" />
<pe:clipboard id="clipNonAjax" trigger="btnNonAjax" action="copy" 
    text="PrimeFaces Clipboard Rocks Without Ajax!" 
    onsuccess="alert('Action: ' + this.action + ' Text:' + this.text);" 
    onerror="alert('Action: ' + this.action + ' FAILED!');" />
```

**Comment by melloware** [comment]
If anyone would like to see Clipboard or any of the other components I have deployed the latest showcase here temporarily...

http://melloware.dyndns-free.com:8080/pe-showcase/views/home.jsf

**Comment by ova2** [comment]
@melloware Thanks for your work and effort! I like to see that our project is keeping alive. Will tweet about the showcase and Hall of Fame :-)

**Comment by melloware** [comment]
@ova2 Thanks!   You guys did all the hard work getting this project going I love being a part of it.  The code is really well organized and writing new components is easy because there are great examples and the Showcase project to test everything out!

**Comment by tandraschko** [comment]
@melloware thanks for you work! Go ahead if you would like to contribute it.

**Comment by tandraschko** [comment]
Just some notes: I don't like the onsucess/onerror on the component itself. Those methods are bound to p:ajax normally.
Why did you add them directly to the component?

**Comment by melloware** [comment]
Good question.  So the Clipboard has onsuccess and onerror events itself which let you know whether data was successfully copied to the clipboard or if it failed because your browser doesn't support it.  So I figured users would want both client side and server side callbacks if they wanted to subscribe to the clipboard copy succeeding or failing.  

Or am I missing what you are saying?

**Comment by tandraschko** [comment]
Yep, therefor i introduced long time ago the "pe:javascript" (also if the name is not perfect).
There are often events which could be used on the client and server side. Always adding a behavior event a "on*" attribute is a little bit to much.

I would remove onsucess/onerror.

Users can then use:
<p:ajax event="success" onstart="someJS; return false;" />
or
<pe:javascript event="success" execute="someJS" />

**Comment by melloware** [comment]
ahh now I see what you mean.   Although it does pre-suppose the user knows they can use pe:javascript.

But for me I like to look at the VDL or Tag doc and see every option available to me on a widget.  If I didn't have onsuccess and onerror callback events on the tag a user might not know they are even available without digging into the source code of the component?

**Comment by mdzaebel** [comment]
Is it possible, to copy via p:menuitem? Obviously, <pe:clipboard ...> can't be used e.g. for <p:contextMenu><p:menuitem> ...

**Comment by melloware** [comment]
It is unclear from your example what text you are trying to copy from this menu item.  The Copy target should be an input text or some control you want to copy text from?

**Comment by mdzaebel** [comment]
Default for _text_ is 'PrimeFaces Rocks!', so I concluded, that the copy does not work, as it is not in the clipboard (paste does not work). In my usecase, I would like to copy via _text="#{bean.value}"_.

**Comment by melloware** [comment]
I just added a new example to the showcase and I have the menu options working fine try this...

It adds a Right Click context menu and assigns the text to the bean #{clipboardController.copyInput} and it all works.

```xml
	    <h:outputText id="lblRightClick">Right click me to view the menu options!</h:outputText>
	    
		<p:contextMenu>
			<p:menuitem id="mnuCopy" value="Copy" url="javascript:void(0)" icon="fa fa-copy" />
		</p:contextMenu>
		
		<pe:clipboard id="clipContextCopy" trigger="mnuCopy" action="copy" text="#{clipboardController.copyInput}">
            <p:ajax event="success" listener="#{clipboardController.successListener}" />
            <p:ajax event="error" listener="#{clipboardController.errorListener}" />
        </pe:clipboard>
```

**Comment by mdzaebel** [comment]
That's great! So _p:clipboard_ must be outside the _p:contextMenu_. Thanks a lot for this example and the documentation, but I did not find it at [https://www.primefaces.org/showcase-ext/sections/clipboard/basicUsage.jsf](https://www.primefaces.org/showcase-ext/sections/clipboard/basicUsage.jsf) However, in my code your solution works too. As documented, without _text_ and _url_, it rocks too. Thank you for this fast reaction!

**Comment by melloware** [comment]
No problem.  My showcase example will be updated when we release 6.2 to show this context menu example.
