### ISSUE TITLE
New Component: GitHub

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions.github.com#440]
GitHub is component to display your Github Repositories.

Based on [jquery.github.js](https://github.com/zenorocha/jquery-github) by Zeno Rocha.

Example:
```xml
<pe:github repository="primefaces/primefaces" iconForks="true" iconIssues="true" iconStars="true" />
```
Renders this cool box displaying the info and links about your project.

![image](https://cloud.githubusercontent.com/assets/4399574/22629504/49eb433a-ebb5-11e6-8ae0-14c1c50ea998.png)

I did find one issue with this plugin which I have reported: https://github.com/zenorocha/jquery-github/issues/48

**Comment by melloware** [comment]
Example here: http://melloware.dyndns-free.com:8080/pe-showcase/sections/github/basicUsage.jsf

**Comment by tandraschko** [comment]
@melloware go ahead! 

Just don't like the "download as zip" buttom from style perspective ;)

I have no problem if you add new component and the css/js are not merged in the PE core files. Just the quality of the widgets should be high enough and it should be no "duplicate" component.

**Comment by melloware** [comment]
Agreed I typically have not been adding the CSS/JS to the PE core for any compoent.  My thoughts being that most components in PFE are so specialized that if someone wants to use one of these extensions components only then should its CSS/JS load and other users not be punished with loading JS they will never use.

**Comment by melloware** [comment]
Ahh the Download button looks fine locally it is munged on deploy which means something must be messing with the SVG font in the "compress" or "copy" resource step of the Maven build.  I will fix.

**Comment by melloware** [comment]
OK so it turned out to be the PFE Resources Optimizer using YUI Compressor and it has this bug converting 0px; to 0 which not all browsers respect.

https://github.com/yui/yuicompressor/issues/113

**Comment by melloware** [comment]
Actually even worse its this issue:  https://github.com/yui/yuicompressor/issues/124

**Comment by melloware** [comment]
OK was able to work around both issues by changing to...

```css
text-indent: 1px;
font-size: 2em;
```

Now it compresses properly and the dowload button looks correct.
