### ISSUE TITLE
New Component: "Coverflow"

### ISSUE THREAD

**Issue by Gigasgagasmann** [primefaces-extensions/primefaces-extensions.github.com#446]
Idea for the next versions:
Although Primefaces has already a p:contentflow component which isn't really useful I suggest to use a more sophisticated implementation like https://vanderlee.github.io/coverflow/
I already integrated this one (using jQuery) into my Primefaces-based application already and it works well, even with pe:documentViewer as "cover" items.

**Comment by melloware** [comment]
Looks pretty cool.  I will see if I can tackle this for 6.2.0...

**Comment by melloware** [comment]
@Gigasgagasmann Can you tell me the advantages of this component over p:contentFlow?   Also p:ContentFlow allows a caption over each image but I can't seem to tell if CoverFlow does or not?

**Comment by Gigasgagasmann** [comment]
It allows full html content (and events) whereas p:contentFlow only allows images.

**Comment by melloware** [comment]
Ahh understood that is a big difference!

**Comment by tandraschko** [comment]
IMO we should try to enhance p:contentFlow instead of doing a second component.

**Comment by melloware** [comment]
@tandraschko I agree with that.  Should I open a PF ticket with this info and close this ticket?

**Comment by tandraschko** [comment]
Yup, +1

**Comment by melloware** [comment]
OK submitted:  https://github.com/primefaces/primefaces/issues/2637

Closing this ticket...
