### ISSUE TITLE
Update Primefaces Extension showcase to version 6.1

### ISSUE THREAD

**Issue by jxmai** [primefaces-extensions/primefaces-extensions.github.com#447]
Currently Primefaces showcase is still using 6.0

> 	PrimeFaces Extensions Showcase - © 2011-2014,	PrimeFaces: 6.0,	PrimeFaces Extensions: 6.0.0,	JSF: mojarra 2.2.8,	Server: jetty/9.4.2.v20170220,	Build time: 2016-06-08 22:55

Showcase: https://www.primefaces.org/showcase-ext/views/home.jsf

![image](https://cloud.githubusercontent.com/assets/10467831/25236755/412de92c-25ae-11e7-821b-e0ea4c0caec6.png)

**Comment by melloware** [comment]
I already sent the WAR yesterday to Optimus Prime but he has not deployed it yet. I will respond here once its deployed!

**Comment by melloware** [comment]
@tandraschko Any word on this from Optimus?

**Comment by tandraschko** [comment]
Nope but you can just ask him via mail again ;)

**Comment by melloware** [comment]
Issue created at PF:  https://github.com/primefaces/primefaces/issues/2428

**Comment by melloware** [comment]
Showcase has finally been updated!
