### ISSUE TITLE
Layout component initClosed attribute bug

### ISSUE THREAD

**Issue by mkomko** [primefaces-extensions/primefaces-extensions.github.com#448]
We just upgraded to PrimeFaces 6.1 and PrimeFaces Extensions 6.1.

Layout:
```
<pe:layout fullPage="false"
	   style="height: 70vh; width: 100%"
	   widgetVar="layoutWidget">
	<pe:layoutPane id="layoutWest"
	   	   	   position="west"
	   	   	   size="300"
	   	   	   initClosed="true">
	</pe:layoutPane>
	<pe:layoutPane id="layoutCenter"
	   	   	   position="center">
	</pe:layoutPane>
</pe:layout>
```

The west pane does not render as closed initially. It auto-closes when you hover over it and then leave the pane area.

Can you please take a look? Thank you very much in advance :-).

**Comment by melloware** [comment]
I have confirmed this is a bug in must be in the upgrade of the new Jquery Layout JS code.  For now to resolve this issue simply remove the initClosed="True" line and add this script to your page to achieve the same results.

```javascript
<script>
$(document).ready(function () {
     PrimeFaces.widgets.layoutWidget.toggle('west');
});
<\script>
```

This will toggle the West closed on initial page load.

**Comment by AndrewShwaika** [comment]
Attribute initHidden="true" is broken also.
Bug is in function resizeAll (0-jquery.layout.js line 4437) in added code for paneResponsive handling.
It doesn't honour  these attributes.

**Comment by melloware** [comment]
Can you suggest a fix I don't mind fixing it in the jquery-layout.js and submitting it back to that team but that project seems to not have a lot of activity right now.   Let me know!

**Comment by GedMarc** [comment]
Thanks Andrew, taking a look

**Comment by GedMarc** [comment]
Thanks a lot,

@melloware I've updated the repository, You can pull the changes down.
@AndrewShwaika You can add the line `if (s.isVisible)' before line 4533 to resolve. 

Thanks for bringing this up

```
                if (s.autoResize && s.size != o.size) // resize pane to original size set in options
                {
                    if (s.isVisible)
                        if (paneResponsive)
```

Please let me know if this is resolved.

Kind Regards,

**Comment by melloware** [comment]
Thanks @GedMarc .  Guys I just updated to the latest JS file and push a 6.1.1-SNAPSHOT jar if you want to try it.  

SNAPSHOT https://oss.sonatype.org/content/repositories/snapshots/org/primefaces/extensions/primefaces-extensions/6.1.1-SNAPSHOT/

**Comment by GedMarc** [comment]
My Apologies, this introduces new responsive recovery bugs.

Please find the correct and complete bug fix in v1.5.12.2

**Comment by melloware** [comment]
No worries thanks for the quick fix.  I have updated to the latest 1.5.12 and pushed a new SNAPSHOT JAR for testing.

**Comment by mkomko** [comment]
Thank you guys very much for the amazingly fast resolution and great teamwork! Also a lot of thanks for pushing a new snapshot that we can use.
:+1: 

I'll leave closing the issue to the experts if you also think it is resolved.

**Comment by melloware** [comment]
@mkomko thanks for testing and thanks to @GedMarc for fixing the issue so quickly! I am going to mark this resolved.

**Comment by GedMarc** [comment]
Don't forget to give a +1 :)

**Comment by melloware** [comment]
@GedMarc done and you should find out if AllPro will make you a committer on the main Jquery UI Layout GitHub.  Your project is now way ahead of his for some features and Jquery 3 support.

**Comment by melloware** [comment]
6.1.1 Release to Maven Central
