### ISSUE TITLE
"Invalid LOC header (bad signature)" for mvn loaded primefaces-extensions-6.1.0.jar

### ISSUE THREAD

**Issue by britzke** [primefaces-extensions/primefaces-extensions.github.com#449]
I use primefaces-extensions-6.*.0.jar loaded from mvn repository. For the latest Version (6.1.0) the servlet-container throws an exception and cannot start. Version 6.1.0 is OK.
```
...
Caused by: java.lang.IllegalArgumentException: java.util.zip.ZipException: invalid LOC header (bad signature)
	at org.apache.catalina.webresources.AbstractSingleArchiveResourceSet.initInternal(AbstractSingleArchiveResourceSet.java:113)
...
```
This occurs for OS X 10.12.3 and Tomcat 8.5.5, Java 8. It seems to be OK for a linux installation.

**Comment by melloware** [comment]
I found this thread which mentions a couple of things..

http://stackoverflow.com/questions/32090921/maven-invalid-loc-header-bad-signature

I am running with Linux and Windows with Java 7 and Jboss EAP 6.4 with no issues so far.

**Comment by britzke** [comment]
OK! I thought it had been reloaded from mvn but the old 6.1.0 files has stayed in the mvn repository. I deleted them and updated the project. So mvn reloaded it. Now every think is fine. Thank you.

**Comment by melloware** [comment]
Awesome thanks for reporting back!
