### ISSUE TITLE
CodeMirror won't save content in PFE 6.1

### ISSUE THREAD

**Issue by myset** [primefaces-extensions/primefaces-extensions.github.com#451]
Hi,
In PFE 6.1 CodeMirror won't save (set) simple text content ... 
```
            <pe:codeMirror id="testCodeMirror"
                           value="#{myBean.myTextField}"
                           readonly="false"
                           smartIndent="false"
                           lineNumbers="true"
                           lineWrapping="true"
                           undoDepth="100"
                           theme="default"/>
```

> Mac OS X 10.12.4 (x86_64)
> Java HotSpot(TM) 64-Bit Server VM 1.8.0_112 Oracle Corporation
> Java Servlet: 3.1 (Tomcat 8.5)
> Java Server Faces: 2.2.14
> PrimeFaces: 6.1
> PrimeFaces Extensions: 6.1.0 

Thank you in advance.

**Comment by melloware** [comment]
I will investigate and fix. Thanks for reporting!

**Comment by melloware** [comment]
OK I fixed it with this commit:
https://github.com/primefaces-extensions/resources-codemirror/commit/0f9dfbc84506107a2cff9fef1eb3a31625addd78

You can try the SNAPSHOT with the fix here:
https://oss.sonatype.org/content/repositories/snapshots/org/primefaces/extensions/resources-codemirror/6.1.1-SNAPSHOT/

Let me know if it works in your testing before I close this ticket.

**Comment by myset** [comment]
Verified successfully.

Thank you for your great work.

**Comment by melloware** [comment]
Awesome thanks for reporting.  I will probably do a 6.1.1 Release after a few more bugs are reported.

**Comment by melloware** [comment]
6.1.1 Release to Maven Central
