### ISSUE TITLE
Google Chart library get loaded multiple times for multiple charts.

### ISSUE THREAD

**Issue by parin1990** [primefaces-extensions/primefaces-extensions.github.com#453]
google chart library is being loaded multiple times ,if the jsf page contains more than one charts. it would create a performance penalty if the page contains multiple charts

**Comment by melloware** [comment]
I have removed this code from the component but now this will require you to include the JS file on your page yourself similar to PrimeFaces GMap component.

Include this script will now be required to make this component work but it will only be loaded once for the whole page.

`<script src="https://www.google.com/jsapi"></script>`

**Comment by melloware** [comment]
Fixed with this commit.

https://github.com/primefaces-extensions/core/commit/948683267cb302eb48766ed037dd1cb1413ea884

**Comment by melloware** [comment]
6.1.1 Release to Maven Central
