### ISSUE TITLE
ClassNotFoundException org.primefaces.extensions.component.spotlight.Spotlight

### ISSUE THREAD

**Issue by juanalejo83** [primefaces-extensions/primefaces-extensions.github.com#454]
Hi,
i have updated the version of primefaces and primefaces-extensions from 6.0 to 6.1
i m trying to deploy my app, but is showing the follow error:

**### weblogic.application.ModuleException: java.lang.ClassNotFoundException: org.primefaces.extensions.component.spotlight.Spotlight
	at weblogic.application.internal.ExtensibleModuleWrapper.start(ExtensibleModuleWrapper.java:140)
	at weblogic.application.internal.flow.ModuleListenerInvoker.start(ModuleListenerInvoker.java:124)
	at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:233)
	at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:228)
	at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)**

i am not using the "spotlight" component in my web app. 
i've tried with the suggested dependencies versions and with the last updates of them.
looking into the primefaces-extensions-6.1.0.jar there is no classes for the spotlight component.

i don't know if i'm missing something, many thanks for your help

all-themes-1.0.10
commons-lang3-3.1
gson-2.2.4
itext-2.1.7
poi-3.9
poi-ooxml-3.9
primefaces-6.1

***
commons-lang3-3.5
gson-2.8.0
itextpdf-5.5.11
javax.el-api-3.0.0
javax.servlet.jsp-api-2.3.1
javax.servlet-api-3.1.0
jsf-api-2.2.14
jsf-impl-2.2.14
poi-3.16
poi-ooxml-3.16
primefaces-6.1

**Comment by tandraschko** [comment]
Clear your temp/workdir/cache stuff. The only 2 places where it could still be referenced are faces-config and taglib and they look fine.

**Comment by Rapster** [comment]
It is not in PF now?

**Comment by melloware** [comment]
Yes Spotlight is no longer a PFE component its a PF component: https://www.primefaces.org/showcase/ui/misc/spotlight.xhtml
