### ISSUE TITLE
PE Calculator - cannot read property 'readonly' of undefined

### ISSUE THREAD

**Issue by jxmai** [primefaces-extensions/primefaces-extensions.github.com#456]
```html
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pe="http://primefaces.org/ui/extensions"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core">

	<h:head>
	</h:head>

	<h:body>
		<pe:calculator></pe:calculator>
	</h:body>

</ui:composition>
```

![image](https://cloud.githubusercontent.com/assets/10467831/25908801/c468664c-3570-11e7-8da8-5f85ad56df98.png)

Using the latest snapshot for both PF and PFE

**Comment by melloware** [comment]
Let me debug with your example.

**Comment by melloware** [comment]
Oh I know why.  Calculator is NOT a standalone component.  You have to attach it to an InputText.

```xml
       <p:inputText id="pInputText" value="#{calculatorController.pInputText}">
            <pe:calculator layout="scientific"/>
        </p:inputText> 
```

Or if you use it standalone you have to tell it what component to attach the calculator to...
`<pe:calculator for="pInputNumber" showOn="both" precision="2"/>`

Just having it standalone will cause the error above.  I wonder if there is some way  I can gracefully detect and throw a JavaScript alert if it is not being used properly?

**Comment by jxmai** [comment]
Shouldn't put a checking logic in here

```js
_applyCalculator : function(input, cfg) {
		this.input = input;
		
		// do not attach calculator if field is readonly
		if (this.input[0].readOnly) {
            return;
        }
		
		var layout = cfg.layout;
		
		if (layout) {
			if (layout === 'standard') {
				// Standard calculator layout with simple operations
				cfg.layout = $.calculator.standardLayout; 
			} else if (layout === 'scientific') {
				// Extended calculator with common scientific operations
				cfg.layout = $.calculator.scientificLayout;
			} else {
			    // custom layout of buttons
			    cfg.layout = layout.split(',');
			}
		}
```

The key is `if (this.input[0].readOnly) {`

if this.input[0] is undefined, don't excute further

**Comment by melloware** [comment]
I was actually thinking a bit higher like this...

```javascript
		if (input.length === 0) {
		    alert('Calculator must use for="target" or be nested inside an input!');  
        } else {
            this._applyCalculator(input, cfg);
        }
```

**Comment by melloware** [comment]
How does this look.  I tested locally and its working.

https://github.com/primefaces-extensions/core/commit/feb0baa76cf640bd6caadb4d72978bac5d3d4bc9

**Comment by jxmai** [comment]
LGTM :+1: but aside from alert, should we also use `console.warn()` since the message can be persisted on the browser ?

**Comment by melloware** [comment]
I am going to use console.error().  To me this is an error condition on how you are using the component.

**Comment by jxmai** [comment]
No problem. console.error() is fine since it violates the component design.

**Comment by melloware** [comment]
OK all changes checked in.  Thanks for reporting!

**Comment by tandraschko** [comment]
Why not throwing a exception on server side to make it clear that it needs to be attached?

**Comment by melloware** [comment]
Good point @tandraschko I didn't know how this was handled in main PF components.  Do you have an example of a component in PF that does anything similar.  I think I modeled this after p:keyfilter?

**Comment by tandraschko** [comment]
Don't know but i think it's quite easy :P

UIComponent comp;
if (for == null) {
   comp = SEF.resolve(for);
} else {
   comp = comp.getParent();
}

if (!(comp instanceof UIInput)) {
   throw new FacesException("calc must be attached to inputs!");
}
