### ISSUE TITLE
PE calculator showcase - Cannot read property 'regionalOptions' of undefined

### ISSUE THREAD

**Issue by jxmai** [primefaces-extensions/primefaces-extensions.github.com#457]
Use `mvn jetty:run` and open the following web page

http://localhost:8080/primeext-showcase/sections/calculator/javascript.jsf

![image](https://cloud.githubusercontent.com/assets/10467831/26007834/cf459be6-3707-11e7-9715-52e9261c289a.png)

There are two more logs:

> Widget not available: ExtCalculator
> core.js.jsf?ln=primefaces&v=6.1:1 Widget not available: ExtCalculator

Page:

![image](https://cloud.githubusercontent.com/assets/10467831/26007908/25bbfda8-3708-11e7-8fee-7378a179c1d5.png)

**Comment by melloware** [comment]
run "mvn clean jetty:run" It looks like it did not pick up your JAR SNAPSHOT changes because I am running locally and this page works fine for me?

**Comment by jxmai** [comment]
Hmm, Looks like I am having local problem now. Even running `mvn clean install` and the problem is still occurring for the calculator component only. 

I will check more before closing this issue.

**Comment by melloware** [comment]
Let me know what you find out.  It definitely could be an issue that for some reason I am not having on my end.

**Comment by jxmai** [comment]
My bad... I accidentally deleted the calculator.js file. The errors are gone after recovering the file.

![image](https://cloud.githubusercontent.com/assets/10467831/26010203/a3fd3cbe-3711-11e7-91ee-7c84d51fdbb6.png)
