### ISSUE TITLE
CodeMirror breaking console.log

### ISSUE THREAD

**Issue by mbechler** [primefaces-extensions/primefaces-extensions.github.com#458]
codemirror.js seems to include CodeMirrors addon/tern/worker.js in the global scope. That overrides console:

```
this.console = {
  log: function(v) { postMessage({type: "debug", message: v}); }
};
```
and even causes an exception when logging as the postMessage expects two arguments.

**Comment by melloware** [comment]
Good catch.  I have removed the tern.js and tern/worker.js addons from the CodeMirror build and I created a SNAPSHOT JAR for you to try.

https://oss.sonatype.org/content/repositories/snapshots/org/primefaces/extensions/resources-codemirror/6.1.1-SNAPSHOT/

**Comment by melloware** [comment]
@mbechler any chance to test this?

**Comment by mbechler** [comment]
A bit busy right now, but I'll test it later today or tomorrow.

**Comment by mbechler** [comment]
Looks good.

**Comment by melloware** [comment]
6.1.1 Release to Maven Central
