### ISSUE TITLE
DynaForm.invokeOnComponent results in endless loop (StackOverflowError)

### ISSUE THREAD

**Issue by DyingSoul81** [primefaces-extensions/primefaces-extensions.github.com#459]
Used libraries: Primefaces Extensions 6.1.0

When traversing the component tree and execution arrives at
[`invokeOnComponent`](https://github.com/primefaces-extensions/core/blob/master/src/main/java/org/primefaces/extensions/component/base/AbstractDynamicData.java#L436) it calls [`resetData()`](https://github.com/primefaces-extensions/core/blob/master/src/main/java/org/primefaces/extensions/component/base/AbstractDynamicData.java#L438).

If `clientId` does not match it delegates to [`invokeOnChildren`](https://github.com/primefaces-extensions/core/blob/master/src/main/java/org/primefaces/extensions/component/dynaform/DynaForm.java#L250) which loops through `dynaFormControls` and sets the `dynaFormControl` as current data (whicht makes sense to me).

After that it calls [`invokeOnComponent`](https://github.com/primefaces-extensions/core/blob/master/src/main/java/org/primefaces/extensions/component/base/AbstractDynamicData.java#L436) again. I think to delegate to the 'child' now by using the current `dynaFormControl` data element.

But [`invokeOnComponent`](https://github.com/primefaces-extensions/core/blob/master/src/main/java/org/primefaces/extensions/component/base/AbstractDynamicData.java#L436) then again calls [`resetData()`](https://github.com/primefaces-extensions/core/blob/master/src/main/java/org/primefaces/extensions/component/base/AbstractDynamicData.java#L438) what is wrong because this clearly results in an infinite loop. Even without the `resetData()` i am not sure that it will work.

To **reproduce the the Problem** it should be enough to initiate a search by id that passes from ViewRoot to the DynaForm (for example by updating an element by id that lies inside the DynaForm). 

![debug screenshot](https://cloud.githubusercontent.com/assets/28896589/26357670/53486182-3fd0-11e7-847a-277fa4284a74.png)

**Comment by DyingSoul81** [comment]
![stacktrace](https://cloud.githubusercontent.com/assets/28896589/26357824/d522e970-3fd0-11e7-9ec4-8f8b29c76a9d.png)

**Comment by Rapster** [comment]
The nice thing with StackoverflowError is that, the stack keeps repeating, so posting few lines of the stack should be enough :)

Otherwise, post some xhtml code or a testable project. I guess the problem should be in there...

**Comment by melloware** [comment]
@DyingSoul81 Yes, a simple reproducible sample XHTML and Bean would be great so we can debug it.

**Comment by kingisep** [comment]
Hello any progress with this bug?

**Comment by melloware** [comment]
I think @Rapster was waiting for someone to provide a reproducible test case so he can debug the issue.

**Comment by Rapster** [comment]
I don't have time at the moment... I'll let you know as soon as I can ;)

**Comment by kingisep** [comment]
OK, thanks

**Comment by juanmiguelRuaDev** [comment]
It seems the exception is thrown when the Dynaform is defined into any dialog form.

**Comment by juanmiguelRuaDev** [comment]
As you can see in the class method `AbstractDynamicData.invokeOnComponent:` line 437, the abstract method `invokeOnChildren(context, clientId, callback);` is invoked. Nevertheless, the overriden implementation of this method in `DynaForm.java:264` call `super.invokeOnComponent(context, clientId, callback)` for each DynaFormControl defined in the DynaFormModel.

**Comment by melloware** [comment]
@juanmiguelRuaDev Do you have a suggested fix?

**Comment by tandraschko** [comment]
Will take care of it. I currently faced the same problem for a customer. Seems like invokeOnChildren isn't implemented completely at all.

**Comment by tandraschko** [comment]
Fixed it. Could anyone please review + test it? Thanks!

**Comment by tandraschko** [comment]
A simple replicate should be if you do a ViewRoot#invokeOnComponent with a absolute ID of a control inside a dynaForm like (form:myDynaform:dnyaFormControlKey:myInput).
