### ISSUE TITLE
<p:autoComplete> renderes a div inside a span

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces-extensions/primefaces-extensions.github.com#462]
The w3c validator is complaining about a div element inside a span element rendered by the autoComplete tag. I suggest to use a span instead of div inside the surrounding span. PR will follow.

**Comment by tandraschko** [comment]
p:autocomplete doesn't belong to PrimeFaces Extensions ;)

**Comment by OBreidenbach** [comment]
Sorry, wrong repository.
