### ISSUE TITLE
documentViewer broken with extrenal URLs after 6.1

### ISSUE THREAD

**Issue by ybendek** [primefaces-extensions/primefaces-extensions.github.com#464]
Hello Guys

I have been using this component without problems until I upgrade to 6.1.1, now when I'm including an external URL an exception is displayed in console and the file is not displayed

VM1172 pdf.viewer.js.jsf?ln=primefaces-extensions&v=6.1.1:20481 Uncaught (in promise) Error: file origin does not match viewer's
at validateFileURL (VM1172 pdf.viewer.js.jsf?ln=primefaces-extensions&v=6.1.1:20481)
at webViewerInitialized (VM1172 pdf.viewer.js.jsf?ln=primefaces-extensions&v=6.1.1:20500)
at <anonymous>

I found that now is required that the URL should be in the same server, apparently you could edit the variable HOSTED_VIEWER_ORIGINS to include the url as is mention in this forum (https://github.com/mozilla/pdf.js/issues/7153) but unfortunatelly with Primefaces-extension I dont have an option, and changing manually that file inside of the jar is an option I dont want to apply

**Comment by melloware** [comment]
Can you try something.  Just somewhere in your own JS code that loads AFTER the PFE code can you add this line...

```javascript
var HOSTED_VIEWER_ORIGINS = ['null',  'http://mozilla.github.io'];
```

Where the URL is the root URL of the PDF you are trying to load?

**Comment by ybendek** [comment]
Nothing, the same exception, I try even debugging the pdf.viewer.js and this code overrides the variable I'm defining in my code, I'm including this code at the end of the file.

**Comment by melloware** [comment]
OK I ripped out that check and updated my notes for any future upgrade to remove this JS.  You can try this 6.1.1-SNAPSHOT I built for your.  Grab the latest one in the DIR from today.

https://oss.sonatype.org/content/repositories/snapshots/org/primefaces/extensions/primefaces-extensions/6.1.1-SNAPSHOT/

**Comment by ybendek** [comment]
Thank you.

How could I include that in my project?  I'm using maven, and I'm including primefaces extensions with a dependency:

<dependency>
            <groupId>org.primefaces.extensions</groupId>
            <artifactId>primefaces-extensions</artifactId>
            <version>6.1.1</version>
            <type>jar</type>
        </dependency>

**Comment by jxmai** [comment]
Don't think snapshot is hosted in [maven](https://mvnrepository.com/artifact/org.primefaces.extensions/primefaces-extensions), so I guess you need to include a local jar file with some setup in `pom.xml`.

---

Here is the  [stackoverflow link](https://stackoverflow.com/questions/4955635/how-to-add-local-jar-files-in-maven-project) that might be helpful to you


![image](https://user-images.githubusercontent.com/10467831/27349875-61833584-55be-11e7-9b7d-0d0b9ebf4210.png)

**Comment by melloware** [comment]
Yep see answer #1 https://stackoverflow.com/questions/7715321/how-to-download-snapshot-version-from-maven-snapshot-repository

**Comment by ybendek** [comment]
thank you
