### ISSUE TITLE
TypeError : PrimefacesEXT.VERSION is undefined 

### ISSUE THREAD

**Issue by SathishKumar07** [primefaces-extensions/primefaces-extensions.github.com#465]
On creating Widget dynamically following Function is called 
"PrimeFacesExt.getPrimeFacesExtensionsResource(name)" during the call it tries to get the Primefaces Extension Version which is UNDEFINED always , Even though the Primefaces Extension is loaded through the parent XHTML

or any work-around solution.

Thanks in advance.

**Comment by tandraschko** [comment]
getPrimeFacesExtensionsResource isn't available since some versions, so there error can't occur anymore.

suggestion:
upgrade to the newest versions or try to forum to get some help for older versions.

**Comment by SathishKumar07** [comment]
Thanks Tandrascho, Can u please let me know the From which version it is available.
I am using Primefaces 3.5 and Primefaces extensions 0.7.1

Thanks 
Sathish

**Comment by tandraschko** [comment]
Not sure, problably since PF 5.x. So it will be a bigger migration.
I would try to set the version via $(function() {...}); manally to workaround the problem. Can't remember the variable name - maybe PrimeFacesExt.VERSION or something.
