### ISSUE TITLE
PDF Exporter: Document Closed before post Processor.

### ISSUE THREAD

**Issue by digopim** [primefaces-extensions/primefaces-extensions.github.com#468]
Since v 6.1 we can not add elements (like sign's bar and images) to a pdf document generated by the exporter, cause the document is closed before the call for postProcessor method.

PDFExporter.class on Version 6.0
`if (postProcessor != null) {postProcessor.invoke(context.getELContext(), new Object[] { document });}}
      document.close();
      writePDFToResponse(context.getExternalContext(), baos, filename);`

PDFExporter.class on Version 6.1.1
`document.close();
      if (postProcessor != null) {postProcessor.invoke(context.getELContext(), new Object[] { document });}
      writePDFToResponse(context.getExternalContext(), baos, filename);`

**Comment by melloware** [comment]
Can you look at this commit.  I moved it after the post processor which is how the code used to be.

https://github.com/primefaces-extensions/core/commit/a4a043ef7162cb25e000695aafb1c56ea0c61ee5
