### ISSUE TITLE
Excel DataExporter: post processor giving wrong row number

### ISSUE THREAD

**Issue by SantoshCCS** [primefaces-extensions/primefaces-extensions.github.com#469]

**Comment by melloware** [comment]
I think this may be related to this?

https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/468

**Comment by SantoshCCS** [comment]
Excel

**Comment by melloware** [comment]
I think it is related to this change.   https://github.com/primefaces-extensions/core/commit/977a2d7f60ac7bcf8f34f9b3228d7c2f0931d36f   

The postProcessor used to be called for every row.

**Comment by melloware** [comment]
OK the more I look at it.  The previous code called the preProcess and postProcess for every row.  I moved it when fixing #433 because that fixed an issue with the PDF Exporter.  I guess this is the intended behavior of the Excel exporter?

**Comment by melloware** [comment]
Can you provide a more detailed example of what you are doing and what is not working?
