### ISSUE TITLE
GChart: Add mapsApi Key

### ISSUE THREAD

**Issue by kukel** [primefaces-extensions/primefaces-extensions.github.com#473]
Currently you are not able to easily provide a key to use with the GChart component. 

See https://stackoverflow.com/questions/45463743/how-to-set-google-maps-api-key-in-primefaces-extensions 

The investigation has already been done and added to the SO question (for the upcoming PFE 6.2 version). Please add this functionality before the release

**Comment by melloware** [comment]
No problem.  I read through that thread but I am unclear on exactly which solution works.  I see he mentions adding the apiKey to the JS then he mentions you have to hack it and add it to the JS URL?  What exactly needs to be done and I don't mind doing it.

**Comment by kukel** [comment]
The 'hack' is for the current 6.1 release. My 'Answer' is for the upcoming 6.2. So ignore the hack/second answer.

**Comment by melloware** [comment]
Got it. Thanks for providing!  I will fix.

- add a mapsApiKey property and getters/setters to GChart.java
- add .attr("mapsApiKey", chart.getMapsApiKey()) to GChartRenderer.java
- add this.mapsApiKey = cfg.mapsApiKey -and 'mapsApiKey': this.mapsApiKey to gchart.js in the right places

**Comment by jepsar** [comment]
I was thinking if you should be able to provide the API key for each component instance. Maybe a context parameter in the web.xml would be enough (for me it would be).

**Comment by melloware** [comment]
@jepsar Hmmm so you could set it on the component but also in the web.xml if you wanted to set it globally.  Good idea.  I think PF does that with its Captcha component i will see how they did it and do the same if I can.

**Comment by jepsar** [comment]
The web.xml parameter could be part of PF core, since it could also be used on https://www.primefaces.org/showcase/ui/data/gmap/basic.xhtml

**Comment by melloware** [comment]
Do you guys mind reviewing this commit:  https://github.com/primefaces-extensions/core/commit/df30bf160c05412997f601dba95d3a92d255871c

I have an apiKey() property you can set on individual charts or you can also use a web.xml  "primefaces.GOOGLE_MAPS_API_KEY" to set it globally for all charts.

**Comment by jepsar** [comment]
Sorry, I was enjoying my vacation last week. Your commit looks great, thanks!
