### ISSUE TITLE
GChart: Double escaping JS after 6.0.19/6.1.1

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions.github.com#475]
From this post https://forum.primefaces.org/viewtopic.php?f=14&t=51344

The Javascript was being escaped in our renderder but PF has globaly changed WidgetBuilder .attr() method to automatically escape JS.  So it was being escaped twice.

**Comment by melloware** [comment]
Fixed with this commit:  https://github.com/primefaces-extensions/core/commit/168d26d49d22c186b4d17831a3f98a58a5930698

**Comment by melloware** [comment]
I created a SNAPSHOT if someone wants to test it.

https://oss.sonatype.org/content/repositories/snapshots/org/primefaces/extensions/primefaces-extensions/6.2-SNAPSHOT/

**Comment by csyperski** [comment]
The snapshot works with 6.1.4 of PF

**Comment by melloware** [comment]
I just cut an Extensions 6.1.5 Elite release including this fix if you need it.  Read here:  https://forum.primefaces.org/viewtopic.php?f=14&t=52458
