### ISSUE TITLE
Remove Component: Analog Clock

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions.github.com#479]
@tandraschko @Rapster @jxmai wanted to take a poll to see if we should remove the Analog clock component from Extensions?

PrimeFaces already has an analog clock:  https://www.primefaces.org/showcase/ui/misc/clock.xhtml

**Comment by jxmai** [comment]
In my opinion, the PF' clock and PFE analog clock are really similar, but there are some subtle differences that should not be ignored. From the framework point of view, until one can be a complete replacement of the other, we should not remove PFE analog clock.

Here is the documentation of p:clock (https://www.primefaces.org/docs/guide/primefaces_user_guide_6_1.pdf): 

![snapshot1](https://user-images.githubusercontent.com/10467831/29747258-6fb72bee-8ab9-11e7-86cf-e214fe1f6cb9.png)

and the documentation of `pe:analogClock` (https://www.primefaces.org/showcase-ext/sections/analogclock/colors.jsf)

![snapshot1](https://user-images.githubusercontent.com/10467831/29747266-ccf04e94-8ab9-11e7-8128-6588761308fe.png)


If we can migrate `colorTheme`, `width` and `startTime` from PFE to PF, the `pe:analogClock` should be safely removed

**Comment by melloware** [comment]
OK it appears both clocks use Rafael.js so it should be possible to migrate these features over to the PF clock if @tandraschko thinks it is worth it.

**Comment by tandraschko** [comment]
- width: coudln't this be done via css?
- colorTheme: css?
- startTime: thats interesting... How can we display a time with a different timezone in PF?

**Comment by melloware** [comment]
- width = you are correct this can be done via CSS
- colorTheme = IMHO this is done poorly in the PFE analogClock as it has all the themes hardcoded in analogclock.js.  So if a new theme is added it won't just work anyway.
- startTime - the PF clock already has a "TimeZone" property and does timezone conversion.  So I think this could be a really small PR on the PF clock.

In my opinion if I can fix the start time primefaces/primefaces#156 issue this component just has too much overlap with a PF component for very little value.

**Comment by jxmai** [comment]
> OK it appears both clocks use Rafael.js

> this component just has too much overlap with a PF component for very little value.

Agree. Especially if these two components are based on the same JS so there is no point to keep.
