### ISSUE TITLE
MasterDetail-Controller throw's NullPointer Exception if masterDetailLevel is not defined

### ISSUE THREAD

**Issue by ssibitz** [primefaces-extensions/primefaces-extensions.github.com#483]
Hello,

I am implementing the MasterDetail-Controller and add new masterDetail's at the Moment.
So it happened to me that i made a mistake and place the masterDetailLevel outSide the masterDetail-Controller.

In the logfile i only got a big NullPointer Stacktrace so I have to debug into the source-code and see that
the renderer is called with no masterDetailLevel - But try to render it instead on given out an missunderstandable error that the DetailLevel is not defined...

> _Here the Stacktrace I got:_

2017-09-08 13:50:37,002 SEVERE [javax.enterprise.resource.webcontainer.jsf.application] (default task-14) Error Rendering View[/calculation/calculations.xhtml]: java.lang.NullPointerException
	at org.primefaces.extensions.component.masterdetail.MasterDetailRenderer.encodeMarkup(MasterDetailRenderer.java:157)
	at org.primefaces.extensions.component.masterdetail.MasterDetailRenderer.encodeEnd(MasterDetailRenderer.java:101)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:920)
	at org.primefaces.renderkit.CoreRenderer.renderChild(CoreRenderer.java:89)
	at org.primefaces.renderkit.CoreRenderer.renderChildren(CoreRenderer.java:72)
	at org.primefaces.component.panel.PanelRenderer.encodeContent(PanelRenderer.java:206)
	at org.primefaces.component.panel.PanelRenderer.encodeMarkup(PanelRenderer.java:123)
	at org.primefaces.component.panel.PanelRenderer.encodeEnd(PanelRenderer.java:58)
	at javax.faces.component.UIComponentBase.encodeEnd(UIComponentBase.java:920)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1863)
	at javax.faces.render.Renderer.encodeChildren(Renderer.java:176)
	at javax.faces.component.UIComponentBase.encodeChildren(UIComponentBase.java:890)
	at javax.faces.component.UIComponent.encodeAll(UIComponent.java:1856)
       ...

 
_When I am doing this (What could be happend):_

From Source:
**Java-Code (Simply):**
`    currentLevel = 4`

**XHTML-Code (Simply):**
```
                    <pe:masterDetail id="masterDetail" level="#{calc.currentLevel}" showAllBreadcrumbItems="false" showBreadcrumb="false">
    <!-- All pe:masterDetailLevel from 1-3 are defined here -->
>
<!-- But here I made the mistake  by placing it outside: -->
<pe:masterDetailLevel level="4" id="LevelRequestPositions">
   <!-- Sample-Code only here -->
  </pe:masterDetailLevel>

```

**What I want ?**
It would be nice if you raise an Exception which say's that the level with the number xx 
is not available in the Master-Controller
instead of showing a bad NullPointer Exception which only say's me there's a Bug in the MasterDetailRender - Class ;-)

**Comment by melloware** [comment]
Fixed with this commit: https://github.com/primefaces-extensions/core/commit/38382d85f56c810796be2f3a34d308f34bef4e2c

**Comment by ssibitz** [comment]
Hello,

Thank you for your fast reply, but as I analyzed your change i think this  
could be done a little bit bether :-)

<b><i>protected void encodeMarkup(FacesContext fc, MasterDetail masterDetail, MasterDetailLevel mdl) throws IOException {
        if (mdl == null) {
            throw new FacesException("MasterDetailLevel must be nested inside a MasterDetail component!");
        }
</i></b>


Is it possible to raise the Faces-Exception on the "right" from which the null-pointer comes
to get a better "readable/understandable" Exception (Or add it) ?

<b>In the MasterDetailRenderer.java - Class the function:</b>
<b><i>public void encodeEnd(FacesContext fc, UIComponent component) throws IOException {</i></b>
calles at last the encodeMarkup Function with a null-pointer for mdl :

<b>
// component has been navigated from the outside, e.g. GET request or POST update from another component<br/>
<i>// masterDetail.getLevel() return 4, but getDetailLevelByLevel return's the null-pointer</i><br/>
    mdl = masterDetail.getDetailLevelByLevel(masterDetail.getLevel());
    }
		// render MasterDetailLevel
		encodeMarkup(fc, masterDetail, mdl);

		// reset calculated values
		masterDetail.resetCalculatedValues();
	}
</b>

But in the debugger i can see that the masterDetail.getLevel() is set to 4,
but not found -> So a null-pointer as result. 

**Here I also would add an Exception like your's, but before calling the encodeMarkup:**

```
        if (mdl == null && && null!=masterDetail && masterDetail.getLevel()!=null) {
           throw new FacesException("MasterDetailLevel [Level="+String.valueOf(masterDetail.getLevel())+"] must be nested inside a MasterDetail component!")
         else
            throw new FacesException("MasterDetailLevel must be nested inside a MasterDetail component!");
}
```
		// render MasterDetailLevel
		encodeMarkup(fc, masterDetail, mdl);

		// reset calculated values
		masterDetail.resetCalculatedValues();
	}

Adding the missing level would be "nice" for the most developer's, so they can search explicit for this level which is missing...

Greetings and Best regards,
Stefan (Sibitz)

**Comment by melloware** [comment]
please submit a PR.  I am little confused on your explanation on where exactly you would put this exception.

**Comment by melloware** [comment]
Nevermind I fixed it:  https://github.com/primefaces-extensions/core/commit/b258e7d58c7b31e82788d89de73ae03dc3533a5f

MasterDetail should never be null so its safe to check and throw this Exception and the one inside encodeMarkup is just a defensive check.

**Comment by ssibitz** [comment]
Now I am confused as I see you now fixed it on the right place
with this commit ?!

[https://github.com/primefaces-extensions/core/commit/b258e7d58c7b31e82788d89de73ae03dc3533a5f]

Do you need more informations because i think that should fix the problem :-)

**Comment by melloware** [comment]
Nope I am good.  All fixed.

**Comment by ssibitz** [comment]
Alright ;-)

Thank you very much for fast fixing it.
