### ISSUE TITLE
CodeMirror: Move code into core

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions.github.com#484]
@tandraschko @jxmai @Rapster 
Does anyone have a problem if I move the CodeMirror code into the core JAR?     I understand leaving CKEDITOR as its own JAR since its 2.5 MB but CodeMirror is down to 300K and it has been greatly simplified.

I just removed AnalogClock which was 172K worth of Javascript so we would not be increasing the JAR size that much but it would be 1 less JAR to release every time we do a build.

Thoughts?

**Comment by tandraschko** [comment]
noone requested it till now and it's a rarely used component, i would leave it in PFE.

**Comment by jxmai** [comment]
Actually I am a codemirror user so it might not be a rarely used component :) 

> Does anyone have a problem if I move the CodeMirror code into the core JAR?


> noone requested it till now and it's a rarely used component, i would leave it in PFE.

I guess the `Core` that melloware mentioned is not Primefaces core, but PFE core, so I am OK with it as we will have one less JAR to maintain separately and it is not big anyway (300K).

**Comment by tandraschko** [comment]
I see. If the license is ok, we can move into core if its really only 300kb.

**Comment by jxmai** [comment]
MIT license, so it should be fine.

**Comment by melloware** [comment]
Yes sorry I meant the PFE core so one less jar to maintain.  I am going to proceed to moving it.  Thanks guys!

**Comment by melloware** [comment]
I have successfully moved the CodeMirror code into the PFE Core Jar, updated the pom.xml and updated the Showcase to remove the old resources-codemirror dependency.  All is working fine!

**Comment by melloware** [comment]
@tandraschko when you get a chance do you mind deleting the resources-codemirror GitHub project.

**Comment by jxmai** [comment]
> when you get a chance do you mind deleting the resources-codemirror GitHub project.

@melloware I have a different opinion here, although resources-codemirror may be not in used later on in the core project, but it contains **the valuable git history** for others to understand how this component was being built / easy to trace bug etc. 

We can **mark it as legacy** but I vote against removing it from repo.

**Comment by melloware** [comment]
@jxmai You are right.   I commented in the readme.md that the project was moved into core.  That should be good enough.

**Comment by jxmai** [comment]
Awesome 😃 . I saw the `README.md` which should be clear enough.
