### ISSUE TITLE
Optimizer: Fork CSS Compressor and make fixes

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions.github.com#495]
As you can see from this thread YUI Compressor seems to be abandoned.

https://github.com/yui/yuicompressor/issues/195

So I am going to grab the CssCompressor.java from that project and just incorporate it right into PFE Optimzer.   The reason being I have been bitten by a few annoying bugs in the compressor but especially this one:  https://github.com/yui/yuicompressor/issues/275

There are also a few PR's for optimization that have never been incorporated either.

**Comment by jxmai** [comment]
YUI has been abandoned by Yahoo for more than 2 years and currently it is only maintained by some external contributors (eventually going downhill IMO).

**Comment by melloware** [comment]
Fixed with this commit: https://github.com/primefaces-extensions/resources-optimizer-maven-plugin/commit/d61fb8a7563d1f5e86781aefc124245c887dd3cf
