### ISSUE TITLE
Layout: Nested CDATA in component

### ISSUE THREAD

**Issue by DimaSol** [primefaces-extensions/primefaces-extensions.github.com#498]
Hi,
When using <pe:layout> and <pe:layoutPane> without any options attribute in <pe:layout>, nested CDATA tags are written in the response which ends up with the 'Error while performing Ajax request: No xml response received -- check server logs' error.
While debugging it, I beliebe I found the root cause: When using <pe:layout> && <pe:layoutPane> without declaring any options attribute in the <pe:layout>, the encodeBegin & encodeEnd methods (in LayoutRenderer.java) are replacing the FacesContext ResponseWriter with a temporary one by using the cloneWithWriter method.
When elementStart method is invoked, it eventually comes to the native JSF com.sun.faces.renderkit.html_basic.HtmlResponseWriter#elementStart that checks if cdata should be written but when the ResponseWriter was cloned, the internal state of the object is not cloned as can be seen in com.sun.faces.renderkit.html_basic.HtmlResponseWriter#cloneWithWriter and the writingCdata boolean flag is not preserved which leads to a state where the writer 'doesn't know' that it is already in the middle of writing cdata so this tag is opened and closed once again what leads to nested cdata tags that leads to this issue.
Below you can find an example of such a response:
```
<update id="some id">
    <![CDATA[<table border="0" cellspacing="0" cellpadding="0" id="terms_tabs" class="tabbedPane">
    ...
        </table>
        ...
        <script id="budgetTblData:addBudgetButton_s" type="text/javascript">
            //<![CDATA[PrimeFaces.cw("CommandButton","widget_budgetTblData_addBudgetButton",{id:"budgetTblData:addBudgetButton"});
            //]]>
        </script>
    ]]>
</update>
```

**Comment by melloware** [comment]
Thanks for reporting.  Let me investigate how best to fix it.

**Comment by melloware** [comment]
I wonder if this is a bug with Mojarra that when you ask for a clone its not cloning all the properties as its missing that "writingCdata" flag when it clones the writer?

**Comment by melloware** [comment]
Can you paste your XHTML here exactly.

**Comment by DimaSol** [comment]
Hi @melloware,
Thank you for the quick response and attention.
I'm not sure if this is indeed Mojarra bug as i don't think that they had an intention that the user will replace the writer in the moddle of writing the reponse.
Regarding providing the xhtml, it is a bit problematic since it is pretty big application. I'll try to create a small example that reproduces the issue.

**Comment by melloware** [comment]
Thank you.  A small sample showing it is all I need.  Then maybe I can figure out how to fix it.

**Comment by DimaSol** [comment]
@melloware 
While creating a small example I found out that this is indeed something that was fixed with Mojarra already but not in the version I am using.
I can see that in 2.2.8 mojarra preserving the state
```
public ResponseWriter cloneWithWriter(Writer writer) {

        try {
            HtmlResponseWriter responseWriter =  new HtmlResponseWriter(writer,
                                          getContentType(),
                                          getCharacterEncoding(),
                                          isScriptHidingEnabled,
                                          isScriptInAttributeValueEnabled,
                                          disableUnicodeEscaping,
                                          isPartial);
            responseWriter.dontEscape = this.dontEscape;
            responseWriter.writingCdata = this.writingCdata;
            return responseWriter;
            
        } catch (FacesException e) {
            // This should never happen
            throw new IllegalStateException();
        }

    }
```
While in 2.0.4 they are not:
```
public ResponseWriter cloneWithWriter(Writer writer) {

        try {
            return new HtmlResponseWriter(writer,
                                          getContentType(),
                                          getCharacterEncoding(),
                                          isScriptHidingEnabled,
                                          isScriptInAttributeValueEnabled,
                                          disableUnicodeEscaping,
                                          isPartial);
        } catch (FacesException e) {
            // This should never happen
            throw new IllegalStateException();
        }

    }
```

**Comment by melloware** [comment]
Ahh that would explain why I don't see it here i am using a a fixed version of Mojarra.  Thanks for reporting back and closing!
