### ISSUE TITLE
pe:ckEditor blur fired after p:commandButton action

### ISSUE THREAD

**Issue by last-free-nick** [primefaces-extensions/primefaces-extensions.github.com#501]
**Szenario:**  Type text in pe:ckEditor with blur event and click on a p:commandButton with an action after that directly

**Actual behaviour:** commandButton action fires before ckEditor blur event.

**Expected behaviour:** blur event should fire before commandButton action.

**Example xhtml:**

```
<p:inputText value="#{Bean.inputText}">
<p:ajax process="@this" /> // correctly fired before commandButton action
</p:inputText>

<pe:ckEditor value="#{ Bean.editorText }">
<p:ajax event="blur" process="@this" update="@none"/> // fired after commandButton action
</pe:ckEditor>

<p:commandButton action="#{ Bean.action() }" process="@this" />
```

**Example bean:**

```
public String inputText;
public String editorText;

public void action () {
  System.out.println(inputText); // works correctly: new value is printed if you change the text in your inputText and then click on the button directly
  System.out.println(editorText); // wrong behaviour: old value is printed if you change the text in your editor and then click on the button directly
}
```

**Comment by melloware** [comment]
@jxmai Any interest in looking at this one?  I have confirmed it is definitely happening just not sure if its a CKEditor issue or not.  The Ajax order of events is definitely as described above.

**Comment by last-free-nick** [comment]
Just found this: https://ckeditor.com/old/forums/CKEdito ... the-editor

They have a delay of 200 ms in the blur event because the focus event is async and causes problem if the blur event doesn't have a delay.

The developer said they'll try to find a solution in 2013, but there's no update on this so far.

**Comment by melloware** [comment]
Ahh so that would definitely explain the behavior we are seeing.

**Comment by jxmai** [comment]
I will take a look later, but is it a CKEditor bug based on the link ? :thinking:

**Comment by melloware** [comment]
@jxmai don't worry about it.  Yes its a CKEDitor issue where they built a 200ms delay into the blur event.

**Comment by jxmai** [comment]
Alright then. but is it already addressed 5 years ago? See: https://github.com/ckeditor/ckeditor-dev/commit/0fdda9f24a9d532ab4b80320a68b2f3b79cea710

**Comment by melloware** [comment]
yeah i am trying to figure out the best way to turn off this delay in our widget.  I found this post too about attaching the focusmanager?  https://stackoverflow.com/questions/23547851/why-is-there-a-delay-when-blurring-in-ckeditor-and-can-i-get-around-it

**Comment by jxmai** [comment]
The easiest way might be to integrate `forceBlur`

https://docs-old.ckeditor.com/ckeditor_api/symbols/CKEDITOR.focusManager.html

> {Undefined} forceBlur() Since: 3.0
Used to indicate that the editor instance has lost the focus. Unlike #blur, this function is synchronous, marking the instance as "blured" immediately.

**Comment by tandraschko** [comment]
Just 2cents from my side: we should not change the default behavior here

**Comment by jxmai** [comment]
Agree, but leave an option to integrate an official api is OK though.

**Comment by melloware** [comment]
Fixed with this commit: https://github.com/primefaces-extensions/core/commit/a29f3d76bed8a12ebe8e45a37f720d8f2584799d

**Comment by melloware** [comment]
Do you think I should revert this and just suggest they add this global config in their own JS file?

**Comment by tandraschko** [comment]
Imo yep

**Comment by melloware** [comment]
Reverted the fix but I left the code commented out in case this comes up again in the future.   The comments will get stripped out by the optimizer anyway so no harm in leaving them in there.
