### ISSUE TITLE
New Component: SpeedTest

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions.github.com#502]
A component the measure the Up-/Download Speed and Ping Response Time for using on "own" server and getting a callback on server when finished with the results?

At current state i need a way to check if one of our customers have problems with the speed to one of our server.

![image](https://user-images.githubusercontent.com/4399574/32553836-ed49e7aa-c465-11e7-8b3d-1e2c8aa242a3.png)

```xml
<pe:speedtest id="speedtest" widgetVar="speedtest" bgColor="#65ed28" captionDownload="Down" captionUpload="Up"  
    captionJitter="Jitter" captionPing="Ping" file="#{request.contextPath}/resources/other/dummy.payload">  
    <p:ajax listener="#{speedTestController.saveResults}" process="@this" update="growl" />  
</pe:speedtest> 
```

**Comment by melloware** [comment]
@ssibitz your component has been incorporated.

**Comment by ssibitz** [comment]
Looks great ;-)

It's for our customer's to check if they have a connection fast enough to work with our application.
Often the customer say's that the application is slow, but forget that they only have an internet-speed of about a little KBit/s to our server by using a phone at no speed ...
