### ISSUE TITLE
GChart: Add ScatterChart

### ISSUE THREAD

**Issue by alkhateeeb** [primefaces-extensions/primefaces-extensions.github.com#506]
GChart Extension not cover all Google Charts
For instance Scatter Chart
Thanks.

**Comment by rapster** [comment]
Yes of course, have you seen the number of existing charts? FYI https://google-developers.appspot.com/chart/interactive/docs/gallery

Feel free to provide a PR

**Comment by melloware** [comment]
I can easily add the SCATTER to the list of options but that doesn't mean it will work out of the box.  You willd have to figure out the right JSON objects to set to make it work.

**Comment by melloware** [comment]
I have added ScatterChart with this commit: https://github.com/primefaces-extensions/core/commit/62ef8eda74ee8805e62f47bd64f959452454b126

Closing this ticket for now.
