### ISSUE TITLE
CKEditor: update causes ` Error code: editor-destroy-iframe.`

### ISSUE THREAD

**Issue by jxmai** [primefaces-extensions/primefaces-extensions.github.com#507]
Sample: 

```xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pe="http://primefaces.org/ui/extensions"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core">

<h:head>
</h:head>

<h:body>
	<h:form>
		<pe:ckEditor id="editor">
		</pe:ckEditor>

		<p:commandButton value="Click me and look at browser console" update="@form"></p:commandButton>
	</h:form>
</h:body>

</html>
```

Step to replicate:

To replicate, Please click the command button

![image](https://user-images.githubusercontent.com/10467831/32915015-1d0b9c5e-cadd-11e7-8b0c-cc7a99feba1c.png)

![image](https://user-images.githubusercontent.com/10467831/32914986-096ad5ac-cadd-11e7-99ad-097de9dd4c75.png)

---

https://docs.ckeditor.com/ckeditor4/docs/#!/guide/dev_errors-section-editor-destroy-iframe

> Location: plugins/wysiwygarea/plugin.js
> Description: The editor's <iframe> could not be destroyed correctly because it had been unloaded before the editor was destroyed. Make sure to destroy the editor before detaching it from the DOM.
Additional data: None.

**Comment by jxmai** [comment]
I did some debug and the error message was popping up from 

```js
this.editable(null);
```

more specifically is here:

```js
CKEDITOR.editor.prototype.editable = function(a) {
            var b = this._.editable;
            if (b && a)
                return 0;
            arguments.length && (b = this._.editable = a ? a instanceof CKEDITOR.editable ? a : new CKEDITOR.editable(this,a) : (b && b.detach(),
            null));
            return b
        }
``` 

---

Without getting into too much details, I noticed that the problem was not about the caller


```js
if (oldInstance) {
                    try {
                        oldInstance.destroy(true);
                    } catch (err) {
                        if (window.console && console.log) {
                            console.log('CKEditor threw an error while destroying the old instance: ' + err);
                        }
                    }
                }
```

since the code above perfectly correct as  https://docs-old.ckeditor.com/ckeditor_api/symbols/CKEDITOR.editor.html#destroy

The main problem is the editor has already been detached from the view before calling destroy. (See below)

![image](https://user-images.githubusercontent.com/10467831/32917192-037eb67a-cae4-11e7-8691-f7e37fa15f07.png)

---

So as an experiment, we can destroy the editor manually and there is no error at all

![image](https://user-images.githubusercontent.com/10467831/32917109-c007082a-cae3-11e7-89a3-1343f2bba3ba.png)


then destroy:

![image](https://user-images.githubusercontent.com/10467831/32917127-d37cd04c-cae3-11e7-8c62-37862fee23c2.png)

**Comment by jxmai** [comment]
By the time commandButton is clicked calling update, the view will be destroyed and re-rendered, so any clean up process should be done on command button start.

There is no way to destroy the editor without the warning when the view is not fully visible.

The following workaround can solve the problem but not a purely native approach

```xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:p="http://primefaces.org/ui"
	xmlns:pe="http://primefaces.org/ui/extensions"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:f="http://xmlns.jcp.org/jsf/core">

<h:head>
</h:head>

<h:body>
	<h:form>
		<pe:ckEditor id="editor" widgetVar="editorWidget">
		</pe:ckEditor>

		<p:commandButton value="Click me and look at browser console" onstart="PF('editorWidget').destroy()"
			update="@form"></p:commandButton>
	</h:form>
</h:body>

</html>
```

![snapshot1](https://user-images.githubusercontent.com/10467831/32928270-c0a1b770-cb16-11e7-8888-aa4bae8d8f1d.png)


but is there a cleaner way to invoke destroy before the editor disappears ? Any JSF lifecycle can be intercepted ? Invoking widget destroy everytime on commandLink, p:ajax, commandButton is not that elegant.

**Comment by melloware** [comment]
agreed. Destroying every Ajax request doesn't make sense.

**Comment by jxmai** [comment]
PR: https://github.com/primefaces-extensions/core/pull/47
