### ISSUE TITLE
<pe:layout> size not changing when using resizeWhileDragging=true

### ISSUE THREAD

**Issue by havivGH** [primefaces-extensions/primefaces-extensions.github.com#510]
Hi,

when using <pe:layout> with resizeWhileDragging=true & size="50%", after resizing I tried to check the new size of the layout but it's didn't changed. (still was 50%)

- I checked it using PrimeFaces widgets.

- And checked it using <p:ajax event="resize" forPosition="center" listener="#{contractTermsTabController.saveNorthSouthLayoutSize}" /> and search in layout options variable.
I also looked in chrome Developer Tools (inspect elements) and checked for the component status inside Network tab but it was empty (see attached image).

Thanks,
Haviv.
![pe_layout network status](https://user-images.githubusercontent.com/33022050/33527031-3b9c6c20-d852-11e7-9727-c580ef060910.jpg)

**Comment by melloware** [comment]
If you use the ajax Resize event I can see the new height and width sent along with the Ajax request and you can capture it. See this example..

https://www.primefaces.org/showcase-ext/sections/layout/fullPage.jsf

Press F12 and watch the network traffic as you resize a pane.

![image](https://user-images.githubusercontent.com/4399574/33527402-3985cec4-d81e-11e7-95fa-a6ba4dbd2920.png)

**Comment by havivGH** [comment]
Hi,
Thank you very much for your answer, it helped me :)
Haviv.

**Comment by melloware** [comment]
Your welcome!
