### ISSUE TITLE
<pe:layout> with <p:ajax> making lots of ajax calls

### ISSUE THREAD

**Issue by havivGH** [primefaces-extensions/primefaces-extensions.github.com#511]
Hi,

I'm using <pe:layout> with resizeWhileDragging=true.
I added <p:ajax event="resize" forPosition="center" listener="#{contractTermsTabController.saveNorthSouthLayoutSize}" /> (I assumed I can do it from here: https://forum.primefaces.org/viewtopic.php?f=14&t=25939) and found two problems:

1. forPosition attribute not working as expected. did you implemented it eventually? maybe other usage?
2. I was expecting to get 1 ajax call but instead I got dozens. I assume you only need to change the overriding the the event onresize to onresize_end

Thank you,
Haviv.

**Comment by melloware** [comment]
1. if you read that forum post you can see Oleg says "but as you know p:ajax doesn't have forPosition attribute".

2. The reason your are seeing lots of Ajax for resize is if you have many panes it is firing the resize event for every pane you have.   See this example and press F12 and watch the network traffic...

https://www.primefaces.org/showcase-ext/sections/layout/fullPage.jsf

You will see a REsize even for the North, South, Center, East and West panes all fired.
