### ISSUE TITLE
XSS attack try

### ISSUE THREAD

**Issue by Loksly** [primefaces-extensions/primefaces-extensions.github.com#512]
Hello everyone,

today I was having a look to the access log file and it surprised me someone tried to get access to our server using something like:

`GET /application/javax.faces.resource/primefaces-extensions.js.jsf;jsessionid=E39B18FBD3057E4291A14440100C2?ln=primefaces-extensions&amp%3Bv=3.2.0&KlDG%3D1312%20AND%201%3D1%20UNION%20ALL%20SELECT%201%2CNULL%2C%27%3Cscript%3Ealert%28%22XSS%22%29%3C%2Fscript%3E%27%2Ctable_name%20FROM%20information_schema.tables%20WHERE%202%3E1--%2F%2A%2A%2F%3B%20EXEC%20xp_cmdshell%28%27cat%20..%2F..%2F..%2Fetc%2Fpasswd%27%29%23 HTTP/1.1`

It was answered with a 500 error. Do you believe it will somehow / anytime succeed?

Thanks for your help.

**Comment by melloware** [comment]
I would not expect that to EVER succeed.  

That being said though I noticed your on PFE 3.2 which is quite old.  The best way to stay on top of library upgrades as well as keeping your server up to date which has the latest security patches closed.  So don't stay on an old version of Jboss or Tomcat or whatever for too long.  Just my 2 cents!

Hope that helps!
