### ISSUE TITLE
Upgrading Resources Optimizer Maven plugin from 2.2.0 to 2.3.0 does not work right anymore !

### ISSUE THREAD

**Issue by ssibitz** [primefaces-extensions/primefaces-extensions.github.com#515]
I have the following setting in maven (Resources Optimizer 2.2.0) which is working correct
without any warnings or error's.

This setting work's correct when i build the WAR - File with the Old Plugin:

```
		<!-- Automatic compress css/js on build -->
		<plugin>
      		<groupId>org.primefaces.extensions</groupId>
      		<artifactId>resources-optimizer-maven-plugin</artifactId>
      		**<version>2.2.0</version>**
			<executions>
	        	<execution>
	          		<id>optimize</id>
	                <phase>package</phase>
	          		<goals>
	            		<goal>optimize</goal>
	          		</goals>
				</execution>
	      	</executions>      
			<configuration>
				<compilationLevel>ADVANCED_OPTIMIZATIONS</compilationLevel>
				<warningLevel>QUIET</warningLevel>
				<failOnWarning>false</failOnWarning>
				<useDataUri>true</useDataUri>
				<suffix>.min</suffix>
			    <resourcesSets>
			      <resourcesSet>
			        <inputDir>${project.build.directory}\\${project.artifactId}\\WEB-INF\\resources\\</inputDir>
			        <includes>
			          <include>**/*.js</include>
			        </includes>
			        <excludes>
			          <exclude>**/*bootstrap*.js</exclude>	// Exclude bootstrap
			          <exclude>**/*min.js</exclude> // Exclude already (manually) compressed files
			        </excludes>
			      </resourcesSet>
			      <resourcesSet>
			        <inputDir>${project.build.directory}\\${project.artifactId}\\WEB-INF\\resources\\</inputDir>
			        <includes>
			          <include>**/*.css</include>
			        </includes>
			        <excludes>
			        	<exclude>**/*min.css</exclude>
			        </excludes>
			      </resourcesSet>
			    </resourcesSets>				
			</configuration>      
		</plugin>

```

When i only change the version of the plugin from 2.2.0 to 2.3.0
then the new plugin ERROR's like that:

- [ERROR] JSC_UNDEFINED_VARIABLE. variable **document** is undeclared at...
- [ERROR] JSC_UNDEFINED_VARIABLE. variable **setTimeout** is undeclared at...
- [ERROR] JSC_UNDEFINED_VARIABLE. variable **window** is undeclared at...
- [ERROR] JSC_UNDEFINED_VARIABLE. variable **Math** is undeclared at...
- [ERROR] JSC_UNDEFINED_VARIABLE. variable **console** is undeclared at...
- [ERROR] JSC_UNDEFINED_VARIABLE. variable **$** is undeclared at...
- 

These are not JavaScript Errors because they are "Standard JavaScript Functions/Variables".
The Dollar-Sign is for jQuery which is in an external File 
but it should only be a WARNING and not a ERROR which breaks the build...

**Comment by melloware** [comment]
Hmmm I use 2.3.0 in my production apps as well as to build PFE.  If you open the PFE core project and run "mvn clean package -Pcompress" it uses the 2.3.0 compressor just fine.

Can you create a small maven project with reproducible example for me?

**Comment by melloware** [comment]
Can you also debug if `<compilationLevel>SIMPLE_OPTIMIZATIONS</compilationLevel>` still causes the issue?  That would help narrow down the bug.

**Comment by melloware** [comment]
Also found this blurb on the WIKI:

**Why does my JavaScript code stop working when I use ADVANCED_OPTIMIZATIONS?**

> Using Advanced mode usually requires some preparation and code changes. Advanced Compilation and Externs explains how to make sure your code works with ADVANCED_OPTIMIZATIONS. You will probably see warnings or errors as well if you use warning levels like DEFAULT or VERBOSE. The Google Closure Compiler validates JavaScript code. E.g. if you declare a global variable without the keyword var, you will see a warning JSC_UNDEFINED_VARIABLE. Warning level can be set in the plugin configuration by the tag warningLevel.

**Comment by melloware** [comment]
@ssibitz any update on this?
