### ISSUE TITLE
Document viewer @ selecting/searching words

### ISSUE THREAD

**Issue by linoleum00** [primefaces-extensions/primefaces-extensions.github.com#525]
I don't know if I am the only one with this particular issue, but the primefaces extensions document viewer component, doesn't work as expected when selecting because the purple background color is way to dark to even see words which are in black color. Or it is even worst when searching because words are covered in green as you can see on the image.

I tried cloning the source and changing colors in the css but it make worst because it then scales words and the look bigger than normal.

![screen shot 2018-02-01 at 8 49 43 pm](https://user-images.githubusercontent.com/3660845/35713035-3187fe0a-0793-11e8-841c-198e5bc55921.png)

**Comment by melloware** [comment]
I have noticed the same thing but since I am not a PDF.js author I didn't spend much time on it.  What is strange though if you go to their running demo it does not happen.

https://mozilla.github.io/pdf.js/web/viewer.html

And I am using their code directly.  Let me know if looking at their viewer vs our viewer helps you figure it out.

**Comment by linoleum00** [comment]
Thanks for your reply @melloware! 
As you said, it's pretty strange that looking at their viewer in action everything works fine.

I don't know maybe styles from the pdf viewer are getting override from primefaces styles?

**Comment by melloware** [comment]
I think I know what is going on and I am going to try to fix it

**Comment by linoleum00** [comment]
that's awesome.. thanks man!

**Comment by melloware** [comment]
OK I found the issue and fixed it.  While I was at it I upgraded to the latest PDF.js release 1.10.88.   

Fixed with commit: https://github.com/primefaces-extensions/core/commit/aa0ef0cb58c1e50f33e9b7b02962794147bd07d7

**Comment by linoleum00** [comment]
Great! Thanks man.... Looking forward to version 6.2 then
