### ISSUE TITLE
New Component - Spreadsheet

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions.github.com#527]
Spreadsheet component that wrappers the excellent [Hansontable](https://handsontable.com/) JavaScript component.

**Features:**

- Fast In-Cell Editing
- Copy/Paste
- Range Selection including Copy/Paste and Fill
- Sorting
- Filtering
- Fixed Columns and Rows
- Ajax Updates and Validation

**Advantages:**

- Ajax Updates only send 1 single cell upon editing and not the entire speadsheet like PF Datatable does
- Can have 10,000 plus editable cells unlike PF Datatable which hits the Form Submit limit
- More familiar Excel like functionality for users especially when replacing an Excel VBA application
- Fills a need in the PF Community: https://forum.primefaces.org/viewtopic.php?f=3&t=51194

**History:**

- Written for a specific client and used in 4 projects before we open sourced it.  
- GitHub Project:  https://github.com/marklcg/jsf-sheet

**Comment by tandraschko** [comment]
Sure that we need to reinvent the wheel? There is already a component available based on PrimeFaces. Can't remember the name currently :D

**Comment by melloware** [comment]
Are you referring to this one?  https://github.com/marklcg/jsf-sheet

**Comment by tandraschko** [comment]
There is another one - let me search on github :D

**Comment by tandraschko** [comment]
http://showcase-showcase.a3c1.starter-us-west-1.openshiftapps.com/index.xhtml

**Comment by melloware** [comment]
Yes I have seen TieFaces but his goals are quite different than HandsonTable.   TieFaces is for taking Excel templates or spreadsheets and displaying them in a web app.  Its all about Importing and Exporting to Excel.

Our sheet component acts like a PrimeFaces datatable but allows in cell editing, sorting etc.  Ours is meant for Data Input as well as display.

TieFaces Data Input Example:  http://showcase-showcase.a3c1.starter-us-west-1.openshiftapps.com/showcase/sheet/WebSheetDataInput.xhtml;jsessionid=d6GdIXSgKuUiE7RdHsijvVsCDUkIHW_Dto68i0Au.showcase-11-xfjgs

All you can do is import and export from Excel and that is not what we use Sheet for.  

**Our Use Case:**
Our customers can view 1 day's worth of 5 minute intervals so (24 * 12 = 288) columns.  They may have 50-100 rows so 28800 cells.  They can tab around and edit any of these 5 minute values which we validate on cell edit if they entered a number too high or too low.  Then when they press submit we only ship the "X" dirty cells to the server side not all 28,800 rows in a Form Submit.

The app was originally a Swing Applet that had the same functionality.  Now with PF and HandsonTable we gave them the exact same if not BETTER user experience.

**Comment by melloware** [comment]
@jxmai @Rapster @ssibitz I have checked in all the code in both Core and Showcase.  I have created 4 demo pages in the showcase to show off the SpreadSheet functionality.  I would love if you guys could take it for a spin and see if there is anything obvious I have missed etc.  Thanks in advance!

**Comment by melloware** [comment]
6.2.1 Deployed in Maven Central!
