### ISSUE TITLE
CKEditor: Can not find resources

### ISSUE THREAD

**Issue by OBreidenbach** [primefaces-extensions/primefaces-extensions.github.com#529]
After the commit https://github.com/primefaces-extensions/core/commit/289b2ed42d950c14647ba72208431df50f883c0d
because of #509 
the CKEditor can not resolve the resources. I think that is because of a failure in:
https://github.com/primefaces-extensions/core/blob/289b2ed42d950c14647ba72208431df50f883c0d/src/main/resources/META-INF/resources/primefaces-extensions/ckeditor/widget.js#L46
the ' + appendedResource' is missing

**Comment by OBreidenbach** [comment]
PR: https://github.com/primefaces-extensions/core/pull/48

**Comment by melloware** [comment]
Hmm what is weird is the showcase works for me and the user that reported the myfaces orchestra issue also reported it working but you are right this definitely looks like a regression.

**Comment by melloware** [comment]
@OBreidenbach I am going to wait a couple weeks to see if there are any other 6.2 issues that arise and probably do a 6.2.1 release

**Comment by OBreidenbach** [comment]
I was also wondering why The showcase is working. But the showcase never reaches that line of code. The ' if (PrimeFacesExt.isExtensionMapping())' is always true.
https://github.com/primefaces-extensions/core/blob/289b2ed42d950c14647ba72208431df50f883c0d/src/main/resources/META-INF/resources/primefaces-extensions/ckeditor/widget.js#L33

**Comment by OBreidenbach** [comment]
@melloware are you aware that the showcase is still version 6.1?
https://www.primefaces.org/showcase-ext

**Comment by melloware** [comment]
Yes I have sent the 6.2 Showcase to Optimus Prime but he has not deployed it yet.  Maybe I will send him a reminder today!

**Comment by thomaswoeckinger** [comment]
When do you plan to release the 6.2.1 version?

**Comment by melloware** [comment]
Will do it today!  I will post back once they are in the Maven Repo.

**Comment by melloware** [comment]
6.2.1 Deployed in Maven Central!

**Comment by OBreidenbach** [comment]
There is already a Version 6.2.2 at Maven Central. What is the difference to 6.2.1. Can not find any hint in the [Release Notes](https://github.com/primefaces-extensions/primefaces-extensions.github.com/wiki/Release-Notes).

**Comment by melloware** [comment]
@OBreidenbach it was an emergency release that fixed 1 issue with Slideout.

https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/535

I will be making a 6.2.3 release coming up that has fixes for CKEditor and the new Sheet Component.
