### ISSUE TITLE
CKEditor resource problem

### ISSUE THREAD

**Issue by murathazer** [primefaces-extensions/primefaces-extensions.github.com#533]
after migrating our application to 6.2, CKEditor does not work anymore. 

In browser console we can see resource loading errors. 

This might be related to [#529](https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/529)

<img width="1435" alt="ss" src="https://user-images.githubusercontent.com/507048/37531348-f3e46a62-294c-11e8-86f1-f4de77eb131f.png">

**Comment by melloware** [comment]
Yep that is the same exact issue.  You can build a SNAPSHOT from source if you want or you can wait another week I am going to build a PFE 6.2.1 patch release including this fix.

**Comment by murathazer** [comment]
@melloware i've built 6.3-SNAPSHOT from source successfully but i get the following error in the browser console and in application log:

`JSF1064: Unable to find or serve resource, ckeditor/ckeditor.js, from library, primefaces-extensions.`

<img width="1435" alt="ss" src="https://user-images.githubusercontent.com/507048/37536795-ae38d60a-295c-11e8-9484-46701e7bc2ea.png">

**Comment by melloware** [comment]
hmm did you build with "mvn clean install -Pcompress" ?

**Comment by melloware** [comment]
Also can you try this in your web.xml...

```xml
	<!-- enable script collecting and moves all script to end of body -->
	<context-param>  
		<param-name>primefaces.MOVE_SCRIPTS_TO_BOTTOM</param-name>  
		<param-value>true</param-value>  
	</context-param>
```

**Comment by murathazer** [comment]
If, i build after adding `primefaces.MOVE_SCRIPTS_TO_BOTTOM` parameter with `mvn clean install` command i get same error:

<img width="1435" alt="ss" src="https://user-images.githubusercontent.com/507048/37538749-a8d5c0f0-2962-11e8-9aad-6b644476ed24.png">

if i build by `mvn clean install -Pcompress` command i get following errors:

<img width="1434" alt="ss" src="https://user-images.githubusercontent.com/507048/37539016-8af1bcf0-2963-11e8-9566-6caabdd2ee5e.png">

**Comment by murathazer** [comment]
@melloware OK, it was my mistake, i forgot to build resources-ckeditor now it runs and only i get require.js error but i think it is OK

`Error: Mismatched anonymous define() module: function (){function a(a){var b=a.toUpperCase().split(" "),c=[],d={"\u2190":37,"\u2191":38,"\u2192":39,"\u2193":40};return b.forEach(function(a){"number"==typeof a?c.push(a):d[a]?c.push(d[a]):c.push(a.charCodeAt(0))}),c}function b(){this._codes={},this._handler=null}return b.prototype._evaluate=function(a){for(var b in this._codes){var c=this._codes[b];c.index=a===c.keys[c.index]?c.index+1:0,c.index===c.keys.length&&(c.index=0,c.callbacks.forEach(function(a){a()}))}},b.prototype.addCode=function(b,c){var d=this._codes[b];if(d)-1===d.callbacks.indexOf(c)&&d.callbacks.push(c);else{if(!this._handler){var e=this;this._handler=function(a){e._evaluate(a.keyCode)},window.addEventListener("keydown",this._handler)}d={callbacks:[c],keys:a(b),index:0},this._codes[b]=d}},b.prototype.removeCode=function(a,b){if(void 0===a&&void 0===b)this._codes={};else if(void 0===b)delete this._codes[a];else{var c=(this._codes[a]||{}).callbacks||[],d=c.indexOf(b);d>-1&&c.splice(d,1)}Object.keys(this._codes).length||(window.removeEventListener("keydown",this._handler),this._handler=null)},b.Code={Batman:"\u2191 \u2191 \u2193 \u2193 \u2190 \u2192 \u2190 \u2192 B A"},window.Konami=b,b}
http://requirejs.org/docs/errors.html#mismatch`

**Comment by melloware** [comment]
nice!

**Comment by melloware** [comment]
6.2.1 Deployed in Maven Central!
