### ISSUE TITLE
New Component: Material Floating Action Button

### ISSUE THREAD

**Issue by ybendek** [primefaces-extensions/primefaces-extensions.github.com#534]
It could be nice to include a similar component like this. Commonly used with the google material design

https://github.com/nobitagit/material-floating-button

**Comment by melloware** [comment]
Here are some other ones to investigate as well:

https://github.com/channasmcs/collapzion

https://www.jqueryscript.net/menu/Material-style-Floating-Button-Panel-Plugin-For-jQuery-st-action-panel.html

I will put this on my TODO list. No promises on timeline though.

**Comment by melloware** [comment]
PF Ticket: https://github.com/primefaces/primefaces/issues/3491

PF Ticket: https://github.com/primefaces/primefaces/issues/1006

**Comment by ybendek** [comment]
Yeap, In fact melloware, as you can see I was the same person who open both requests for primefaces. I think it could be an awesome addition for primefaces extensions :)

**Comment by Rapster** [comment]
@melloware I like the first link, but the implementation is kinda usual as it used only JavaScript...  Not sure it will be possible to port that fork

@ybendek It seems you've been in need of this component for a while now, as you can see,  no one has been able to do it ever since. Why don't you give it a shot? You can't simply delegate the work to other people without giving a shot... It's a good way to start, I don't think it show be too difficult to implement (once the JavaScript/jQuery plugin found :wink:) Saying this, you'll help the JSF community to grow, helping us fixing bugs and improve the library maybe :wink: it's definitely worth to try.

**Comment by melloware** [comment]
@Rapster Agreed I definitely want to use menuRenderer somehow so the component will look something like this...

```xml
<pe:materialButton ...
    <p:menuitem value="Save" actionListener="#{menuView.save}" update="messages" icon="ui-icon-disk" />
    <p:menuitem value="Update" actionListener="#{menuView.update}" update="messages" icon="ui-icon-arrowrefresh-1-w"/>
</pe:materialButton>
```

But from the components I posted above I think only one of them will make that even kinda possible without a ton of work.

**Comment by Rapster** [comment]
Exactly, the behavior is actually the same as `MenuButton`

**Comment by ybendek** [comment]
This is another interesting resource to read....https://material.io/guidelines/components/buttons-floating-action-button.html

The official definition from google material design, I know it could be hard to implement as is recommended by google but some points could be interesting to include.

**Comment by jepsar** [comment]
@melloware did you start working on this? If not, I could try to implement it.

**Comment by melloware** [comment]
@jepsar I have not. Feel free to implement.  I think it would be a useful component.

**Comment by jepsar** [comment]
Another option: https://codepen.io/joaofnds/pen/aBMLXj
I like the simplicity of this solution.

**Comment by melloware** [comment]
Wow I do like that one.  Simply and clean and mostly CSS.

**Comment by jepsar** [comment]
CSS only: https://codepen.io/kylelavery88/pen/KdmBOe

**Comment by jepsar** [comment]
I just remembered this component: https://www.primefaces.org/showcase/ui/menu/stack.xhtml

Isn't that (almost) exactly what is requested?

**Comment by melloware** [comment]
I agree its almost identical i think the Floating Action Button that most people want is the one that is styled like he Google Standards for a Floating Action Button like you posted in your CodePen.  Maybe that Stack component can be mofified to be styled using Font Icons and look like your CodePen.

**Comment by ybendek** [comment]
> I just remembered this component: https://www.primefaces.org/showcase/ui/menu/stack.xhtml
> 
> Isn't that (almost) exactly what is requested?

Well, kind of...but not the same behaviour recommended by Google Material Design...but you are right, the idea implemented will be pretty similar, a collection of menuitems.

One thing it could be a little tricky is the usage of attributes like rendered, for example if you have 3 items and the second is rendered=false, the others should rendered properly filling the empty space.

**Comment by jepsar** [comment]
Okay, in the end I didn't found any of the implementations to be 100% useful, so I created one myself on which I'll base the component.

```
<style>
  .ui-fab {
    position: fixed;
    right: 1rem;
    bottom: 1rem;
  }

  .ui-fab * {
    transition-duration: 100ms;
    transition-timing-function: ease-out;
    transition-property: none;
  }

  .ui-fab-main.ui-button {
    position: absolute;
    right: 0;
    bottom: 0;
    margin: 0;
    width: 56px;
    height: 56px;
    border-radius: 56px;
    z-index: 2;
  }

  .ui-fab .ui-icon {
    position: absolute;
  }

  .ui-fab-main .ui-icon {
    top: 11px;
    left: 11px;
    font-size: 32px;
  }

  .ui-fab ul {
    position: absolute;
    margin: 0;
    padding: 0;
    right: 0;
    bottom: 56px;
    display: flex;
    flex-direction: column-reverse;
  }

  .ui-fab li {
    flex: 0 0 auto;
    list-style-type: none;
    position: relative;
    height: 40px;
    margin-bottom: -40px;
    transition-property: margin;
  }
  .ui-fab.ui-state-active li {
    margin-bottom: 10px;
  }

  .ui-fab li .ui-icon {
    top: 10px;
    left: 10px;
  }

  .ui-fab li a {
    outline: none;
  }

  .ui-fab li .ui-button {
    width: 40px;
    height: 40px;
    border-radius: 40px;
    margin: 0 9px;
    transform: scale(0.5);
    transform-origin: center;
    transition-property: transform;
  }
  .ui-fab.ui-state-active li .ui-button {
    transform: scale(1);
  }

  .ui-fab li .ui-menuitem-text {
    background: #999;
    color: #fff;
    padding: 3px 10px;
    position: absolute;
    right: 56px;
    top: 6px;
    white-space: nowrap;
    display: none;
  }
  .ui-fab.ui-state-active li:hover .ui-menuitem-text {
    display: block;
  }
</style>
```
```
<span class="ui-fab ui-widget"
      onclick="$(this).toggleClass('ui-state-active')">
  <span class="ui-fab-main ui-button">
    <span class="ui-icon pi pi-plus"></span>
  </span>
  <ul>
    <li class="" role="menuitem">
      <a tabindex="-1" class="" href="#">
        <span class="ui-button"><span class="ui-icon pi pi-star"></span></span>
        <span class="ui-menuitem-text ui-corner-all">Eerste</span>
      </a>
    </li>
    <li class="" role="menuitem">
      <a tabindex="-1" class="" href="#">
        <span class="ui-button"><span class="ui-icon pi pi-key"></span></span>
        <span class="ui-menuitem-text ui-corner-all">Tweede maar dan lang</span>
      </a>
    </li>
    <li class="" role="menuitem">
      <a tabindex="-1" class="" href="#">
        <span class="ui-button"><span class="ui-icon pi pi-tag"></span></span>
        <span class="ui-menuitem-text ui-corner-all">Derde</span>
      </a>
    </li>
  </ul>
</span>
```

**Comment by jepsar** [comment]
Just added a PR: https://github.com/primefaces-extensions/core/pull/78

**Comment by jepsar** [comment]
I'm working on the showcase and found some issues with the different themes. I'll try to fix them in a new PR.

**Comment by jepsar** [comment]
Added by https://github.com/primefaces-extensions/core/pull/78
