### ISSUE TITLE
Slideout: Tab offscreen on load

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions.github.com#535]
@tandraschko Can you help me understand this.  Here is what is happening.

Go here and click the Open Button:  https://www.primefaces.org/showcase-ext/sections/slideout/basicUsage.jsf

See the handle is incorrect?

1. Slideout loads but it renders its handle offset from the container. In PF 6.1 this worked fine.

2. In PF 6.2 it now renders incorrectly and I have traced it to this issue.  It loads with initWithDomReady() and in PF 6.1 that was wrapped in function{}; and it rendered properly.

3. Now the only way the component draws correctly is if I add in my widget.js the following code...

```javascript
        // create the slideout
        $(document).ready(function() {
            $this.jq.tabSlideOut(opts);
        });
```
Then my handle renders properly because it is basing it off the panel.   So my question is the old initWithDomReady() worked.  Do we need a WidgetBuilder.init method that wraps in "$(document).ready" ???

**Comment by tandraschko** [comment]
WidgetBuilder#init normally uses document.ready as $(function() {...}} and $(document).ready is the same. It just doesn't use the ready handler if MOVE_SCRIPTS_TO_BOTTOM is enabled.

**Comment by melloware** [comment]
Ahhh I have MOVE_SCRIPTS_TO_BOTTOM and my component in the Showcase is not working.   So it does not have the function{} but its still not loading like document.Ready is?

**Comment by tandraschko** [comment]
MOVE_SCRIPTS_TO_BOTTOM moves the scripts to the end of the body, which means its short short short before document.ready. So it's actually NEARLY the same.

Could you try if it works for you, if you you add a $(function(){..}) around our merged script in MoveScriptsToBottomResponseWriter#mergeAndMinimizeInlineScripts?

**Comment by melloware** [comment]
Let me try that...

**Comment by tandraschko** [comment]
https://stackoverflow.com/questions/6026645/document-readyfunction-vs-script-at-the-bottom-of-page

**Comment by tandraschko** [comment]
But also if that works, it would be just a hack probably. 
We can wait if other similar bugs occur, otherwise we would need to re-add a method in the widgetBuilder called initWithDocumentReady. So 99% of the scripts would just use #init which dynamically renders the readyhandler if MOVE_SCRIPTS_TO_BOTTOM is false, 1% can use strictly the document ready handler.

**Comment by melloware** [comment]
That does not work.  It's the same behavior.   But If I add the $(document).ready() back the tab renders correctly.  its almost as if when the Jquery Tab is doing it calculation for the top and bottom of the Tab as
```css
style="left: -5px; bottom: -1px;"
```
But using $(document).ready() the Jquery Tab calculates the tab to be...
```css
style="left: -5px; bottom: -33px;"
```


.  But in

**Comment by melloware** [comment]
Fixed with commit: https://github.com/primefaces-extensions/core/commit/ec587cc2589137928ca84f95cba8a28e4855ad63
