### ISSUE TITLE
Layout: Deferred Renderer Issue

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions.github.com#536]
@tandraschko have another strange new one for you.  

1. First go here: https://www.primefaces.org/showcase-ext/sections/layout/elementLayout.jsf

2. Click the Switch Between Layouts button and then the layout appears.

Here is what is happening in the Debugger.

1. The Inner Layout is being called with renderDeferred() and the ":visible" check is reporting false so then it falls back to finding the closest "ui-hidden-container" container which is NULL as there is none.

2. The Outer Layout (the one for the whole showcase gets called) its attached to "body" so its ":visible" check in renderDeferred returns true so its rendered.

3. The Inner Layout is never drawn because it was never attached to an OnShow handler in renderDeferred().

This was not broken before so I think it may also be related to MOVE_SCRIPTS_TO_BOTTOM.  Either way I am wonder if in DeferredRenderWidget the fallback if this.jq.closest('.ui-hidden-container') returns NULL that it attaches the OnShowHandler to 'body' which we know will be shown?

Thoughts?

**Comment by tandraschko** [comment]
Does it make sense that Layout is a defferedWidget?

**Comment by tandraschko** [comment]
But really, no idea here :D Never looked at the layout code and no idea here. Also don't have enough to time to check this currently.

**Comment by melloware** [comment]
I will dig further.  That Layout has been Deferred since PFE 3.0 and it looks like the PF version of Layout is also a DeferredWidget.  I will let you know what I find out.

**Comment by melloware** [comment]
It looks like this is a problem with any Deferred Widget living inside the Layout component.

**Comment by melloware** [comment]
OK i spent a lot of time debugging this issue and comparing PF Layout to PF Extensions Layout.   I now know why PF works and PFE doesn't and its nothing to do with MOVE_SCRIPTS or widget.initWithDomReady().   

In any DeferredWidget it checks if jq.is(:visible) to see if its visible in the DOM and render it.  JQuery determines if something is visible by "If an element is visible if its browser-reported offsetWidth or offsetHeight is greater than 0.".

**Test:**  I put just a PrimeFaces InputSwitch in a PF Layout and a PFE Layout.
**Result:**
PF: The offsetWidth and offSetHeight of the InputSwitch are > 0 and this visible = true.
PFE: The offsetWidth and offSetHeight of the InputSwitch are == 0 and this visible = false.

So they both use the identical version of Jquery Layout so now I cannot figure out the difference in why PFE LayoutPane <div> has no offsets and height but the PF one does.

Anyone have any ideas?

**Comment by melloware** [comment]
Nevermind I just answered my own question. PFE has custom CSS doing this for some reason....
```css
.ui-layout-north,
.ui-layout-south,
.ui-layout-west,
.ui-layout-east,
.ui-layout-center {
    display: none;
}
```
Which is totally unnecessary and is causing (:visible) to report false.  Removing this style has fixed this deferrned renderer issue.  I am now going to revert all the other document.ready() changes I made in the other components and test out.

**Comment by melloware** [comment]
Fixed with commit: https://github.com/primefaces-extensions/core/commit/d0963360bff6380b1e40fc60714f9445877caec6
