### ISSUE TITLE
Sheet: cell styleClass does not update on change

### ISSUE THREAD

**Issue by jxmai** [primefaces-extensions/primefaces-extensions.github.com#537]
**1. go to https://www.primefaces.org/showcase-ext/sections/sheet/basicUsage.jsf**

**2. select a cell**

![image](https://user-images.githubusercontent.com/10467831/37723833-5531c82e-2cfd-11e8-80b1-44b208501474.png)

**3. change the value from positive to negative**

![image](https://user-images.githubusercontent.com/10467831/37723864-6f58768a-2cfd-11e8-8499-aba2c5c478ab.png)

**Expecting the cell with negative value to be red, but it stays green**

![image](https://user-images.githubusercontent.com/10467831/37723896-89f99000-2cfd-11e8-8c41-01af7af603ed.png)

**Comment by melloware** [comment]
OK just checked in a fix!  Give it a spin...

**Comment by jxmai** [comment]
Works :+1:  !
