### ISSUE TITLE
Sheet: filtering does not work until the second mouse click 

### ISSUE THREAD

**Issue by jxmai** [primefaces-extensions/primefaces-extensions.github.com#538]
**1. go to https://www.primefaces.org/showcase-ext/sections/sheet/basicUsage.jsf**

![image](https://user-images.githubusercontent.com/10467831/37739256-8fc6594e-2d27-11e8-8de1-ba80712833ca.png)

**2. enter 'a' in id filter, and click on any empty area outside the table**

![image](https://user-images.githubusercontent.com/10467831/37739339-c255723c-2d27-11e8-8177-889bfa817703.png)

**3. The filter does not work until user generates another mouse click inside the filter bar**

![image](https://user-images.githubusercontent.com/10467831/37739466-26a43b9c-2d28-11e8-997b-fbfc380b449f.png)

---

**After clearing the filter bar, the same bug can lead to no records can be shown even if the filter bar is cleared.**

![image](https://user-images.githubusercontent.com/10467831/37739446-117b278a-2d28-11e8-9315-4c5bc2107f7b.png)

**Comment by melloware** [comment]
I don't think I ever noticed this before because I type filter "aa" and I press Enter always to initiate the filter.

Anyway I added filtering on "focusOut". I just checked in a change if you don't mind checking it out and trying again?

**Comment by jxmai** [comment]
I will check right away.

**Comment by melloware** [comment]
Awesome.  Also check this out.  A guy asked about a custom context menu.

https://forum.primefaces.org/viewtopic.php?f=14&t=55020

**Comment by melloware** [comment]
Agreed that is not ideal but I remember having to do that funkiness or filtering that have to destroy the editor and rebuild it..

```javascript
// destroy editor to avoid posting request after filter/sort
sheet.ht.destroyEditor(true);
```

I haven't revisited that in a long time!  And we eat the ENTER so it doesn't do a FORM Submit of the whole page.

**Comment by jxmai** [comment]
Alright, I see. looks weird that we have to destroy the editor before calling filtering (the editor won't be destroyed from the browser after stepping through that line), but I am not fully into the background context to make suggestions :thinking: 

```js
// again, eat enter key. but also fire filter event on enter
    filterKeyUp: function (sheet, e) {
        e.stopImmediatePropagation();
        var key = e.which, keyCode = $.ui.keyCode;
        if ((key === keyCode.ENTER || key === keyCode.NUMPAD_ENTER)) {
            // destroy editor to avoid posting request after resort
            sheet.ht.destroyEditor(true);

            $(e.target).change();
            sheet.filter();
            e.preventDefault();
        }
    },
```

**Comment by melloware** [comment]
Yep feel free to dive in and get familiar so we can make this component great!

**Comment by jxmai** [comment]
Sure! first off I will need to get familiar with the component usages :+1:  Looks like a lot of potential improvements can be made if this component is built on top of  https://handsontable.com/features .

**Comment by melloware** [comment]
Yeah HandsonTable is insane with features.

**Comment by melloware** [comment]
Closing this ticket as the original issue has been fixed.
