### ISSUE TITLE
Sheet: 'total records' on the footer is not updated on filtering - missing a way to get filtered list

### ISSUE THREAD

**Issue by jxmai** [primefaces-extensions/primefaces-extensions.github.com#539]
**1. go to https://www.primefaces.org/showcase-ext/sections/sheet/basicUsage.jsf**

![snapshot1](https://user-images.githubusercontent.com/10467831/37748762-0f7345fa-2d53-11e8-9ef8-cc325eecf837.png)

**2. filter records**

![snapshot1](https://user-images.githubusercontent.com/10467831/37748806-3154d67a-2d53-11e8-8a45-313346c2221c.png)

![snapshot1](https://user-images.githubusercontent.com/10467831/37748838-48584fe6-2d53-11e8-800c-e59bf1e71f73.png)

```html
<h:outputText value="#{sheetController.assets.size()} Records" />  
```

**It seems like missing a way to get a filtered List**

**Comment by melloware** [comment]
OK commit added and Showcase examples updated.  There is a new property called "filterValue" similar to how the Datatable works where it stores the filtered/sorted list.  Then the footer references that and now the records number is dynamic.
