### ISSUE TITLE
DynaForm: add staticTop/staticBottom facet

### ISSUE THREAD

**Issue by Rapster** [primefaces-extensions/primefaces-extensions.github.com#540]
I have this use case where the form is set according to what has been choosed by a user. For example: 

![image](https://user-images.githubusercontent.com/7521311/37760177-373313c8-2db6-11e8-850a-0be4ef950f07.png)

Once picked, form is not aligned with rest:

![image](https://user-images.githubusercontent.com/7521311/37760293-83d4a6ba-2db6-11e8-9977-17d8979946ac.png)

Using staticTop/staticBottom facet will help me to achieve that, as every controls will be in the same table

**Comment by melloware** [comment]
@Rapster I will be doing a 6.2.3 PFE release this week sometime do you want this fix to be a part of it?

**Comment by Rapster** [comment]
Okay I'll try to fix this asap. Thanks for letting me know :wink:

**Comment by Rapster** [comment]
I'll close that ticket once showcase updated

**Comment by melloware** [comment]
Release in 6.2.4 should be in Maven Central shortly.  Showcase sent to PF to update.
