### ISSUE TITLE
CKEditor: Internet Explorer support broken in 6.2 due to  b.startsWith

### ISSUE THREAD

**Issue by svenkatgit** [primefaces-extensions/primefaces-extensions.github.com#545]
I've the following setup: PF6.2.1, Extensions 6.2 (also 6.2.RC1/.1/.2) , CKEditor 6.2.x

If I try to use IE11 in combination with ckeditor it fails with a JavaScript error: "Das Objekt unterstützt die Eigenschaft oder Methode "startsWith" nicht" (object doesn't support ... startsWith)

Error occurs in
CKEDITOR_GETURL=function(a){ ... b.startsWith("\x26")&& ...

According to https://www.w3schools.com/jsref/jsref_startswith.asp IE supports this method with version 12.0

TIA

**Comment by melloware** [comment]
Looks like startsWith is an ES6 feature that of course IE11 doesn't support but all other browsers do.

Solution: https://stackoverflow.com/questions/30867172/code-not-running-in-ie-11-works-fine-in-chrome

Fixing it now.
