### ISSUE TITLE
SourceMaps Missing for minor releases.

### ISSUE THREAD

**Issue by efogleman** [primefaces-extensions/primefaces-extensions.github.com#554]
Getting 404 error using BlockUI component -
https://raw.githubusercontent.com/primefaces-extensions/core/master/src/sourcemap/6.2.4/blockui.js.map
using primefaces-extensions versions 6.2.1, 6.2.2, 6.2.3 and 6.2.4

**Comment by melloware** [comment]
Yep I only genreated source maps for 6.2   Didn't generate for any of the sub items.

**Comment by melloware** [comment]
OK SourceMaps for 6.2.4 are now available!
