### ISSUE TITLE
GChart: Support language property

### ISSUE THREAD

**Issue by neXus1987** [primefaces-extensions/primefaces-extensions.github.com#555]
Is it possible to support the locale:
 google.charts.load("current",{packages:["corechart","geochart","orgchart"], 'language': '<variable>'});

**Comment by melloware** [comment]
Yep should be no problem!

**Comment by melloware** [comment]
Fixed with this commit:  https://github.com/primefaces-extensions/core/commit/9598e08950853c7fcff451ab07f6ac0c8205bbfa

Please review!
