### ISSUE TITLE
Layout: When using layout, InputSwitch isn't rendered correctly inside a datatable until updating the table

### ISSUE THREAD

**Issue by Kameecoding** [primefaces-extensions/primefaces-extensions.github.com#562]
## 1) Version
Primefaces 6.1
Primefaces-extensions 6.1.1

## 2.) Issue 
Input switch isn't rendered correctly only as a vertical line

## 3.) Debugging 
So far I have isolated the cause being the layout, until using it the inputSwitch was rendering correctly.

## Sample Code
```
<pe:layout
	resizeTitle="resize"
        fullPage="true"
	stateCookie="true"
	widgetVar="layout">
	<c:if test="#{resizeComponent ne null}">
		<p:ajax event="resize" update=":#{p:component(resizeComponent)}" />
	</c:if>

	<pe:layoutPane
		position="north"
		closable="false"
		resizable="false"
		spacingOpen="0">
		    <!-- ui:insert header here -->
	</pe:layoutPane>
        <pe:layoutPane
		position="center"
		resizable="true"
		size="50%">
		        <!-- ui:insert dataTable here -->
	</pe:layoutPane>
	<pe:layoutPane
		position="east"
        	resizable="true"
		initClosed="true"
		size="50%">
	               <!-- ui:insert detail panel here -->
	</pe:layoutPane>
	<pe:layoutPane
		position="south"
		resizable="false"
		closable="false">
		<!-- ui:insert footer here -->
	</pe:layoutPane>
</pe:layout>
```

**Comment by melloware** [comment]
Do me a favor can you Clone this repository https://github.com/primefaces/primefaces-test.git and make a small reproducible test case.

The attach the zip here so I can just run "mvn clean jetty:run" to see the behavior.

**Comment by melloware** [comment]
Also just for my knowledge can you try this bug again with the following web.xml switch.

```xml
	<!-- enable script collecting and moves all script to end of body -->
	<context-param>  
		<param-name>primefaces.MOVE_SCRIPTS_TO_BOTTOM</param-name>  
		<param-value>true</param-value>  
	</context-param>
```
I want to see if that makes any difference.

**Comment by melloware** [comment]
OK i was able to reproduce it.

**Comment by melloware** [comment]
It is related to this issue: https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/536

InputSwitch is a DeferredRenderer for some reason and this is why its not rendering correctly inside of a Layout.

**Comment by melloware** [comment]
Fixed with commit: https://github.com/primefaces-extensions/core/commit/d0963360bff6380b1e40fc60714f9445877caec6
