### ISSUE TITLE
Sheet: update to Handsontable 2.0.0

### ISSUE THREAD

**Issue by fheldt** [primefaces-extensions/primefaces-extensions.github.com#563]
The sheet component should update to the latest version **2.0.0** of the underlying Handsontable component.

Currently it uses 0.38.0, which is 2 versions behind. I did a quick test with version **0.38.1** (just replace the 0-handsontable.full.(js,css) with the new versions and I have not seen any problems with it.

**Comment by melloware** [comment]
Just committed 2.0.0 JS and CSS!  Thanks for letting me know.
