### ISSUE TITLE
Error when langagueIn = ECMASCRIPT6

### ISSUE THREAD

**Issue by danilomagrini** [primefaces-extensions/primefaces-extensions.github.com#566]
My pom.xml:

         <plugin>
                <groupId>org.primefaces.extensions</groupId>
                <artifactId>resources-optimizer-maven-plugin</artifactId>
                <version>2.3.2</version>
                <executions>
                    <execution>
                        <id>optimize</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>optimize</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <compilationLevel>ADVANCED_OPTIMIZATIONS</compilationLevel>
                    <warningLevel>VERBOSE</warningLevel>
                    <failOnWarning>true</failOnWarning>
                    <languageIn>ECMASCRIPT6</languageIn>
                    
                    <resourcesSets>
                        <resourcesSet>
                            <inputDir>${project.build.directory}/${project.artifactId}-${project.version}</inputDir>
                            <includes>
                              <include>**/*.js</include>
                            </includes>                            
                        </resourcesSet>
                        <resourcesSet>
                            <inputDir>${project.build.directory}/${project.artifactId}-${project.version}</inputDir>
                            <includes>
                              <include>**/*.css</include>
                            </includes>                            
                        </resourcesSet>
                    </resourcesSets>
                </configuration>
            </plugin>

resources-optimizer-maven-plugin:2.3.2:optimize (optimize):

Input language spec'ECMASCRIPT6' is wrong. Valid constants are: 'ECMASCRIPT3', 'ECMASCRIPT5','ECMASCRIPT5_STRICT','ECMASCRIPT6','ECMASCRIPT6_STRICT','ECMASCRIPT6_TYPED' -> [Help 1]

what should I do? Thx.

**Comment by jxmai** [comment]
I give it a quick run and I can see the warning:

```
[WARNING] Using 'QUIET' as warning level
[WARNING] Input language spec'ECMASCRIPT6' is wrong. Valid constants are: 'ECMASCRIPT3', 'ECMASCRIPT5','ECMASCRIPT5_STRICT','ECMASCRIPT6','ECMASCRIPT6_STRICT','ECMASCRIPT6_TYPED'

```
which means that the exception was thrown in the following method

```java
private LanguageMode getLanguageIn(String languageIn) throws MojoExecutionException {
        try {
            return LanguageMode.valueOf(languageIn);
        }
        catch (Exception e) {
            final String errMsg = "Input language spec'" + languageIn + "' is wrong. Valid constants are: 'ECMASCRIPT3', " +
                        "'ECMASCRIPT5','ECMASCRIPT5_STRICT','ECMASCRIPT6','ECMASCRIPT6_STRICT'," +
                        "'ECMASCRIPT6_TYPED'";
            if (failOnWarning) {
                throw new MojoExecutionException(errMsg);
            }
            else {
                getLog().warn(errMsg);
                getLog().warn("Using 'QUIET' as warning level");

                return LanguageMode.ECMASCRIPT3;
            }
        }
    }
```

so it seems like  the following class throws an exception by invoking  `LanguageMode.valueOf(languageIn);`

```java
import com.google.javascript.jscomp.CompilerOptions.LanguageMode;
```

**Comment by jxmai** [comment]
The error message itself is contradicting, so I will mark it as a bug

```
Input language spec'ECMASCRIPT6' is wrong. Valid constants are: 'ECMASCRIPT3', 'ECMASCRIPT5','ECMASCRIPT5_STRICT','ECMASCRIPT6','ECMASCRIPT6_STRICT','ECMASCRIPT6_TYPED'
```

**Comment by danilomagrini** [comment]
Hi. I used ECMASCRIPT_2018 and worked like a charm.

Reference:
https://github.com/google/closure-compiler/blob/master/src/com/google/javascript/jscomp/CompilerOptions.java

**Comment by jxmai** [comment]
Resolved by: https://github.com/primefaces-extensions/resources-optimizer-maven-plugin/commit/5334da6e19b765db436762b78f9d362ff4e87b76

---


set optimizer plugin to version 2.3.3-SNAPSHOT to get the latest plugin

```xml
<primefaces.core.version>6.2</primefaces.core.version>
		<primefaces.theme.version>1.0.10</primefaces.theme.version>
		<primefaces.optimizer.version>2.3.3-SNAPSHOT</primefaces.optimizer.version>
```

and you can see the following warning message if you try to use ECMASCRIPT6  instead 


```java
[WARNING] Input language spec'ECMASCRIPT6' is wrong. Valid constants are: 'ECMASCRIPT3', 'ECMASCRIPT5','ECMASCRIPT5_STRICT','ECMASCRIPT_2015','ECMASCRIPT_2016','ECMASCRIPT_2017','ECMASCRIPT_2018','ECMASCRIPT_NEXT','ECMASCRIPT6_TYPED'

```

**Comment by melloware** [comment]
thanks @jxmai I just updated the WIKI page too:  https://github.com/primefaces-extensions/primefaces-extensions.github.com/wiki/Maven-plugin-for-web-resource-optimization

**Comment by jxmai** [comment]
Good catch ! looking good so far.
