### ISSUE TITLE
Showcase - deferred widgets look broken on initial page load

### ISSUE THREAD

**Issue by jxmai** [primefaces-extensions/primefaces-extensions.github.com#567]
https://www.primefaces.org/showcase-ext/sections/codeMirror/basicUsage.jsf

![image](https://user-images.githubusercontent.com/10467831/39559080-38b3d1ec-4e59-11e8-8183-d9af939be038.png)

https://www.primefaces.org/showcase-ext/sections/codeMirror/jsCodeCompletion.jsf

![image](https://user-images.githubusercontent.com/10467831/39559096-58793e7c-4e59-11e8-9230-c8d59c1a97f6.png)

@melloware Is it by design or broken ?

**Comment by melloware** [comment]
I think this is related to this same issue: https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/536

**Comment by jxmai** [comment]
Hmm, CKEditor is also a deferred widget, but the resources can be correctly loaded on the initial screen

https://www.primefaces.org/showcase-ext/sections/ckEditor/basicUsage.jsf

![snapshot1](https://user-images.githubusercontent.com/10467831/39613371-5a59ac4e-4f2c-11e8-8b44-5575ab0ae84c.png)

```js
PrimeFaces.widget.ExtCKEditor = PrimeFaces.widget.DeferredWidget.extend({
```


---

On the other note, it seems like layout might be also broken: https://www.primefaces.org/showcase-ext/sections/layout/elementLayout.jsf since there is no layout displayed initially

![image](https://user-images.githubusercontent.com/10467831/39613394-ae277446-4f2c-11e8-9e47-1e92f473d3a4.png)

```js
PrimeFaces.widget.ExtLayout = PrimeFaces.widget.DeferredWidget.extend({
```

**Comment by melloware** [comment]
Its all explained in this issue.

https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/536

If you step through the debugger of the init() method of a widget when it calls this._renderDeferred() when you step into that method it asks "Am I visible?", and the answer now is NO since theh changed to not wrap scripts in the [IFFE](http://adripofjavascript.com/blog/drips/an-introduction-to-iffes-immediately-invoked-function-expressions.html) block.  Maybe you can help me figure it out.  But its all the same issue

**Comment by melloware** [comment]
I think its possible I might need to take another look at wrapping the function{} block around the whole MOVE_SCRIPTS_TO_BOTTOM.  @tandraschko doesn't think that will matter but I am down to that seems to be the only difference between 6.1 when this worked and 6.2 when it doesn't.  Some components seems to need their DOM visible before they can calculate their sizes etc but I have to admit I just don't know enough about it.

**Comment by tandraschko** [comment]
I think you need to write the order of how scripts are initialized and when the "hidden container" logic is called
Then we can discuss it, what exactly happens

**Comment by melloware** [comment]
@tandraschko You are right I can't believe I missed that.  In my example that is not working..

https://www.primefaces.org/showcase-ext/sections/layout/elementLayout.jsf

The scripts are in this order:
```javascript
pf.cw("ExtLayout","widget_j_idt19",{id:"j_idt19");
pf.cw("ExtLayout","fullLayoutWidget",
```

So the inner widget is being rendered before its containing parent widget.

**Comment by tandraschko** [comment]
yep, thats be design
the inner widget must register or a later rendering

**Comment by melloware** [comment]
So I think what's happening for Deferred Widgets is the inner widget renders but says "its parent isn't visible" so nothing happens.  What is strange though is I am trying this with PrimeFaces without Extensions and the Deferred Widgets seem to be working even though it should have the exact same problem?

**Comment by tandraschko** [comment]
Not sure, i didn't implemented this part.

But AFAIR the component, which needs to be initialized when the parent is visible, is a DefferedWidget (e.g. the PrimeFaces.widget.Editor = PrimeFaces.widget.DeferredWidget).

The outer container, when a part or tab becomes visible, then calls PrimeFaces.invokeDeferredRenders

**Comment by jxmai** [comment]
> What is strange though is I am trying this with PrimeFaces without Extensions and the Deferred Widgets seem to be working even though it should have the exact same problem?

Not really, Primefaces widgets also face the same problem. If you try the `p:textEditor` component.

Debug mode:

Page load:

![image](https://user-images.githubusercontent.com/10467831/39736861-df18d11c-5247-11e8-9f48-eca8ba9c3981.png)


step into  renderDeferred. Expecting `this.jq.visible` is true, but the result is false.


![image](https://user-images.githubusercontent.com/10467831/39737047-b1438100-5248-11e8-8829-a7d8c9c26133.png)

No UI hidden container, skipping the if block, so p:textEditor cannot be rendered on page load

![image](https://user-images.githubusercontent.com/10467831/39737177-5e913f14-5249-11e8-86ca-976a1168015a.png)


![image](https://user-images.githubusercontent.com/10467831/39737199-7bde9486-5249-11e8-8a94-00af260d7d7e.png)

The whole logic is pretty much the same as melloware's description, but I just clarify that not only primefaces extensions widget are under affected, but also primefaces widgets.

**Comment by melloware** [comment]
Thanks for verifying!!!   The next thing I think we should try is adding the functions{()} wrapper around the whole MOVE_SCRIPTS_TO_BOTTOM.   My only thought was that was how PF worked in 6.1 and those components were "visible" at that time and thus DeferredWidgets always worked.

**Comment by jxmai** [comment]
@melloware  I guess you just fixed this issue :) ? https://github.com/primefaces-extensions/core/commit/0a0ac35aa4cbfec286cc61c7210a26f24dfc6883

**Comment by melloware** [comment]
Well I fixed it but I don't think it is the right fix.  I had to add document.ready() wrappers around our init() calls which doesn't feel like the right fix.  I still there there is something fundamental about the different in PF from Jquery 2 to Jquery 3 that I don't quite understand.

**Comment by melloware** [comment]
Fixed with commit: https://github.com/primefaces-extensions/core/commit/d0963360bff6380b1e40fc60714f9445877caec6
