### ISSUE TITLE
Invalid URL: clicking maven central link directs to a 404 page

### ISSUE THREAD

**Issue by jxmai** [primefaces-extensions/primefaces-extensions.github.com#570]
![snapshot1](https://user-images.githubusercontent.com/10467831/40208333-c013616a-59fe-11e8-865b-48cd3218fc22.png)

will direct to https://repo.maven.apache.org/maven2/org/primefaces/primefaces-extensions/

and results in

![snapshot1](https://user-images.githubusercontent.com/10467831/40208345-d616823a-59fe-11e8-8c4f-69800290d81a.png)

**Comment by melloware** [comment]
You are right I just updated the URL to the correct place!
