### ISSUE TITLE
Sheet: implement several "styleClass" attributes

### ISSUE THREAD

**Issue by fheldt** [primefaces-extensions/primefaces-extensions.github.com#573]
There are several CSS class options in the underlying handsontable component, which should be trivial to implement as attributes, eg:

activeHeaderClassNameString
commentedCellClassNameString
currentColClassNameString
currentHeaderClassNameString
currentRowClassNameString
invalidCellClassNameString
noWordWrapClassNameString
placeholderCellClassNameString
readOnlyCellClassNameString

**Comment by melloware** [comment]
Let me add these atttributes.  These are good suggestions.

**Comment by melloware** [comment]
Added these new attributes on the sheet with commit:  https://github.com/primefaces-extensions/core/commit/2b70412f854330e5c131188a1851f522d3374ec9

I used the property name "StyleClass" to be more in line with other PF components.

        activeHeaderStyleClass
        commentedCellStyleClass
        currentColStyleClass
        currentHeaderStyleClass
        currentRowStyleClass
        invalidCellStyleClass
        noWordWrapStyleClass
        placeholderCellStyleClass
        readOnlyCellStyleClass
