### ISSUE TITLE
New Component: Country Selector

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions.github.com#578]
I like to write the ideas down here when I find things that may be useful as JSF components.

https://masbaehr.github.io/nicecountryinput/

**Comment by tandraschko** [comment]
isn't it just a selectOneMenu, custom layout, with countries as content?

**Comment by melloware** [comment]
Yeah you are probably right it just looks slick with the flags and also has the Contintent selector.  It could definitely all be created with a Select One menu and having the data and flags etc.
