### ISSUE TITLE
primefaces-extensions-6.2.5 Can't Match resources-codemirror-6.1.1

### ISSUE THREAD

**Issue by goodZhaoliu** [primefaces-extensions/primefaces-extensions.github.com#579]
When I Update primefaces-extensions Version To V6.2.5,Then resources-codemirror Show Error！！

**Comment by melloware** [comment]
You no longer need to include the code mirror 6.1.1 it is now part of the PFE 6.2 core library. Simply remove that 6.11 and everything should start working.

**Comment by goodZhaoliu** [comment]
Thanks For your attention，but now the codeMirror Show like areatext，it lose codeMirror future。

**Comment by goodZhaoliu** [comment]
Thanks For your attention,but now the codeMirror Show like areatext,it has lost codeMirror features.

**Comment by melloware** [comment]
Ahh yes it looks like the showcase is broken too.  Are you using it inside a pe:layout or p:layout?

https://www.primefaces.org/showcase-ext/sections/codeMirror/codeCompletion.jsf

It seems if its used inside a deferred component it is broken

**Comment by melloware** [comment]
OK turns out its the same issue as:  https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/536

Fixed with commit:  https://github.com/primefaces-extensions/core/commit/0a0ac35aa4cbfec286cc61c7210a26f24dfc6883

**Comment by melloware** [comment]
OK PF 6.2.6 is in Maven Central now with this fix!
