### ISSUE TITLE
CKEditor New Line in Custom Toolbar

### ISSUE THREAD

**Issue by glaydsongmv** [primefaces-extensions/primefaces-extensions.github.com#580]
Hi,

Its possible to add a new line to a custom toolbar? In the showcase just appear a separator ('-') and i don't find anyway to do this. In the site https://ckeditor.com/latest/samples/toolbarconfigurator/ can configura that way.

Thanks.

**Comment by melloware** [comment]
Did you try the ('/') instead of ('-')???  Looks like from their configuration a '/' is the new line and '-' is just the line separator.

**Comment by glaydsongmv** [comment]
I tried but don't work.

**Comment by melloware** [comment]
Its possible it might be a new feature of CKEDitor.  Adding @jxmai for his insight.

**Comment by melloware** [comment]
I figured it out.  Doing this creates the row separator.
```xml
toolbar="[['Cut','Copy','Paste','PasteText','PasteFromWord','-', 'SpellChecker'], '/', ['Undo', 'Redo']]"
```


![image](https://user-images.githubusercontent.com/4399574/41857967-afd77544-7866-11e8-80b9-f512cf4e4f73.png)

**Comment by jxmai** [comment]
Thanks melloware for inviting me 👍 

@glaydsongmv  For your info, please also take a look at https://ckeditor.com/latest/samples/toolbarconfigurator/index.html#basic where you can customize the toolbar and output the configuration.

![image](https://user-images.githubusercontent.com/10467831/41889946-d785dca4-78d2-11e8-85f3-321240586152.png)

**Comment by jxmai** [comment]
and here is the old toolbar documentation if you interested : https://ckeditor.com/latest/samples/old/toolbar/toolbar.html

**Comment by glaydsongmv** [comment]
Thanks a lot for the informations. I was confused about inserting a new line because needed to close bracket (has two in the configuration line), I was inserting as a line separator (-). Its interesting to add this example to the showcase.
