### ISSUE TITLE
Sheet: additional "native" validator attribute

### ISSUE THREAD

**Issue by fheldt** [primefaces-extensions/primefaces-extensions.github.com#581]
The sheetcolumn component already has a validator attribute, which works as a classic JSF validator (call to a method in the backing bean).

The underlying handsontable has a column option with the same name "validator" (https://docs.handsontable.com/4.0.0/Options.html#validator) which can be either a function, RegEx or predefined string. All of them are very useful in validating the input in a cell.

Also with these validators in place you can call the method "validateAll()" and it will check the whole sheet and mark invalid values, which is extremely handy when importing values through the backing bean (from eg an excel sheet). The JSF validator will not be called by this method!

So it would be a nice extension to get the full potential of the underlying handsontable. Although I have to admit that I've no idea on whats the best way how to implement this.

**Comment by melloware** [comment]
very cool.  Just need to figure out a clever way to try and implement it.

**Comment by melloware** [comment]
Fixed with commit: https://github.com/primefaces-extensions/core/commit/9c58261c918215f1038dcb3a35d7cf819de2f250

New attribute on the sheetcolumn like "onvalidate=".
```javascript
var myRegex = /^\d+$/; // regex only digits

// function must return callback(bool)
function validateEquals6(value, callback) {
    if (value != 6) {
        callback(false);
    } else {
        callback(true);
    }
}
```

```xml
    <pe:sheetcolumn headerText="Regex" value="#{row.value2}" onvalidate="myRegex"\>
    <pe:sheetcolumn headerText="JS Exactly 6" value="#{row.value3}" onvalidate="validateEquals6"\>
```

You can use a RegEx, Function, or one of the default validators.  I have it set where HandsonTable won't let you leave the CellEditor until the validator passes.
