### ISSUE TITLE
DynaForm: Nested DynaForms will lose data

### ISSUE THREAD

**Issue by stefan-ziel** [primefaces-extensions/primefaces-extensions.github.com#585]
Building nested dynaforms like this

```xml
<pe:dynaForm id="A" ...>
  <pe:dynaFormControl id="B" type="container" ...>
      <pe:dynaForm id="C"...>
        <pe:dynaFormControl id="D" type="hinput" ... >
          <p:inputText id="E" ...
```
if there is data so that two instances of "B" will be rendered and subsequently two instances of "C" data of "E" in the first instance is lost because AbstractDynamicData dose not consider it self nested within an iterator. It is easy to fix it like this 
```java
	protected Boolean isNestedWithinIterator() {
		if (isNested == null) {
			UIComponent parent = this;
			while (null != (parent = parent.getParent())) {
				if (parent instanceof javax.faces.component.UIData	|| 
						parent.getClass().getName().endsWith("UIRepeat") || 
						parent instanceof UITabPanel && ((UITabPanel) parent).isRepeating() || 
						parent instanceof AbstractDynamicData) {
					isNested = Boolean.TRUE;
					break;
				}
			}
```

**Comment by tandraschko** [comment]
Thats the same problem as why we probably introduced p:repeat.
Mojarra UIRepeat has a code snippet to check if it's nested inside another UIRepeat/Data. Therefore we had to fork it.
MyFaces UIRepeat doesn't require such a check.

We should probably check why this is required in our code and have a look at the MyFaces implenentation.

**Comment by Rapster** [comment]
@tandraschko I added this check 'cause I had a dynaForm contained in `ui:repeat` and only the values from the last dynaForm was kept after submission (FYI, `p:repeat` did not solve that problem at that time). However, I agree those checks are quite redundant... and should be handled by `ui:repeat`/`p:repeat`. `p:datatable` (just like `javax.faces.UIData`) contains the same logic

@melloware The PR looks good to me, but give me some time to make sure of it

**Comment by melloware** [comment]
@Rapster I can make the above fix if you feel its good to go?

**Comment by Rapster** [comment]
@melloware yes you can do the above fix, thank you :wink:

**Comment by melloware** [comment]
Fixed with commit: https://github.com/primefaces-extensions/core/commit/ce1c5edfa3b8a62455cfbad9653ae9e539edacbc

**Comment by stefan-ziel** [comment]
Thanks :)
