### ISSUE TITLE
Waypoint showcase - infinite scrolling is broken

### ISSUE THREAD

**Issue by jxmai** [primefaces-extensions/primefaces-extensions.github.com#593]
https://www.primefaces.org/showcase-ext/sections/waypoint/examples/infiniteScrollingTwo.jsf

![image](https://user-images.githubusercontent.com/10467831/42969819-0e8c3728-8b6d-11e8-8abf-679edd3beef9.png)

**Comment by melloware** [comment]
I will investigate.  I wonder if it is an issue with Flickr.

**Comment by jxmai** [comment]
Most likely causing by jquery 3 since we can notice `indexOf is not a function` by looking at the error message. 

https://jquery.com/upgrade-guide/3.0/#breaking-change-load-unload-and-error-removed


> link Breaking change: .load(), .unload(), and .error() removed
These methods are shortcuts for event operations, but had several API limitations. The event .load() method conflicted with the ajax .load() method. The .error() method could not be used with window.onerror because of the way the DOM method is defined. If you need to attach events by these names, use the .on() method, e.g. change $("img").load(fn) to $("img").on("load", fn).

Here is a block of code where error popped up

```js
 reached : function(dir, way) {
        var behavior = this.cfg.behaviors ? this.cfg.behaviors["reached"] : null;
        if (behavior) {
            var options = {
                params : [ {
                    name : this.id + '_direction',
                    value : dir
                }, {
                    name : this.id + '_waypointId',
                    value : $(way).attr('id')
                } ],
                direction : dir,
                waypoint : way
            };

            behavior.call(this, options);
        }
    }

...
pf.cw("ExtWaypoint","widget_waypoint",{id:"waypoint",target:"@(img[data-src])",continuous:true,enabled:true,horizontal:false,triggerOnce:false,offset:'100%',behaviors:{reached:function(ext,event) {PrimeFacesExt.behavior.Javascript({source:'waypoint',event:'reached',execute:function(source,event,params,ext){handleWaypoint(ext);}},ext);}}});
```

**Comment by melloware** [comment]
Fixed with commit: https://github.com/primefaces-extensions/showcase/commit/ca5d08aff4185cf20055e839559b9b8331db6745
