### ISSUE TITLE
Sheet : empty message appear two times

### ISSUE THREAD

**Issue by awenger63** [primefaces-extensions/primefaces-extensions.github.com#595]
pe:sheet on version 6.2.7

When there no data, empty message appera 2 time like this 
![image](https://user-images.githubusercontent.com/16153617/43006444-03f66760-8c36-11e8-8b33-afb4d8daa4bb.png)
I see also there no border right of the "empty cell" on the left top when sheet is empty or not. Perhaps it exist a link whit the two empty message ?

**Comment by melloware** [comment]
Thanks for reporting! Fixed with commit: https://github.com/primefaces-extensions/core/commit/0dd92f953366d3640474ca16b76960e453241990

**Comment by awenger63** [comment]
@melloware , I have install new version 6.2.8 but no change ? I always have 2 empty message when form load without data.

**Comment by melloware** [comment]
Hmmm can you post your pe:sheet settings here.  I had reproduce your issue and fixed it so I thought?

**Comment by awenger63** [comment]
There is 
`<pe:sheet id="listSheet" var="list" value="#{web.listCurrentSheet}" height="400" style="height:100%!important;"
                                  rowKey="#{listSheet.num}" emptyMessage="#{web['web.listEmptySheet']}"
                                  widgetVar="listSheet">`
Tell me if you need more

**Comment by melloware** [comment]
Hmm I can't seem to reproduce.  I just put your settings in the showcase Basic example and here is the screenshot..

```xml
<pe:sheet id="sheet" widgetVar="sheetWidget" 
    value="#{sheetController.assets}" var="row" 
    height="400" rowKey="#{row.assetId}"  
    style="height:100%!important;" 
   emptyMessage="Testing empty sheet message!" 
    filteredValue="#{sheetController.filteredAssets}"
    sortBy="#{row.assetId}" sortOrder="ascending" >
```

![image](https://user-images.githubusercontent.com/4399574/44030448-cf193f8a-9ece-11e8-9422-408334488002.png)

**Comment by awenger63** [comment]
@melloware 
Sorry, I think update on new version is not complet, I clear all my project and reinstall new versions PF 6.2 (previous 6.1.15) and PFExtension 6.2.8 => same as your show case.
Now I see a change (one empty message) but correction it's not complet I have a new error on the navigator console 
`Widget for var 'listSheet' not available! core.js:1:3294
TypeError: PF(...) is undefined[En savoir plus] WebFrom.xhtml:1:1
` 
And the cell for empty message don't have the same widht of the sheet (Last column is not include). I suppose this is the result of the widget var error ?

To be sure this error it's not from my code, I delete all JS use to add sheet contextMenu. I don't have any code with PF('')

Thanks a lot for your help

**Comment by melloware** [comment]
Sounds like you are in JS loading hell?  Are you using MOVE_SCRIPTS_TO_BOTTOM or something else?  

The best bet would be to try and reproduce the issue by using the Primefaces Test: https://github.com/primefaces/primefaces-test

Without a test case its hard for me to reproduce.

**Comment by awenger63** [comment]
I don't know what is MOVE_SCRIPT_TO_BOTTOM ? What do you mean ?
For test case I will looking for to do one ....

**Comment by melloware** [comment]
ok if you don't know what it is then you are not using it.

**Comment by awenger63** [comment]
What it sure, I cannot use my previous version 6.1.15 I have one more console error on sheet script
`TypeError: e.hasBehavior is not a function[En savoir plus] sheet.source.js:64469:14
	_render sheet.source.js:64469:14
	renderDeferred http://localhost:8080/WebForm/javax.faces.resource/core.js:5:1349
	init http://localhost:8080/WebForm/javax.faces.resource/sheet/sheet.js:1457:1
	Class.extend/e[d]</< http://localhost:8080/WebFrom/javax.faces.resource/core.js:5:333
	c http://localhost:8080/WebForm/javax.faces.resource/core.js:5:427
	createWidget http://localhost:8080/WebForm/javax.faces.resource/core.js:1:5003
	cw http://localhost:8080/WebForm/javax.faces.resource/core.js:1:4819
	<anonyme> http://localhost:8080/WebForm/WebCopyright.xhtml:382:14
	i http://localhost:8080/WebForm/javax.faces.resource/jquery/jquery.js:2:27146
	fireWith http://localhost:8080/WebFrom/javax.faces.resource/jquery/jquery.js:2:27914
	ready http://localhost:8080/WebForm/javax.faces.resource/jquery/jquery.js:2:29705
	J http://localhost:8080/WebForm/javax.faces.resource/jquery/jquery.js:2:29890
`
Whith PF 6.2 this error not exist. I don't know if this can help to search ?

**Comment by melloware** [comment]
From what I can tell of your errors above you still had PrimFaces 6.1.15 somewhere in your classpath that was conflicting with PF 6.2.

**Comment by awenger63** [comment]
Yes I look at this type of conflict but cannot find something. What it's seem that came from PF6.2 and when I search information to reproduce exactly the error for a test case, I find that the error not appear at each time ! For example, if I make network trace on the navigator console, the error can disapear. It's an issue on sequential and delay process ! Whith network trace, duration of process are different and error PF('') not appear
perhaps I will try with an other newer version of PF ? But before I see with PF support team.

For current issue, What i would say 

> the cell for empty message don't have the same widht of the sheet (Last column is not include)

It is what you can see on this screenshot 
![image](https://user-images.githubusercontent.com/16153617/44154641-7b742866-a0ab-11e8-9c29-d422c28e808d.png)
Now, only one message but not on the total width of the sheet.

**Comment by melloware** [comment]
Do a View Source on your HTML page and do then a Find for "core.js".

It should look like this and ONLY one should be found. IF you see version 6.1.15 or more than one core.js then you know you have some conflict.

`<script type="text/javascript" src="/showcase/javax.faces.resource/core.js.xhtml?ln=primefaces&amp;v=6.2">`

**Comment by melloware** [comment]
I will need your exact test cases to reproduce.  I am having trouble following all your different trial and error use cases.  If you can provide a working sample using the Primefaces Test project that would be great!

**Comment by awenger63** [comment]
Hi, Perhaps I found a solution for resolve this error

> `Widget for var 'listSheet' not available!`

I have these lines on my web.xml
`<servlet-name>Faces Servlet</servlet-name>`
`<servlet-class>javax.faces.webapp.FacesServlet</servlet-class>`
`<load-on-startup>1</load-on-startup>`
When I replace 1 by 0 on load-on-startup error seem's to disapear. I cannot reproduce it on a priemfaces-test when added this line .... By default on primefaces-test web.xml there is no load-on-startup !
Hope this really resolve this problem, and can help someone in the futur.

Than, @melloware, about this issue, it stay the size of the cell empty message, see screenshot => the last colonne is missing. You can reproduce it on primefaces-test, just with a pe:sheet without data.

`<pe:sheet id="listCars" var="listCars" value="#{testView.listCars}" height="400" style="height:100%!important;" 
                      rowKey="#{listCars.id}" emptyMessage="No row find" 
                      widgetVar="listSheet">
                    <pe:sheetcolumn headerText="Brand" value="#{listCars.brand}" colWidth="100" />
                    <pe:sheetcolumn headerText="Year" value="#{listCars.year}" readonly="true" colWidth="200" />
                    <pe:sheetcolumn headerText="Color" value="#{listCars.color}" colWidth="100" />
            </pe:sheet>`

`private List<Car> listCars;
@PostConstruct
public void init() {
        testString = "Welcome to PrimeFaces!!!";
        listCars = new ArrayList<>();
    }`

**Comment by melloware** [comment]
OK let me re-open this ticket and try and reproduce.

**Comment by melloware** [comment]
Fixed with commit: https://github.com/primefaces-extensions/core/commit/9e305414409326bcac943831abada3cf77d98b29

**Test project:**
[primefaces-sheet.zip](https://github.com/primefaces-extensions/primefaces-extensions.github.com/files/2314223/primefaces-sheet.zip)

**Comment by awenger63** [comment]
Work fine since migration PF 6.2.x and PFE 6.2.9 ! thanks
