### ISSUE TITLE
Sheet : height property cannot be empty

### ISSUE THREAD

**Issue by awenger63** [primefaces-extensions/primefaces-extensions.github.com#597]
Version 6.2.7
it's not possible to have height property empty or not present on pe:sheet : 
Than there no simply way to have a height reponsive like 100% ... of the inner content.
Is it possible to put nothing and work like is it explain on this article : https://handsontable.com/blog/articles/a-complete-guide-to-changing-size-of-handsontable ?
Thanks.

**Comment by melloware** [comment]
Fixed with commit: https://github.com/primefaces-extensions/core/commit/71461c35aab7e861a78c8d3d114e8ebe3a0aebb0

Now you can simply omit the height="200" property entirely and it will make the height="100%".  What you can't do is height="" since that will get a number conversion error.

**Comment by awenger63** [comment]
@melloware , I look in your Fixed you put "height:100%" if is empty on pe:sheet, but in handsontable blog it's say that they are no settings to work.
I don't have a lot experience with handsontable today, but my understand is : It work for the width (no value) but not for height, and in the code width it's before height and there nothing in style if the two value are empty.
You don't think it will be better to change only the test to put a empty value if there is nothing ? something like this
`if (style.length() > 0) {
             responseWriter.writeAttribute("style", style, null);
} else {
             responseWriter.writeAttribute("style", "", null);
}`
Thanks for your time.

**Comment by melloware** [comment]
OK here is what I tried.

1. Having no style property at all.
2. Trying your suggestion of style=""
3. Added something in there like style="overflow:hidden"

All three resulted in the same thing which is the screenshot here:
![image](https://user-images.githubusercontent.com/4399574/43136495-efd33928-8f16-11e8-9efd-f38a0bbab7f4.png)

If I revert back to my original fix using height:100% the whole sheet renders the screenshot looks like below:
![image](https://user-images.githubusercontent.com/4399574/43136586-3d8c452e-8f17-11e8-8c30-fb1565d17509.png)

**Comment by awenger63** [comment]
Thanks for your tests, I can't actually do it. I trust you made the best solution.
It's alway difficult with datascroll to have 100% of the "bottom part" of the page ... Sometime I have use p:layout with header, central and bottom part, but cagataycivici said it will be depreciate ...

**Comment by melloware** [comment]
You can always switch to pe:layout which we will continue to support.  Its based on the same Jquery Library as PF component.  https://www.primefaces.org/showcase-ext/views/layout.jsf

**Comment by awenger63** [comment]
Hi @melloware.
I test it all this morning, it work, but it not really do the job.
First : when there is no heigth porperty on pe:sheet, the empty message is not visible (present on html tree, but not visible)
Second : what I would like to have when height is empty, it's like the artcile I linked on my first post.
See directly the result [here](https://jsfiddle.net/handsoncode/r1o77f6b/?utm_source=website&utm_medium=embed&utm_campaign=r1o77f6b) and [here](https://jsfiddle.net/handsoncode/fapgeug0/?utm_source=website&utm_medium=embed&utm_campaign=fapgeug0) 
Than all space in div "exemple1" is use and table seem's responsive on this part !
How I can do that ?

Whith pe:sheet, I cannot make a difference between the height and the width of the Component/container and of the Table and his content.  
On the exemple you have 
`<div id="exemple1"` _whith is personnal dimension or not for all space_
`      <div id = "ht_xxx ......`
but with pe:sheet component you have
`<div id="pesheet"`
`    <div id="pesheet_tbl"`    _this is should be same at exemple1 but automaticly created_
`       <div id ="ht_xxx   ....`
pe:sheet height property cannot have two value !
I try to add a new div  to content pe:sheet or with css but without result.
I hope you understand the problem. 
What is the solution with pe:sheet ?
Thanks

**Comment by melloware** [comment]
I think I see what you are saying.  Why not just use CSS?

So if I go to the showcase here: https://www.primefaces.org/showcase-ext/sections/sheet/basicUsage.jsf

Two DIVS get created.

1.<div id="sheet" name="sheet" class="ui-handsontable ui-widget"></div>

2. <div id="sheet_tbl" name="sheet_tbl" class="handsontable-inner handsontable htRowHeaders htColumnHeaders" style="height: 400px; overflow: hidden;" data-initialstyle="height: 400px;" data-originalstyle="height: 400px; overflow: hidden;">

Why not just use CSS and style the "outer" DIV using its ID like...

```
#sheet {
  height: 100px;
}
```

**Comment by awenger63** [comment]
(FYI : in show case when form load, vertical scroll is not here in Chrome and FireFox. it appear when scrolling)

> Why not just use CSS and style the "outer" DIV using its ID like...

I would try, but I don't arrived. I want use 100% af the heigth, not a fixed value !
See these screen example of the need, is it more visual !
![example of need](https://user-images.githubusercontent.com/16153617/45220341-1ddee280-b2ae-11e8-809f-3729d0aaddd7.png)

**Comment by melloware** [comment]
> I would try, but I don't arrived. I want use 100% af the heigth, not a fixed value !

OK if you want 100% height why not this on the outer DIV?

```
#sheet {
  height: 100%;
}
```
