### ISSUE TITLE
Sheet : change event for checkbox/dropdown cells

### ISSUE THREAD

**Issue by awenger63** [primefaces-extensions/primefaces-extensions.github.com#599]
version 6.2.7
 Ajax 'change' event is call when the cell lost focus.
 But when it'is on a colType="checkbox" (and also "dropdown"  = no validation phase need)  the "change" event could be occur when the click is done.

Test it on the show case :
 - click one time on a checkbox => your check box change but no update message
 - click a second time on the same checkbox => your check box change, the update message appear one row update, and your check box change another time 

 Another test , same show case to update few checkbox one by one :
 - click one checkbox => your check box change but no update message
 - click another check box => your new check box change, the update message appear one row update (it is the last check box = good)
 - click another check box => your new check box change, the update message appear No row update (the previous change it's do
 - click another .... 
 ==> only the first checkchange is done

**Comment by melloware** [comment]
Fixed with commit: https://github.com/primefaces-extensions/core/commit/29294b0b00b8b3482ddcecbe3906b79e4089b3a9

Please test it fixes DropDown and Checkbox cell types to fire the change event immediately.

**Comment by melloware** [comment]
@awenger63 Did you get a change to test this in 6.2.8?

**Comment by awenger63** [comment]
@melloware I will make a final test when I arrive to stabilized my application with new version 6.2.8 with PF 6.2  ....
Today I cannot use 6.2.8 pe:sheet cannot work

**Comment by melloware** [comment]
I am using PF 6.2 + PFE 6.2.8 in production right now.  I think you are having some sort of JAR conflicts in your classpath.

**Comment by awenger63** [comment]
@melloware 
I fork the application to be able for use differents PF version. So I can work on pe:sheet PFE 6.2.8.
Know it seem's to work.
Thanks
