### ISSUE TITLE
Sheet : record count and empty message are not updated when line remove

### ISSUE THREAD

**Issue by awenger63** [primefaces-extensions/primefaces-extensions.github.com#604]
Version 6.2.8
Test on show case
When a line is remove, bottom line counter is not update.
When all line are remove, empty message is not visible

**Comment by melloware** [comment]
Do you mean with right click on the Context Menu on the Dynamic Columns example?

That is only Javascript and doesn't effect the backend component at all.  You would have to use a p:remoteCommand to update the backing bean and table.  That is not core sheet functionality that is just a demo of how to use the context menu.

**Comment by awenger63** [comment]
ok, sometime pe:sheet must be updated, sometime not ! 
in this case, I add on backend "getCurrentInstance().update()" when list is empty after remove data than empty message appear. Hope this can help another dev.

**Comment by melloware** [comment]
thanks for updating!
