### ISSUE TITLE
DocumentViewer: load document without updating the viewer

### ISSUE THREAD

**Issue by KarlKnapp** [primefaces-extensions/primefaces-extensions.github.com#605]
When opening a new document the complete viewer is re-initialized which becomes annoying if the rest of the page stays static. 

https://stackoverflow.com/questions/51822573/load-content-in-primefaces-extensions-documentviewer

Demo Application:
https://github.com/KarlKnapp/ViewerTest

**Comment by melloware** [comment]
I will see if there is anything clever I can do to swap out the document.

**Comment by melloware** [comment]
I am going to say it does not look like it is possible with the way the PDF Viewer JS works in conjunction with how the Component is designed.   Closing for now.  If someone ever figures out a way i would gladly accept a PR.

**Comment by KarlKnapp** [comment]
using:

```
function refresh() {
     document.getElementById('viewerForm:viewer').contentDocument.location.reload();
}
<p:commandButton value="Load document" ... oncomplete="refresh()" />
```

instead of 

```
<p:commandButton` value="Load document" ...  update="viewerForm:viewer" />
```

works for me.

**Comment by melloware** [comment]
Nice work @KarlKnapp !
