### ISSUE TITLE
New Component: Static Message

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions.github.com#608]
Original PF Issue: https://github.com/primefaces/primefaces/issues/3981

**Comment by tandraschko** [comment]
Nope but here is the source from my company:
https://gist.github.com/tandraschko/2fc779f7f95cf49a1a14097f1ec09904
https://gist.github.com/tandraschko/dc89a451fe2a63bca67d36fbb2b39564

**Comment by Rapster** [comment]
By the description, it sounds something like this: https://introjs.com/ no?

**Comment by tandraschko** [comment]
no idea
it's just a way to render a p:message without the usage of fc.addMessage.

**Comment by Rapster** [comment]
IMO, I would have simply add an attribute to `<p:messages />`

**Comment by tandraschko** [comment]
as i said, my change was reverted some years ago ;)

**Comment by melloware** [comment]
Yeah if it was rejected by the PF Team then we need to add it to PFE.  The fact that Thomas and the original writer of the ticket both had this requirement means there is a need for this component.

**Comment by Rapster** [comment]
There is a need that's for sure, I needed that feature as well. But I would wait an answer from PrimeTek to see if we could simply add an attribute to `<p:messages />`

**Comment by melloware** [comment]
OK who is going to ask PrimeTek?

**Comment by Rapster** [comment]
> as i said, my change was reverted some years ago ;) Therefor i want ask again to implement it.

Thomas I guess :smile:

**Comment by melloware** [comment]
@tandraschko any word on this component?

**Comment by tandraschko** [comment]
https://github.com/primefaces/primefaces/issues/4258
