### ISSUE TITLE
DocumentViewer and browser cache

### ISSUE THREAD

**Issue by francescociani** [primefaces-extensions/primefaces-extensions.github.com#609]
We had some incosistent behaviour on DocumentViewer component after upgrading from 6.2.6 to 6.2.8 and we finally realized that the problem was caused by the browser caching old resource.

We believe the problem is due to the fact that the URL cretated to retrieve the resources specifies only major.minor version and not the patch version, in our case 6.2 and not 6.2.8.

See generated URL (with reference to ln=primefaces-extensions&v=6.2 ) 

https://mydomain.com/webtng/javax.faces.resource/documentviewer/pdfviewer.html.jsf?ln=primefaces-extensions&v=6.2&file=%2Fwebtng%2Fjavax.faces.resource%2Fdynamiccontent.properties.jsf%3Fln%3Dprimefaces%26v%3D6.2.6%26pfdrid%3D9d913b9fd9725cd4df0fd2989ff30b32%26pfdrt%3Dsc%26streamedContentIdentifier%3D4c4ff1ac-7c6a-47c0-95c6-4286d540bafa%26pfdrid_c%3Dfalse%26uid%3Da42dabdc-f33d-41ac-82e3-bb4862afd81b%26download%3Dnull#locale=en-US

As you can see primefaces standard component resources are loaded using full version, 6.2.6

**Comment by melloware** [comment]
Fixed with commit: https://github.com/primefaces-extensions/core/commit/15dcdbbdebfdef74790ed48b816c251ca7032a5c
