### ISSUE TITLE
BlockUI: Not respecting CSSOverlay property

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions.github.com#613]
Introduced when BlockUI jquery plugin was updated it was not respecting the CSS overlay property.

**Comment by melloware** [comment]
Fixed with commit: https://github.com/primefaces-extensions/core/commit/1d760dfcc84cca1ac31525be3fcd5163697c3ddd

**Comment by Rapster** [comment]
What's the difference with blockUI from PF?
