### ISSUE TITLE
ImageRotateAndResize: Rotation issue using 80 degrees

### ISSUE THREAD

**Issue by Keegans69** [primefaces-extensions/primefaces-extensions.github.com#615]
Hello,

I am a novice at primefaces. I recently used image rotation methods and I have a problem. The "rotateLeft" and "rotateRight" methods work correctly only when the angle is 90. By changing the angle, the image rotates, but its center moves by several pixels.

```xml
<p:commandButton icon="ui-icon-arrowreturnthick-1-w" value="Rotate Left"  
             onclick="PF('rotateAndResizeWidget').rotateLeft(80);return false;"/>  // doesnt work
<p:commandButton icon="ui-icon-arrowreturnthick-1-e" value="Rotate Right"  
             onclick="PF('rotateAndResizeWidget').rotateRight(90);return false;"/>  // work fine
```

Thanks for your help

**Comment by melloware** [comment]
Let me investigate whether its a problem with our code or the underlying Jquery plugin. I will let you know what I find out!

**Comment by melloware** [comment]
OK so this code is 100% PFE code and no jquery plugin.  The original author is currently on vacation and will be back next week.

However I am using the Showcase and I set my to 80 degrees and it looks like its rotates it correctly.  I can't really see or tell if its shifting any pixels or not?  It does not appear to be with the naked eye.  How are you determining it has moved?

**Comment by Keegans69** [comment]
Thank you for you reply
Displacement is visible to the naked eye. Let's say that the rotation point of the image is no longer the same

**Comment by melloware** [comment]
OK I was able to update your example as a runnable test attached here.  Run "mvn clean jetty:run" and navigate to http://localhost:8080/primefaces-test/test.xhtml

[pfe-615.zip](https://github.com/primefaces-extensions/primefaces-extensions.github.com/files/2405318/pfe-615.zip)

**Comment by Keegans69** [comment]
80 degrees works fine for you ?

**Comment by melloware** [comment]
No I took your example and made it a "runnable" sample above.  Just download it and run "mvn clean jetty:run" to run it. its the exact example you sent me just in an easy to run digestible format.   The original developer of this component is on vacation right now.  but yeah it definitely looks like a bug.

**Comment by tandraschko** [comment]
I developed the component only for 90 degrees for a customer.
I dont have time to fix it and its simple canvas manipulation.
Feel free to provide a PR to fix it.

**Comment by melloware** [comment]
@Keegans69 the math is all right here if you want to review it: https://github.com/primefaces-extensions/core/blob/master/src/main/resources/META-INF/resources/primefaces-extensions/imagerotateandresize/imagerotateandresize.js

**Comment by Keegans69** [comment]
Sorry I work for a company I do not have time to make any changes on this item. I will see for another framework. Thanks a lot for your help.

**Comment by melloware** [comment]
Understood . Marking as wontfix close.

**Comment by tandraschko** [comment]
We all work for a company :P
