### ISSUE TITLE
Sheet: Change event not always fired on multi update

### ISSUE THREAD

**Issue by rbetjes** [primefaces-extensions/primefaces-extensions.github.com#622]
The change event is not allways fired when the changes are made via "Autofill.fill".

You can see this in action in the showcase - Basic usage.
If you change the contents of a cell (e.g. one in the date column in the showcase), and before anything else, you drag that cell down to change the cells below to get the same content you changed the first cell to, then the cells will get the new content but the change event is only fired for the original cell.
You can verify that in 2 ways: 
1. the showcase says: 1 rows updated, which should be at least more than one.
2. change the contents of a cell on the same row as one of the supposidly changed cells. The supposidly changed cell (in the date column in my example) will change back to it's original content.

It's a bit hard to explain but I hope this is clear.

**Comment by melloware** [comment]
Yeah its like the "Cell Change" event is firing for your currently editing cell when you drag down and auto fill.  its doing the change event of the unedited cell.

What happens if you...

1. Edit the cell and leave it so the change for that cell fires.

2. Then drag that already committed cell down to autofill?

**Comment by rbetjes** [comment]
Yeah, that works. But as it turns out, that is not how users work.
I can only trigger it in dropdown and date columns because you can dismiss the editor without firing the change for that cell.
Could be related to issue #599 but that's a guess.

**Comment by melloware** [comment]
Yep I just wanted you to verify my assumption, of what was happening.  I will see if I can fix it.

I bet this behavior has always been like this, just no one has reported it.

**Comment by rbetjes** [comment]
Think I found the problem. I'll do some testing and create a PR if it's fixed.

**Comment by melloware** [comment]
You rock. Much appreciated.

**Comment by melloware** [comment]
Fixed with commit: https://github.com/primefaces-extensions/core/commit/ff38c184cc8f3d52f1f70933c6ad710abe059e33

Thanks for the PR!
