### ISSUE TITLE
Sheet Component: could not capture update event after copy, paste, cell editing, and sort and filter not work

### ISSUE THREAD

**Issue by sparkji** [primefaces-extensions/primefaces-extensions.github.com#625]
PrimeFaces: 6.2
PrimeFeaces Extension: 6.2.9
JSF: Mojarra/2.2.18
Server: Wildfly 13 or 14

Copy, paste, add new rows work well.

**Comment by melloware** [comment]
@fheldt @rbetjes @francescociani @eduarddrenth are any of you guys having the problem described above?

**Comment by eduarddrenth** [comment]
not me...

**Comment by eduarddrenth** [comment]
and do not exactly understand the problem the way it is described neither do I recognize it from our experience

**Comment by sparkji** [comment]
Thanks guys. My coworker has solved the problem. I will let you know how he made it when we meet in next week.

**Comment by melloware** [comment]
@sparkji thanks looking forward to the solution.
