### ISSUE TITLE
Tooltip: maxWidth/minWidth attribute

### ISSUE THREAD

**Issue by fheldt** [primefaces-extensions/primefaces-extensions.github.com#627]
It is very runabout to change the max-width of a tooltip, eg to show some longer text lines. A "maxWidth"/"minWidth" attribute would be nice in these cases.

BTW: pe:tooltip has no style attribute (only styleClass).

**Comment by fheldt** [comment]
To illustrate the problem:

`
<h:outputStylesheet>
	.mw500 {
		max-width: 500px;
	}
</h:outputStylesheet>
`

`
<pe:tooltip for="..."	styleClass="qtip qtip-shadow qtip-rounded mw500">
...
</pe:tooltip>
`

To get a wider tooltip, you have to define a CSS style class and attach it to the tooltip, with a style attribute (or a maxWidth attribute) this could be done directly at the tooltip.

**Comment by melloware** [comment]
Fixed with this commit: https://github.com/primefaces-extensions/core/commit/b70e796b1ad475e2559d06ed68369a38d30aa17f

**Comment by fheldt** [comment]
There's a little typo in the commit...

public void setMaxWidth(final String minWidth) {
        getStateHelper().put(PropertyKeys.maxWidth, **minWidth**);
}

**Comment by fheldt** [comment]
Even when I fix the typo it doesn't work. I see no change at all from the default 280px max-width (whereas the CSS styleClass solution does)

**Comment by melloware** [comment]
If you look in the browser View Source this is what is generated.

```javascript
style: {widget:false,classes:'qtip-default','min-width':'0px'}
```

Accoridng to qTip2 docs I should just be able to add style attributes right in that "style" JSON payload.

Although some people suggest you have to use your own class:  https://stackoverflow.com/questions/12672508/qtip-dynamic-width

**Comment by melloware** [comment]
Confirmed.  Qtip2 you must use a style class: http://craigsworks.com/projects/forums/showthread.php?tid=1342   I will revert my changes.

**Comment by melloware** [comment]
Closing for now as the only option is to use a style class like you have been doing.
