### ISSUE TITLE
SheetColumn: No Renderer found for component

### ISSUE THREAD

**Issue by KevinSJ** [primefaces-extensions/primefaces-extensions.github.com#630]
PE 6.2.9

I was seeing these warnings on my projects and tried to running the showcase using MyFaces, it is showing the same warning.

`No Renderer found for component {Component-Path : [Class: javax.faces.component.UIViewRoot,ViewId: /sections/sheet/dynamicColumns.xhtml][Class: javax.faces.component.html.HtmlBody,Id: j_id_5][Class: org.primefaces.extensions.component.layout.Layout,Id: fpl][Class: javax.faces.component.html.HtmlForm,Id: mainForm][Class: org.primefaces.extensions.component.layout.LayoutPane,Id: layoutCenter][Class: javax.faces.component.html.HtmlPanelGroup,Id: j_id_s][Class: org.primefaces.extensions.component.sheet.Sheet,Id: sheet][Class: org.primefaces.extensions.component.sheet.SheetColumn,Id: j_id_x_23_1]} (component-family=org.primefaces.extensions.component, renderer-type=javax.faces.Text) created from: /sections/sheet/example-dynamicColumns.xhtml at line 26 and column 43`

A similar issue to this is #395, and a quick fix is to set the renderer type to null.

**Comment by melloware** [comment]
So I read that thread.   It looks like almost all PF Extensions components have a rendererType in the XML.  Switch does not.  

It looks like all PF components have a renderer too: https://github.com/primefaces/primefaces/blob/master/src/main/resources/META-INF/primefaces-p.taglib.xml

@tandraschko Why does MyFaces throw this warning when it looks like that is the proper way to define a component?

**Comment by melloware** [comment]
Hmm it could be SheetColumn and not Sheet.  SheetColumn has no renderer defined.

```xml
	<tag>
		<description>
			<![CDATA[Data sheet column used to define the available columns in a Sheet component.]]>
		</description>
		<tag-name>sheetcolumn</tag-name>
		<component>
			<component-type>org.primefaces.extensions.component.SheetColumn</component-type>
		</component>
```

**Comment by melloware** [comment]
OK I think I fixed it with this commit: https://github.com/primefaces-extensions/core/commit/c9c3ea5a4e1773238a6e5b7dfd3ad1f354a98217

**Comment by melloware** [comment]
So you did this?

```java
    /**
     * Default constructor
     */
    public SheetColumn() {
        setRendererType(null);
    }
```

**Comment by KevinSJ** [comment]
Yes, that's what I did.

**Comment by melloware** [comment]
OK thanks!  I committed that change.

**Comment by KevinSJ** [comment]
Thank you!

**Comment by melloware** [comment]
Thanks for reporting and helping fix.
