### ISSUE TITLE
SpeedTest: Set dummy.html manually

### ISSUE THREAD

**Issue by ssibitz** [primefaces-extensions/primefaces-extensions.github.com#631]
Is it possible to also set the dummy.html file manually as attribute instead 
of using a fix resource name in speedtest.source.js ?

I will need that because otherwise the component is not working in combination
with the omnifaces resource handler which currenctly redirects all dynamic resources from primefaces and primefaces-ext to a static URL:
e.g.
href="/showcase-ext/javax.faces.resource/theme.css.jsf?ln=primefaces-omega"
will be rendered as:
href="/showcase-ext/javax.faces.resource/primefaces-omega/theme.css.jsf"
Why ? Because then our proxy caching server is able to cache primefaces resources !

So:
Instead of using  (In function singlePing, testUp) :
url: PrimeFacesExt.getFacesResource('speedtest/dummy.html', PrimeFacesExt.RESOURCE_LIBRARY, PrimeFacesExt.VERSION) + '?id=' + start,
can you use:
url: $this.getFileNameDummyHTML() + '?id=' + start,

and a parameter like "dummyfile" in the speedtest component ?

Primefaces-Ext-Version: 6.2.9
Example: Identical as on Showcase, but Omnifaces Resource Handler will redirect anything
like ?ln=primefaces to \primefaces\ ...

**Comment by ssibitz** [comment]
Setting the dummy-file manually to a static URL will fix this issue that i get when you try to 
get the static resource via the function:
PrimeFacesExt.getFacesResource

This function will raise an error because with the omnifaces cdn handler there will never be a 
ln=
in any URL so the script fails on this line:

      // find the library like ln=primefaces
      var libraryRegex = new RegExp('[?&]([^&=]*)**ln**=(.*?)(&|$)');

      // Link will never contain "Ln=" so [2] will never exists:
      // find library to replace e.g. 'ln=primefaces'
      var currentLibraryName = 'ln=' + libraryRegex.exec(scriptURI)[2];

**Comment by ssibitz** [comment]
When i call the function on primefaces-extensions showcase:
**PrimeFacesExt.getFacesResource("speedtest/dummy.html",PrimeFacesExt.RESOURCE_LIBRARY,PrimeFacesExt.VERSION)**
i will get the URL:
**"https://www.primefaces.org/showcase-ext/javax.faces.resource/speedtest/dummy.html.jsf?ln=primefaces-extensions&v=6.2.8"**

But the problem in the getFacesResource - function is that always a **ln=** - tag is required which is not needed because the tag can also be written like : 
"https://www.primefaces.org/showcase-ext/javax.faces.resource/primefaces-extensions/speedtest/dummy.html.jsf?v=6.2.8"

Omnifaces Resource Handler will always render a resource in that way, so you will never get a **ln=** tag in your script so it always will fail.

**Comment by melloware** [comment]
Yes I definitely understand the problem and what OmniFaces is doing.  I am just trying to figure out the correct way to make this work for all components.   The JS will have no idea OmniFaces is being used.

**Comment by ssibitz** [comment]
I think the should be something like that (prototype)

```
   getFacesResource : function(name, library, version) {
      // just get sure - name shoudln't start with a slash
      if (name.indexOf('/') === 0) {
         name = name.substring(1, name.length);
      }
      // find any JS served JSF resource
      var scriptURI = PrimeFacesExt.getResourceScriptURI();
      // Now the general tag can be build by search for the resource-tag and and library, name to it:
      var resourceTAG = "javax.faces.resource/";
      var resourceIndex = scriptURI.indexOf(resourceTAG);
      var resourceURL = scriptURI.substring(0, resourceIndex+resourceTAG.length);
     return resourceURL + library + "/" + name + "?V=" + version;
   },

```

**Comment by ssibitz** [comment]
With my example you will always get a working URL in always the style:
"https://www.primefaces.org/showcase-ext/javax.faces.resource/primefaces-extensions/speedtest/dummy.html.jsf?v=6.2.8"

I do this by always searching for the javax.faces.resource - tag instead the ln-tag.
So i will build first the resource-tag:
https://www.primefaces.org/showcase-ext/javax.faces.resource/
and then add the library and then the name and version number to this string.

**Comment by melloware** [comment]
Can you try it with and without CombinedResourceHandler?  I want to verify if this will work for all scenarios.

**Comment by ssibitz** [comment]
At the moment i can't because we are in release process - so i don't have much time for this test's.

But i will come back with the test's because i have to setup the primefaces-extensions maven-build to get the test's working and that needs a little time ...

**Comment by ssibitz** [comment]
It seems that i currently can't build a complete clean 6.2.9 primefaces-extensions version because 
not all gihub-projects are tagged with the primefaces-extensions-6.2.9 tag:
core: primefaces-extensions-6.2.9
showcase: ????
resources-ckeditor: ????
master-pom: ????
resources-optimizer-maven-plugin: ????

Only the head so the "beta" 6.3 version is checked in but i don't won't to use a beta version in my release build ....

So i can only try the fix within the 6.3 version and the current showcase but i am not be able to test it in my own project because i am using primefaces 6.2.9 and the extensions also in 6.2.9 version ....

**Comment by ssibitz** [comment]
Now the showcase 6.3 is working for the speedtest with this changes in core.js.
I tested the showcase with and without activating the combined resource handler from Omnifaces
and it works perfect.

But the CKEditor is not working right because it seems that the resources he request's are not really a right resource but only plugings without any right names:

getFacesResource("ckeditor/plugins/dialogui/", "primefaces-extensions", "6.3-SNAPSHOT")
=> "ckeditor/plugins/dialogui/" -> This is not a resource, so what should this be ?

```
   getFacesResource : function(name, library, version) {
      // just get sure - name shoudln't start with a slash
      if (name.indexOf('/') === 0) {
         name = name.substring(1, name.length);
      }

      // find any JS served JSF resource
      var scriptURI = PrimeFacesExt.getResourceScriptURI();
      var scriptName = PrimeFacesExt.getResourceScriptName(scriptURI);

      // replace core.js with our custom name
      scriptURI = scriptURI.replace(scriptName, name);
	  
	  // Remove all params from scriptURI to get a normal link:
	  var paramIdx = scriptURI.indexOf("?");
	  if (paramIdx != -1) {
		scriptURI = scriptURI.substring(0,paramIdx);
	  }
	  
	  // Split resource tag into prefix and suffix:
	  var resourceTAG = "javax.faces.resource/";
	  var resourceIdx = scriptURI.indexOf(resourceTAG);
	  var scriptPrefix = scriptURI.substring(0,resourceIdx+resourceTAG.length);
	  var scriptSuffix = scriptURI.substring(resourceIdx+resourceTAG.length);
	  
	  // Now rebuild the resource URL:
	  var resourceURL = scriptPrefix + library + "/" + scriptSuffix;
	  
	  // Optionally add the version number tag:
	  if (version) {
		  resourceURL = resourceURL + "?V=" + version;
	  }
	  return resourceURL;
   },

```

**Comment by melloware** [comment]
Adding @jxmai.  Yes the CKEditor has to do a lot of really strange magic to make all of the plugins work.

**Comment by ssibitz** [comment]
I currently don't have the time to debug the CKEditor what the problem here is because i don't use the editor in my project and i am in release process of our projects.
So i turned off the Omnifaces Resource Handler to make my project work right by now.

With the script i can run the Speedtest Component and the Document Viewer Component sucessfully
but not the CKEditor. Both components are running with Omnifaces CombinedResourceHandler set to on or off.

To Debug i have to implement it in my project and this spends at the moment to much time - 
this is only possible without using it without activating Omnifaces CombinedResourceHandler ...

**Comment by ssibitz** [comment]
I currently fixed the problem by overwrite the speedtest.js - Script from the primefaces-extensions
by using a hardcoded url instead of trying to build it in a wrong way:

Overwriting the url-tag in the e.g. singlePing function:
(Must be replaces in all function which are using the url attribute in combination with the dummy.html

**So instead of using:**
url: PrimeFaces.resources.getFacesResource("speedtest/dummy.html",PrimeFacesExt.RESOURCE_LIBRARY,PrimeFacesExt.VERSION)+"?id\x3d"+c
which results in an error

i am using:
url: 
".../dummy.html" + "?id\x3d" + c

So the solution for the problem when you using ominfaces is that
the url of the dummy.html file must be given by the user.
This could be done very easy by adding an empty empty dummy.html file to the user's project...

**Comment by melloware** [comment]
@ssibitz is it safe to close this ticket?
