### ISSUE TITLE
Sheet: autocomplete more comparisons

### ISSUE THREAD

**Issue by eduarddrenth** [primefaces-extensions/primefaces-extensions.github.com#632]
Right now autocomplete seems to do a "contains", it would be good to offer some more comparisons.

Perhaps I'll contribute some...if I can find the time

**Comment by eduarddrenth** [comment]
Have been looking in the 70000! lines big sheet.source.js, around line 29000 I see a AutocompleteEditor. So far I cannot figure out what to code where....sorry

**Comment by melloware** [comment]
It it helps here is the HandsonTable doc for AutoComplete: https://handsontable.com/docs/6.2.0/demo-autocomplete.html

**Comment by melloware** [comment]
It looks like the only thing you can really set is "strict" mode.  Other than that it looks like its always contains in HandsontTable.

**Comment by eduarddrenth** [comment]
Let's close this one for now? Our users can live with the way it works now.

**Comment by melloware** [comment]
Got it. Closing.
