### ISSUE TITLE
Global: Switch components to "base" pattern

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions.github.com#634]
Switch components to use "Base" pattern like PF to just contain all their properties.

**Comment by melloware** [comment]
Agreed. My only thought was consistency with PF but you are right this is a low priority task.   Maybe only as we touch a component convert it in the future.  I may do Sheet now though as that is a huge component that would actually benefit from the readability of separating out the base methods.

**Comment by tandraschko** [comment]
+1 for consistency
but it's up to you, if you would like to invest to the time, it's not mandatory to do it

**Comment by melloware** [comment]
Closing for now as its not needed and not enough bang for the buck.  If we migrate any components over to PF its easy enough to make that change then.
