### ISSUE TITLE
Sheet: Invisible columns receive focus when using arrows or tab

### ISSUE THREAD

**Issue by eduarddrenth** [primefaces-extensions/primefaces-extensions.github.com#639]
I'm using primefaces sheet extension 6.2.10 and configurably hide columns with the visibility property. The invisible columns receive focus when using arrows or tab, which is confusing for users.

**Comment by eduarddrenth** [comment]
perhaps related to https://github.com/handsontable/handsontable/issues/5673

**Comment by melloware** [comment]
It looks like in 6.2 they added that hiddenColumns property:  https://handsontable.com/docs/6.2.2/demo-hiding-columns.html

**Comment by eduarddrenth** [comment]
Hi, I was aware of the columns still being there..also saw they have a tabindex -1.

hiddenColumns is a pro feature I saw.

**Comment by melloware** [comment]
Ahh I didn't notice it was a PRO issue only.  So do you have a proposed fix?

**Comment by eduarddrenth** [comment]
not yet....I think it may hard to fix, since tabindex is already -1, so I assume handsontable does it's own key handling for navigation and I haven't found a nice hook yet

**Comment by eduarddrenth** [comment]
something to do during holidays....

**Comment by eduarddrenth** [comment]
Perhaps trigger tab key event in onfocus of 'invisible' td, wouldn't be good for left arrow though.

**Comment by melloware** [comment]
Fixed in HandsonTable 8.0.0 which we can't use... See: https://github.com/handsontable/handsontable/issues/5871

**Comment by eduarddrenth** [comment]
That's a pitty... "can't use" as in licensing issues? Or api redesign?

**Comment by melloware** [comment]
License. We are stuck on 6.2.2 it is their last MIT licensed based version.  Everything after that is commercial license only.

**Comment by eduarddrenth** [comment]
ok....what about the future of the sheet extension? For oat.hisgis.nl it is a crucial component. Perhaps we should further discuss this offline.

**Comment by melloware** [comment]
We can chat on the PF Extensions Gitter if you would like? 
https://gitter.im/primefaces-extensions/primefaces-extensions
