### ISSUE TITLE
Sheet: Numeric editing cell not respecting i18n

### ISSUE THREAD

**Issue by alessandro1511** [primefaces-extensions/primefaces-extensions.github.com#641]
If you pass to sheet an european Locale (example "it-IT") using "," as decimal separator, numeric cells are correctly rendered (for example 123,45) but if you edit the value, the editor show "." as decimal separtor and do not allow user to enter "," as decimal separator.

If you use "." as decimal separtor while editing, on save the value is correctly parse and show with ",".

We are using numericPattern="0,0.00"

**Comment by melloware** [comment]
Thank you for reporting I will investigate.

**Comment by melloware** [comment]
So just to be clear you are using the locale in both places right?

Locale on the Sheet
`<pe:sheet locale="de-DE" `

"numericLocale" on the Numeric editor:
```
	<pe:sheetcolumn headerText="Price" value="#{row.purchasePrice}" colWidth="100" 
	                styleClass="htRight #{row.purchasePrice gt 0 ? 'positive' : 'negative'}" 
	                colType="numeric" 
	                numericLocale="de-DE" 
	                numericPattern="$0,0.00"
	                required="true" 
	                requiredMessage="Price is required!">
```

**Comment by alessandro1511** [comment]
I have loaded gitlab primefaces-extensions and editing /showcase/src/main/webapp/sections/sheet/example-basicUsage.xhtml

On the <pe:sheet, attribute locale not used, I have tried but after entering it the result is the same.

**Comment by melloware** [comment]
OK i was able to reproduce it.  It looks like the Handsontable NumericEditor is just a TextEditor.

https://github.com/handsontable/handsontable/blob/master/src/editors/numericEditor.js

The code does nothing, and defefinitely does not respect Locale.  I will have to create a custom Editor and register it for it to work like in this "Custom Editor" example: https://handsontable.com/docs/6.2.2/tutorial-cell-editor.html#page-creating-custom-editor

Or you could try it its all just JS you can inject into the HandsonTable.

**Comment by alessandro1511** [comment]
Thank you for your suggestion, but on primefaces-extensions basicUsage.jsf on numeric colum I can't use "," and (on numeric pad) "."

On handsontable example:
https://handsontable.com/docs/6.2.2/demo-numeric.html?_ga=2.208666770.1884851727.1547824850-1952222121.1547824850
every numeric colums I can use and automatically convert on locale "," and "."

Can you check?

**Comment by alessandro1511** [comment]
Thanks, now it works perfectly.

When do you plan to make the next release?

**Comment by melloware** [comment]
PF 7.0 is coming out in the Next Couple of weeks right now there is a Release Candidate 1.   I will release PFE 7.0 to coincide with the main PrimeFaces release!

**Comment by alessandro1511** [comment]
Thanks!
