### ISSUE TITLE
New component: E.164 phone number

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions.github.com#650]
I would like to see a new component based on https://github.com/jackocnr/intl-tel-input

Do you take pull request for such a component? Is there documentation on requirements for new components?

**Comment by melloware** [comment]
That is pretty slick. Yes we take PR's for new components.  My advice is to model it after a similar component so you get the feel for what is going on.  Once you get it working i am more than happy to review it and help you refine it.

**Comment by melloware** [comment]
Also let me know if you get stuck or need a hand with anything.

**Comment by jepsar** [comment]
I've spend some time getting the JavaScript library to work in a PrimeFaces application, loading resources using JSF, and it is all working nicely in combination with a `p:inputText`. So, the next step would be creating a component :-)

We could create a component with a `for` attribute pointing to a `p:inputText`, or should we create one component which renders the HTML input as well. What do you think?

As a reference, I currently have:
````
<h:outputStylesheet name="css/intlTelInput.min.css"/>
<h:outputScript name="js/intlTelInput.min.js"/>
````
..modified this bit of CSS:
````
.iti-flag {
  height: 15px;
  box-shadow: 0px 0px 1px 0px #888;
  background-image: url("#{resource['img/flags.png']}");
  background-repeat: no-repeat;
  background-color: #DBDBDB;
  background-position: 20px 0; }
  @media (-webkit-min-device-pixel-ratio: 2), (min-resolution: 192dpi) {
    .iti-flag {
      background-image: url("#{resource['img/flags@2x.png']}"); } }
````
..and this XHTML (tag) (with a lot of hard coded stuff):
````
<p:inputText id="#{id}" .../>
<script>
var #{id}TelInput = document.querySelector(PrimeFaces.escapeClientId("#{p:component(id)}"));
var #{id}Tel = intlTelInput(#{id}TelInput, {
    "utilsScript": "#{request.contextPath}/javax.faces.resource/js/intlTelUtils.js.xhtml",
    "nationalMode": false,
    "preferredCountries": ["nl"]
  });
#{id}TelInput.onchange = function(){ #{id}TelInput.value = #{id}Tel.getNumber(); }
#{id}TelInput.addEventListener("countrychange", function(){ #{id}TelInput.value = #{id}Tel.getNumber(); });
</script>
````

**Comment by melloware** [comment]
I think we should make it create and control its own Input on the screen instead of for="".

**Comment by jepsar** [comment]
> I think we should make it create and control its own Input on the screen instead of for="".

Yeah.. seems the be best option. We can probably extend the input text renderer.. I'll create a fork and a branch and put some stuff in there.

**Comment by melloware** [comment]
Maybe look at InputMask and InPutNumber in PF as examples that use JS components to mark up an Input.

**Comment by melloware** [comment]
Can you review this commit: https://github.com/primefaces-extensions/core/commit/18525bf9a0851cdbcc7cbc01a9ea771bc58ae2a1

1. You had duplicate inputStyle and inputStyleClass so I removed one of them.
2. The CSS and JS is now compressing like our other components.
3. I left the utils.js untouched.
4. I did some minor Javadoc cleanup.
5. I ran my formatter settings and verified checkstyle is still passing.
6. Add credit in NOTICE.txt

**Comment by jepsar** [comment]
> 1. You had duplicate inputStyle and inputStyleClass so I removed one of them.

Why? They are two different things (for rendering the `class` and `style` attribute). Input number also has both of them.

I'll check the rest soon, when I have time to do so.

**Comment by jepsar** [comment]
> Why? They are two different things (for rendering the `class` and `style` attribute). Input number also has both of them.

Ah! I applied style and style class on the input? They should have gone on the wrapping span, right?

One small detail I found is https://github.com/primefaces-extensions/core/commit/18525bf9a0851cdbcc7cbc01a9ea771bc58ae2a1#r32496031 everything else is looking good.

**Comment by melloware** [comment]
Yep you had it correct with style on the outer span and inputStyle on the input box.  You just had copied the two descriptions twice in the taglib.  

I just committed fixes for your code review comments as well as added some Widget helper methods to make the component more useful from a JS standpoint.

**Comment by jepsar** [comment]
Hmm.. in that case I think I forgot to remove them earlier when I copied the entire `InputNumer` tag and added them again later when I actually was rendering them. Silly mistake.

**Comment by jepsar** [comment]
Is it up to me to close this issue? It think it can be closed.
