### ISSUE TITLE
Sheet: Dynamic column not working

### ISSUE THREAD

**Issue by muhdkhokhar** [primefaces-extensions/primefaces-extensions.github.com#652]
I have this 

```xml
<c:forEach items="#{row.data}" var="cd" varStatus="status">
                    <pe:sheetcolumn headerText="Reference T"
                                    readOnly="true"
                                    value="#{cd.key}"
                                    colWidth="150" />
</c:forEach>
```

Its not working. row data is Map<String,String>

**Comment by Rapster** [comment]
> Its not working

It's a bit vague don't you think? What is the result of this so far?

**Comment by melloware** [comment]
I don't think you are doing it right.  Please look at my example using Dynamic Columns here: https://www.primefaces.org/showcase-ext/sections/sheet/dynamicColumns.jsf

Study it and you will see the differences between mine and yours.

**Comment by muhdkhokhar** [comment]
Sorry guys it was my bad. I found the issue and got it fixed. Thansk
