### ISSUE TITLE
Sheet: Blocking Multi rows selection

### ISSUE THREAD

**Issue by muhdkhokhar** [primefaces-extensions/primefaces-extensions.github.com#653]
Is there anyways to block mulitple rows selection or multiple columns on two rows. Just Allow them to select single row

**Comment by melloware** [comment]
Is this what you want?  https://handsontable.com/docs/6.2.2/demo-selecting-ranges.html

Forcing them to select a single cell instead of multiselect rows or ranges?

**Comment by muhdkhokhar** [comment]
Yes basically don't let them select multiple rows.

**Comment by melloware** [comment]
OK try this.  Using this showcase Example: https://www.primefaces.org/showcase-ext/sections/sheet/dynamicColumns.jsf

Use the "extender" feature `extender="sheetExtender"` and then make the JS for that method at the bottom of the page look like this...

```javascript
<script type="text/javascript">  
function sheetExtender() {  
    this.cfg.selectionMode = 'single';  
};  
<script>
```

**Comment by muhdkhokhar** [comment]
Just perfect man. Thanks a lot. It worked like a charm.

Is there anyway to export sheet in excel/csv?

**Comment by melloware** [comment]
Unfortunately it looks like exporting is a Handsontable PRO feature not available to the Open Source Community version we use: https://handsontable.com/docs/6.2.2/demo-export-file.html

So you probably have to write your own Controller method that loops over your data and builds a CSV or Excel file using `<p:download>`.

**Comment by melloware** [comment]
I added the selectionMode attribute to the sheet for the next release, Commit: https://github.com/primefaces-extensions/core/commit/b79998cdaa5023848e364ff419dbb62787379b06
