### ISSUE TITLE
New component: Letter Avatar

### ISSUE THREAD

**Issue by aripddev** [primefaces-extensions/primefaces-extensions.github.com#654]
Hi, I would like to implement a new component based on https://gist.github.com/leecrossley/6027780

It basically generates data URI to embed small avatar image files inline in documents. There is no third party dependencies required. I would like to use "letteravatar" as tag name.

**Comment by melloware** [comment]
I like it.  Feel free to submit a PR and I can help critique or clean it up once you think you have it ready to go!

**Comment by aripddev** [comment]
Hi @melloware , i have just seen your message after I submit PR. I am getting error during travis build. Can you please help me?

**Comment by melloware** [comment]
Don't worry about Travis its a little wonky the way our current build is set up.  I will take care of it once I merge. I sent you some PR comments to adjust first!

**Comment by melloware** [comment]
Nice job.  I cleaned it up a little and wrote a showcase demo for it. This will be part of the 7.0 release.

![image](https://user-images.githubusercontent.com/4399574/53307764-c20f1280-3869-11e9-8565-acb5bd4cf52d.png)

**Comment by aripddev** [comment]
Thanks. Happy for the contribution.
