### ISSUE TITLE
codemirror: context and token property in CompleteEvent with code completion

### ISSUE THREAD

**Issue by sberequek** [primefaces-extensions/primefaces-extensions.github.com#656]
Hi,

when I use the codemirror component in mode "text / x-yaml" or "javascript" with code completion, the "context" and "token" properties in the CompleteEvent object are often null or wrong.
Would it be possible to give the user the possibility to optionally specify javascript functions for the calculation of the "context" and "token" values?

Thanks

**Comment by melloware** [comment]
Can you create a small reproducible sample so I can see the problem? 
 Use this small test project https://github.com/primefaces/primefaces-test

**Comment by sberequek** [comment]
Hi @melloware,

I attached the project with the use case.

[primefaces-test.zip](https://github.com/primefaces-extensions/primefaces-extensions.github.com/files/2919647/primefaces-test.zip)

Thanks

**Comment by melloware** [comment]
let me investigate this.

**Comment by melloware** [comment]
OK so here is the Complete JS method;  https://github.com/primefaces-extensions/core/blob/master/src/main/resources/META-INF/resources/primefaces-extensions/codemirror/widget.js#L54-L114

You could override this yourself simply by adding this code in your XHTML page...

```javascript
PrimeFaces.widget.ExtCodeMirror.prototype.complete= function() {
   .. yourn own code here
}
```

**Comment by sberequek** [comment]
thanks @melloware I solved using your solution.

**Comment by melloware** [comment]
Glad I could help!
