### ISSUE TITLE
InputPhone: add geoIpLookup attribute

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions.github.com#657]
See https://github.com/primefaces-extensions/showcase/commit/f7b4511a84eca7e375014d72f88410ca5a615b71#r32495417

**Comment by melloware** [comment]
Thanks!  I will approve once you submit the PR.

**Comment by melloware** [comment]
I just updated to v 15.0.1 which they released yesterday.  Looks like mostly they just updated the Google Libraries.

**Comment by jepsar** [comment]
@melloware I'm already using this component in an application I'm working on and I'm very happy with it so far! In this app we are starting phone calls. While in the call I would like to display how much time was elapsed since the call was started. I checked the `timer` component and tried `<pe:timer timeout="0" format="HH:mm:ss"/>`, but that was not working. Is it worth adding a direction attribute so it could count up / show time elapsed as well or do you think that does not make sense for the timer.

**Comment by melloware** [comment]
I think we should add direction to timer.  Since that is really what you want is a timer.  Feel free to create a new ticket for the timer enhancment.  We should call the property direction and the values should be "up" and "down" with "down" being the default.

**Comment by jepsar** [comment]
@melloware I'm sorry.. I totally missed this one: https://www.primefaces.org/showcase-ext/sections/timer/direction.jsf The only thing I'm missing is a start value. I'll have a look at the JS before I create a new issue.

**Comment by melloware** [comment]
Nice.  For some reason I remembered that being in there.
