### ISSUE TITLE
InputPhone: submitted value gets null

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions.github.com#658]
Here the value is correct:

https://github.com/primefaces-extensions/core/blob/eaf2d477e93b5b024d94a3ac5e43cadb52d10d52/src/main/java/org/primefaces/extensions/component/inputphone/InputPhoneRenderer.java#L55

Here the value is null:

https://github.com/primefaces-extensions/core/blob/eaf2d477e93b5b024d94a3ac5e43cadb52d10d52/src/main/java/org/primefaces/extensions/component/inputphone/InputPhoneRenderer.java#L65

I'm not sure what is happening here as this is pretty much the same as with the `InputNumber` component.

Update: This is not happening in the showcase... I'll dig deeper...

**Comment by melloware** [comment]
Let me know what you find out.

**Comment by jepsar** [comment]
Pfff.. this took me way too long.. it turned out that my Faces Servlet URL mapping was wrong!

**Comment by jepsar** [comment]
@melloware Actually, I think something else was happening as well. I had a `commandButton` with `process=@(.someClass :input)` and that caused my phone input to not be processed. I'll do further testing tonight and might file an issue at PF (search expression).

**Comment by tandraschko** [comment]
Thats probably expected If your component has a wrapper Like div or span

**Comment by jepsar** [comment]
@tandraschko OK, good to know. That's the case here. That behavior is useful with updating, not so much with processing though.

**Comment by jepsar** [comment]
@tandraschko could we check for [`InputHolder`](https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/component/api/InputHolder.java) components [here](https://github.com/primefaces/primefaces/blob/79934bb1da899d44449c51eb4d1b4128e4ef06ce/src/main/java/org/primefaces/util/CSVBuilder.java#L71) and compensate for them? Or would that be a performance drain?

**Comment by tandraschko** [comment]
ok, i dont even know this :D
