### ISSUE TITLE
Sheet: change in license with handsontable V7.0.0

### ISSUE THREAD

**Issue by fheldt** [primefaces-extensions/primefaces-extensions.github.com#660]
The underlying component of pe:sheet changed the license with handsontable 7.0.0.

It has to seen if this is still compatible with primefaces extensions.

**Comment by melloware** [comment]
I believe this means HT 6.2.2 will be the last version we will be allowed to use for PrimeFaces Extensions.

https://github.com/handsontable/handsontable/issues/5831
