### ISSUE TITLE
New component: Countdown

### ISSUE THREAD

**Issue by aripddev** [primefaces-extensions/primefaces-extensions.github.com#661]
I would like to add a countdown component based on http://fengyuanchen.github.io/countdown/

**Comment by melloware** [comment]
We already have this right?  https://www.primefaces.org/showcase-ext/sections/timer/format.jsf

Lets you count up or down, show MomentJS time formats etc.?

**Comment by aripddev** [comment]
Right. I missed it.
Thanks.
