### ISSUE TITLE
InputPhone: add server side validation

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions.github.com#663]

**Comment by cnsgithub** [comment]
Don't know how validation is performed on client side, but https://github.com/googlei18n/libphonenumber might be an option for server side validation (which of course has to be done :wink:).

**Comment by jepsar** [comment]
@cnsgithub Yes, that was the plan. See https://gitter.im/primefaces-extensions/primefaces-extensions

**Comment by melloware** [comment]
Looks great.  I did some minor refactoring like making an encodeHiddenInput() java method as that is how a lot of the PF components do it.  Great work!
