### ISSUE TITLE
Global: Move hardcoded UI texts to message bundle

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions.github.com#665]
See https://github.com/primefaces-extensions/core/pull/68#discussion_r265268017

Comment by @cnsgithub: At least in PF there is a resource bundle Messages, see https://github.com/primefaces/primefaces/blob/96d30807fc67a2b6183f4956cb29202ae44759ee/src/main/java/org/primefaces/component/calendar/Calendar.java#L153 as an usage example.

**Comment by jepsar** [comment]
@melloware if you want me to have a look, just let me know.

**Comment by melloware** [comment]
If you want feel free!   I will merge your other PR in the morning if no one else has anything to say.  Looks good to me.

**Comment by jepsar** [comment]
Found this class:

https://github.com/primefaces-extensions/core/blob/master/src/main/java/org/primefaces/extensions/util/MessageUtils.java

which looks pretty much like:

https://github.com/primefaces/primefaces/blob/master/src/main/java/org/primefaces/util/MessageFactory.java

I could simply add a bundle to `MessageUtils.java`, but it would be better to reduce some duplicates.

**Comment by melloware** [comment]
So maybe we should create a MessageFactory that extends the PF Message Factory that way we can reduce all that duplicate code and just inject our message bundle into it?  Over the last couple of years I found lots of duplicates like this and I have slowly been replacing PFE classes with core PF classes.

I am all for reducing code duplication between PFE and PF.

**Comment by jepsar** [comment]
@melloware we cannot extend `MessageFactory` in its current form. I created an intermediate solution: https://github.com/jepsar/core/tree/fix-665.

**Comment by melloware** [comment]
Yep I think it’s good enough and then we should submit a PR to Primefaces to make that method public so we can fix our code in the future.

**Comment by melloware** [comment]
Nice work!

**Comment by jepsar** [comment]
@melloware FYI I've opened https://github.com/primefaces/primefaces/issues/4642 to change `getLocale()` to public at the PF side.

**Comment by melloware** [comment]
Much appreciated!
