### ISSUE TITLE
Showcase themes: add Nova, Luna, Omega

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions.github.com#670]
.. and maybe it's an idea to modernize the overall look

**Comment by melloware** [comment]
The showcase currently uses Omega.  But yes we need to add the Nova and Luna themes.

**Comment by melloware** [comment]
Fixed with commit: https://github.com/primefaces-extensions/showcase/commit/9c3dfd5933b8b60c8041bd199645a214da45cae8

**Comment by jepsar** [comment]
Shouldn't the old themes be removed? I was playing with #534 and noticed that Prime Icons were not working with legacy themes. I think I'll also have a go at #444 and see what I can come up with and try to integrate the documentation in it as well.

**Comment by melloware** [comment]
I guess theoretically we could remove the old themes but are we using PrimeIcons in the showcase?  I thought we were only using FontAwesome?

**Comment by jepsar** [comment]
Not yet ;-) I wanted to used them in #534 but maybe I shouldn't.

**Comment by melloware** [comment]
Nah go ahead and use them.  I prefer FontAwesome to PrimeIcons but that is just me.   Our default is OMEGA theme so it will work but if people switch themes to legacy themes its OK if it doesn't work.

The reason I leave the legacy themes is if someone wants to see what a component looks like in a legacy theme.
