### ISSUE TITLE
Showcase: logo link destination is broken (404)

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions.github.com#672]
Points to https://www.primefaces.org/views/home.jsf

Context path missing?

**Comment by melloware** [comment]
Yep  must have missed that one.  Will fix.

**Comment by melloware** [comment]
Fixed with cmmit: https://github.com/primefaces-extensions/showcase/commit/56e8e02f345e4c2543a8f787dddf538e579a7e95
