### ISSUE TITLE
Java 8

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions.github.com#676]
- [ ] See https://github.com/primefaces/primefaces/issues/4375
- [x] pom.xml set for Java 8
- [x] RTLAware interface is now a Default interface so check all RTLAware PFE components.
- [x] Widget is now a default interface so all resolveWidgetVar() methods can be removed.

**Comment by melloware** [comment]
@jepsar I checked in all the changes to move to PF 7.1-SNAPSHOT and Java 8.  I fixed all the compiler warnings and 3 of of the 4 tasks above.
