### ISSUE TITLE
TimeAgo/TimePicker support Java 8 time

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions.github.com#677]

**Comment by jepsar** [comment]
See also https://github.com/primefaces/primefaces/issues/4646

**Comment by melloware** [comment]
OK this ticket is ready to be worked on.

**Comment by melloware** [comment]
We want to look at CalendaUtils in PrimeFaces as it has a lot of functions like getValue() thta handle getting it as Date or LocalDate etc.

**Comment by jepsar** [comment]
Alright, I'll have a look at it

**Comment by melloware** [comment]
Fixed TimePicker with commit: https://github.com/primefaces-extensions/core/commit/5ae7824e352202d5578adee85e3582998653b3ec

it now supports either java.util.Date or java.time.LocalTime.  Also updated the showcase to show the use of both types.
