### ISSUE TITLE
sheet: change event does not fire when changing numeric value from "" to 0

### ISSUE THREAD

**Issue by eduarddrenth** [primefaces-extensions/primefaces-extensions.github.com#681]
- primfaces 7.0 (.1), extensions 7.0

In a sheet with an ajax change event like this:
```xml
<p:ajax event="change" listener="xxxx" />
```
the event will not fire when changing the value from empty to 0 in a column defined like this:
```xml
<pe:sheetcolumn value="xxx" colType="numeric"/>
```
As a workaround I define the column like this:
```xml
<pe:sheetcolumn value="xxx" onvalidate="validInt"/>
```

**Comment by melloware** [comment]
Does the change event fire if you go from empty to 1 or any other number or is 0 special?

**Comment by eduarddrenth** [comment]
from empty to 0, all other changes fire

**Comment by melloware** [comment]
Javascript and == vs === https://stackoverflow.com/questions/12422064/why-javascript-treats-0-equal-to-empty-string.

Fixed with commit: https://github.com/primefaces-extensions/core/commit/950455c643c6cabec6fb2f278cb7392fc619e9ba

**Comment by eduarddrenth** [comment]
nice.... by the way, our users are quite satisfied with the sheet

**Comment by melloware** [comment]
Awesome!  Thanks for the feedback.  We wrote it for one of our clients because we had a specific use case and I figured others out there would have similar needs.  It makes me happy to know all the effort was worth it!

**Comment by melloware** [comment]
p.s. I will release 7.0.1 PFE in the next couple of weeks as we are just buttoning up examples on the TimeAgo component.

**Comment by jepsar** [comment]
> p.s. I will release 7.0.1 PFE in the next couple of weeks as we are just buttoning up examples on the TimeAgo component.

@melloware I'm back in action. I'll do some work on that tonight.
