### ISSUE TITLE
Showcase EL function getFileContent uses incorrect encoding

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions.github.com#683]
It used to work OK (7.0) with, for example, the bean on https://www.primefaces.org/showcase-ext/sections/calculator/localization.jsf

However that bean used incorrect encoding and was fixed.

Try build the master (7.0.1), deploy and go to /showcase-ext/sections/calculator/localization.jsf and check the bean.

**Comment by jepsar** [comment]
This will be fixed by https://github.com/primefaces-extensions/showcase/pull/14/commits/fe69cc093752beab53f198be00ccc3974e62bc8a

**Comment by jepsar** [comment]
@melloware By the way, why isn't UTF-8 used? PF uses UTF-8.

https://github.com/primefaces/primefaces/blob/d55ad99cba86d29aa2c4a18b809f56479f59853a/pom.xml#L62

**Comment by tandraschko** [comment]
I would use UTF-8

**Comment by jepsar** [comment]
I would too. Currently both core and the showcase (and maybe more repos) are in ISO 8859-1. Should we convert them?

**Comment by tandraschko** [comment]
+1
@melloware ?

**Comment by melloware** [comment]
No idea it has alays been like that since I inherited this project.  I say go ahead and convert I always try and use UTF-8!

**Comment by jepsar** [comment]
Okay, I've created #685 for this.
