### ISSUE TITLE
Sheet: numericPattern

### ISSUE THREAD

**Issue by alessandro1511** [primefaces-extensions/primefaces-extensions.github.com#684]
Hi,
In the sheet for a price on sheetcolumn we use numericLocale="de-DE" numericPattern="$0,0.00" and the number changes to the correct value (es DE: 10,00€).

For dimension, exists somethings to determine on locale the corresponding value (es DE: 10,00mt , 10,00cm ; es US: 10,00ft)

**Comment by melloware** [comment]
I think what you are asking is there a sheet cell type "dimension" or if there is a numeric pattern that supports dimentions?  The answer is no.

**Comment by alessandro1511** [comment]
Thanks
