### ISSUE TITLE
Global: change source encoding to UTF-8

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions.github.com#685]

**Comment by jepsar** [comment]
For documentation sake I'll paste my shell commands here.

```
find . -type f -not -path "./.git/*"  -path "*.java" -exec sh -c "iconv -f ISO-8859-1 -t UTF-8 {} > {}.utf8"  \; -exec mv "{}".utf8 "{}" \;
```

**Comment by jepsar** [comment]
@melloware I think you've overlooked https://github.com/primefaces-extensions/core/pull/75 which is also part of this fix.

**Comment by melloware** [comment]
Sorry I thought it was just a showcase fix!  I didn't realize the core project also had issues.   It must have been like this since the project inception.  Thanks for taking care of this.
