### ISSUE TITLE
Showcase: replace deprecated bean annotations with CDI

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions.github.com#686]
Bit of build output:

```
org/primefaces/extensions/showcase/controller/masterdetail/SelectLevelListener.java:[21,24] javax.faces.bean.ManagedBean in javax.faces.bean has been deprecated
org/primefaces/extensions/showcase/controller/masterdetail/SelectLevelListener.java:[22,24] javax.faces.bean.RequestScoped in javax.faces.bean has been deprecated
org/primefaces/extensions/showcase/controller/fluidgrid/FluidGridDynaFormController.java:[25,24] javax.faces.bean.ManagedBean in javax.faces.bean has been deprecated
org/primefaces/extensions/showcase/controller/fluidgrid/FluidGridDynaFormController.java:[26,24] javax.faces.bean.ViewScoped in javax.faces.bean has been deprecated
```

**Comment by jepsar** [comment]
Fixed with https://github.com/primefaces-extensions/showcase/commit/d19be3b3c97982a6210f5edb833b138dfad2dd53

**Comment by melloware** [comment]
I can't run "mvn clean jetty:run".  Can you investigate?

**Comment by jepsar** [comment]
The issue has to do with the beans that used to be eager. I've upgraded OmniFaces to 2.7 and used its `@Eager` annotation, but that results in a different issue where Jetty won't start:

```
[WARNING] Failed startup of context o.e.j.m.p.JettyWebAppContext@418ee41b{/primeext-showcase,[file:///Users/jasper/NetBeansProjects/GitHub/PFE/showcase/src/main/webapp/, jar:file:///Users/jasper/.m2/repository/org/primefaces/themes/all-themes/1.0.10/all-themes-1.0.10.jar!/META-INF/resources, jar:file:///Users/jasper/.m2/repository/org/omnifaces/omnifaces/2.7/omnifaces-2.7.jar!/META-INF/resources, jar:file:///Users/jasper/.m2/repository/org/primefaces/primefaces/7.0/primefaces-7.0.jar!/META-INF/resources, jar:file:///Users/jasper/.m2/repository/org/glassfish/javax.faces/2.3.2/javax.faces-2.3.2.jar!/META-INF/resources, jar:file:///Users/jasper/.m2/repository/org/primefaces/extensions/primefaces-extensions/7.0.1-SNAPSHOT/primefaces-extensions-7.0.1-SNAPSHOT.jar!/META-INF/resources],UNAVAILABLE}{file:///Users/jasper/NetBeansProjects/GitHub/PFE/showcase/src/main/webapp/}
java.lang.NoClassDefFoundError: org/eclipse/jetty/server/handler/ContextHandler$Context
    at org.jboss.weld.environment.jetty.WeldDecorator.process (WeldDecorator.java:49)
    at org.jboss.weld.environment.jetty.JettyContainer.initialize (JettyContainer.java:74)
    at org.jboss.weld.environment.servlet.WeldServletLifecycle.initialize (WeldServletLifecycle.java:220)
    at org.jboss.weld.environment.servlet.EnhancedListener.onStartup (EnhancedListener.java:62)
```

This is after I've added `jetty-web.xml` fixing an other class not found:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Configure PUBLIC "-//Jetty//Configure//EN" "http://www.eclipse.org/jetty/configure.dtd">

<Configure class="org.eclipse.jetty.webapp.WebAppContext">
    <Call name="prependServerClass"><Arg>-org.eclipse.jetty.servlet.</Arg></Call>
</Configure>
```

I'm not a Jetty expert and don't really know what to do with this. We could revert the change, but at some point the deprecated managed beans will no longer work.

**Comment by melloware** [comment]
primefaces test project https://github.com/primefaces/primefaces-test uses CDI and Jetty.  Maybe there is something we are missing?

**Comment by tandraschko** [comment]
we probably use OWB there and not weld

**Comment by melloware** [comment]
Good idea we should make our dependencies the same as the PF test project and see if we can get it to work.  @jepsar the reason it has to work in Jetty is that is how PrimeTek deploys it when we do releases its running as Jetty WAR.

**Comment by jepsar** [comment]
On a side note: what is the status of #444? If that still needs to be done, it might be better to take care of these deprecated beans in that new showcase.

**Comment by melloware** [comment]
AS for #444 Rapster and I both agree I like the PFE Showcase better than the PF showcase.  For the main reason being ours has the example, code, and documentation on all the same page so users dont have to go looking anywhere else for information.   So currently we have no plans to do #444.  What are your thoughts?

**Comment by jepsar** [comment]
I do like that the documentation is incorporated. However, it is taking valuable screen space, all the time. The documentation is now limited to the attributes, Ajax events are not documented. An other thing I don't like is the extra click needed to get to the basic example. And a new look wouldn't hurt :-) So I think some improvements can be made.

**Comment by melloware** [comment]
Definitely.  I forgot to mention if you look at Clipboard or Calculator you can document the Ajax events!

**Comment by jepsar** [comment]
Ha, I should add that to the phone component as well then.

**Comment by melloware** [comment]
Fixed with commit: https://github.com/primefaces-extensions/showcase/commit/346d41f7f99d8459ff92f9210ee0d260617b9c67

I updated all the libraries, fixed all the issues and now we can run with MyFaces or Mojarra.  I switched to use OpenWebBeans to match the PrimeFaces Test project and showcase.
