### ISSUE TITLE
Speedtest component is no longer working in PF-Extensions 7.0

### ISSUE THREAD

**Issue by ssibitz** [primefaces-extensions/primefaces-extensions.github.com#687]
The speedtest component now raises an error in the primefaces 7,0 extensions.

So the component is not working even in the showcase you will only get an 
error instead of showing all speedtest gauges.

**Comment by jepsar** [comment]
Can you test with 7.0.1 SNAPSHOT? See https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/679

**Comment by ssibitz** [comment]
I currently can't test it against the 7.0.1 SNAPSHOT,
but when i added the missing library eve.js from https://github.com/adobe-webplatform/eve
as described in the ticket #679 manually,
the speedtest component is then working right.

So i think the fix for the 7.0.1 SNAPSHOT should also work for the speedtest component ...

**Comment by melloware** [comment]
Yep that will do it.  Closing this ticket as its fixed for 7.0.1
