### ISSUE TITLE
Sheet: onstart, oncomplete and update not working

### ISSUE THREAD

**Issue by leonardozoso** [primefaces-extensions/primefaces-extensions.github.com#690]
I'm using PrimeFaces 7.0.1 and PrimeFaces extensions 7.0.
On sheet component I'm trying to define an ajax behavior on 'filter' event.
The listener method is called, but the onstart, oncomplete and update attributes are not working.
This happens to me with 'filter' and 'sort' event, while the 'change' event works.

**Comment by melloware** [comment]
I will investigate.

**Comment by melloware** [comment]
@tandraschko I debugged this and verified all the events on the sheet work fine except "sort" and "filter".  They call their server side "listener" method but they don't call even "onstart" which should happen before any Ajax event gets fired.

```xml
	<p:ajax event="change"  onstart="alert('WORKS');"/>
	<p:ajax event="sort"  onstart="alert('NOT CALLED');"  />
	<p:ajax event="filter" onstart="alert('NOT CALLED');"  />
```

Have you ever seen this behavior before?  Are sort and filter somehow reserved words?

**Comment by tandraschko** [comment]
no idea but you can get a bit more debug infos with p:log

**Comment by melloware** [comment]
OK figured it out.  Now just need to know how to fix it.

**Comment by melloware** [comment]
Fixed with commit: https://github.com/primefaces-extensions/core/commit/87f7e2590642c13b7fb5a321f7d29074b2b3a6f3

Will be in 7.0.1.
