### ISSUE TITLE
Search is broken for CodeMirror extension 6.0.0

### ISSUE THREAD

**Issue by traviswinter** [primefaces-extensions/primefaces-extensions.github.com#692]
We started using code mirror for displaying YAML - both in a view only and editable mode - but discovered today that the search functionality (ctrl+f) seems broken. It does not let me write directly into the field, nor does it let me key paste (ctrl+v) though it does let me paste through right-click > Paste. Ideally this would work in both cases however I would be satisfied just being able to disable the feature all together (and default to the generic browser search).

Here's an example of the code:

`<pe:codeMirror id="editYamlDisplay" class="codeMirrorYamlDisplay" mode="yaml" gutter="false"
		    value="#{resourceDialogBean.yaml}" keyMap="default" lineNumbers="true"
		    matchBrackets="true" readonly="false" autofocus="true" />`

**Comment by melloware** [comment]
I would definitely upgrade to PrimeFaces 6.2 and PFE 6.2.10.   There has been so many fixes and changes since then.  I would assume your problem is solved.

We don't fix bugs in legacy versions.   6.0.0 is 3+ years old.

**Comment by traviswinter** [comment]
Thank you for the quick response - unfortunately we're hamstrung on Primefaces 6 for the time being. If its unsupported then I understand completely - was more just hoping that there was a config somewhere I could just update to prevent it from using the search addon.

**Comment by melloware** [comment]
Ahh that stinks.  Only thing you may be able to do is download the 6.0.0 source and just remove the search plugin and rebuild the JAR.  Source code available here: https://github.com/primefaces-extensions/core/releases/tag/primefaces-extensions-6.0.0
