### ISSUE TITLE
SelectOneMenu not creating rendered columns if it is being rendered as table for some cases

### ISSUE THREAD

**Issue by TalmeezFaizy** [primefaces-extensions/primefaces-extensions.github.com#693]
I have a <p:selectOneMenu> in which selectItem and selectItems are defined in this way: 
  <f:selectItem itemLabel="#{res.label_selectOne}" itemValue="#{null}" noSelectionOption="true"/>
  <f:selectItems value="#{caBulkUpdateDataBean.bulkUpdationList}"/>

Now after all the fetching of values and everything, 
I reached to the class SelectOneMenuRendered where this selectoneMenu goes to method encodeOptionAsTable(). 
And from here my question starts,
in this method 
we have the following code snippet:

 protected void encodeOptionsAsTable(FacesContext context, SelectOneMenu menu, List<SelectItem> selectItems, List<Column> columns)
            throws IOException 
{
//some code here
writer.startElement("tr", null);
            writer.writeAttribute("class", itemStyleClass, null);
            writer.writeAttribute("data-label", itemLabel, null);
            if (selectItem.getDescription() != null) {
                writer.writeAttribute("title", selectItem.getDescription(), null);
            }

            if (itemValue == null || (valueType != null && !valueType.isAssignableFrom(itemValue.getClass()))) {
                writer.startElement("td", null);
                writer.writeAttribute("colspan", columns.size(), null);
                writer.writeText(selectItem.getLabel(), null);
                writer.endElement("td");
            }
            else {
                for (int j = 0; j < columns.size(); j++) {
                    Column column = columns.get(j);
                    String style = column.getStyle();
                    String styleClass = column.getStyleClass();

                    writer.startElement("td", null);
                    if (style != null) {
                        writer.writeAttribute("style", style, null);
                    }
                    if (styleClass != null) {
                        writer.writeAttribute("class", styleClass, null);
                    }

                    renderChildren(context, column);
                    writer.endElement("td");
                }
            }

            writer.endElement("tr");
}

SelectOneMenuRenderer is primefaces Class and I have doubt that why 
in if-condition they have put check in form of **!valueType.isAssignableFrom(itemValue.getClass())**
because I believe that because of this check my code is not rendering columns in selectOneMenu even when value is present there, as for every Case  the given condition is giving 'false'. 
valueType and itemValue.getClass() both are of java.lang.String type. 

Earlier the given code was working in primefaces 5.3 , and there if-condition had simpple check:
`if(itemValue instanceof String) {
                writer.startElement("td", null);
                writer.writeAttribute("colspan", columns.size(), null);
                writer.writeText(selectItem.getLabel(), null);
                writer.endElement("td");
            } `

but now with the given change in condition in **PrimeFaces 7.0**, now selectOneMenu is not working as expected.

**Comment by melloware** [comment]
I think you have the wrong tracker?  I think you want PrimeFaces: https://github.com/primefaces/primefaces/issues

This is PrimeFaces Extensions issue tracker.

**Comment by TalmeezFaizy** [comment]
OKy i will close point here then... thanks :)
