### ISSUE TITLE
Issue with time picker

### ISSUE THREAD

**Issue by lodhipr** [primefaces-extensions/primefaces-extensions.github.com#694]
### As with your basic project of time picker link is :
**https://www.primefaces.org/showcase-ext/sections/timePicker/basicUsage.jsf**

### i am facing an issue, you have used <pe:timepicker> tas it generates an error as:
**<pe:timePicker> Tag Library supports namespace: http://primefaces.org/ui, but no tag was defined for name: timePicker**

_### please help me to resolve this issue_

**Comment by jepsar** [comment]
You need to use this namespace `http://primefaces.org/ui/extensions`
