### ISSUE TITLE
Layout: CSS missing borders with Nova and Luna theme

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions.github.com#696]
See https://github.com/primefaces-extensions/showcase/commit/a382006f59640350ccdd7f17b2cf59729a441182

**Comment by jepsar** [comment]
Why does this component still exist? Wasn't it moved to PrimeFaces?

https://www.primefaces.org/showcase/ui/panel/layout/element.xhtml

By the way, it is deprecated there. Shouldn't it be be deprecated here as well?

**Comment by melloware** [comment]
No we use Layout heavily.  PF has a similar component that was created AFTER the PFE one.  Many users are still using this one and I have recommended it as a upgrade path if users want to switch from PF once PF removes it.

**Comment by melloware** [comment]
I even have this ticket: https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/532

**Comment by jepsar** [comment]
Alright. In that case it needs some CSS work as well.

**Comment by melloware** [comment]
Is it missing in the Layout CSS or in Nova/Luna?  Because Omega works fine and so do the legacy themes.  I wonder if it something PF is not including in the themes that it should be?

**Comment by melloware** [comment]
OK fixed with commit: https://github.com/primefaces-extensions/core/commit/d3b93dc263ff101b55ba70557bfdfed63a958fb0

Turns out we just needed to add the PF layout styles to our layout and the premium themes then work.

**Comment by jepsar** [comment]
Ha, that's a nice fix!
