### ISSUE TITLE
Sheet: clearFilters() call?

### ISSUE THREAD

**Issue by fheldt** [primefaces-extensions/primefaces-extensions.github.com#697]
Currently the sheet component has no way to clear all set filters (which is very annoying).

In the standard primefaces datatable there's the very convinient PF('table').clearFilters() JS function.

**Comment by melloware** [comment]
Fixed with commit: https://github.com/primefaces-extensions/core/commit/d9c4ada9ac288f0ca0cea100e052f32fdf18f07b
