### ISSUE TITLE
DynaForm: readOnly attribute

### ISSUE THREAD

**Issue by pzoli** [primefaces-extensions/primefaces-extensions.github.com#698]
I set readOnly attribute by program in a dynaForm, but not works for me. Is this a correct way?

		if (rights.readOnly() != null) {
			Boolean readonly = evalELToBoolean(rights.readOnly());
			if (readonly != null && readonly) {
				component.getAttributes().put("readOnly",true);
			}
		}

**Comment by melloware** [comment]
@Rapster is the DynaForm expert I will wait for him to chime in.

**Comment by pzoli** [comment]
I use version 7.0

**Comment by Rapster** [comment]
Hi,

Sorry I'm kinda taking a break from PF issues lately... But by the sound of it, it looks like a duplicate of #571. As far as I can remember, I thought I fixed it, but @melloware had issues after this fix. So, whenever I'll have time to investigate on this, I'll let you know

**Comment by melloware** [comment]
Marking as duplicate for now as its tracked in the other issue.
