### ISSUE TITLE
InputPhone widget does not load the utils script when it should

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions.github.com#700]

**Comment by jepsar** [comment]
.. ti seems that the utils script is not loaded

**Comment by melloware** [comment]
Might be related to when I run a release mode build the scripts are compressed.  You can simulate with "mvn clean package -Pcompress".  Maybe something with script compression is breaking it.

**Comment by jepsar** [comment]
@melloware Thanks. I don't think it's caused by that, but I'll have a look tonight (CET).

**Comment by jepsar** [comment]
Okay, a coworker of mine experienced this in a project I now no longer trust.. there must be an issue in that project. I just tested with a different project and there it was just working fine.

**Comment by melloware** [comment]
Good.  Yeah the Showcase was working fine for me locally.

**Comment by jepsar** [comment]
We had a JIRA issue collector in the failing project. I had issues with it in combination with PF before, so I just removed it and now the input is working without problems. Weird thing though is that I didn't see any issues in the browsers JS console.
