### ISSUE TITLE
Issue with data export 

### ISSUE THREAD

**Issue by lodhipr** [primefaces-extensions/primefaces-extensions.github.com#702]
Can you please help me designing a custom pdf form like i have a data table when i click to export pdf it generate advanced form like a job card which have some preentered values and my data table in it which may looks like an image below
![22047e0a88337b47da2beece718e2431](https://user-images.githubusercontent.com/45519944/58195314-49431980-7ce5-11e9-8517-10099ac962e6.jpg)

**Comment by melloware** [comment]
This is not possible with the exporter.  Your best bet is to create a custom PDF for this export using something like Apache PDFBox: https://pdfbox.apache.org/

But there is no way to make this component magically generate that form for you.  You will have to create the PDF custom in your code. Sorry.
