### ISSUE TITLE
InputPhone: Update JS and Java libraries

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions.github.com#703]
https://github.com/jackocnr/intl-tel-input/releases/tag/v15.1.0

**Comment by melloware** [comment]
Fixed with commit: https://github.com/primefaces-extensions/core/commit/ec8f716633a05db67658410ad616211f21af0a07

**Comment by jepsar** [comment]
I was planning to update the libs just before the release of 7.0.2. The Java lib also has updates (they update very frequently).

**Comment by melloware** [comment]
OK re-opened and i will leave open until right before we release 7.0.2

**Comment by jepsar** [comment]
The Java library already is up to date, right?

https://github.com/primefaces-extensions/master-pom/blob/e720d5652a1501d393c036305e26ce4f5387085b/pom.xml#L63

**Comment by melloware** [comment]
I think we need to update the JAR as there is a newer version. We are using 8.10.7 there is an 8.10.17

https://search.maven.org/artifact/com.googlecode.libphonenumber/libphonenumber/8.10.17/jar

**Comment by jepsar** [comment]
Right.. I overlooked the 1. I'll upgrade it as well.

**Comment by jepsar** [comment]
See PR https://github.com/primefaces-extensions/master-pom/pull/2 and https://github.com/primefaces-extensions/core/pull/85
