### ISSUE TITLE
GChart: Add Gantt chart

### ISSUE THREAD

**Issue by fheldt** [primefaces-extensions/primefaces-extensions.github.com#704]
The current GChart component allows only a few chart types, although the underlying Google Charts library has a lot more variants.

Also an "extension" attribute would be great, eg to set the option parameter for the chart(s).

**Comment by melloware** [comment]
Extender is a great idea.  However for Chart Types I have only been adding them as people request them.

See this class: https://github.com/primefaces-extensions/core/blob/master/src/main/java/org/primefaces/extensions/component/gchart/model/GChartType.java

**Comment by fheldt** [comment]
Then how about the gantt chart? That would give a really nice new possibility :-)

https://developers.google.com/chart/interactive/docs/gallery/ganttchart

**Comment by melloware** [comment]
OK fixed with commit: https://github.com/primefaces-extensions/core/commit/92345ae33fade95a1995cc160e15a0b51dacd02c

Adding another ticket for Extender functionality.

**Comment by fheldt** [comment]
Sorry for my late comment, but this there are 2 errors in your commit:

``` 
--- a/src/main/java/org/primefaces/extensions/component/gchart/model/GChartType.java
+++ b/src/main/java/org/primefaces/extensions/component/gchart/model/GChartType.java
@@ -26,7 +26,7 @@ public enum GChartType {
     COLUMN("ColumnChart"),
     LINE("LineChart"),
     SCATTER("ScatterChart"),
-    GANNT("GanttChart");
+    GANTT("Gantt");
     // @formatter:on
 
     private String chartName; 
```

**Comment by melloware** [comment]
Fixed with commit: https://github.com/primefaces-extensions/core/commit/b549920601d5bfbadb2b88e4d90572cce5cbd05b
