### ISSUE TITLE
TimeAgo: Short flashing display of date string on page load and Ajax update

### ISSUE THREAD

**Issue by stolp** [primefaces-extensions/primefaces-extensions.github.com#707]
I am using Primefaces Extensions 7.0.1 with simple p:timeAgo instance like the following:
```
<pe:timeAgo id="createdTime"
      value="#{bean.created}" titlePattern="#{pageHandler.localizedDatePattern}" />
```
Upon page load or when the containing form is updated via an Ajax submit, I am noticing a small flicker. It looks like that the date string from the title is shortly inserted before the correct timeAgo text is shown. This is very irritating.

Is anybody else experiencing this as well?

**Comment by melloware** [comment]
Let me investigate and get back to you.

**Comment by melloware** [comment]
I have confirmed your issue.

**Comment by jepsar** [comment]
That's how that library rolls.. they are replacing HTML the original HTML would serve as a fallback in case JS is not available (we don't need that). Maybe we should do a rewrite of the script (we could also solve #678 then).

**Comment by jepsar** [comment]
By the way.. I've noticed that Chrome has having rendering issues lately. I'm not sure what you are using. Could you please let me know what browser you are using?

**Comment by stolp** [comment]
Good idea, the behaviour indeed varies with the browser implementation:

Brave/Chrome: Annoying
Firefox: Bearable but present
Edge/IE: Not visible

I tested on Brave initially

**Comment by jepsar** [comment]
If we want to get rid of this we should port the implementation to Java...

**Comment by melloware** [comment]
Well but if you sit on the page you will notice the TimeAgo keeps changing every minute.  So we would still need some JS code to make the component work.

**Comment by jepsar** [comment]
@melloware I think some delay may be caused by how a locale file is loaded:

https://github.com/primefaces-extensions/core/blob/b549920601d5bfbadb2b88e4d90572cce5cbd05b/src/main/resources/META-INF/resources/primefaces-extensions/timeago/1-timeago-widget.js#L22-L30

I'm not sure if that will be the (only) cause of experienced delay, but I'd like to rewrite that bit at least.

**Comment by melloware** [comment]
I was wondering that.  I think that is a good idea.

**Comment by jepsar** [comment]
Maybe we should switch back to https://github.com/primefaces-extensions/core/commit/260f02f22ba6752a742ac773f50639c00c1113d6#diff-058fd7b8ab970dfb58f974683e2085b2R124

**Comment by melloware** [comment]
Yeah you can give it a try and see if it reduces the flickering?  If so I said we go for it.
