### ISSUE TITLE
Gravatar: Use "LetterAvatar" as placeholder for Gravatar.notFound

### ISSUE THREAD

**Issue by pizzit** [primefaces-extensions/primefaces-extensions.github.com#709]
it would be nice to use LetterAvatar as placeholder when Gravatar account does not exists

**Comment by melloware** [comment]
Not a bad suggestion.

**Comment by melloware** [comment]
OK will be in 7.0.2.  Fixed with this commit: https://github.com/primefaces-extensions/core/commit/55cb701021bb1eed0cf79a5de6c7bfdc6de7f54b

You will be able to do this...

```xml
<pe:gravatar value="iamadummygravataruser@gmail.com" 
                     notFound="https%3A%2F%2Fui-avatars.com%2Fapi%2F/Primefaces+Rocks"/>
```

You can see all the customizations here: https://ui-avatars.com/

You have to use this callback URL mechanism.
