### ISSUE TITLE
New Component: Credit Card

### ISSUE THREAD

**Issue by marcelocaser** [primefaces-extensions/primefaces-extensions.github.com#711]
I suggest writing a credit card component as in the example below:
https://github.com/amarofashion/react-credit-cards

**Comment by melloware** [comment]
That is a very nice component.  Too bad that one in particular is specifically for React.  We need to find a raw JavaScript or Jquery based one.

**Comment by marcelocaser** [comment]
I found some in:
https://www.learningjquery.com/2016/03/10-jquery-credit-card-form-plugins
In particular these:
https://github.com/jessepollak/card
http://kenkeiter.com/skeuocard/
https://github.com/wangjohn/creditly

**Comment by melloware** [comment]
I like the look of https://github.com/jessepollak/card but it concerns me he is not really accepting PR's anymore and has open PR's.   But that one of the 3 looks like the most recently maintained.

**Comment by melloware** [comment]
Working on this...
```xml
<h:form id="frmMain">
	<p:panelGrid id="pnlCreditCard" columns="4">
		<f:facet name="header">
			<pe:creditCard id="creditCard" />
		</f:facet>
		<p:inputText id="txtNumber" placeholder="Card number" pt:name="number" />
		<p:inputText id="txtName" placeholder="Full name" pt:name="name" />
		<p:inputText id="txtExpiry" placeholder="MM/YY" pt:name="expiry" />
		<p:inputText id="txtCvc" placeholder="CVC" pt:name="cvc" />
	</p:panelGrid>
</h:form>
```

![image](https://user-images.githubusercontent.com/4399574/78388418-f695e780-75ae-11ea-8a2b-91f9e6d66d01.png)

**Comment by marcelocaser** [comment]
Wow! a great job @melloware! I can't wait to be able to test it!

**Comment by melloware** [comment]
@jepsar @aripdev please review the commit of this new component
https://github.com/primefaces-extensions/core/commit/e2dc639feefb9ea3d82f4826465d82e663516661

Attached is a runnable test project to test the component:
[pfe-card.zip](https://github.com/primefaces-extensions/primefaces-extensions.github.com/files/4429681/pfe-card.zip)

The only disappointing thing is the library's heavy use of `eval()` prevents it from being used with primefaces.CSP.

**Comment by melloware** [comment]
Solved the CSP problem!  Had to change webpack to build the JS without eval() statements.  Now the component works with CSP.

**Comment by marcelocaser** [comment]
some data for the final version?

**Comment by melloware** [comment]
Probably 8.0.1 in the next 1-2 weeks.  @aripddev is finishing up his FuzzySearch component

**Comment by melloware** [comment]
OK card is done and showcase example added.

**Comment by melloware** [comment]
8.0.1 is now in Maven Central if you want to give this component a shot @marcelocaser

**Comment by melloware** [comment]
Sorry make that 8.0.2. Found a bug

**Comment by marcelocaser** [comment]
thanks a lot @melloware

**Comment by melloware** [comment]
@marcelocaser make sure to read this thread: https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/790

**Comment by marcelocaser** [comment]
yes!! thanks!! great job!

**Comment by mortadha-dev** [comment]
Hello Guys , iam using Credit Card and i want to override the placeholderNumber how can i do that

**Comment by melloware** [comment]
> Hello Guys , iam using Credit Card and i want to override the placeholderNumber how can i do that

There is a property `placeholderNumber ` "Placeholder for the card number. Default '•••• •••• •••• ••••'".  Is it not working?

**Comment by mortadha-dev** [comment]
Yeah , yeah sorry melloware for disturbing it is working, i just was making changes in another page and wait for the result Lol

**Comment by melloware** [comment]
No worries glad you got it working.

**Comment by mortadha-dev** [comment]
melloware i have a question if i initialise a number for the placeholderNumber and for the input. i don't get the color as if i put it manually, is there any way to get the card colored when the number is initialised.

**Comment by melloware** [comment]
@mortadha-dev did you figure out your issue?

**Comment by mortadha-dev** [comment]
Yes resolved thank you

**Comment by mortadha-dev** [comment]
Hello Melloware i want to have list of credit cards in a carousel view but the color dissapear , can you please help me 
![creditCard](https://user-images.githubusercontent.com/60823618/169502510-15acc361-b825-406c-9f62-93b666bb8881.PNG)

`  <h:form prependId="false">
            <div class="card">
                <p:carousel value="#{customerCardsController.cardsList}" var="card" numVisible="2"
                            numScroll="3"
                >

                    <p:panelGrid columns="1" id="pnlCreditCard">
                        <f:facet name="header">
                            <pe:creditCard id="creditCard" labelMonthYear="MM/YY" placeholderExpiry="**/**"
                                           placeholderNumber="#{card.cardNumber}"
                                           placeholderName="#{card.cardHolderName}"/>
                        </f:facet>
                        <h:panelGrid columns="2">
                            <h:outputLabel value="Card Number" for="number"/>
                            <p:inputText id="number" placeholder="Card number"
                                         style="margin-right: 1em"
                                         value="#{card.cardNumber}"
                                         inputmode=" numeric"
                                         required="true"
                                         requiredMessage="#{cardMessages.mandatoryNumber}"

                            />
                        </h:panelGrid>
                        <h:panelGrid columns="2">
                            <h:outputLabel value="Holder Name " for="name"/>

                            <p:inputText id="name" value="#{card.cardHolderName}"

                                         placeholder="Full name"/>
                        </h:panelGrid>
                        <h:panelGrid columns="2">
                            <h:outputLabel value="Expiration Date" for="expiration"/>

                            <p:outputPanel id="expiration">
                                <p:datePicker id="month" widgetVar="monthPicker" view="month"
                                              pattern="yyyy.MM.dd"
                                              yearNavigator="true"
                                              yearRange="2000:2050"
                                              placeholder="#{card.expirationDate}"
                                              onchange="$('#expiry').val(PF('monthPicker').input.val()); $('#expiry')[0].dispatchEvent(new Event('change'));"/>
                                <p:inputText value="#{card.expirationDate}"
                                             id="expiry"
                                             required="true"
                                             requiredMessage="#{cardMessages.mandatoryExpiration}"
                                             inputmode="numeric" style="display:none"/>
                            </p:outputPanel>
                        </h:panelGrid>
                        <h:panelGrid columns="2">
                            <h:outputLabel value="CVC" for="cvc"/>

                            <p:inputText id="cvc" placeholder="CVC" inputmode="numeric"
                                         value="#{card.cvc}"
                                         required="true"
                                         requiredMessage="#{cardMessages.mandatoryCVC}"

                            />
                        </h:panelGrid>
                        <h:panelGrid columns="2">
                            <h:outputLabel value="Current Balance" for="currentBalance"/>

                            <p:inputText id="currentBalance" placeholder="Current Balance"
                                         type="number"
                                         value="#{card.currentBalance}"
                                         required="true"
                                         requiredMessage="#{cardMessages.mandatoryCVC}"
                            />
                        </h:panelGrid>


                    </p:panelGrid>

                </p:carousel>
            </div>
        </h:form>`

**Comment by jepsar** [comment]
@mortadha-dev please create a new issue and attach a reproducer using https://github.com/primefaces/primefaces-test

**Comment by melloware** [comment]
Agreed with @jepsar and also our new Issues area is here: https://github.com/primefaces-extensions/primefaces-extensions/issues

**Comment by mortadha-dev** [comment]
Okay i will create a new issue
