### ISSUE TITLE
Sheet: Text first character empty (Space or blank)

### ISSUE THREAD

**Issue by awenger63** [primefaces-extensions/primefaces-extensions.github.com#712]
Hi, in 6.2.10 on sheetcolmun colType="text", 
- I cannot add a space on fisrt character type " TOTO", result is "TOTO" on the sheetUpdate.getNewValue(); Same issue on the last char (You can test it on showcase)

Put on bean
`private String testTOTO= " TOTO"; // and getter and setter`
Put on form
`<pe:sheetcolumn headerText="TOTO" value="#{myBean.testTOTO}" colType="text"/>` 
 - User cannot see fisrt space char. but On edit , it appear (YES) but when lost focus the update process sheetUpdate.getNewValue() remove this fisrt space !!! and after data is "TOTO" whitout the blanck !

"text" it's a String that can contain space on each position we need first, last or other !
How is it possible to conserve the space (on edit or after an update)

**Comment by melloware** [comment]
Will investigate.

**Comment by melloware** [comment]
Looks like I might have to add trimWhiteSpace property to the SheetColumn.  See: https://handsontable.com/docs/7.1.1/Options.html#trimWhitespace

**Comment by melloware** [comment]
Fixed with commit: https://github.com/primefaces-extensions/core/commit/f8b1e1b1a48bbb995cd3038c8b9ae14f933decde
