### ISSUE TITLE
Showcase: pe:timer link is incorrect

### ISSUE THREAD

**Issue by francescociani** [primefaces-extensions/primefaces-extensions.github.com#714]
Hi,

in the showcase menu, the timer item actually links to:

https://www.primefaces.org/showcase-ext/views/timeago.jsf

should link to:

https://www.primefaces.org/showcase-ext/views/timer.jsf

**Comment by melloware** [comment]
Thanks for the report!  Fixed with commit: https://github.com/primefaces-extensions/showcase/commit/ccae2e36a0936960f33ecadc8e14147d4cddb0b3
