### ISSUE TITLE
Sheet: org.apache.myfaces.renderkit.html.HtmlRenderKitImpl.getRenderer Unsupported component-family/renderer-type: org.primefaces.extensions.component/org.primefaces.extensions.component.SheetColumnRenderer

### ISSUE THREAD

**Issue by jdgorrin** [primefaces-extensions/primefaces-extensions.github.com#715]
Hello,

I have a problem using primefaces extensions Sheet, my tomcat logs is too big with the following messages:

05-Aug-2019 11:14:40.098 WARNING [http-nio-8084-exec-57] org.apache.myfaces.renderkit.html.HtmlRenderKitImpl.getRenderer Unsupported component-family/renderer-type: org.primefaces.extensions.component/org.primefaces.extensions.component.SheetColumnRenderer
05-Aug-2019 11:14:40.098 WARNING [http-nio-8084-exec-57] javax.faces.component.UIComponentBase.getRenderer No Renderer found for component {Component-Path : [Class: javax.faces.component.UIViewRoot,ViewId: /secured/wp/wp-wis.xhtml][Class: javax.faces.component.html.HtmlBody,Id: j_id_b][Class: org.primefaces.component.outputpanel.OutputPanel,Id: mainpanel][Class: javax.faces.component.html.HtmlForm,Id: form1][Class: org.primefaces.extensions.component.sheet.Sheet,Id: sheet][Class: org.primefaces.extensions.component.sheet.SheetColumn,Id: j_id_3t]} (component-family=org.primefaces.extensions.component, renderer-type=org.primefaces.extensions.component.SheetColumnRenderer) created from: /secured/wp/wp-wis.xhtml at line 76 and column 80

I use primefaces extensions with the following pom config:

         <dependency>
            <groupId>org.apache.myfaces.core</groupId>
            <artifactId>myfaces-impl</artifactId>
            <version>2.3.2</version>
        </dependency>       
        <dependency>
            <groupId>org.apache.myfaces.core</groupId>
            <artifactId>myfaces-api</artifactId>
            <version>2.3.2</version>
        </dependency>
         <dependency>
            <groupId>org.primefaces</groupId>
            <artifactId>primefaces</artifactId>
            <version>6.2</version>
        </dependency>       
        <dependency>
            <groupId>org.primefaces.extensions</groupId>
            <artifactId>primefaces-extensions</artifactId>
            <version>6.2.10</version>
        </dependency>

It seems the same problem as indicated here:
https://github.com/primefaces-extensions/primefaces-extensions.github.com/issues/630

Thanks a lot for your help

**Comment by melloware** [comment]
Hmmm according to my notes that was fixed in 6.2.10 but you say you are still seeing this issue?  Are you sure there are no other older PFE versions on your classpath somehow?

**Comment by jdgorrin** [comment]
Hi @melloware thanks for your answer. I only have PFE 6.2.10 on my classpath. The problem start when i changed from Mojarra to MyFaces.

**Comment by melloware** [comment]
Hmm I am using MyFaces 2.3.3 in Spring Boot with PFE and was not seeing this message. Then again I am using PF 7.0 and PFE 7.0.1 on that project.

**Comment by jdgorrin** [comment]
I changed from MyFaces 2.3.2 to 2.3.4 right now but the problem persist. I looked everywhere but I can't find previous versions of PFE. I attached my local log with "extensions" word filtered
[Log Filtered.txt](https://github.com/primefaces-extensions/primefaces-extensions.github.com/files/3468401/Log.Filtered.txt)

**Comment by melloware** [comment]
Can you upgrade to PF7.0 PFE 7.0.1?

**Comment by melloware** [comment]
OK figured it out.  Fixed with this commit: https://github.com/primefaces-extensions/core/commit/80dec1116327da8c8ebbd7e9ab22fcf66a66ba45

I am not going to patch 6.2.10 but if you want to crack the JAR open just edit the primefaces.extensions-taglib.xml and remove that line and repackage the JAR should fix your issue!
