### ISSUE TITLE
Password mask with copy/paste

### ISSUE THREAD

**Issue by himbertm** [primefaces-extensions/primefaces-extensions.github.com#716]
Hi, what i found really good is the option of the password mask. Although, if you copy/paste the password elsewhere (for example notepad++), then you can see the password not as *** but as real characters.

**Comment by jepsar** [comment]
I'd opt for a password field where you would be able to toggle the readability of the text using an eye icon / button.

**Comment by himbertm** [comment]
Hi, maybe we misunderstood each other. What I mean is that unauthorized people get access to the real password. How? By copying and pasting the password (which is initially written in ***(stars) in the password mask) to their Tool notepad++ they can see the exact and unmasked letters/characters. 
The function could also be used for data worthy of protection. Only authorized persons do not see stars but plain text.

**Comment by himbertm** [comment]
Sorr this Issue is allways oben.

**Comment by melloware** [comment]
@himbertm This is the PF Extensions project. Did you mean to post this to the Primefaces project? And are you referring to the https://www.primefaces.org/showcase/ui/input/password.xhtml password field?
