### ISSUE TITLE
AjaxSessionTimeoutListener

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions.github.com#717]
Lot's of discussions and questions about this on the internet.

## 1) Environment
- PrimeFaces version: 6.2(.9)
- Does it work on the newest released PrimeFaces version? No
- Does it work on the newest sources in GitHub? No
- Application server + version: payara 5.183
- Affected browsers: all
- PrimeExceptionHandlerFactory and ajaxExceptionHandler in place

## 2) Expected behavior

when an ajax request fires and my session is invalid I want to know and I want to get a chance to login again

## 3) Actual behavior

when an ajax request fires and my session is invalid I see nothing, under the hood I get a response that looks like this:

```<?xml version='1.0' encoding='UTF-8'?>
<partial-response><changes><update id="j_id1:javax.faces.ViewState:0"><![CDATA[3793564356142802147:-5855215245280144347]]></update></changes></partial-response>
```

## 4) Steps to reproduce

develop an app with security context and login with at least one protected page that fires ajax

## 5) Sample XHTML

left as a todo

## 6) Sample bean

can be any simple bean

**Comment by melloware** [comment]
@eduarddrenth  from https://github.com/primefaces/primefaces/issues/4109

**Comment by melloware** [comment]
Fixed with commit: https://github.com/primefaces-extensions/core/commit/bd0f6f4c9c0f1d3258b9a470d6ef3fa3d70d5888

**Comment by tandraschko** [comment]
-1
Even the Login.xhtml is hardcoded

**Comment by melloware** [comment]
Do you recommend reading it from somewhere. Is there a way to pass props from faces-config.xml?

**Comment by tandraschko** [comment]
yep
also, how does the current code check for a invalid session? 
Also i would try MyFaces what happens...

**Comment by eduarddrenth** [comment]
> -1
> Even the Login.xhtml is hardcoded

The default yes, getLoginPath can be overridden

**Comment by eduarddrenth** [comment]
> yep
> also, how does the current code check for a invalid session?
> Also i would try MyFaces what happens...

The session is always invalid, that's the whole point of this listener

**Comment by tandraschko** [comment]
Why does a forward always means a invalid session?

**Comment by eduarddrenth** [comment]
I guess you're right, there may be other situations that lead to a forward. For these situations (did not encounter one yet) it may be undesirable to redirect, I'll build in a check.

**Comment by tandraschko** [comment]
And as long as nobody checks MyFaces, i still think thats an bug in mojarra and therefore -1 to add something
