### ISSUE TITLE
DocumentViewer: add options to restrict download or print files

### ISSUE THREAD

**Issue by ybendek** [primefaces-extensions/primefaces-extensions.github.com#718]
Hi.  I've been using  the DocumentViewer component to display some files, but now I have a request from a client to restrict the options to download or print the file from the viewer.

I made some research about the library used (https://github.com/mozilla/pdf.js/issues/2611) and as far as I found the best way is to add the class "hidden" to the download button. I tried to do it with no success with the component, mainly because is inside of an iframe and because is loaded unsync using a worker.

I was wondering if it could be possible to add in some way these options to the DocumentViewer component

**Comment by melloware** [comment]
No problem glad I could help

**Comment by imnotscott** [comment]
Greetings!

I have an issue similar to the op but my scenario is a little bit different.  I am using document viewer to display a PDF report.  When the page loads, the document viewer is not rendered. The user supplies some report filter criteria and clicks a submit button, then the PDF is created and the document viewer is rendered.  This is all working great but I have the same requirement to hide the buttons or preferably the entire toolbar.  I have been struggling to find a way to execute a javascript after the component is rendered.  My code below with an added button for testing.  Any suggestions you could provide would be very much appreciated.

`<h:panelGroup id="pdfPreview_panelGroup"
                                  rendered="#{inspectionHistoryReportMB.displayPDF}">
                        <div class="card">
                            <p:commandButton id="exportPDF_button"
                                             value="Export to PDF" 
                                             actionListener="#{inspectionHistoryReportMB.generatePDF(inspectionHistoryReportMB.inspectionHistoryReportDTOList, true)}"
                                             styleClass="submitCancelButton"
                                             ajax="false"/>
                            <p:commandButton id="exportExcel_button"
                                             value="Export to Excel" 
                                             actionListener="#{inspectionHistoryReportMB.generateExcel(inspectionHistoryReportMB.inspectionHistoryReportDTOList)}"
                                             styleClass="submitCancelButton"
                                             ajax="false"/>
                            <p:commandButton id="testButton" onclick="window.frames[0].PDFViewerApplication.toolbar.items.openFile.hidden = true;" />
                            <br/><br/>
                            <pe:documentViewer id="report_pdf" 
                                               value="#{pdfViewerMB.streamedContent}"
                                               download="#{inspectionHistoryReportMB.docTitle.concat('.pdf')}"
                                               width="100%" 
                                               height="1200px">
                            </pe:documentViewer>
                        </div>
                    </h:panelGroup>`

**Comment by melloware** [comment]
This should be pretty easy can you paste your Submit button code where you actually call to render to the DocumntViewer?  Can you paste it here?

**Comment by scott-abernethy66** [comment]
The xhtml for the submit is here:

<h:panelGrid columns="4">      
                            <p:commandButton id="submit_button"
                                             value="#{labels['screen.submit']}" 
                                             action="#{inspectionHistoryReportMB.submit}"
                                             update="inspectionHistoryReport_messages @form"
                                             onclick="PF('blockUI_search').show();"
                                             styleClass="submitCancelButton"/>

                            <p:commandButton id="cancel_button"
                                             value="#{labels['screen.cancel']}"
                                             action="/reports/reports?faces-redirect=true"
                                             immediate="true"
                                             styleClass="submitCancelButton"/>

                        </h:panelGrid>

**Comment by melloware** [comment]
OK in your submit button add...
```javascript
oncomplete="hidePdfButtons();"
```
which will execute once your AJAX request is complete. Then in your hidePdfButton use a "delay" because the DocViewer PDF is still rendering the buttons might not be there yet

```javascript
setTimeout(function() {
    var pdfViewer = window.frames[0].PDFViewerApplication;
    if (pdfViewer) {
        pdfViewer.toolbar.items.openFile.hidden = true;
        pdfViewer.toolbar.items.viewBookmark.hidden = true;
    }
}, 1500);
```
You can tweak the 1500 as that is 1.5 seconds as per whatever you need for load time.

**Comment by scott-abernethy66** [comment]
This works perfectly. Thank you!

**Comment by melloware** [comment]
Glad I could help

**Comment by Dilakshi** [comment]
Please let me know if anyone knows a way to hide the fullscreen(**presentationMode**) button as well. works for print,download,openFile,viewBookmark buttons except presentationMode

![image](https://user-images.githubusercontent.com/15982283/156915424-30b69dc7-3ce5-476b-945e-852812ec1d36.png)

**Comment by melloware** [comment]
@Dilakshi depending on what version of PrimeFaces Extensions you are using you can try this too...

```js
pdfViewer.toolbar.buttons.find(el => el.eventName === 'presentationmode').element.style.display = "none";
```

**Comment by Dilakshi** [comment]
@melloware Thank you I'll try this too

**Comment by melloware** [comment]
Let me know if it doesn't work. I just tried that in the console of the showcase and it hidden the button.

**Comment by Dilakshi** [comment]
> ```js
> window.frames[0].PDFViewerApplication
> ```

It did nicely. Thank you

**Comment by melloware** [comment]
Linking to updated ticket: https://github.com/primefaces-extensions/primefaces-extensions/issues/217
