### ISSUE TITLE
New Component: Color Legend

### ISSUE THREAD

**Issue by mores** [primefaces-extensions/primefaces-extensions.github.com#721]
It would be great if there was a legend component like: https://tilemill-project.github.io/tilemill/docs/guides/advanced-legends/

I would like to make more use of the timeline component - Color coding all the events is one way to communicate some meaning of the model.
But then I need a legend to show what all the different colors mean.

**Comment by melloware** [comment]
I am not sure this needs to be a JSF component when you can simply add the HTML/CSS directly to your page and customize it. Check out this working demo I just wrote: https://jsfiddle.net/L918hfzt/

**Comment by mores** [comment]
Yes, I agree it is very easy to add this to html/css. Here is my use case: https://github.com/mores/primefaces-test/tree/timeline001-needLegend

![image](https://user-images.githubusercontent.com/1318377/64921022-f0aff480-d78b-11e9-89c3-85bf43cf42a2.png)

If one could simply add 
`<pe:legend layout="vertical"  css="#{customTimelineView.colors}" />`
to explain this complicated timeline, it would make life easier.

**Comment by melloware** [comment]
Yeah I think it would have to be something like this though because you need to match a text label too.
```xml
<pe:legend layout="vertical">
   <pe:legendItem style="background:#F1EEF6;" label="0 - 20%" />
   <pe:legendItem style="background:#BDC9E1;" label="40%" />
  <pe:legendItem style="background:#2B8CBE;" label="41-100%" />
</pe:legend>
```

**Comment by mores** [comment]
colors is a Map:

`colors = new HashMap<>();
	colors.put("unavailable", "#F03030");
	colors.put("available", "#1AA11A" );
	colors.put("maybe", "#FFA500" );
	colors.put("ready", "#150578" );
	colors.put("call", "#78C0E0" );
	colors.put("order", "#AAA95A");`

**Comment by melloware** [comment]
Fixed with commit: https://github.com/primefaces-extensions/core/commit/4cecd92bcc011e30614bdd38f5b9f8f44966aec0

Usage:
```xml
<pe:legend layout="horizontal" values="#{legendController.values}">
	<f:facet name="title">
		Horizontal Title Facet
	</f:facet>
	<f:facet name="footer">
		Source: <a href="http://www.primefaces.org">PrimeFaces Rocks!</a>
	</f:facet>
</pe:legend>
```

**Comment by jepsar** [comment]
@melloware are we targeting 7.1 now? Shouldn't we bump Java to 1.8 as well then?

https://github.com/primefaces-extensions/master-pom/blob/b42309b58cc5826fadb7f8a003da315e39c27167/pom.xml#L51-L52

**Comment by melloware** [comment]
I have been putting that in there but i still may do a 7.0.3 release.   I like to get ready for 7.1 once PF releases their first Release Candidate for 7.1.

**Comment by melloware** [comment]
@mores 7.0.3 is in Maven central if you want to try this component now.
