### ISSUE TITLE
LetterAvatar: Two names with the same initials should have two different colors

### ISSUE THREAD

**Issue by mores** [primefaces-extensions/primefaces-extensions.github.com#726]
When these are generated:
<pe:letterAvatar value="PrimeFaces Extensions" height="150" width="150" />
<pe:letterAvatar value="Photo Extreme" height="150" width="150" />
they should have 2 different colors.

**Comment by melloware** [comment]
Thanks for reporting.  Let me see what I can do.

**Comment by melloware** [comment]
From looking at the code this was on purpose that the same initials would generate the same color.

**Comment by mores** [comment]
For my use case I am using this for grouping....
so all blue PE is linked to database object id=1
and all red PE is linked to database object id=2

It would even be great to utilize round / square....
all yellow round PE is linked to database object id=3
all yellow square PE is linked to database object id=4

**Comment by melloware** [comment]
I wonder if we should add overrides like color="#FFFEEE" and shape="square" to not let the letter avatar auto calculate but force it to the color you want?

**Comment by mores** [comment]
I would want these values to come from an algorithm...

**Comment by melloware** [comment]
Be my guest...  current algorithm is right here:
https://github.com/primefaces-extensions/core/blob/dfc060d634601b0fd41124b8dca28360b25b3f86/src/main/resources/META-INF/resources/primefaces-extensions/letteravatar/0-letteravatar.js#L5-L43

**Comment by jepsar** [comment]
Why do we generate an image here? Isn't is easier to generate HTML + CSS? This would also allow customization.

**Comment by melloware** [comment]
No reason this component was donated but we can do whatever we want!

**Comment by jepsar** [comment]
Regarding coloring the same letters differently, you could calculate a hash of the full name, get the modulo of 360 and use that as the hue value of a HSL color.

**Comment by melloware** [comment]
@aripddev Put a comment in this ticket so I can add you as the owner

**Comment by aripddev** [comment]
Thanks @jepsar for the algorithm

**Comment by melloware** [comment]
Fixed with commit: https://github.com/primefaces-extensions/core/commit/6dc9d19e7d879fc0ee9d0651951d7ad3a2810d10
