### ISSUE TITLE
Sheet: how clear, restart or reload on update form

### ISSUE THREAD

**Issue by awenger63** [primefaces-extensions/primefaces-extensions.github.com#729]
Hi, 
In my application, I use pe.sheet (v6.2.10) component.
When user change a day selection in a calendar, form replace all data on the sheet by a new value array content by an update action.

Users said  "after a number of day change, the form doesn't work properly" :  some actions save in DB not work correctly, LOV in cell aren't update or sheet seem to react slowly.

I Wonder know if someone have same issue ?

In fact, when a day change, the sheet is updated.
Since this update, is it possible when I reload all data on the sheet to call a restart, reload or something to re-create a new handsontable like is it a new loading form ? Perhaps this reload can clear memory or object to restart whit null  ?

Thanks for your help.

**Comment by melloware** [comment]
Try this in whatever method or Ajax you are updating the sheet try this in your onstart for example...

```javascript
<p:ajax update="mySheet" onstart="PF('mySheetWidget').ht.destroy()" />
```
`PF('mySheetWidget').ht.destroy()` is the HandonTable method to destroy the sheet and remove it from memory.  You should just be able to hit F12 and type that into your console to watch the sheet get detroyed.  Let me know if that helps?

**Comment by awenger63** [comment]
Yes, I test it on console and onstart event like you suggest and I work like a charm. It is exactly what I need to restart at each day selection.
I will implement this for the moment and wait user return !
Thanks @melloware

**Comment by melloware** [comment]
OK let me know if that fixes it for your users. 

I also just added this commit: https://github.com/primefaces-extensions/core/commit/e17ca2d8c44cfbbea1a44323856c3118345ece97

If you want to try if this fixes it without the "start" trick add this code to your page.

```javascript
PrimeFaces.widget.ExtSheet.prototype.destroy = function() {
        this._super();

        // clean up HT memory
        if (this.ht) {
            this.ht.destroy();
        }
 };
```
