### ISSUE TITLE
CKEditor/CodeMirror: Keeping the scroll position is not always working

### ISSUE THREAD

**Issue by blutorange** [primefaces-extensions/primefaces-extensions.github.com#735]
Now that primefaces-extensions/primefaces-extensions.github.com#732 is fixed, I can come back to what I had been taking a look at.

Some time ago, I [submitted a change](https://github.com/primefaces-extensions/core/pull/83) to keep the scroll position of the CKEditor and the CodeMirror during AJAX updates.

A bit later, there was an issue (primefaces-extensions/primefaces-extensions.github.com#719) which was caused by `CKEditorInstance.document` being `undefined`.

The code in question was run in the `refresh` method of the widget. The `refresh` method is called when `JQuery#replaceWith` is used after an AJAX request was made to replace the widget DOM content.

Turns out that when only the editor component itself is updated, the  old CKEditor still exists at the point in time. But when a parent component is updated, it doesn't. This explains the JavaScript error from the issue - and it also means that keeping the scroll position does not work in these cases.

---

So what I've been trying is to add a listener for the `scroll` event to save the current scroll position so that we can restore it later.

I didn't see any performance issue (it's not manipulating the DOM), so I think we could go with this solution. What do you think?

---

For CodeMirror

```javascript
        // Save scroll position so we can restore it after an AJAX update
        this.instance.on("scroll", function(cMirror) {
            if (cMirror) {
                $this.scrollInfo = cMirror.getScrollInfo();
            }
        });
```

For CKEditor:

```javascript
            // Do not save the scroll position in source mode as the editor automatically switches back to wysiwyg mode
            // during an AJAX update.
            if (editor.mode === 'wysiwyg' && editable.getDocument()) {
                editable.attachListener(editable.getDocument(), 'scroll', $.proxy(function() {
                    if (this.instance && this.instance.document && this.instance.document.$ && this.instance.document.$.documentElement) {
                        this.scrollTop = this.instance.document.$.documentElement.scrollTop;
                        this.scrollLeft = this.instance.document.$.documentElement.scrollLeft;    
                    }
                }, this));
            }
```

**Comment by melloware** [comment]
I like it.

**Comment by melloware** [comment]
Fixed with commit: https://github.com/primefaces-extensions/core/commit/935f16a16b65accb7df6bdccd3cb65ab13342b8d
