### ISSUE TITLE
DocumentViewer:  preserve the current page and zoom

### ISSUE THREAD

**Issue by sberequek** [primefaces-extensions/primefaces-extensions.github.com#739]
Hi,

I have in a tab a documentViewer and a tree where I select the files to display. Each time I go back to the tab the navigation settings (page and zoom) of current document are reset to initial settings. 
I tried to enable the cache option but although the navigation settings are preserved, I can't change the document to be displayed. 
Is it possible to have the current navigation information (page and zoom) every time they are modified? 
Or is it possible to have a method to clean the component's cache?

thanks

**Comment by melloware** [comment]
This is not currently possible out of the box with the way PDF.js works and loads in an IFRAME with a URL.   The only way you might be able to do it is onTabChange write some JQuery code that gets those values from the DocumentViewer IFRAME and sends them to backing bean values using p:remoteCommand Javascript.
