### ISSUE TITLE
TimeAgo should be able to render the title in the original time zone

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions.github.com#742]
The should be an attribute to either use the system zone or the zone present in the time object

**Comment by melloware** [comment]
Yep a lo of other components have a timezone prop as a java.lang.Object and then there is a CalendarUtils method to take that and return a ZoneId even if its a java.util.TimeZone or ZoneId.

**Comment by jepsar** [comment]
Yeah, but this one does not need to convert from a string to a time object, so I think a boolean switch should do the job.

**Comment by melloware** [comment]
@jepsar Any chance you want to fix this one before I cut 8.0.3 as well?

**Comment by jepsar** [comment]
I didn't really needed this so it was not really a priority. Let me see what I can do about this one.

**Comment by jepsar** [comment]
@melloware feel free to release 8.0.3. I'm not sure how much sense this issue makes if you don't include the time zone in the formatted text.. I'm not sure how I'd like to solve this issue.

**Comment by melloware** [comment]
No problem thanks for letting me know.
