### ISSUE TITLE
InputPhone should support .ui-inputgroup

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions.github.com#751]

**Comment by jepsar** [comment]
Hi @mertsincan

Is there a reason why the input group CSS rules are written like `.ui-inputgroup > .ui-inputtext` instead of `.ui-inputgroup .ui-inputtext`?

The latter would allow us use `ui-inputtext` on components like the phone input (which are wrapped in some node). Should I open an issue at the PF repo for this?

**Comment by melloware** [comment]
@jepsar Why not just add this to the inputphone.css ?  This is what InputNumber does.

.ui-inputgroup > .ui-inputphone:not(:first-child) > .ui-inputtext {
    border-top-left-radius: 0;
    border-bottom-left-radius: 0;
    border-left: 0 none;
}

.ui-inputgroup > .ui-inputphone:not(:last-child) > .ui-inputtext {
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
    border-right: 0 none;
}

**Comment by jepsar** [comment]
I'd prefer a generic solution, but, yes, we could add specific rules.

**Comment by melloware** [comment]
I think we have to since that is how all the other PF components do it.

**Comment by jepsar** [comment]
Alright then. I'll add it tonight.

**Comment by melloware** [comment]
Fix with this commit: https://github.com/primefaces-extensions/core/commit/49b3105804f3415e3f07a82e40481703e26773d2

Please review.

**Comment by jepsar** [comment]
@melloware There was a small issue with the selectors. Fixed with https://github.com/primefaces-extensions/core/commit/80e97ef37e2544ef4bbf1519e965a341f52cf196

**Comment by melloware** [comment]
awesome!
