### ISSUE TITLE
TimePicker: NPE in js, when using with omnifaces CombinedResourceHandler

### ISSUE THREAD

**Issue by cocorossello** [primefaces-extensions/primefaces-extensions.github.com#752]
When using [CombinedResourceHandler](http://showcase.omnifaces.org/resourcehandlers/CombinedResourceHandler) timepicker throws an NPE in core.js:139. 

The problem appears in [v7.0.3](https://github.com/primefaces-extensions/core/commit/1b046f47f60bcd41b7154dfeffc81ceb6c397af2#commitcomment-35981158) 

There is no specific `<link>` tag, so this themeURL is always null in this case.

Options would be to just return false in this case (users can override) or render a hidden `<i class="pi pi-check"></i>`  and test for size, but note this is slow and can also be flaky.

**Comment by melloware** [comment]
@cocorossello When I run the PFE Showcase with OmniFaces Combined Resource Handler here is what I see.
```
<link type="text/css" rel="stylesheet" href="/primeext-showcase/javax.faces.resource/theme.css.jsf?ln=primefaces-omega" />
<link type="text/css" rel="stylesheet" href="/primeext-showcase/javax.faces.resource/fa/font-awesome.css.jsf?ln=primefaces&amp;v=8.0-SNAPSHOT" />
<link type="text/css" rel="stylesheet" href="/primeext-showcase/javax.faces.resource/eNp9jmEKwyAMhU-0-d9r7AQuZDVMjZiUVdjhZ-2wZYX9CHnv5SNJLhTx4QDlgotiEuIkNrjKs5qtXUHknQdngWPmhEnlZ3LcoC3MBE8sZpf_eOaglM23d7KVnQLfXRj28NFqZ0FwgjIC9Rjx9iIFfzpnuyRo58wuOyQ1qVs8TT60UixWtAYUcxqs-Acj4nyj.css.jsf?ln=omnifaces.combined&amp;v=1574082297000" />
```
The theme.css is not bundled in the ResourceHandler due to the way OmniFaces collects and PrimeFaces adds the theme directly so it is not processed by OmniFaces?

**Comment by melloware** [comment]
I just checked in this defensive fix: https://github.com/primefaces-extensions/core/commit/4d75aa0d80ff0afef713acdb6850103b7cabc729

if you need this fix right now just add this JavaScript to your page.
```javascript
PrimeFacesExt.getTheme = function() { return "omega"};
```
Or return whatever your theme is,

**Comment by cocorossello** [comment]
Ok, thanks, looks good. 

In my case I was combining also the theme via a custom HeadRenderer (as balusc recomends):

`@ResourceDependency(library = "javax.faces", name = "jsf.js")
@ResourceDependency(library = "primefaces-bootstrap", name = "theme.css")
@ResourceDependency(library = "org.apache.myfaces", name = "oamSubmit.js")
@ResourceDependency(library = "primefaces", name = "jquery/jquery.js")
@ResourceDependency(library = "primefaces", name = "jquery/jquery-plugins.js")
@ResourceDependency(library = "primefaces", name = "core.js")
@ResourceDependency(library = "primefaces", name = "components.js")
@ResourceDependency(library = "primefaces-extensions", name = "primefaces-extensions.js")
@ResourceDependency(library = "primefaces-extensions", name = "timepicker/timepicker.js")
@ResourceDependency(library = "primefaces", name = "components.css")
public class HeadRenderer extends Renderer {...`


I already had it patched.

**Comment by melloware** [comment]
OK got it that makes a lot of sense!
