### ISSUE TITLE
focus <pe:inputPhone /> fail

### ISSUE THREAD

**Issue by 4lp3rt0rq0** [primefaces-extensions/primefaces-extensions.github.com#753]
I have next code:
`<p:inpulText id="txtEmail" onkeypress="if(event.keyCode ==13){PF('txtTel').jq.focus(); return false;}" value="#{myBean.email}"/> <p:inputPhone id="txtTel" value="#{myBean.tel}" />`
when the enter key is pressed inside txtEmail, it doesn't focus on txtTel.

**Comment by melloware** [comment]
Try...
```javascript
PF('txtTel').inputJq.focus();
```

**Comment by 4lp3rt0rq0** [comment]
thanks, it works !!!

**Comment by melloware** [comment]
In 8.0 I am adding a widget method `focus()` as a shortcut to this so you will be able to do `PF('txtTel).focus().

Fixed with commit: https://github.com/primefaces-extensions/core/commit/6e3568458511f6570a0c5bc1fcce0de4a1f72b01
