### ISSUE TITLE
New component: HashChange

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions.github.com#755]
I would like to easily do Ajax updates and allow the user to use the browser back button. I'm thinking of implementing something like:

    <p:commandButton ... onsuccess="location.hash = 'list'"/>
    <p:commandButton ... onsuccess="location.hash = 'product-xyz'"/>
    <pe:hashChange startsWith="list" listener="..." update="..."/>
    <pe:hashChange startsWith="product-" listener="..." update="..."/>

Let me know what you think.

See also:

* https://stackoverflow.com/questions/20443883/primefaces-ajax-navigation-with-browser-history-hashtag
* https://stackoverflow.com/questions/3475076/retrieve-the-fragment-hash-from-a-url-and-inject-the-values-into-the-bean
* https://developer.mozilla.org/en-US/docs/Web/API/Window/hashchange_event

**Comment by melloware** [comment]
if you have the use case good with me but would like @tandraschko to weigh in.

**Comment by jepsar** [comment]
I think I'll be implementing this in our current project anyway. If it turns out to be useful I can always create a component out of it.

**Comment by tandraschko** [comment]
in generell +0
one can simply use onhashchange + remoteCommand.

Otherwise please don't add listener/update to the component itself, just reuse behaviors / p:ajax.
So renderer will just render the window.onhashchange script and nothing else

**Comment by jepsar** [comment]
For now I'll use `p:remoteCommand`.
