### ISSUE TITLE
Exporter should check rendered state of targeted components

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions.github.com#757]
.. or should the user take care of that? @melloware ?

See https://stackoverflow.com/questions/60076040/non-rendered-pdatatable-ends-up-in-peexporter-pdf

**Comment by RosaNatali** [comment]
that resolves my problem.
**Big thanks.** #

**Comment by melloware** [comment]
I think we should add a rendered check in the Exporter.  @jepsar Do you want to take care of that or did you want me to?  Feel free if you have the time but let me know if you want me to do it.

**Comment by jepsar** [comment]
Feel free to take it. I was planning to address a few other things as well:

* From the documentation it's not really clear you can set multiple targets.
* In JSF one would usually separate clientIds with a space, In PF you can use either space or comma. Here only comma is allowed (at first glance).

**Comment by melloware** [comment]
OK I checked in this fix: https://github.com/primefaces-extensions/core/commit/47736dfe2f626ffbdf5d06c152b3390c936a2086

I do see what you mean this component is hard wired for comma seaprated tables and that check happens in multiple places.

As for docmentation I think they were just assuming you look at this example but I think the TagLib docu should be updated to mention comma separated for the target attribute.

https://www.primefaces.org/showcase-ext/sections/exporter/multipleTables.jsf

**Comment by melloware** [comment]
OK this commit updates the taglib: https://github.com/primefaces-extensions/core/commit/a72a2bf467e3fbbeb97bd69830e48c4861abdcfe

**Comment by jepsar** [comment]
Space separation should be a new issue IMO.

**Comment by melloware** [comment]
Agreed since that is a bigger change.  I will close this ticker as FIXED.
