### ISSUE TITLE
CKEditor: Attribute "toolbar" is ignored

### ISSUE THREAD

**Issue by Exandra** [primefaces-extensions/primefaces-extensions.github.com#759]
## 1) Environment
- PrimeFaces version: 8.0.RC1, 8.0.RC3
- PrimeFaces extensions version: 8.0.RC1
- Application server + version: Jetty, WildFly 14.0.1
- Affected browsers: All

## 2) Expected behavior

Attribute "toolbar" should customize CKEditor toolbar icons. (Primefaces 7.0)

![primefaces-extensions ckeditor 70](https://user-images.githubusercontent.com/30283406/74418219-56420300-4e48-11ea-9e40-0a571a88abcc.PNG)

## 3) Actual behavior

Attribute "toolbar" is ignored. All CKEditor toolbar icons are displayed. (Primefaces 8.0.RC1/3)

![primefaces-extensions ckeditor 80RC1](https://user-images.githubusercontent.com/30283406/74418232-5c37e400-4e48-11ea-863f-f62b48fbd673.PNG)

## 4) Steps to reproduce

1. git clone https://github.com/Exandra/primefaces-test.git
2. cd primefaces-test
3. mvn-jetty:run

- Or visit the primefaces extensions showcase https://www.primefaces.org/showcase-ext/sections/ckEditor/customToolbar.jsf

## 5) Sample XHTML

```
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html"
	  xmlns:pe="http://primefaces.org/ui/extensions">

    <h:head>
        <title>PrimeFaces Test</title>
    </h:head>
    <h:body>

    <h:form id="form1">
        <pe:ckEditor 
			toolbar="[['Cut','Copy','Paste','PasteText','PasteFromWord','-', 'SpellChecker'], '/', ['Undo', 'Redo']]">
        </pe:ckEditor>    
    </h:form>

    </h:body>
</html>
```

## 6) Comment

Maybe related to https://github.com/primefaces-extensions/core/commit/dc2bcfc3109af645e6d1d46959317b7753ea239c ? Sorry, I don't know the inner workings of primefaces to really fix this problem. :(

**Comment by melloware** [comment]
Thanks for reporting!  I had to make a PF fix here:
https://github.com/primefaces/primefaces/pull/5595

This will be fixed in 8.0 Final with this commit: https://github.com/primefaces-extensions/core/commit/733101ba874cb40cc3ee43ed87a12715e0cdb1fe
