### ISSUE TITLE
CommandButtonSingleClick: Problem in Datatable

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions.github.com#761]
If you have a Datatable with a CommandButton in the first column.

```xml
<p:column>
    <p:commandButton id="btnActions" value="Button" 
         oncomplete="alert('#{component.clientId}');" immediate="true" process="@this" />
<p:column>
```

Because in encodeMarkup we are calling button.resolvewidgetVar() it is resolving it incorrectly.

All of the buttons in my table are being rendered with widgetVar :0:

```
frmMain:tblTest:0:btnActions
frmMain:tblTest:0:btnActions
frmMain:tblTest:0:btnActions
frmMain:tblTest:0:btnActions
```

instead of 

```
frmMain:tblTest:0:btnActions
frmMain:tblTest:1:btnActions
frmMain:tblTest:2:btnActions
frmMain:tblTest:3:btnActions
```

**Comment by melloware** [comment]
Actually it looks like the oncomplete method gets rendered with the wrong ID where they are a ll button0.

**Comment by melloware** [comment]
Still debugging couldn't reproduce with simple reproducer.
[pfe-761.zip](https://github.com/primefaces-extensions/primefaces-extensions.github.com/files/4298325/pfe-761.zip)

**Comment by melloware** [comment]
OK I was able to reproduce it!
[pfe-761.zip](https://github.com/primefaces-extensions/primefaces-extensions.github.com/files/4298341/pfe-761.zip)

if you run that sample app and press each button they will all say "button0" in the alert. However if you remove the CommandButtonSingleClick renderer it works fine and each button reports its proper value.

**Comment by jepsar** [comment]
Originally I was using `PrimeFaces.getWidgetById(domNodeId)`. I need to test if that will work with buttons in tables, but I've not had any issues with that in our application. That would require Javascript though, as we don't know the client's DOM node ID in the renderer.

**Comment by jepsar** [comment]
Weird.. the rendered `onclick` of button 0: 

`PrimeFaces.bcn(this,event,[function(event){var w=PF('widget_j_idt5_tblCars_0_btnActions');if(w){w.disable();};},function(event){PrimeFaces.ab({s:"j_idt5:tblCars:0:btnActions",f:"j_idt5",p:"j_idt5:tblCars:0:btnActions",onco:function(xhr,status,args,data){var w=PF('widget_j_idt5_tblCars_0_btnActions');if(w){w.enable();};alert('j_idt5:tblCars:0:btnActions');;}});return false;}]);`

and button 4:

`PrimeFaces.bcn(this,event,[function(event){var w=PF('widget_j_idt5_tblCars_4_btnActions');if(w){w.disable();};var w=PF('widget_j_idt5_tblCars_3_btnActions');if(w){w.disable();};var w=PF('widget_j_idt5_tblCars_2_btnActions');if(w){w.disable();};var w=PF('widget_j_idt5_tblCars_1_btnActions');if(w){w.disable();};var w=PF('widget_j_idt5_tblCars_0_btnActions');if(w){w.disable();};},function(event){PrimeFaces.ab({s:"j_idt5:tblCars:4:btnActions",f:"j_idt5",p:"j_idt5:tblCars:4:btnActions",onco:function(xhr,status,args,data){var w=PF('widget_j_idt5_tblCars_4_btnActions');if(w){w.enable();};var w=PF('widget_j_idt5_tblCars_3_btnActions');if(w){w.enable();};var w=PF('widget_j_idt5_tblCars_2_btnActions');if(w){w.enable();};var w=PF('widget_j_idt5_tblCars_1_btnActions');if(w){w.enable();};var w=PF('widget_j_idt5_tblCars_0_btnActions');if(w){w.enable();};alert('j_idt5:tblCars:0:btnActions');;}});return false;}]);`

**Comment by jepsar** [comment]
The issue is with prefixing and setting the attributes: https://github.com/primefaces-extensions/core/blob/primefaces-extensions-8.0/src/main/java/org/primefaces/extensions/renderer/CommandButtonSingleClickRenderer.java#L35-L36

**Comment by melloware** [comment]
Yeah its like its additive.

**Comment by melloware** [comment]
Also go to this example in the showcase:
https://www.primefaces.org/showcase-ext/sections/slideout/basicUsage.jsf

You can only click the buttons once.

**Comment by jepsar** [comment]
> Also go to this example in the showcase:
> https://www.primefaces.org/showcase-ext/sections/slideout/basicUsage.jsf
> 
> You can only click the buttons once.

Hmm.. those buttons don't have an action. I'll throw in a check on that as well.
