### ISSUE TITLE
Badge is not overflowing on modern themes

### ISSUE THREAD

**Issue by jepsar** [primefaces-extensions/primefaces-extensions.github.com#762]
See https://www.primefaces.org/showcase-ext/sections/badge/basicUsage.jsf and switch to Nova Light. Caused by a CSS rule in the theme:

```
body .ui-button.ui-button-icon-only { overflow: hidden; }
```

Not sure why they have that rule, and if we need to file an issue at PF.

**Comment by melloware** [comment]
Let me file an issue with PrimeTek and see.

**Comment by melloware** [comment]
If you want to look at fixing it in case PrimeTek comes back and say that is for good reason we might need to fix it on our side.

**Comment by mertsincan** [comment]
Please try;
```
body .ui-button.ui-button-icon-only {
   overflow: visible;
}

body .ui-button.ui-button-icon-only .ui-button-text {
    transform: scale(0);
}
```

Could you please try the above css code on all browsers?

Best Regards,

**Comment by melloware** [comment]
Closing ticket as PF is going to fix the themes.

**Comment by jepsar** [comment]
Should we remove the milestone as nothing was done at PFE?

**Comment by melloware** [comment]
done
