### ISSUE TITLE
LetterAvatar: Invert CSS font-color depending on background-color

### ISSUE THREAD

**Issue by aripddev** [primefaces-extensions/primefaces-extensions.github.com#775]
Solution to https://github.com/primefaces-extensions/core/pull/101#issuecomment-608584862

There is `mix-blend-mode: difference`

**Comment by melloware** [comment]
Were you going to submit a new PR for this fix?

**Comment by aripddev** [comment]
yesterday I tried twice but cannot submit because of too many conflicts. So I closed PRs. I will try it again after completed fuzzysearch

**Comment by melloware** [comment]
Yes you need to make a new branch in your fork.  But first you must resync the changes to your fork. I will send you instructions.

**Comment by melloware** [comment]
To resync your master with all the changes.

`git fetch upstream`
`git checkout master` 
`git merge upstream/master`
`git push origin master`

Now your master has the latest code.  Create a new branch now called PFE775 and you can fix just this bug and submit a PR from that branch.

**Comment by aripddev** [comment]
Thanks @melloware . I submitted PRs for both core and showcase.

**Comment by melloware** [comment]
@jepsar @aripddev here is the current showcase screenshot

![image](https://user-images.githubusercontent.com/4399574/78498840-cff4bf80-771a-11ea-8686-ad23ed80f80c.png)
