### ISSUE TITLE
CKEditor: EnterMode and ShiftEnterMode

### ISSUE THREAD

**Issue by testing138** [primefaces-extensions/primefaces-extensions.github.com#779]
Hi all,

It would be very very awesome if you can avoid the <p> and </p> tags which will be generated by default from the Editor.

I like the editor, but with this "bug" a cannot use it in my project in some scenarios. I´m currently substring my string in the backend, but this will also not work everytime.

If I google this, many other users have the same issue.
I´ve tried already to create my own ckeditor.js and changed the following code:

CKEDITOR.config = {
......
**enterMode: CKEDITOR.ENTER_BR,**

But this seems not working.

It would be so nice, if you can add a flag like: avoidBreaklinesStartEnd 

Many thanks

**Comment by melloware** [comment]
I think i will add 2 new props.

https://ckeditor.com/docs/ckeditor4/latest/features/enterkey.html

"EnterMode" and "ShiftEnterMode" allowing you to control the type but I will default to CKEDITOR.ENTER_P

**Comment by melloware** [comment]
Fixed with commit: https://github.com/primefaces-extensions/core/commit/758a327ab216af7ccb3cb7ef2de25a341d8b15b0

Will be in 8.0.1 which will be released in the next 1-2 weeks!

**Comment by testing138** [comment]
Wow, many many thanks - you made my day!

**Comment by melloware** [comment]
8.0.1 is now in Maven Central
