### ISSUE TITLE
JQuery 3.5.0 Preparation

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/primefaces-extensions.github.com#784]
jQuery 3.5.0 has been released with a security fix:
https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/

So the biggest change for security reasons Jquery not longer allows you to do..
```javascript
jq.html('<span/>');
```
It used to autocomplete for you but now they force you to have proper closing tags on any HTML like..
```javascript
jq.html('<span></span>');
```

Linked to: https://github.com/primefaces/primefaces/issues/5807

**Comment by melloware** [comment]
@jepsar please review.

Fixed with this commit: https://github.com/primefaces-extensions/core/commit/b030e14901b91982355dc5e157c2d84bba070711

I tested the components I touched in the showcase and everything seems to be working fine.

**Comment by jepsar** [comment]
Looking good to me
