### ISSUE TITLE
CustomExporterFactory stopped work in version 8.0.

### ISSUE THREAD

**Issue by pauloalexandre3d** [primefaces-extensions/primefaces-extensions.github.com#788]
Hi,

Last week we updated version from 6.2 to 8.0 and my
`public class CustomExporterFactory implements ExporterFactory` stopped work. And now I got this exception:

`java.util.ServiceConfigurationError: org.primefaces.extensions.component.exporter.ExporterFactory: my.package.CustomExporterFactory not a subtype`

I have my.package.CustomExporterFactory configured under src/META-INF/services/org.primefaces.extensions.component.exporter.ExporterFactory file.

Do you have any idea?

**Comment by melloware** [comment]
I suggest reviewing our example: https://www.primefaces.org/showcase-ext/sections/exporter/customExporter.jsf

The source code can all be found here: https://github.com/primefaces-extensions/showcase

See this class: https://github.com/primefaces-extensions/showcase/blob/master/src/main/java/org/primefaces/extensions/showcase/util/CustomExporterFactory.java

Notice the class extends 'org.primefaces.extensions.component.exporter.ExporterFactory`  make sure your code is doing the same thing.

**Comment by pauloalexandre3d** [comment]
Hi @melloware,

Thank you very much.
