### ISSUE TITLE
CreditCard: required attribute not working

### ISSUE THREAD

**Issue by aripddev** [primefaces-extensions/primefaces-extensions.github.com#790]
I have added `required="true"` for cardNumber, cardHolderName, expire and cvc inputs, but it does not trigger `messages` or `growl`.

<img width="697" alt="Screen Shot 2020-04-29 at 02 18 47" src="https://user-images.githubusercontent.com/9448030/80547069-f1666580-89bf-11ea-8849-0d048688dbb4.png">

**Comment by melloware** [comment]
You are right. Reproducible test case: 
[pfe-790.zip](https://github.com/primefaces-extensions/primefaces-extensions.github.com/files/4551331/pfe-790.zip)

it looks related to having to to use the `pt:name` is no longer binding it to the component.

**Comment by melloware** [comment]
Yuck looks like this is the problem:
https://stackoverflow.com/questions/15893876/how-to-specify-name-attribute-in-hinputtext

So using `name="cvc"` etc allow browsers to know these are autocomplete fields let the browser fill in your CC info and that is how Card.js default looks for those fields.   However JSF needs the `name` field to bind to the backend.

Have to think about this...

**Comment by melloware** [comment]
OK got it working with this example: 
[pfe-790.zip](https://github.com/primefaces-extensions/primefaces-extensions.github.com/files/4551379/pfe-790.zip)

You have to use `prependId="false"` on the form and make the id's the names instead of using passthrough.

```xml
		
<h:form prependId="false">
	<p:growl id="growl" showDetail="true" showSummary="true">
		<p:autoUpdate />
	</p:growl>
	<p:panelGrid id="pnlCreditCard" columns="4">
		<f:facet name="header">
			<pe:creditCard id="creditCard" labelMonthYear="MM/YY" placeholderExpiry="**/**" placeholderName="Optimus Prime"/>
		</f:facet>
		<p:inputText id="number" placeholder="Card number" required="true"/>
		<p:inputText id="name" placeholder="Full name"  required="true"/>
		<p:inputText id="expiry" placeholder="MM/YY"  required="true"/>
		<p:inputText id="cvc" placeholder="CVC"  required="true"/>
	</p:panelGrid>
	<p:commandButton value="Update" update="@form" process="@form" />
</h:form>
```

**Comment by aripddev** [comment]
Well done 👍, thanks

<img width="713" alt="Screen Shot 2020-04-29 at 15 15 06" src="https://user-images.githubusercontent.com/9448030/80594735-3d4ef400-8a2c-11ea-8d67-674e706fe36c.png">

**Comment by melloware** [comment]
awesome
