### ISSUE TITLE
CreditCard: Card image lost after validation not passed

### ISSUE THREAD

**Issue by aripddev** [primefaces-extensions/primefaces-extensions.github.com#791]
Card image has been lost after validation not passed any form items. Below is the picture of before and after form submission.

<img width="697" alt="Screen Shot 2020-04-29 at 20 22 44" src="https://user-images.githubusercontent.com/9448030/80626567-4f925780-8a57-11ea-9038-b6e1a948829d.png">

**Comment by melloware** [comment]
Fixed with commit: https://github.com/primefaces-extensions/core/commit/ca45110c43737823e0573caeeae4083ce8b7961c

If you need this fix now here is a MonkeyPatch you can add to your JS file that fixes it.

```javascript
PrimeFaces.widget.ExtCreditCard.prototype.refresh = function(cfg) {
    PrimeFaces.widget.BaseWidget.prototype.refresh.call(this, cfg);

    $(document).ready(function() {
        const blur = new Event('blur');
        const change = new Event('change');
        $('.ui-state-filled').each(function(index) {
            this.dispatchEvent(blur);
            this.dispatchEvent(change);
        })
    });
};
```
