### ISSUE TITLE
unable to add custom css in pe:gChart

### ISSUE THREAD

**Issue by maniratna2019** [primefaces-extensions/primefaces-extensions.github.com#794]
- PrimeFaces version: 6.0.0
- PrimeFaces Extensions:6.1.1 

GChartModelBuilder chartBuilder = new GChartModelBuilder();
chartBuilder.setChartType(GChartType.PIE);
chartBuilder.addColumns("Topping", "Slices");
chartBuilder.addRow("Sleep", 7);  
chartBuilder.addRow("Work", 6);
chartBuilder.addOption("pieSliceText", "value");
chartBuilder.addOption("tooltip", "{isHtml: true, text:'value'}");
chartBuilder.addOption("legend","{ position: 'top', 'alignment': 'start' }");

Here I defined tooltip property and legend properties but does not appear in chart.
On inspection of the page i found out 
chart:"{\"type\":\"PieChart\",\"options\":{\"pieSliceText\":\"value\",\"tooltip\":\"{isHtml: true,text: \\u0027value\\u0027}\",\"legend\":\"{ position: \\u0027top\\u0027, \\u0027alignment\\u0027: \\u0027start\\u0027 }\"}

**Comment by maniratna2019** [comment]
i got the answer https://stackoverflow.com/questions/61492942/how-to-show-absolute-value-in-tooltip-in-a-pegchart

**Comment by melloware** [comment]
Thanks I will update my Showcase example to help future people as well.
