### ISSUE TITLE
FAB: AJAX listeners

### ISSUE THREAD

**Issue by rider87** [primefaces-extensions/primefaces-extensions.github.com#801]
Hi, 

As described in the forum:
https://forum.primefaces.org/viewtopic.php?f=14&t=62468

How can I invoke a listener method for the p:ajax events?**
I´ve tried this, but this is not working

```
<pe:fab id="btnFab" icon="fa fa-question" iconActive="fa fa-times"
		style="background: green;">
		<p:ajax event="open" listener="#{mybean.doOpenWidget}"
			 global="false" />
		<p:ajax event="close" listener="#{mybean.doCloseWidget}"
			global="false" />
	</pe:fab>
```

**Comment by melloware** [comment]
@jepsar want to look at this one?

**Comment by melloware** [comment]
Actually @rider87 can you open another ticket. I think we should track the AJAX Open and Close as 1 issue and the FAB+Badge as another issue.

**Comment by jepsar** [comment]
Yeah, I can have a look. I might have time this weekend (depending on the weather).

**Comment by melloware** [comment]
Fixed with commit: https://github.com/primefaces-extensions/core/commit/2e3b9d3b9d7f3cd10d02842aa942fdab9b5d0168

Will be in version 8.0.3. @rider87 thanks for reporting!
