### ISSUE TITLE
FAB and Badge not working together

### ISSUE THREAD

**Issue by rider87** [primefaces-extensions/primefaces-extensions.github.com#802]
Hi, 

As described in the forum:
https://forum.primefaces.org/viewtopic.php?f=14&t=62468

I´m using the pe:fab and pe:badge on right top corner...**
I tried this, but it´s always only showing after the pe:fab:

`<pe:fab id="btnFab" icon="fa fa-question" iconActive="fa fa-times"
		style="background: green;">
	</pe:fab>
		<pe:badge content="1" for="btnFab"  position="top-right"/>`

**Comment by jepsar** [comment]
Probably because of the absolute positioning of the FAB. @melloware I can also have a look at this if you like.

**Comment by melloware** [comment]
@jepsar You take this one and i will take the other one.
