### ISSUE TITLE
Avoid GSON

### ISSUE THREAD

**Issue by tandraschko** [primefaces-extensions/primefaces-extensions.github.com#803]
Currently if you add pfe, you always get GSON as dependency.
Actually its only used for some component and should be optional.
We should try to use PF JSON or JSONB

**Comment by tandraschko** [comment]
switched the fuzzySearchRendererd to PF JSON. Dont time for now to further work on it.
If someone has time, feel free... :D

**Comment by melloware** [comment]
I will work on it.

**Comment by melloware** [comment]
OK I have made all the changes and marked GSON as `optional=true` dependency.  its only used in 3 components JsonConverter, Layout, and GChart.

I will update the release notes to reflect this but now PF Extensions successfully has no dependencies just like PF and I was able to deploy a PrimeFaces test app successfully proving it.

**Comment by tandraschko** [comment]
is it to much work for the other components to switch?

**Comment by melloware** [comment]
Well it seems they re using GSON specific features such as Date Conversion to a certain format and something called GSonTree which doesn't translate 1-1 with JSONObject.  So we would probably have to re-engineeer all of them to have custom objects to serialize.
