### ISSUE TITLE
Try to avoid commons-lang usage

### ISSUE THREAD

**Issue by tandraschko** [primefaces-extensions/primefaces-extensions.github.com#804]
Most of the time utils like StringUtils are used, which are already available in PF core. Use them instead common-langs

Maybe we can reven remove the dependency.

**Comment by tandraschko** [comment]
Replaced commons-lang by ~60 LOC

@melloware the only usage left is StringEscapeUtils. Can we remove this taglib functions (never used it but introduced it ;)) ? or can we reuse the owas escape stuff from PF core?

**Comment by melloware** [comment]
Yep I think we can replace with OWASP EscapeUtils. 

As for JSON can't we do something similar as PF and use the JSONObject instead of GSON?

**Comment by tandraschko** [comment]
would you take care of the Owasp EscapeUtils thing?
i will check JSON now

**Comment by melloware** [comment]
yep! on it.

**Comment by melloware** [comment]
OK I removed all Commons Lang and switched it to `test` scope in the pom.xml because some unit tests were using it.  so now it will no longer automatically be downloaded by PFE.  Thanks for working on this!

**Comment by tandraschko** [comment]
what about that taglib functions?

**Comment by melloware** [comment]
let me look at those. I didn't even realize they were there.  Maybe we should remove them?

**Comment by tandraschko** [comment]
yeah, thats what i said 2 posts earlier here :D
i would remove them and add a migration guide hint to add them in the application manually (commons lang + the taglib entry)

**Comment by melloware** [comment]
Sorry i missed that I will remove them.
