### ISSUE TITLE
PrimeFaces Extensions and jasper report 

### ISSUE THREAD

**Issue by bushramashaiekh** [primefaces-extensions/primefaces-extensions.github.com#827]
Hi All , 
I use java to create dynamic jasper report and then I show it in pe:documentviewer i use version (primefaces-extensions-6.2.jar)
it is work well but last month i have issue when we print in pe:documentviewer it is duplicate the Arabic characters  but when i download the report its work well (so i think i have error in Arabic font in primefaces extensions ) so what i can do ? update the version of primefaces-extensions or any other solution please ? 
Thank you

**Comment by bushramashaiekh** [comment]
@ova2  @sudheerj  @tandraschko  @melloware

**Comment by jepsar** [comment]
Please try with 12 and use the correct issue tracker.

**Comment by melloware** [comment]
Correct issue tracker: https://github.com/primefaces-extensions/primefaces-extensions/issues

**Comment by jepsar** [comment]
> Correct issue tracker: https://github.com/primefaces-extensions/primefaces-extensions/issues

That was removed in the edit 😁
